package game.scene.world.base {
    import com.utils.Constants;

    import game.base.JTSprite;
    import game.manager.AssetMgr;

    import starling.display.Button;
    import starling.display.Image;
    import starling.text.TextField;
    import starling.textures.Texture;

    public class JTUIGitTollgate extends JTSprite {
        public var txt_title:TextField = null;
        public var txt_cu_progress:TextField = null;
        public var txt_tolltage_num:TextField = null;
        public var txt_about:TextField = null;
        public var txt_diamond:TextField = null;
        public var txt_star:TextField = null;
        public var txt_tried:TextField = null;
        public var btn_get_giftButton:Button = null;
        public var img_mc_icon:Image = null;

        public function JTUIGitTollgate() {
            var txture_ui_gongyong_zhiwanzidi015:Texture = AssetMgr.instance.getTexture('ui_gongyong_zhiwanzidi');
            var ui_gongyong_zhiwanzidi015img_3:Image = new Image(txture_ui_gongyong_zhiwanzidi015);
            ui_gongyong_zhiwanzidi015img_3.x = 0;
            ui_gongyong_zhiwanzidi015img_3.y = 15;
            ui_gongyong_zhiwanzidi015img_3.width = 453;
            ui_gongyong_zhiwanzidi015img_3.height = 164;
            ui_gongyong_zhiwanzidi015img_3.smoothing = Constants.smoothing;
            //   ui_gongyong_zhiwanzidi015img_3.touchable = false;
            this.addQuiackChild(ui_gongyong_zhiwanzidi015img_3);
            var txture_ui_chaojixingyunxing630:Texture = AssetMgr.instance.getTexture('ui_chaojixingyunxing');
            var ui_chaojixingyunxing630img_4:Image = new Image(txture_ui_chaojixingyunxing630);
            ui_chaojixingyunxing630img_4.x = 63;
            ui_chaojixingyunxing630img_4.y = 0;
            ui_chaojixingyunxing630img_4.width = 335;
            ui_chaojixingyunxing630img_4.height = 78;
            ui_chaojixingyunxing630img_4.smoothing = Constants.smoothing;
            //  ui_chaojixingyunxing630img_4.touchable = false;
            this.addQuiackChild(ui_chaojixingyunxing630img_4);
            var txture_ui_gongyong_zhiwanzidi_wenzikuang116212:Texture = AssetMgr.instance.getTexture('ui_gongyong_zhiwanzidi_wenzikuang1');
            var ui_gongyong_zhiwanzidi_wenzikuang116212img_5:Image = new Image(txture_ui_gongyong_zhiwanzidi_wenzikuang116212);
            ui_gongyong_zhiwanzidi_wenzikuang116212img_5.x = 162;
            ui_gongyong_zhiwanzidi_wenzikuang116212img_5.y = 12;
            ui_gongyong_zhiwanzidi_wenzikuang116212img_5.width = 142;
            ui_gongyong_zhiwanzidi_wenzikuang116212img_5.height = 49;
            ui_gongyong_zhiwanzidi_wenzikuang116212img_5.smoothing = Constants.smoothing;
            // ui_gongyong_zhiwanzidi_wenzikuang116212img_5.touchable = false;
            this.addQuiackChild(ui_gongyong_zhiwanzidi_wenzikuang116212img_5);
            var txture_ui_gongyong_zhiwanzidi_wenzikuang12912:Texture = AssetMgr.instance.getTexture('ui_gongyong_zhiwanzidi_wenzikuang');
            var ui_gongyong_zhiwanzidi_wenzikuang12912img_6:Image = new Image(txture_ui_gongyong_zhiwanzidi_wenzikuang12912);
            ui_gongyong_zhiwanzidi_wenzikuang12912img_6.x = 129;
            ui_gongyong_zhiwanzidi_wenzikuang12912img_6.y = 12;
            ui_gongyong_zhiwanzidi_wenzikuang12912img_6.width = 36;
            ui_gongyong_zhiwanzidi_wenzikuang12912img_6.height = 49;
            ui_gongyong_zhiwanzidi_wenzikuang12912img_6.smoothing = Constants.smoothing;
            //  ui_gongyong_zhiwanzidi_wenzikuang12912img_6.touchable = false;
            this.addQuiackChild(ui_gongyong_zhiwanzidi_wenzikuang12912img_6);
            var txture_ui_gongyong_zhiwanzidi0334:Texture = AssetMgr.instance.getTexture('ui_gongyong_zhiwanzidi');
            var ui_gongyong_zhiwanzidi0334img_7:Image = new Image(txture_ui_gongyong_zhiwanzidi0334);
            ui_gongyong_zhiwanzidi0334img_7.x = 0;
            ui_gongyong_zhiwanzidi0334img_7.y = 334;
            ui_gongyong_zhiwanzidi0334img_7.width = 453;
            ui_gongyong_zhiwanzidi0334img_7.height = 164;
            ui_gongyong_zhiwanzidi0334img_7.scaleY = -1.088897705078125;
            ui_gongyong_zhiwanzidi0334img_7.smoothing = Constants.smoothing;
            //  ui_gongyong_zhiwanzidi0334img_7.touchable = false;
            this.addQuiackChild(ui_gongyong_zhiwanzidi0334img_7);
            var txture_ui_gongyong_zhiwanzidi_wenzikuang33712:Texture = AssetMgr.instance.getTexture('ui_gongyong_zhiwanzidi_wenzikuang');
            var ui_gongyong_zhiwanzidi_wenzikuang33712img_8:Image = new Image(txture_ui_gongyong_zhiwanzidi_wenzikuang33712);
            ui_gongyong_zhiwanzidi_wenzikuang33712img_8.x = 337;
            ui_gongyong_zhiwanzidi_wenzikuang33712img_8.y = 12;
            ui_gongyong_zhiwanzidi_wenzikuang33712img_8.width = 36;
            ui_gongyong_zhiwanzidi_wenzikuang33712img_8.height = 49;
            ui_gongyong_zhiwanzidi_wenzikuang33712img_8.scaleX = -1.496124267578125;
            ui_gongyong_zhiwanzidi_wenzikuang33712img_8.smoothing = Constants.smoothing;
            //  ui_gongyong_zhiwanzidi_wenzikuang33712img_8.touchable = false;
            this.addQuiackChild(ui_gongyong_zhiwanzidi_wenzikuang33712img_8);
            txt_title = new TextField(197, 41, '', '', 28, 0x2E0203, false);
            txt_title.touchable = false;
            txt_title.hAlign = 'center';
            txt_title.text = '关卡奖励';
            txt_title.x = 134;
            txt_title.y = 15;
            this.addQuiackChild(txt_title);
            txt_cu_progress = new TextField(123, 33, '', '', 22, 0x2E0203, false);
            txt_cu_progress.touchable = false;
            txt_cu_progress.hAlign = 'left';
            txt_cu_progress.text = '当前进度';
            txt_cu_progress.x = 36;
            txt_cu_progress.y = 75;
            this.addQuiackChild(txt_cu_progress);
            txt_tolltage_num = new TextField(123, 36, '', '', 24, 0xFB000F, false);
            txt_tolltage_num.touchable = false;
            txt_tolltage_num.hAlign = 'left';
            txt_tolltage_num.text = '29/30';
            txt_tolltage_num.x = 165;
            txt_tolltage_num.y = 76;
            this.addQuiackChild(txt_tolltage_num);
            var txture_ui_atlas_bottom48113:Texture = AssetMgr.instance.getTexture('ui_atlas_bottom');
            var ui_atlas_bottom48113img_9:Image = new Image(txture_ui_atlas_bottom48113);
            ui_atlas_bottom48113img_9.x = 48;
            ui_atlas_bottom48113img_9.y = 113;
            ui_atlas_bottom48113img_9.width = 368;
            ui_atlas_bottom48113img_9.height = 160;
            ui_atlas_bottom48113img_9.smoothing = Constants.smoothing;
            ui_atlas_bottom48113img_9.touchable = false;
            this.addQuiackChild(ui_atlas_bottom48113img_9);
            txt_about = new TextField(369, 36, '', '', 24, 0xB83104, false);
            txt_about.touchable = false;
            txt_about.hAlign = 'center';
            txt_about.text = '通过关卡就能领取大礼包哦！';
            txt_about.x = 47;
            txt_about.y = 269;
            this.addQuiackChild(txt_about);
            txt_diamond = new TextField(123, 33, '', '', 22, 0x2E0203, false);
            txt_diamond.touchable = false;
            txt_diamond.hAlign = 'left';
            txt_diamond.text = 'x10000';
            txt_diamond.x = 310;
            txt_diamond.y = 122;
            this.addQuiackChild(txt_diamond);
            txt_star = new TextField(123, 33, '', '', 22, 0x2E0203, false);
            txt_star.touchable = false;
            txt_star.hAlign = 'left';
            txt_star.text = '0';
            txt_star.x = 310;
            txt_star.y = 175;
            this.addQuiackChild(txt_star);
            txt_tried = new TextField(123, 33, '', '', 22, 0x2E0203, false);
            txt_tried.touchable = false;
            txt_tried.hAlign = 'left';
            txt_tried.text = 'x50';
            txt_tried.x = 310;
            txt_tried.y = 238;
            this.addQuiackChild(txt_tried);
            var btn_get_giftButton_txture:Texture = AssetMgr.instance.getTexture('ui_shangcheng_jinxiangziguan');
            btn_get_giftButton = new Button(btn_get_giftButton_txture);
            btn_get_giftButton.x = 33;
            btn_get_giftButton.y = 69;
            this.addQuiackChild(btn_get_giftButton);
            var txture_mc_icon:Texture = AssetMgr.instance.getTexture('ui_gongyong_jianglilingqu');
            img_mc_icon = new Image(txture_mc_icon);
            img_mc_icon.touchable = false;
            img_mc_icon.x = 165;
            img_mc_icon.y = 215;
            img_mc_icon.width = 95;
            img_mc_icon.height = 39;
            this.addQuiackChild(img_mc_icon);
            var txture_ui_gongyong_zuanshi261115:Texture = AssetMgr.instance.getTexture('ui_gongyong_zuanshi');
            var ui_gongyong_zuanshi261115img_10:Image = new Image(txture_ui_gongyong_zuanshi261115);
            ui_gongyong_zuanshi261115img_10.x = 261;
            ui_gongyong_zuanshi261115img_10.y = 115;
            ui_gongyong_zuanshi261115img_10.width = 46;
            ui_gongyong_zuanshi261115img_10.height = 44;
            ui_gongyong_zuanshi261115img_10.smoothing = Constants.smoothing;
            ui_gongyong_zuanshi261115img_10.touchable = false;
            this.addQuiackChild(ui_gongyong_zuanshi261115img_10);
            var txture_ui_wudixingyunxing_xingxing260228:Texture = AssetMgr.instance.getTexture('ui_wudixingyunxing_xingxing');
            var ui_wudixingyunxing_xingxing260228img_11:Image = new Image(txture_ui_wudixingyunxing_xingxing260228);
            ui_wudixingyunxing_xingxing260228img_11.x = 260;
            ui_wudixingyunxing_xingxing260228img_11.y = 228;
            ui_wudixingyunxing_xingxing260228img_11.width = 47;
            ui_wudixingyunxing_xingxing260228img_11.height = 45;
            ui_wudixingyunxing_xingxing260228img_11.smoothing = Constants.smoothing;
            ui_wudixingyunxing_xingxing260228img_11.touchable = false;
            this.addQuiackChild(ui_wudixingyunxing_xingxing260228img_11);
            var txture_ui_tubiao_zhuxianpilaozhi265170:Texture = AssetMgr.instance.getTexture('ui_tubiao_zhuxianpilaozhi');
            var ui_tubiao_zhuxianpilaozhi265170img_12:Image = new Image(txture_ui_tubiao_zhuxianpilaozhi265170);
            ui_tubiao_zhuxianpilaozhi265170img_12.x = 265;
            ui_tubiao_zhuxianpilaozhi265170img_12.y = 170;
            ui_tubiao_zhuxianpilaozhi265170img_12.width = 38;
            ui_tubiao_zhuxianpilaozhi265170img_12.height = 48;
            ui_tubiao_zhuxianpilaozhi265170img_12.smoothing = Constants.smoothing;
            ui_tubiao_zhuxianpilaozhi265170img_12.touchable = false;
            this.addQuiackChild(ui_tubiao_zhuxianpilaozhi265170img_12);

        }

        override public function dispose():void {
            btn_get_giftButton.dispose();
            super.dispose();

        }

    }
}
