package game.view.activity.base {
    import com.dialog.Dialog;
    import com.utils.Constants;

    import game.manager.AssetMgr;

    import starling.display.Button;
    import starling.display.Image;
    import starling.text.TextField;
    import starling.textures.Texture;

    public class ActivityDlgBase extends Dialog {
        public var closeButton:Button;
        public var diamondTxt:TextField;
        public var k1Txt:TextField;
        public var RechargeButton:Button;
        public var dsf2234Image:Image;
        public var moneyTxt:TextField;
        public var kTxt:TextField;

        public function ActivityDlgBase() {
            var ui_gongyong_tielianpaizi35826Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_tielianpaizi');
            var ui_gongyong_tielianpaizi35826Image:Image = new Image(ui_gongyong_tielianpaizi35826Texture);
            ui_gongyong_tielianpaizi35826Image.x = 358;
            ui_gongyong_tielianpaizi35826Image.y = -25;
            ui_gongyong_tielianpaizi35826Image.width = 244;
            ui_gongyong_tielianpaizi35826Image.height = 137;
            ui_gongyong_tielianpaizi35826Image.smoothing = Constants.smoothing;
            ui_gongyong_tielianpaizi35826Image.touchable = false;
            this.addQuiackChild(ui_gongyong_tielianpaizi35826Image);
            var closeTexture:Texture = AssetMgr.instance.getTexture('ui_gongyong_tuichuanniiu');
            closeButton = new Button(closeTexture);
            closeButton.x = 829;
            closeButton.y = -40;
            this.addQuiackChild(closeButton);
            var ui_gongyong_yibanmubanhentiao0110Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao0110Image:Image = new Image(ui_gongyong_yibanmubanhentiao0110Texture);
            ui_gongyong_yibanmubanhentiao0110Image.x = 0;
            ui_gongyong_yibanmubanhentiao0110Image.y = 110;
            ui_gongyong_yibanmubanhentiao0110Image.width = 490;
            ui_gongyong_yibanmubanhentiao0110Image.height = 73;
            ui_gongyong_yibanmubanhentiao0110Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao0110Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao0110Image);
            var ui_gongyong_yibanmubanhentiao960110Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao960110Image:Image = new Image(ui_gongyong_yibanmubanhentiao960110Texture);
            ui_gongyong_yibanmubanhentiao960110Image.x = 960;
            ui_gongyong_yibanmubanhentiao960110Image.y = 110;
            ui_gongyong_yibanmubanhentiao960110Image.width = 490;
            ui_gongyong_yibanmubanhentiao960110Image.height = 73;
            ui_gongyong_yibanmubanhentiao960110Image.scaleX = -1;
            ui_gongyong_yibanmubanhentiao960110Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao960110Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao960110Image);
            var ui_gongyong_yibanmubanhentiao0183Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao0183Image:Image = new Image(ui_gongyong_yibanmubanhentiao0183Texture);
            ui_gongyong_yibanmubanhentiao0183Image.x = 0;
            ui_gongyong_yibanmubanhentiao0183Image.y = 183;
            ui_gongyong_yibanmubanhentiao0183Image.width = 490;
            ui_gongyong_yibanmubanhentiao0183Image.height = 73;
            ui_gongyong_yibanmubanhentiao0183Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao0183Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao0183Image);
            var ui_gongyong_yibanmubanhentiao960183Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao960183Image:Image = new Image(ui_gongyong_yibanmubanhentiao960183Texture);
            ui_gongyong_yibanmubanhentiao960183Image.x = 960;
            ui_gongyong_yibanmubanhentiao960183Image.y = 183;
            ui_gongyong_yibanmubanhentiao960183Image.width = 490;
            ui_gongyong_yibanmubanhentiao960183Image.height = 73;
            ui_gongyong_yibanmubanhentiao960183Image.scaleX = -1;
            ui_gongyong_yibanmubanhentiao960183Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao960183Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao960183Image);
            var ui_gongyong_yibanmubanhentiao0256Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao0256Image:Image = new Image(ui_gongyong_yibanmubanhentiao0256Texture);
            ui_gongyong_yibanmubanhentiao0256Image.x = 0;
            ui_gongyong_yibanmubanhentiao0256Image.y = 256;
            ui_gongyong_yibanmubanhentiao0256Image.width = 490;
            ui_gongyong_yibanmubanhentiao0256Image.height = 73;
            ui_gongyong_yibanmubanhentiao0256Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao0256Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao0256Image);
            var ui_gongyong_yibanmubanhentiao960256Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao960256Image:Image = new Image(ui_gongyong_yibanmubanhentiao960256Texture);
            ui_gongyong_yibanmubanhentiao960256Image.x = 960;
            ui_gongyong_yibanmubanhentiao960256Image.y = 256;
            ui_gongyong_yibanmubanhentiao960256Image.width = 490;
            ui_gongyong_yibanmubanhentiao960256Image.height = 73;
            ui_gongyong_yibanmubanhentiao960256Image.scaleX = -1;
            ui_gongyong_yibanmubanhentiao960256Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao960256Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao960256Image);
            var ui_gongyong_yibanmubanhentiao0329Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao0329Image:Image = new Image(ui_gongyong_yibanmubanhentiao0329Texture);
            ui_gongyong_yibanmubanhentiao0329Image.x = 0;
            ui_gongyong_yibanmubanhentiao0329Image.y = 329;
            ui_gongyong_yibanmubanhentiao0329Image.width = 490;
            ui_gongyong_yibanmubanhentiao0329Image.height = 73;
            ui_gongyong_yibanmubanhentiao0329Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao0329Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao0329Image);
            var ui_gongyong_yibanmubanhentiao960329Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao960329Image:Image = new Image(ui_gongyong_yibanmubanhentiao960329Texture);
            ui_gongyong_yibanmubanhentiao960329Image.x = 960;
            ui_gongyong_yibanmubanhentiao960329Image.y = 329;
            ui_gongyong_yibanmubanhentiao960329Image.width = 490;
            ui_gongyong_yibanmubanhentiao960329Image.height = 73;
            ui_gongyong_yibanmubanhentiao960329Image.scaleX = -1;
            ui_gongyong_yibanmubanhentiao960329Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao960329Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao960329Image);
            var ui_gongyong_yibanmubanhentiao0402Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao0402Image:Image = new Image(ui_gongyong_yibanmubanhentiao0402Texture);
            ui_gongyong_yibanmubanhentiao0402Image.x = 0;
            ui_gongyong_yibanmubanhentiao0402Image.y = 402;
            ui_gongyong_yibanmubanhentiao0402Image.width = 490;
            ui_gongyong_yibanmubanhentiao0402Image.height = 73;
            ui_gongyong_yibanmubanhentiao0402Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao0402Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao0402Image);
            var ui_gongyong_yibanmubanhentiao960402Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao960402Image:Image = new Image(ui_gongyong_yibanmubanhentiao960402Texture);
            ui_gongyong_yibanmubanhentiao960402Image.x = 960;
            ui_gongyong_yibanmubanhentiao960402Image.y = 402;
            ui_gongyong_yibanmubanhentiao960402Image.width = 490;
            ui_gongyong_yibanmubanhentiao960402Image.height = 73;
            ui_gongyong_yibanmubanhentiao960402Image.scaleX = -1;
            ui_gongyong_yibanmubanhentiao960402Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao960402Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao960402Image);
            var ui_gongyong_yibanmubanhentiao0475Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao0475Image:Image = new Image(ui_gongyong_yibanmubanhentiao0475Texture);
            ui_gongyong_yibanmubanhentiao0475Image.x = 0;
            ui_gongyong_yibanmubanhentiao0475Image.y = 475;
            ui_gongyong_yibanmubanhentiao0475Image.width = 490;
            ui_gongyong_yibanmubanhentiao0475Image.height = 73;
            ui_gongyong_yibanmubanhentiao0475Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao0475Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao0475Image);
            var ui_gongyong_yibanmubanhentiao960475Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao960475Image:Image = new Image(ui_gongyong_yibanmubanhentiao960475Texture);
            ui_gongyong_yibanmubanhentiao960475Image.x = 960;
            ui_gongyong_yibanmubanhentiao960475Image.y = 475;
            ui_gongyong_yibanmubanhentiao960475Image.width = 490;
            ui_gongyong_yibanmubanhentiao960475Image.height = 73;
            ui_gongyong_yibanmubanhentiao960475Image.scaleX = -1;
            ui_gongyong_yibanmubanhentiao960475Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao960475Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao960475Image);
            var ui_gongyong_yibanmubanhentiao0548Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao0548Image:Image = new Image(ui_gongyong_yibanmubanhentiao0548Texture);
            ui_gongyong_yibanmubanhentiao0548Image.x = 0;
            ui_gongyong_yibanmubanhentiao0548Image.y = 548;
            ui_gongyong_yibanmubanhentiao0548Image.width = 490;
            ui_gongyong_yibanmubanhentiao0548Image.height = 73;
            ui_gongyong_yibanmubanhentiao0548Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao0548Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao0548Image);
            var ui_gongyong_yibanmubanhentiao960548Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao960548Image:Image = new Image(ui_gongyong_yibanmubanhentiao960548Texture);
            ui_gongyong_yibanmubanhentiao960548Image.x = 960;
            ui_gongyong_yibanmubanhentiao960548Image.y = 548;
            ui_gongyong_yibanmubanhentiao960548Image.width = 490;
            ui_gongyong_yibanmubanhentiao960548Image.height = 73;
            ui_gongyong_yibanmubanhentiao960548Image.scaleX = -1;
            ui_gongyong_yibanmubanhentiao960548Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao960548Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao960548Image);
            var ui_background_intensify3257595Texture:Texture = AssetMgr.instance.getTexture('ui_background_intensify3');
            var ui_background_intensify3257595Image:Image = new Image(ui_background_intensify3257595Texture);
            ui_background_intensify3257595Image.x = 257;
            ui_background_intensify3257595Image.y = 595;
            ui_background_intensify3257595Image.width = 683;
            ui_background_intensify3257595Image.height = 1;
            ui_background_intensify3257595Image.smoothing = Constants.smoothing;
            ui_background_intensify3257595Image.touchable = false;
            this.addQuiackChild(ui_background_intensify3257595Image);
            var ui_gongyong_jinbibaizidi2405Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_jinbibaizidi2');
            var ui_gongyong_jinbibaizidi2405Image:Image = new Image(ui_gongyong_jinbibaizidi2405Texture);
            ui_gongyong_jinbibaizidi2405Image.x = 40;
            ui_gongyong_jinbibaizidi2405Image.y = 5;
            ui_gongyong_jinbibaizidi2405Image.width = 197;
            ui_gongyong_jinbibaizidi2405Image.height = 99;
            ui_gongyong_jinbibaizidi2405Image.smoothing = Constants.smoothing;
            ui_gongyong_jinbibaizidi2405Image.touchable = false;
            this.addQuiackChild(ui_gongyong_jinbibaizidi2405Image);
            diamondTxt = new TextField(166, 44, '', '', 26, 0xffffff, false);
            diamondTxt.touchable = false;
            diamondTxt.hAlign = 'left';
            diamondTxt.x = 92;
            diamondTxt.y = 58;
            this.addQuiackChild(diamondTxt);
            k1Txt = new TextField(34, 46, '', '', 32, 0xff9201, false);
            k1Txt.touchable = false;
            k1Txt.hAlign = 'left';
            k1Txt.x = 191;
            k1Txt.y = 56;
            this.addQuiackChild(k1Txt);
            var RechargeTexture:Texture = AssetMgr.instance.getTexture('ui_button_chongzhitubiao');
            RechargeButton = new Button(RechargeTexture);
            RechargeButton.x = 245;
            RechargeButton.y = 44;
            this.addQuiackChild(RechargeButton);
            var dsf2234Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_zuanshi');
            dsf2234Image = new Image(dsf2234Texture);
            dsf2234Image.x = 49;
            dsf2234Image.y = 55;
            dsf2234Image.width = 46;
            dsf2234Image.height = 44;
            this.addQuiackChild(dsf2234Image);
            var ui_background_intensify311117Texture:Texture = AssetMgr.instance.getTexture('ui_background_intensify3');
            var ui_background_intensify311117Image:Image = new Image(ui_background_intensify311117Texture);
            ui_background_intensify311117Image.x = 11;
            ui_background_intensify311117Image.y = 117;
            ui_background_intensify311117Image.width = 934;
            ui_background_intensify311117Image.height = 1;
            ui_background_intensify311117Image.smoothing = Constants.smoothing;
            ui_background_intensify311117Image.touchable = false;
            this.addQuiackChild(ui_background_intensify311117Image);
            var ui_gongyong_bumangdi_shangbianyikuaitie358105Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_bumangdi_shangbianyikuaitie');
            var ui_gongyong_bumangdi_shangbianyikuaitie358105Image:Image = new Image(ui_gongyong_bumangdi_shangbianyikuaitie358105Texture);
            ui_gongyong_bumangdi_shangbianyikuaitie358105Image.x = 358;
            ui_gongyong_bumangdi_shangbianyikuaitie358105Image.y = 105;
            ui_gongyong_bumangdi_shangbianyikuaitie358105Image.width = 30;
            ui_gongyong_bumangdi_shangbianyikuaitie358105Image.height = 21;
            ui_gongyong_bumangdi_shangbianyikuaitie358105Image.smoothing = Constants.smoothing;
            ui_gongyong_bumangdi_shangbianyikuaitie358105Image.touchable = false;
            this.addQuiackChild(ui_gongyong_bumangdi_shangbianyikuaitie358105Image);
            var ui_gongyong_bumangdi_shangbianyikuaitie602105Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_bumangdi_shangbianyikuaitie');
            var ui_gongyong_bumangdi_shangbianyikuaitie602105Image:Image = new Image(ui_gongyong_bumangdi_shangbianyikuaitie602105Texture);
            ui_gongyong_bumangdi_shangbianyikuaitie602105Image.x = 602;
            ui_gongyong_bumangdi_shangbianyikuaitie602105Image.y = 105;
            ui_gongyong_bumangdi_shangbianyikuaitie602105Image.width = 30;
            ui_gongyong_bumangdi_shangbianyikuaitie602105Image.height = 21;
            ui_gongyong_bumangdi_shangbianyikuaitie602105Image.scaleX = -1;
            ui_gongyong_bumangdi_shangbianyikuaitie602105Image.smoothing = Constants.smoothing;
            ui_gongyong_bumangdi_shangbianyikuaitie602105Image.touchable = false;
            this.addQuiackChild(ui_gongyong_bumangdi_shangbianyikuaitie602105Image);
            var ui_gongyong_jinbi5017Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_jinbi');
            var ui_gongyong_jinbi5017Image:Image = new Image(ui_gongyong_jinbi5017Texture);
            ui_gongyong_jinbi5017Image.x = 50;
            ui_gongyong_jinbi5017Image.y = 17;
            ui_gongyong_jinbi5017Image.width = 40;
            ui_gongyong_jinbi5017Image.height = 40;
            ui_gongyong_jinbi5017Image.smoothing = Constants.smoothing;
            ui_gongyong_jinbi5017Image.touchable = false;
            this.addQuiackChild(ui_gongyong_jinbi5017Image);
            moneyTxt = new TextField(166, 44, '', '', 26, 0xffffff, false);
            moneyTxt.touchable = false;
            moneyTxt.hAlign = 'left';
            moneyTxt.x = 92;
            moneyTxt.y = 17;
            this.addQuiackChild(moneyTxt);
            kTxt = new TextField(30, 46, '', '', 32, 0xff9201, false);
            kTxt.touchable = false;
            kTxt.hAlign = 'left';
            kTxt.x = 191;
            kTxt.y = 14;
            this.addQuiackChild(kTxt);
            var ui_activities_zi43736Texture:Texture = AssetMgr.instance.getTexture('ui_activities_zi');
            var ui_activities_zi43736Image:Image = new Image(ui_activities_zi43736Texture);
            ui_activities_zi43736Image.x = 437;
            ui_activities_zi43736Image.y = 36;
            ui_activities_zi43736Image.width = 85;
            ui_activities_zi43736Image.height = 42;
            ui_activities_zi43736Image.smoothing = Constants.smoothing;
            ui_activities_zi43736Image.touchable = false;
            this.addQuiackChild(ui_activities_zi43736Image);
            var ui_gongyong_wupingkuang_baozaodibian3_hei41164Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_wupingkuang_baozaodibian3_hei');
            var ui_gongyong_wupingkuang_baozaodibian3_hei41164Image:Image = new Image(ui_gongyong_wupingkuang_baozaodibian3_hei41164Texture);
            ui_gongyong_wupingkuang_baozaodibian3_hei41164Image.x = 41;
            ui_gongyong_wupingkuang_baozaodibian3_hei41164Image.y = 164;
            ui_gongyong_wupingkuang_baozaodibian3_hei41164Image.width = 197;
            ui_gongyong_wupingkuang_baozaodibian3_hei41164Image.height = 425;
            ui_gongyong_wupingkuang_baozaodibian3_hei41164Image.smoothing = Constants.smoothing;
            ui_gongyong_wupingkuang_baozaodibian3_hei41164Image.touchable = false;
            this.addQuiackChild(ui_gongyong_wupingkuang_baozaodibian3_hei41164Image);
            var ui_gongyong_wupingkuang_baozaodibian2_hei42130Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_wupingkuang_baozaodibian2_hei');
            var ui_gongyong_wupingkuang_baozaodibian2_hei42130Image:Image = new Image(ui_gongyong_wupingkuang_baozaodibian2_hei42130Texture);
            ui_gongyong_wupingkuang_baozaodibian2_hei42130Image.x = 42;
            ui_gongyong_wupingkuang_baozaodibian2_hei42130Image.y = 130;
            ui_gongyong_wupingkuang_baozaodibian2_hei42130Image.width = 196;
            ui_gongyong_wupingkuang_baozaodibian2_hei42130Image.height = 47;
            ui_gongyong_wupingkuang_baozaodibian2_hei42130Image.smoothing = Constants.smoothing;
            ui_gongyong_wupingkuang_baozaodibian2_hei42130Image.touchable = false;
            this.addQuiackChild(ui_gongyong_wupingkuang_baozaodibian2_hei42130Image);
            var ui_gongyong_wupingkuang_baozaodibian_hei201333Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_wupingkuang_baozaodibian_hei');
            var ui_gongyong_wupingkuang_baozaodibian_hei201333Image:Image = new Image(ui_gongyong_wupingkuang_baozaodibian_hei201333Texture);
            ui_gongyong_wupingkuang_baozaodibian_hei201333Image.x = 201;
            ui_gongyong_wupingkuang_baozaodibian_hei201333Image.y = 333;
            ui_gongyong_wupingkuang_baozaodibian_hei201333Image.width = 40;
            ui_gongyong_wupingkuang_baozaodibian_hei201333Image.height = 261;
            ui_gongyong_wupingkuang_baozaodibian_hei201333Image.smoothing = Constants.smoothing;
            ui_gongyong_wupingkuang_baozaodibian_hei201333Image.touchable = false;
            this.addQuiackChild(ui_gongyong_wupingkuang_baozaodibian_hei201333Image);
            var ui_gongyong_wupingkuang_baozaodibian_hei71391Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_wupingkuang_baozaodibian_hei');
            var ui_gongyong_wupingkuang_baozaodibian_hei71391Image:Image = new Image(ui_gongyong_wupingkuang_baozaodibian_hei71391Texture);
            ui_gongyong_wupingkuang_baozaodibian_hei71391Image.x = 71;
            ui_gongyong_wupingkuang_baozaodibian_hei71391Image.y = 391;
            ui_gongyong_wupingkuang_baozaodibian_hei71391Image.width = 40;
            ui_gongyong_wupingkuang_baozaodibian_hei71391Image.height = 261;
            ui_gongyong_wupingkuang_baozaodibian_hei71391Image.scaleX = -1;
            ui_gongyong_wupingkuang_baozaodibian_hei71391Image.scaleY = -1;
            ui_gongyong_wupingkuang_baozaodibian_hei71391Image.smoothing = Constants.smoothing;
            ui_gongyong_wupingkuang_baozaodibian_hei71391Image.touchable = false;
            this.addQuiackChild(ui_gongyong_wupingkuang_baozaodibian_hei71391Image);
            var ui_gongyong_wupingkuang_baozaodibian1_hei241372Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_wupingkuang_baozaodibian1_hei');
            var ui_gongyong_wupingkuang_baozaodibian1_hei241372Image:Image = new Image(ui_gongyong_wupingkuang_baozaodibian1_hei241372Texture);
            ui_gongyong_wupingkuang_baozaodibian1_hei241372Image.x = 241;
            ui_gongyong_wupingkuang_baozaodibian1_hei241372Image.y = 372;
            ui_gongyong_wupingkuang_baozaodibian1_hei241372Image.width = 20;
            ui_gongyong_wupingkuang_baozaodibian1_hei241372Image.height = 242;
            ui_gongyong_wupingkuang_baozaodibian1_hei241372Image.scaleX = -1;
            ui_gongyong_wupingkuang_baozaodibian1_hei241372Image.scaleY = -1;
            ui_gongyong_wupingkuang_baozaodibian1_hei241372Image.smoothing = Constants.smoothing;
            ui_gongyong_wupingkuang_baozaodibian1_hei241372Image.touchable = false;
            this.addQuiackChild(ui_gongyong_wupingkuang_baozaodibian1_hei241372Image);
            var ui_gongyong_wupingkuang_baozaodibian2_hei41600Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_wupingkuang_baozaodibian2_hei');
            var ui_gongyong_wupingkuang_baozaodibian2_hei41600Image:Image = new Image(ui_gongyong_wupingkuang_baozaodibian2_hei41600Texture);
            ui_gongyong_wupingkuang_baozaodibian2_hei41600Image.x = 41;
            ui_gongyong_wupingkuang_baozaodibian2_hei41600Image.y = 600;
            ui_gongyong_wupingkuang_baozaodibian2_hei41600Image.width = 196;
            ui_gongyong_wupingkuang_baozaodibian2_hei41600Image.height = 47;
            ui_gongyong_wupingkuang_baozaodibian2_hei41600Image.scaleY = -1;
            ui_gongyong_wupingkuang_baozaodibian2_hei41600Image.smoothing = Constants.smoothing;
            ui_gongyong_wupingkuang_baozaodibian2_hei41600Image.touchable = false;
            this.addQuiackChild(ui_gongyong_wupingkuang_baozaodibian2_hei41600Image);
            var ui_gongyong_wupingkuang_baozaodibian1_hei32358Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_wupingkuang_baozaodibian1_hei');
            var ui_gongyong_wupingkuang_baozaodibian1_hei32358Image:Image = new Image(ui_gongyong_wupingkuang_baozaodibian1_hei32358Texture);
            ui_gongyong_wupingkuang_baozaodibian1_hei32358Image.x = 32;
            ui_gongyong_wupingkuang_baozaodibian1_hei32358Image.y = 358;
            ui_gongyong_wupingkuang_baozaodibian1_hei32358Image.width = 20;
            ui_gongyong_wupingkuang_baozaodibian1_hei32358Image.height = 242;
            ui_gongyong_wupingkuang_baozaodibian1_hei32358Image.smoothing = Constants.smoothing;
            ui_gongyong_wupingkuang_baozaodibian1_hei32358Image.touchable = false;
            this.addQuiackChild(ui_gongyong_wupingkuang_baozaodibian1_hei32358Image);
            var ui_gongyong_wupingkuang_baozaodibian1_hei256359Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_wupingkuang_baozaodibian1_hei');
            var ui_gongyong_wupingkuang_baozaodibian1_hei256359Image:Image = new Image(ui_gongyong_wupingkuang_baozaodibian1_hei256359Texture);
            ui_gongyong_wupingkuang_baozaodibian1_hei256359Image.x = 256;
            ui_gongyong_wupingkuang_baozaodibian1_hei256359Image.y = 359;
            ui_gongyong_wupingkuang_baozaodibian1_hei256359Image.width = 20;
            ui_gongyong_wupingkuang_baozaodibian1_hei256359Image.height = 242;
            ui_gongyong_wupingkuang_baozaodibian1_hei256359Image.smoothing = Constants.smoothing;
            ui_gongyong_wupingkuang_baozaodibian1_hei256359Image.touchable = false;
            this.addQuiackChild(ui_gongyong_wupingkuang_baozaodibian1_hei256359Image);
            var ui_gongyong_wupingkuang_baozaodibian2_hei277131Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_wupingkuang_baozaodibian2_hei');
            var ui_gongyong_wupingkuang_baozaodibian2_hei277131Image:Image = new Image(ui_gongyong_wupingkuang_baozaodibian2_hei277131Texture);
            ui_gongyong_wupingkuang_baozaodibian2_hei277131Image.x = 277;
            ui_gongyong_wupingkuang_baozaodibian2_hei277131Image.y = 131;
            ui_gongyong_wupingkuang_baozaodibian2_hei277131Image.width = 637;
            ui_gongyong_wupingkuang_baozaodibian2_hei277131Image.height = 47;
            ui_gongyong_wupingkuang_baozaodibian2_hei277131Image.smoothing = Constants.smoothing;
            ui_gongyong_wupingkuang_baozaodibian2_hei277131Image.touchable = false;
            this.addQuiackChild(ui_gongyong_wupingkuang_baozaodibian2_hei277131Image);
            var ui_gongyong_wupingkuang_baozaodibian_hei295392Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_wupingkuang_baozaodibian_hei');
            var ui_gongyong_wupingkuang_baozaodibian_hei295392Image:Image = new Image(ui_gongyong_wupingkuang_baozaodibian_hei295392Texture);
            ui_gongyong_wupingkuang_baozaodibian_hei295392Image.x = 295;
            ui_gongyong_wupingkuang_baozaodibian_hei295392Image.y = 392;
            ui_gongyong_wupingkuang_baozaodibian_hei295392Image.width = 40;
            ui_gongyong_wupingkuang_baozaodibian_hei295392Image.height = 261;
            ui_gongyong_wupingkuang_baozaodibian_hei295392Image.scaleX = -1;
            ui_gongyong_wupingkuang_baozaodibian_hei295392Image.scaleY = -1;
            ui_gongyong_wupingkuang_baozaodibian_hei295392Image.smoothing = Constants.smoothing;
            ui_gongyong_wupingkuang_baozaodibian_hei295392Image.touchable = false;
            this.addQuiackChild(ui_gongyong_wupingkuang_baozaodibian_hei295392Image);
            var ui_gongyong_wupingkuang_baozaodibian1_hei933373Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_wupingkuang_baozaodibian1_hei');
            var ui_gongyong_wupingkuang_baozaodibian1_hei933373Image:Image = new Image(ui_gongyong_wupingkuang_baozaodibian1_hei933373Texture);
            ui_gongyong_wupingkuang_baozaodibian1_hei933373Image.x = 933;
            ui_gongyong_wupingkuang_baozaodibian1_hei933373Image.y = 373;
            ui_gongyong_wupingkuang_baozaodibian1_hei933373Image.width = 20;
            ui_gongyong_wupingkuang_baozaodibian1_hei933373Image.height = 242;
            ui_gongyong_wupingkuang_baozaodibian1_hei933373Image.scaleX = -1;
            ui_gongyong_wupingkuang_baozaodibian1_hei933373Image.scaleY = -1;
            ui_gongyong_wupingkuang_baozaodibian1_hei933373Image.smoothing = Constants.smoothing;
            ui_gongyong_wupingkuang_baozaodibian1_hei933373Image.touchable = false;
            this.addQuiackChild(ui_gongyong_wupingkuang_baozaodibian1_hei933373Image);
            var ui_gongyong_wupingkuang_baozaodibian2_hei274601Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_wupingkuang_baozaodibian2_hei');
            var ui_gongyong_wupingkuang_baozaodibian2_hei274601Image:Image = new Image(ui_gongyong_wupingkuang_baozaodibian2_hei274601Texture);
            ui_gongyong_wupingkuang_baozaodibian2_hei274601Image.x = 274;
            ui_gongyong_wupingkuang_baozaodibian2_hei274601Image.y = 601;
            ui_gongyong_wupingkuang_baozaodibian2_hei274601Image.width = 625;
            ui_gongyong_wupingkuang_baozaodibian2_hei274601Image.height = 47;
            ui_gongyong_wupingkuang_baozaodibian2_hei274601Image.scaleY = -1;
            ui_gongyong_wupingkuang_baozaodibian2_hei274601Image.smoothing = Constants.smoothing;
            ui_gongyong_wupingkuang_baozaodibian2_hei274601Image.touchable = false;
            this.addQuiackChild(ui_gongyong_wupingkuang_baozaodibian2_hei274601Image);
            var ui_background_intensify336599Texture:Texture = AssetMgr.instance.getTexture('ui_background_intensify3');
            var ui_background_intensify336599Image:Image = new Image(ui_background_intensify336599Texture);
            ui_background_intensify336599Image.x = 36;
            ui_background_intensify336599Image.y = 599;
            ui_background_intensify336599Image.width = 201;
            ui_background_intensify336599Image.height = 1;
            ui_background_intensify336599Image.smoothing = Constants.smoothing;
            ui_background_intensify336599Image.touchable = false;
            this.addQuiackChild(ui_background_intensify336599Image);
            var ui_background_intensify3257602Texture:Texture = AssetMgr.instance.getTexture('ui_background_intensify3');
            var ui_background_intensify3257602Image:Image = new Image(ui_background_intensify3257602Texture);
            ui_background_intensify3257602Image.x = 257;
            ui_background_intensify3257602Image.y = 602;
            ui_background_intensify3257602Image.width = 683;
            ui_background_intensify3257602Image.height = 1;
            ui_background_intensify3257602Image.smoothing = Constants.smoothing;
            ui_background_intensify3257602Image.touchable = false;
            this.addQuiackChild(ui_background_intensify3257602Image);
            var ui_background_intensify3257601Texture:Texture = AssetMgr.instance.getTexture('ui_background_intensify3');
            var ui_background_intensify3257601Image:Image = new Image(ui_background_intensify3257601Texture);
            ui_background_intensify3257601Image.x = 257;
            ui_background_intensify3257601Image.y = 601;
            ui_background_intensify3257601Image.width = 683;
            ui_background_intensify3257601Image.height = 1;
            ui_background_intensify3257601Image.smoothing = Constants.smoothing;
            ui_background_intensify3257601Image.touchable = false;
            this.addQuiackChild(ui_background_intensify3257601Image);
            var ui_background_intensify340599Texture:Texture = AssetMgr.instance.getTexture('ui_background_intensify3');
            var ui_background_intensify340599Image:Image = new Image(ui_background_intensify340599Texture);
            ui_background_intensify340599Image.x = 40;
            ui_background_intensify340599Image.y = 599;
            ui_background_intensify340599Image.width = 201;
            ui_background_intensify340599Image.height = 1;
            ui_background_intensify340599Image.smoothing = Constants.smoothing;
            ui_background_intensify340599Image.touchable = false;
            this.addQuiackChild(ui_background_intensify340599Image);
            var ui_gongyong_wupingkuang_baozaodibian3_hei273165Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_wupingkuang_baozaodibian3_hei');
            var ui_gongyong_wupingkuang_baozaodibian3_hei273165Image:Image = new Image(ui_gongyong_wupingkuang_baozaodibian3_hei273165Texture);
            ui_gongyong_wupingkuang_baozaodibian3_hei273165Image.x = 273;
            ui_gongyong_wupingkuang_baozaodibian3_hei273165Image.y = 165;
            ui_gongyong_wupingkuang_baozaodibian3_hei273165Image.width = 641;
            ui_gongyong_wupingkuang_baozaodibian3_hei273165Image.height = 425;
            ui_gongyong_wupingkuang_baozaodibian3_hei273165Image.smoothing = Constants.smoothing;
            ui_gongyong_wupingkuang_baozaodibian3_hei273165Image.touchable = false;
            this.addQuiackChild(ui_gongyong_wupingkuang_baozaodibian3_hei273165Image);
            var ui_gongyong_wupingkuang_baozaodibian_hei893341Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_wupingkuang_baozaodibian_hei');
            var ui_gongyong_wupingkuang_baozaodibian_hei893341Image:Image = new Image(ui_gongyong_wupingkuang_baozaodibian_hei893341Texture);
            ui_gongyong_wupingkuang_baozaodibian_hei893341Image.x = 893;
            ui_gongyong_wupingkuang_baozaodibian_hei893341Image.y = 341;
            ui_gongyong_wupingkuang_baozaodibian_hei893341Image.width = 40;
            ui_gongyong_wupingkuang_baozaodibian_hei893341Image.height = 261;
            ui_gongyong_wupingkuang_baozaodibian_hei893341Image.smoothing = Constants.smoothing;
            ui_gongyong_wupingkuang_baozaodibian_hei893341Image.touchable = false;
            this.addQuiackChild(ui_gongyong_wupingkuang_baozaodibian_hei893341Image);

        }

        override public function dispose():void {
            closeButton.dispose();
            RechargeButton.dispose();
            super.dispose();

        }

    }
}
