package game.view.userLog {
    import com.dialog.Dialog;
    import com.utils.Constants;

    import flash.geom.Rectangle;
    import flash.text.StageText;

    import game.manager.AssetMgr;

    import starling.core.Starling;
    import starling.display.Button;
    import starling.display.Image;
    import starling.text.TextField;
    import starling.textures.Texture;

    public class GetBackPasswordVerificationCodeDlgBase extends Dialog {
        public var okButton:Button;
        public var backButton:Button;
        public var titleTxt:TextField;
        public var tips2Txt:TextField;
        public var tips1Txt:TextField;
        public var phoneNumberTxt:StageText;
        public var securityCodeTxt:StageText;
        public var securityCodeButton:Button;

        public function GetBackPasswordVerificationCodeDlgBase() {
            var ui_dengludi_muban14177Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_muban');
            var ui_dengludi_muban14177Image:Image = new Image(ui_dengludi_muban14177Texture);
            ui_dengludi_muban14177Image.x = 14;
            ui_dengludi_muban14177Image.y = 177;
            ui_dengludi_muban14177Image.width = 419;
            ui_dengludi_muban14177Image.height = 53;
            ui_dengludi_muban14177Image.smoothing = Constants.smoothing;
            ui_dengludi_muban14177Image.touchable = false;
            this.addQuiackChild(ui_dengludi_muban14177Image);
            var ui_dengludi_muban1472Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_muban');
            var ui_dengludi_muban1472Image:Image = new Image(ui_dengludi_muban1472Texture);
            ui_dengludi_muban1472Image.x = 14;
            ui_dengludi_muban1472Image.y = 72;
            ui_dengludi_muban1472Image.width = 419;
            ui_dengludi_muban1472Image.height = 53;
            ui_dengludi_muban1472Image.smoothing = Constants.smoothing;
            ui_dengludi_muban1472Image.touchable = false;
            this.addQuiackChild(ui_dengludi_muban1472Image);
            var ui_dengludi_muban14125Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_muban');
            var ui_dengludi_muban14125Image:Image = new Image(ui_dengludi_muban14125Texture);
            ui_dengludi_muban14125Image.x = 14;
            ui_dengludi_muban14125Image.y = 125;
            ui_dengludi_muban14125Image.width = 419;
            ui_dengludi_muban14125Image.height = 53;
            ui_dengludi_muban14125Image.smoothing = Constants.smoothing;
            ui_dengludi_muban14125Image.touchable = false;
            this.addQuiackChild(ui_dengludi_muban14125Image);
            var ui_dengludi_muban14229Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_muban');
            var ui_dengludi_muban14229Image:Image = new Image(ui_dengludi_muban14229Texture);
            ui_dengludi_muban14229Image.x = 14;
            ui_dengludi_muban14229Image.y = 229;
            ui_dengludi_muban14229Image.width = 419;
            ui_dengludi_muban14229Image.height = 53;
            ui_dengludi_muban14229Image.smoothing = Constants.smoothing;
            ui_dengludi_muban14229Image.touchable = false;
            this.addQuiackChild(ui_dengludi_muban14229Image);
            var okTexture:Texture = AssetMgr.instance.getTexture('ui_yonghuzhuce_button1');
            okButton = new Button(okTexture);
            okButton.x = 237;
            okButton.y = 327;
            this.addQuiackChild(okButton);
            okButton.textBounds = new Rectangle(14, 39, 145, 42);
            okButton.fontSize = 34;
            okButton.fontColor = 0xFFA200;
            okButton.fontBold = false;
            var backTexture:Texture = AssetMgr.instance.getTexture('ui_yonghuzhuce_button1');
            backButton = new Button(backTexture);
            backButton.x = 38;
            backButton.y = 327;
            this.addQuiackChild(backButton);
            backButton.textBounds = new Rectangle(14, 39, 145, 42);
            backButton.fontSize = 34;
            backButton.fontColor = 0xFFA200;
            backButton.fontBold = false;
            var ui_dengludi_muban14281Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_muban');
            var ui_dengludi_muban14281Image:Image = new Image(ui_dengludi_muban14281Texture);
            ui_dengludi_muban14281Image.x = 14;
            ui_dengludi_muban14281Image.y = 281;
            ui_dengludi_muban14281Image.width = 419;
            ui_dengludi_muban14281Image.height = 53;
            ui_dengludi_muban14281Image.smoothing = Constants.smoothing;
            ui_dengludi_muban14281Image.touchable = false;
            this.addQuiackChild(ui_dengludi_muban14281Image);
            var ui_dengludi_paizi120Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_paizi');
            var ui_dengludi_paizi120Image:Image = new Image(ui_dengludi_paizi120Texture);
            ui_dengludi_paizi120Image.x = 12;
            ui_dengludi_paizi120Image.y = 0;
            ui_dengludi_paizi120Image.width = 423;
            ui_dengludi_paizi120Image.height = 65;
            ui_dengludi_paizi120Image.smoothing = Constants.smoothing;
            ui_dengludi_paizi120Image.touchable = false;
            this.addQuiackChild(ui_dengludi_paizi120Image);
            var ui_dengludi_tietiao1575Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_tietiao1');
            var ui_dengludi_tietiao1575Image:Image = new Image(ui_dengludi_tietiao1575Texture);
            ui_dengludi_tietiao1575Image.x = 5;
            ui_dengludi_tietiao1575Image.y = 75;
            ui_dengludi_tietiao1575Image.width = 16;
            ui_dengludi_tietiao1575Image.height = 245;
            ui_dengludi_tietiao1575Image.smoothing = Constants.smoothing;
            ui_dengludi_tietiao1575Image.touchable = false;
            this.addQuiackChild(ui_dengludi_tietiao1575Image);
            var ui_dengludi_tietiao21665Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_tietiao2');
            var ui_dengludi_tietiao21665Image:Image = new Image(ui_dengludi_tietiao21665Texture);
            ui_dengludi_tietiao21665Image.x = 16;
            ui_dengludi_tietiao21665Image.y = 65;
            ui_dengludi_tietiao21665Image.width = 415;
            ui_dengludi_tietiao21665Image.height = 18;
            ui_dengludi_tietiao21665Image.smoothing = Constants.smoothing;
            ui_dengludi_tietiao21665Image.touchable = false;
            this.addQuiackChild(ui_dengludi_tietiao21665Image);
            var ui_dengludi_tietiao142575Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_tietiao1');
            var ui_dengludi_tietiao142575Image:Image = new Image(ui_dengludi_tietiao142575Texture);
            ui_dengludi_tietiao142575Image.x = 425;
            ui_dengludi_tietiao142575Image.y = 75;
            ui_dengludi_tietiao142575Image.width = 16;
            ui_dengludi_tietiao142575Image.height = 245;
            ui_dengludi_tietiao142575Image.smoothing = Constants.smoothing;
            ui_dengludi_tietiao142575Image.touchable = false;
            this.addQuiackChild(ui_dengludi_tietiao142575Image);
            var ui_dengludi_guaijiao44363Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_guaijiao');
            var ui_dengludi_guaijiao44363Image:Image = new Image(ui_dengludi_guaijiao44363Texture);
            ui_dengludi_guaijiao44363Image.x = 443;
            ui_dengludi_guaijiao44363Image.y = 63;
            ui_dengludi_guaijiao44363Image.width = 32;
            ui_dengludi_guaijiao44363Image.height = 33;
            ui_dengludi_guaijiao44363Image.scaleX = -1;
            ui_dengludi_guaijiao44363Image.smoothing = Constants.smoothing;
            ui_dengludi_guaijiao44363Image.touchable = false;
            this.addQuiackChild(ui_dengludi_guaijiao44363Image);
            var ui_dengludi_guaijiao063Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_guaijiao');
            var ui_dengludi_guaijiao063Image:Image = new Image(ui_dengludi_guaijiao063Texture);
            ui_dengludi_guaijiao063Image.x = 0;
            ui_dengludi_guaijiao063Image.y = 63;
            ui_dengludi_guaijiao063Image.width = 32;
            ui_dengludi_guaijiao063Image.height = 33;
            ui_dengludi_guaijiao063Image.smoothing = Constants.smoothing;
            ui_dengludi_guaijiao063Image.touchable = false;
            this.addQuiackChild(ui_dengludi_guaijiao063Image);
            var ui_dengludi_tietiao216330Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_tietiao2');
            var ui_dengludi_tietiao216330Image:Image = new Image(ui_dengludi_tietiao216330Texture);
            ui_dengludi_tietiao216330Image.x = 16;
            ui_dengludi_tietiao216330Image.y = 330;
            ui_dengludi_tietiao216330Image.width = 415;
            ui_dengludi_tietiao216330Image.height = 18;
            ui_dengludi_tietiao216330Image.smoothing = Constants.smoothing;
            ui_dengludi_tietiao216330Image.touchable = false;
            this.addQuiackChild(ui_dengludi_tietiao216330Image);
            var ui_dengludi_guagou38330Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_guagou');
            var ui_dengludi_guagou38330Image:Image = new Image(ui_dengludi_guagou38330Texture);
            ui_dengludi_guagou38330Image.x = 38;
            ui_dengludi_guagou38330Image.y = 330;
            ui_dengludi_guagou38330Image.width = 26;
            ui_dengludi_guagou38330Image.height = 21;
            ui_dengludi_guagou38330Image.smoothing = Constants.smoothing;
            ui_dengludi_guagou38330Image.touchable = false;
            this.addQuiackChild(ui_dengludi_guagou38330Image);
            var ui_dengludi_guaijiao443350Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_guaijiao');
            var ui_dengludi_guaijiao443350Image:Image = new Image(ui_dengludi_guaijiao443350Texture);
            ui_dengludi_guaijiao443350Image.x = 443;
            ui_dengludi_guaijiao443350Image.y = 350;
            ui_dengludi_guaijiao443350Image.width = 32;
            ui_dengludi_guaijiao443350Image.height = 33;
            ui_dengludi_guaijiao443350Image.scaleX = -1;
            ui_dengludi_guaijiao443350Image.scaleY = -1;
            ui_dengludi_guaijiao443350Image.smoothing = Constants.smoothing;
            ui_dengludi_guaijiao443350Image.touchable = false;
            this.addQuiackChild(ui_dengludi_guaijiao443350Image);
            var ui_dengludi_guaijiao0350Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_guaijiao');
            var ui_dengludi_guaijiao0350Image:Image = new Image(ui_dengludi_guaijiao0350Texture);
            ui_dengludi_guaijiao0350Image.x = 0;
            ui_dengludi_guaijiao0350Image.y = 350;
            ui_dengludi_guaijiao0350Image.width = 32;
            ui_dengludi_guaijiao0350Image.height = 33;
            ui_dengludi_guaijiao0350Image.scaleY = -1;
            ui_dengludi_guaijiao0350Image.smoothing = Constants.smoothing;
            ui_dengludi_guaijiao0350Image.touchable = false;
            this.addQuiackChild(ui_dengludi_guaijiao0350Image);
            var ui_dengludi_guagou408330Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_guagou');
            var ui_dengludi_guagou408330Image:Image = new Image(ui_dengludi_guagou408330Texture);
            ui_dengludi_guagou408330Image.x = 408;
            ui_dengludi_guagou408330Image.y = 330;
            ui_dengludi_guagou408330Image.width = 26;
            ui_dengludi_guagou408330Image.height = 21;
            ui_dengludi_guagou408330Image.scaleX = -1;
            ui_dengludi_guagou408330Image.smoothing = Constants.smoothing;
            ui_dengludi_guagou408330Image.touchable = false;
            this.addQuiackChild(ui_dengludi_guagou408330Image);
            var ui_dengludi_guagou239328Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_guagou');
            var ui_dengludi_guagou239328Image:Image = new Image(ui_dengludi_guagou239328Texture);
            ui_dengludi_guagou239328Image.x = 239;
            ui_dengludi_guagou239328Image.y = 328;
            ui_dengludi_guagou239328Image.width = 26;
            ui_dengludi_guagou239328Image.height = 21;
            ui_dengludi_guagou239328Image.smoothing = Constants.smoothing;
            ui_dengludi_guagou239328Image.touchable = false;
            this.addQuiackChild(ui_dengludi_guagou239328Image);
            var ui_dengludi_guagou208328Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_guagou');
            var ui_dengludi_guagou208328Image:Image = new Image(ui_dengludi_guagou208328Texture);
            ui_dengludi_guagou208328Image.x = 208;
            ui_dengludi_guagou208328Image.y = 328;
            ui_dengludi_guagou208328Image.width = 26;
            ui_dengludi_guagou208328Image.height = 21;
            ui_dengludi_guagou208328Image.scaleX = -1;
            ui_dengludi_guagou208328Image.smoothing = Constants.smoothing;
            ui_dengludi_guagou208328Image.touchable = false;
            this.addQuiackChild(ui_dengludi_guagou208328Image);
            titleTxt = new TextField(272, 57, '', '', 34, 0xFFFECF, false);
            titleTxt.touchable = false;
            titleTxt.hAlign = 'center';
            titleTxt.x = 88;
            titleTxt.y = 5;
            this.addQuiackChild(titleTxt);
            tips2Txt = new TextField(393, 42, '', '', 18, 0xE8201B, false);
            tips2Txt.touchable = false;
            tips2Txt.hAlign = 'center';
            tips2Txt.x = 28;
            tips2Txt.y = 284;
            this.addQuiackChild(tips2Txt);
            var ui_yonghuzhuce_wenbentiao64128Texture:Texture = AssetMgr.instance.getTexture('ui_yonghuzhuce_wenbentiao');
            var ui_yonghuzhuce_wenbentiao64128Image:Image = new Image(ui_yonghuzhuce_wenbentiao64128Texture);
            ui_yonghuzhuce_wenbentiao64128Image.x = 64;
            ui_yonghuzhuce_wenbentiao64128Image.y = 128;
            ui_yonghuzhuce_wenbentiao64128Image.width = 311;
            ui_yonghuzhuce_wenbentiao64128Image.height = 48;
            ui_yonghuzhuce_wenbentiao64128Image.smoothing = Constants.smoothing;
            ui_yonghuzhuce_wenbentiao64128Image.touchable = false;
            this.addQuiackChild(ui_yonghuzhuce_wenbentiao64128Image);
            var ui_yonghuzhuce_wenbentiao68231Texture:Texture = AssetMgr.instance.getTexture('ui_yonghuzhuce_wenbentiao');
            var ui_yonghuzhuce_wenbentiao68231Image:Image = new Image(ui_yonghuzhuce_wenbentiao68231Texture);
            ui_yonghuzhuce_wenbentiao68231Image.x = 68;
            ui_yonghuzhuce_wenbentiao68231Image.y = 231;
            ui_yonghuzhuce_wenbentiao68231Image.width = 153;
            ui_yonghuzhuce_wenbentiao68231Image.height = 48;
            ui_yonghuzhuce_wenbentiao68231Image.smoothing = Constants.smoothing;
            ui_yonghuzhuce_wenbentiao68231Image.touchable = false;
            this.addQuiackChild(ui_yonghuzhuce_wenbentiao68231Image);
            tips1Txt = new TextField(392, 44, '', '', 18, 0xE8201B, false);
            tips1Txt.touchable = false;
            tips1Txt.hAlign = 'left';
            tips1Txt.x = 26;
            tips1Txt.y = 180;
            this.addQuiackChild(tips1Txt);
            phoneNumberTxt = new StageText();
            phoneNumberTxt.fontSize = 22 * Constants.scale;
            phoneNumberTxt.text = '输入用户名(必须是手机号码)';
            phoneNumberTxt.color = 0xFFF6EA;
            phoneNumberTxt.stage = Starling.current.nativeStage;
            var starlingViewPort:Rectangle = Starling.current.viewPort;
            var stageTextViewPort:Rectangle = phoneNumberTxt.viewPort;
            if (!stageTextViewPort) {
                stageTextViewPort = new Rectangle();
            }
            stageTextViewPort.x = 67 * Constants.scale;
            stageTextViewPort.y = 133 * Constants.scale;
            stageTextViewPort.width = 302 * Constants.scale;
            stageTextViewPort.height = 44 * Constants.scale;
            phoneNumberTxt.viewPort = stageTextViewPort;
            phoneNumberTxt.maxChars = 0;
            securityCodeTxt = new StageText();
            securityCodeTxt.fontSize = 22 * Constants.scale;
            securityCodeTxt.text = '输入验证码';
            securityCodeTxt.color = 0xFFF6EA;
            securityCodeTxt.stage = Starling.current.nativeStage;
            starlingViewPort = Starling.current.viewPort;
            stageTextViewPort = securityCodeTxt.viewPort;
            if (!stageTextViewPort) {
                stageTextViewPort = new Rectangle();
            }
            stageTextViewPort.x = 65 * Constants.scale;
            stageTextViewPort.y = 239 * Constants.scale;
            stageTextViewPort.width = 154 * Constants.scale;
            stageTextViewPort.height = 34 * Constants.scale;
            securityCodeTxt.viewPort = stageTextViewPort;
            securityCodeTxt.maxChars = 0;
            var securityCodeTexture:Texture = AssetMgr.instance.getTexture('ui_button_Password_back_Send1');
            securityCodeButton = new Button(securityCodeTexture);
            securityCodeButton.x = 237;
            securityCodeButton.y = 228;
            this.addQuiackChild(securityCodeButton);
            var ui_button_Password_back_Send32715Texture:Texture = AssetMgr.instance.getTexture('ui_button_Password_back_Send3');
            var ui_button_Password_back_Send32715Image:Image = new Image(ui_button_Password_back_Send32715Texture);
            ui_button_Password_back_Send32715Image.x = 27;
            ui_button_Password_back_Send32715Image.y = 15;
            ui_button_Password_back_Send32715Image.width = 100;
            ui_button_Password_back_Send32715Image.height = 23;
            ui_button_Password_back_Send32715Image.smoothing = Constants.smoothing;
            ui_button_Password_back_Send32715Image.touchable = false;
            securityCodeButton.addQuiackChild(ui_button_Password_back_Send32715Image);
            var ui_button_Password_back_Send200Texture:Texture = AssetMgr.instance.getTexture('ui_button_Password_back_Send2');
            var ui_button_Password_back_Send200Image:Image = new Image(ui_button_Password_back_Send200Texture);
            ui_button_Password_back_Send200Image.x = 0;
            ui_button_Password_back_Send200Image.y = 0;
            ui_button_Password_back_Send200Image.width = 153;
            ui_button_Password_back_Send200Image.height = 53;
            ui_button_Password_back_Send200Image.smoothing = Constants.smoothing;
            ui_button_Password_back_Send200Image.touchable = false;
            securityCodeButton.addQuiackChild(ui_button_Password_back_Send200Image);

        }

        override public function dispose():void {
            okButton.dispose();
            backButton.dispose();
            phoneNumberTxt.stage = null;
            phoneNumberTxt.dispose();
            securityCodeTxt.stage = null;
            securityCodeTxt.dispose();
            securityCodeButton.dispose();
            super.dispose();

        }

    }
}