package game.view.userLog {
    import com.dialog.Dialog;
    import com.utils.Constants;

    import flash.geom.Rectangle;
    import flash.text.StageText;

    import game.manager.AssetMgr;

    import starling.core.Starling;
    import starling.display.Button;
    import starling.display.Image;
    import starling.text.TextField;
    import starling.textures.Texture;

    public class ResetPasswordDlgBase extends Dialog {
        public var backButton:Button;
        public var okButton:Button;
        public var titleTxt:TextField;
        public var tipsTxt:TextField;
        public var inputTxt:StageText;
        public var reInputTxt:StageText;

        public function ResetPasswordDlgBase() {
            var ui_dengludi_muban14177Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_muban');
            var ui_dengludi_muban14177Image:Image = new Image(ui_dengludi_muban14177Texture);
            ui_dengludi_muban14177Image.x = 14;
            ui_dengludi_muban14177Image.y = 177;
            ui_dengludi_muban14177Image.width = 419;
            ui_dengludi_muban14177Image.height = 53;
            ui_dengludi_muban14177Image.smoothing = Constants.smoothing;
            ui_dengludi_muban14177Image.touchable = false;
            this.addQuiackChild(ui_dengludi_muban14177Image);
            var backTexture:Texture = AssetMgr.instance.getTexture('ui_yonghuzhuce_button1');
            backButton = new Button(backTexture);
            backButton.x = 38;
            backButton.y = 325;
            this.addQuiackChild(backButton);
            backButton.textBounds = new Rectangle(14, 39, 145, 42);
            backButton.fontSize = 34;
            backButton.fontColor = 0xFFA200;
            backButton.fontBold = false;
            var okTexture:Texture = AssetMgr.instance.getTexture('ui_yonghuzhuce_button1');
            okButton = new Button(okTexture);
            okButton.x = 237;
            okButton.y = 325;
            this.addQuiackChild(okButton);
            okButton.textBounds = new Rectangle(14, 39, 145, 42);
            okButton.fontSize = 34;
            okButton.fontColor = 0xFFA200;
            okButton.fontBold = false;
            var ui_dengludi_muban1472Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_muban');
            var ui_dengludi_muban1472Image:Image = new Image(ui_dengludi_muban1472Texture);
            ui_dengludi_muban1472Image.x = 14;
            ui_dengludi_muban1472Image.y = 72;
            ui_dengludi_muban1472Image.width = 419;
            ui_dengludi_muban1472Image.height = 53;
            ui_dengludi_muban1472Image.smoothing = Constants.smoothing;
            ui_dengludi_muban1472Image.touchable = false;
            this.addQuiackChild(ui_dengludi_muban1472Image);
            var ui_dengludi_muban14125Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_muban');
            var ui_dengludi_muban14125Image:Image = new Image(ui_dengludi_muban14125Texture);
            ui_dengludi_muban14125Image.x = 14;
            ui_dengludi_muban14125Image.y = 125;
            ui_dengludi_muban14125Image.width = 419;
            ui_dengludi_muban14125Image.height = 53;
            ui_dengludi_muban14125Image.smoothing = Constants.smoothing;
            ui_dengludi_muban14125Image.touchable = false;
            this.addQuiackChild(ui_dengludi_muban14125Image);
            var ui_dengludi_muban14229Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_muban');
            var ui_dengludi_muban14229Image:Image = new Image(ui_dengludi_muban14229Texture);
            ui_dengludi_muban14229Image.x = 14;
            ui_dengludi_muban14229Image.y = 229;
            ui_dengludi_muban14229Image.width = 419;
            ui_dengludi_muban14229Image.height = 53;
            ui_dengludi_muban14229Image.smoothing = Constants.smoothing;
            ui_dengludi_muban14229Image.touchable = false;
            this.addQuiackChild(ui_dengludi_muban14229Image);
            var ui_dengludi_muban14281Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_muban');
            var ui_dengludi_muban14281Image:Image = new Image(ui_dengludi_muban14281Texture);
            ui_dengludi_muban14281Image.x = 14;
            ui_dengludi_muban14281Image.y = 281;
            ui_dengludi_muban14281Image.width = 419;
            ui_dengludi_muban14281Image.height = 53;
            ui_dengludi_muban14281Image.smoothing = Constants.smoothing;
            ui_dengludi_muban14281Image.touchable = false;
            this.addQuiackChild(ui_dengludi_muban14281Image);
            var ui_dengludi_paizi120Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_paizi');
            var ui_dengludi_paizi120Image:Image = new Image(ui_dengludi_paizi120Texture);
            ui_dengludi_paizi120Image.x = 12;
            ui_dengludi_paizi120Image.y = 0;
            ui_dengludi_paizi120Image.width = 423;
            ui_dengludi_paizi120Image.height = 65;
            ui_dengludi_paizi120Image.smoothing = Constants.smoothing;
            ui_dengludi_paizi120Image.touchable = false;
            this.addQuiackChild(ui_dengludi_paizi120Image);
            var ui_dengludi_tietiao1575Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_tietiao1');
            var ui_dengludi_tietiao1575Image:Image = new Image(ui_dengludi_tietiao1575Texture);
            ui_dengludi_tietiao1575Image.x = 5;
            ui_dengludi_tietiao1575Image.y = 75;
            ui_dengludi_tietiao1575Image.width = 16;
            ui_dengludi_tietiao1575Image.height = 245;
            ui_dengludi_tietiao1575Image.smoothing = Constants.smoothing;
            ui_dengludi_tietiao1575Image.touchable = false;
            this.addQuiackChild(ui_dengludi_tietiao1575Image);
            var ui_dengludi_tietiao21665Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_tietiao2');
            var ui_dengludi_tietiao21665Image:Image = new Image(ui_dengludi_tietiao21665Texture);
            ui_dengludi_tietiao21665Image.x = 16;
            ui_dengludi_tietiao21665Image.y = 65;
            ui_dengludi_tietiao21665Image.width = 415;
            ui_dengludi_tietiao21665Image.height = 18;
            ui_dengludi_tietiao21665Image.smoothing = Constants.smoothing;
            ui_dengludi_tietiao21665Image.touchable = false;
            this.addQuiackChild(ui_dengludi_tietiao21665Image);
            var ui_dengludi_tietiao216328Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_tietiao2');
            var ui_dengludi_tietiao216328Image:Image = new Image(ui_dengludi_tietiao216328Texture);
            ui_dengludi_tietiao216328Image.x = 16;
            ui_dengludi_tietiao216328Image.y = 328;
            ui_dengludi_tietiao216328Image.width = 415;
            ui_dengludi_tietiao216328Image.height = 18;
            ui_dengludi_tietiao216328Image.smoothing = Constants.smoothing;
            ui_dengludi_tietiao216328Image.touchable = false;
            this.addQuiackChild(ui_dengludi_tietiao216328Image);
            var ui_dengludi_guagou38328Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_guagou');
            var ui_dengludi_guagou38328Image:Image = new Image(ui_dengludi_guagou38328Texture);
            ui_dengludi_guagou38328Image.x = 38;
            ui_dengludi_guagou38328Image.y = 328;
            ui_dengludi_guagou38328Image.width = 26;
            ui_dengludi_guagou38328Image.height = 21;
            ui_dengludi_guagou38328Image.smoothing = Constants.smoothing;
            ui_dengludi_guagou38328Image.touchable = false;
            this.addQuiackChild(ui_dengludi_guagou38328Image);
            var ui_dengludi_tietiao142575Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_tietiao1');
            var ui_dengludi_tietiao142575Image:Image = new Image(ui_dengludi_tietiao142575Texture);
            ui_dengludi_tietiao142575Image.x = 425;
            ui_dengludi_tietiao142575Image.y = 75;
            ui_dengludi_tietiao142575Image.width = 16;
            ui_dengludi_tietiao142575Image.height = 245;
            ui_dengludi_tietiao142575Image.smoothing = Constants.smoothing;
            ui_dengludi_tietiao142575Image.touchable = false;
            this.addQuiackChild(ui_dengludi_tietiao142575Image);
            var ui_dengludi_guaijiao443348Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_guaijiao');
            var ui_dengludi_guaijiao443348Image:Image = new Image(ui_dengludi_guaijiao443348Texture);
            ui_dengludi_guaijiao443348Image.x = 443;
            ui_dengludi_guaijiao443348Image.y = 348;
            ui_dengludi_guaijiao443348Image.width = 32;
            ui_dengludi_guaijiao443348Image.height = 33;
            ui_dengludi_guaijiao443348Image.scaleX = -1;
            ui_dengludi_guaijiao443348Image.scaleY = -1;
            ui_dengludi_guaijiao443348Image.smoothing = Constants.smoothing;
            ui_dengludi_guaijiao443348Image.touchable = false;
            this.addQuiackChild(ui_dengludi_guaijiao443348Image);
            var ui_dengludi_guaijiao0348Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_guaijiao');
            var ui_dengludi_guaijiao0348Image:Image = new Image(ui_dengludi_guaijiao0348Texture);
            ui_dengludi_guaijiao0348Image.x = 0;
            ui_dengludi_guaijiao0348Image.y = 348;
            ui_dengludi_guaijiao0348Image.width = 32;
            ui_dengludi_guaijiao0348Image.height = 33;
            ui_dengludi_guaijiao0348Image.scaleY = -1;
            ui_dengludi_guaijiao0348Image.smoothing = Constants.smoothing;
            ui_dengludi_guaijiao0348Image.touchable = false;
            this.addQuiackChild(ui_dengludi_guaijiao0348Image);
            var ui_dengludi_guaijiao44363Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_guaijiao');
            var ui_dengludi_guaijiao44363Image:Image = new Image(ui_dengludi_guaijiao44363Texture);
            ui_dengludi_guaijiao44363Image.x = 443;
            ui_dengludi_guaijiao44363Image.y = 63;
            ui_dengludi_guaijiao44363Image.width = 32;
            ui_dengludi_guaijiao44363Image.height = 33;
            ui_dengludi_guaijiao44363Image.scaleX = -1;
            ui_dengludi_guaijiao44363Image.smoothing = Constants.smoothing;
            ui_dengludi_guaijiao44363Image.touchable = false;
            this.addQuiackChild(ui_dengludi_guaijiao44363Image);
            var ui_dengludi_guaijiao063Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_guaijiao');
            var ui_dengludi_guaijiao063Image:Image = new Image(ui_dengludi_guaijiao063Texture);
            ui_dengludi_guaijiao063Image.x = 0;
            ui_dengludi_guaijiao063Image.y = 63;
            ui_dengludi_guaijiao063Image.width = 32;
            ui_dengludi_guaijiao063Image.height = 33;
            ui_dengludi_guaijiao063Image.smoothing = Constants.smoothing;
            ui_dengludi_guaijiao063Image.touchable = false;
            this.addQuiackChild(ui_dengludi_guaijiao063Image);
            var ui_dengludi_guagou408328Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_guagou');
            var ui_dengludi_guagou408328Image:Image = new Image(ui_dengludi_guagou408328Texture);
            ui_dengludi_guagou408328Image.x = 408;
            ui_dengludi_guagou408328Image.y = 328;
            ui_dengludi_guagou408328Image.width = 26;
            ui_dengludi_guagou408328Image.height = 21;
            ui_dengludi_guagou408328Image.scaleX = -1;
            ui_dengludi_guagou408328Image.smoothing = Constants.smoothing;
            ui_dengludi_guagou408328Image.touchable = false;
            this.addQuiackChild(ui_dengludi_guagou408328Image);
            var ui_dengludi_guagou239328Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_guagou');
            var ui_dengludi_guagou239328Image:Image = new Image(ui_dengludi_guagou239328Texture);
            ui_dengludi_guagou239328Image.x = 239;
            ui_dengludi_guagou239328Image.y = 328;
            ui_dengludi_guagou239328Image.width = 26;
            ui_dengludi_guagou239328Image.height = 21;
            ui_dengludi_guagou239328Image.smoothing = Constants.smoothing;
            ui_dengludi_guagou239328Image.touchable = false;
            this.addQuiackChild(ui_dengludi_guagou239328Image);
            var ui_dengludi_guagou208328Texture:Texture = AssetMgr.instance.getTexture('ui_dengludi_guagou');
            var ui_dengludi_guagou208328Image:Image = new Image(ui_dengludi_guagou208328Texture);
            ui_dengludi_guagou208328Image.x = 208;
            ui_dengludi_guagou208328Image.y = 328;
            ui_dengludi_guagou208328Image.width = 26;
            ui_dengludi_guagou208328Image.height = 21;
            ui_dengludi_guagou208328Image.scaleX = -1;
            ui_dengludi_guagou208328Image.smoothing = Constants.smoothing;
            ui_dengludi_guagou208328Image.touchable = false;
            this.addQuiackChild(ui_dengludi_guagou208328Image);
            titleTxt = new TextField(272, 57, '', '', 34, 0xFFFECF, false);
            titleTxt.touchable = false;
            titleTxt.hAlign = 'center';
            titleTxt.x = 88;
            titleTxt.y = 5;
            this.addQuiackChild(titleTxt);
            tipsTxt = new TextField(390, 40, '', '', 18, 0xE8201B, false);
            tipsTxt.touchable = false;
            tipsTxt.hAlign = 'center';
            tipsTxt.x = 28;
            tipsTxt.y = 286;
            this.addQuiackChild(tipsTxt);
            var ui_yonghuzhuce_wenbentiao66129Texture:Texture = AssetMgr.instance.getTexture('ui_yonghuzhuce_wenbentiao');
            var ui_yonghuzhuce_wenbentiao66129Image:Image = new Image(ui_yonghuzhuce_wenbentiao66129Texture);
            ui_yonghuzhuce_wenbentiao66129Image.x = 66;
            ui_yonghuzhuce_wenbentiao66129Image.y = 129;
            ui_yonghuzhuce_wenbentiao66129Image.width = 311;
            ui_yonghuzhuce_wenbentiao66129Image.height = 48;
            ui_yonghuzhuce_wenbentiao66129Image.smoothing = Constants.smoothing;
            ui_yonghuzhuce_wenbentiao66129Image.touchable = false;
            this.addQuiackChild(ui_yonghuzhuce_wenbentiao66129Image);
            inputTxt = new StageText();
            inputTxt.fontSize = 22 * Constants.scale;
            inputTxt.text = '点击输入新密码';
            inputTxt.color = 0xFFF6EA;
            inputTxt.stage = Starling.current.nativeStage;
            var starlingViewPort:Rectangle = Starling.current.viewPort;
            var stageTextViewPort:Rectangle = inputTxt.viewPort;
            if (!stageTextViewPort) {
                stageTextViewPort = new Rectangle();
            }
            stageTextViewPort.x = 70 * Constants.scale;
            stageTextViewPort.y = 134 * Constants.scale;
            stageTextViewPort.width = 302 * Constants.scale;
            stageTextViewPort.height = 40 * Constants.scale;
            inputTxt.viewPort = stageTextViewPort;
            inputTxt.maxChars = 0;
            var ui_yonghuzhuce_wenbentiao66230Texture:Texture = AssetMgr.instance.getTexture('ui_yonghuzhuce_wenbentiao');
            var ui_yonghuzhuce_wenbentiao66230Image:Image = new Image(ui_yonghuzhuce_wenbentiao66230Texture);
            ui_yonghuzhuce_wenbentiao66230Image.x = 66;
            ui_yonghuzhuce_wenbentiao66230Image.y = 230;
            ui_yonghuzhuce_wenbentiao66230Image.width = 311;
            ui_yonghuzhuce_wenbentiao66230Image.height = 48;
            ui_yonghuzhuce_wenbentiao66230Image.smoothing = Constants.smoothing;
            ui_yonghuzhuce_wenbentiao66230Image.touchable = false;
            this.addQuiackChild(ui_yonghuzhuce_wenbentiao66230Image);
            reInputTxt = new StageText();
            reInputTxt.fontSize = 22 * Constants.scale;
            reInputTxt.text = '重复输入新密码';
            reInputTxt.color = 0xFFF6EA;
            reInputTxt.stage = Starling.current.nativeStage;
            starlingViewPort = Starling.current.viewPort;
            stageTextViewPort = reInputTxt.viewPort;
            if (!stageTextViewPort) {
                stageTextViewPort = new Rectangle();
            }
            stageTextViewPort.x = 70 * Constants.scale;
            stageTextViewPort.y = 236 * Constants.scale;
            stageTextViewPort.width = 302 * Constants.scale;
            stageTextViewPort.height = 39 * Constants.scale;
            reInputTxt.viewPort = stageTextViewPort;
            reInputTxt.maxChars = 0;

        }

        override public function dispose():void {
            backButton.dispose();
            okButton.dispose();
            inputTxt.stage = null;
            inputTxt.dispose();
            reInputTxt.stage = null;
            reInputTxt.dispose();
            super.dispose();

        }

    }
}