package game.dialog {
    import com.utils.Constants;

    import game.manager.AssetMgr;

    import starling.display.Image;
    import starling.display.Sprite;
    import starling.textures.Texture;

    public class DialogBackground1 extends Sprite {

        public function DialogBackground1() {
            var ui_gongyong_yibanmubanhentiao0139Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao0139Image:Image = new Image(ui_gongyong_yibanmubanhentiao0139Texture);
            ui_gongyong_yibanmubanhentiao0139Image.x = 0;
            ui_gongyong_yibanmubanhentiao0139Image.y = 139;
            ui_gongyong_yibanmubanhentiao0139Image.width = 490;
            ui_gongyong_yibanmubanhentiao0139Image.height = 72;
            ui_gongyong_yibanmubanhentiao0139Image.smoothing = Constants.smoothing;
//            ui_gongyong_yibanmubanhentiao0139Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao0139Image);
            var ui_gongyong_yibanmubanhentiao960139Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao960139Image:Image = new Image(ui_gongyong_yibanmubanhentiao960139Texture);
            ui_gongyong_yibanmubanhentiao960139Image.x = 960;
            ui_gongyong_yibanmubanhentiao960139Image.y = 139;
            ui_gongyong_yibanmubanhentiao960139Image.width = 490;
            ui_gongyong_yibanmubanhentiao960139Image.height = 72;
            ui_gongyong_yibanmubanhentiao960139Image.scaleX = -1;
            ui_gongyong_yibanmubanhentiao960139Image.smoothing = Constants.smoothing;
//            ui_gongyong_yibanmubanhentiao960139Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao960139Image);
            var ui_gongyong_yibanmubanhentiao0211Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao0211Image:Image = new Image(ui_gongyong_yibanmubanhentiao0211Texture);
            ui_gongyong_yibanmubanhentiao0211Image.x = 0;
            ui_gongyong_yibanmubanhentiao0211Image.y = 211;
            ui_gongyong_yibanmubanhentiao0211Image.width = 490;
            ui_gongyong_yibanmubanhentiao0211Image.height = 72;
            ui_gongyong_yibanmubanhentiao0211Image.smoothing = Constants.smoothing;
//            ui_gongyong_yibanmubanhentiao0211Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao0211Image);
            var ui_gongyong_yibanmubanhentiao960211Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao960211Image:Image = new Image(ui_gongyong_yibanmubanhentiao960211Texture);
            ui_gongyong_yibanmubanhentiao960211Image.x = 960;
            ui_gongyong_yibanmubanhentiao960211Image.y = 211;
            ui_gongyong_yibanmubanhentiao960211Image.width = 490;
            ui_gongyong_yibanmubanhentiao960211Image.height = 72;
            ui_gongyong_yibanmubanhentiao960211Image.scaleX = -1;
            ui_gongyong_yibanmubanhentiao960211Image.smoothing = Constants.smoothing;
//            ui_gongyong_yibanmubanhentiao960211Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao960211Image);
            var ui_gongyong_yibanmubanhentiao0282Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao0282Image:Image = new Image(ui_gongyong_yibanmubanhentiao0282Texture);
            ui_gongyong_yibanmubanhentiao0282Image.x = 0;
            ui_gongyong_yibanmubanhentiao0282Image.y = 282;
            ui_gongyong_yibanmubanhentiao0282Image.width = 490;
            ui_gongyong_yibanmubanhentiao0282Image.height = 72;
            ui_gongyong_yibanmubanhentiao0282Image.smoothing = Constants.smoothing;
//            ui_gongyong_yibanmubanhentiao0282Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao0282Image);
            var ui_gongyong_yibanmubanhentiao960282Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao960282Image:Image = new Image(ui_gongyong_yibanmubanhentiao960282Texture);
            ui_gongyong_yibanmubanhentiao960282Image.x = 960;
            ui_gongyong_yibanmubanhentiao960282Image.y = 282;
            ui_gongyong_yibanmubanhentiao960282Image.width = 490;
            ui_gongyong_yibanmubanhentiao960282Image.height = 72;
            ui_gongyong_yibanmubanhentiao960282Image.scaleX = -1;
            ui_gongyong_yibanmubanhentiao960282Image.smoothing = Constants.smoothing;
//            ui_gongyong_yibanmubanhentiao960282Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao960282Image);
            var ui_gongyong_yibanmubanhentiao0354Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao0354Image:Image = new Image(ui_gongyong_yibanmubanhentiao0354Texture);
            ui_gongyong_yibanmubanhentiao0354Image.x = 0;
            ui_gongyong_yibanmubanhentiao0354Image.y = 354;
            ui_gongyong_yibanmubanhentiao0354Image.width = 490;
            ui_gongyong_yibanmubanhentiao0354Image.height = 72;
            ui_gongyong_yibanmubanhentiao0354Image.smoothing = Constants.smoothing;
//            ui_gongyong_yibanmubanhentiao0354Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao0354Image);
            var ui_gongyong_yibanmubanhentiao960354Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao960354Image:Image = new Image(ui_gongyong_yibanmubanhentiao960354Texture);
            ui_gongyong_yibanmubanhentiao960354Image.x = 960;
            ui_gongyong_yibanmubanhentiao960354Image.y = 354;
            ui_gongyong_yibanmubanhentiao960354Image.width = 490;
            ui_gongyong_yibanmubanhentiao960354Image.height = 72;
            ui_gongyong_yibanmubanhentiao960354Image.scaleX = -1;
            ui_gongyong_yibanmubanhentiao960354Image.smoothing = Constants.smoothing;
//            ui_gongyong_yibanmubanhentiao960354Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao960354Image);
            var ui_gongyong_yibanmubanhentiao0425Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao0425Image:Image = new Image(ui_gongyong_yibanmubanhentiao0425Texture);
            ui_gongyong_yibanmubanhentiao0425Image.x = 0;
            ui_gongyong_yibanmubanhentiao0425Image.y = 425;
            ui_gongyong_yibanmubanhentiao0425Image.width = 490;
            ui_gongyong_yibanmubanhentiao0425Image.height = 72;
            ui_gongyong_yibanmubanhentiao0425Image.smoothing = Constants.smoothing;
//            ui_gongyong_yibanmubanhentiao0425Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao0425Image);
            var ui_gongyong_yibanmubanhentiao960425Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao960425Image:Image = new Image(ui_gongyong_yibanmubanhentiao960425Texture);
            ui_gongyong_yibanmubanhentiao960425Image.x = 960;
            ui_gongyong_yibanmubanhentiao960425Image.y = 425;
            ui_gongyong_yibanmubanhentiao960425Image.width = 490;
            ui_gongyong_yibanmubanhentiao960425Image.height = 72;
            ui_gongyong_yibanmubanhentiao960425Image.scaleX = -1;
            ui_gongyong_yibanmubanhentiao960425Image.smoothing = Constants.smoothing;
//            ui_gongyong_yibanmubanhentiao960425Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao960425Image);
            var ui_gongyong_yibanmubanhentiao0497Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao0497Image:Image = new Image(ui_gongyong_yibanmubanhentiao0497Texture);
            ui_gongyong_yibanmubanhentiao0497Image.x = 0;
            ui_gongyong_yibanmubanhentiao0497Image.y = 497;
            ui_gongyong_yibanmubanhentiao0497Image.width = 490;
            ui_gongyong_yibanmubanhentiao0497Image.height = 72;
            ui_gongyong_yibanmubanhentiao0497Image.smoothing = Constants.smoothing;
//            ui_gongyong_yibanmubanhentiao0497Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao0497Image);
            var ui_gongyong_yibanmubanhentiao960497Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao960497Image:Image = new Image(ui_gongyong_yibanmubanhentiao960497Texture);
            ui_gongyong_yibanmubanhentiao960497Image.x = 960;
            ui_gongyong_yibanmubanhentiao960497Image.y = 497;
            ui_gongyong_yibanmubanhentiao960497Image.width = 490;
            ui_gongyong_yibanmubanhentiao960497Image.height = 72;
            ui_gongyong_yibanmubanhentiao960497Image.scaleX = -1;
            ui_gongyong_yibanmubanhentiao960497Image.smoothing = Constants.smoothing;
//            ui_gongyong_yibanmubanhentiao960497Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao960497Image);
            var ui_gongyong_yibanmubanhentiao0568Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao0568Image:Image = new Image(ui_gongyong_yibanmubanhentiao0568Texture);
            ui_gongyong_yibanmubanhentiao0568Image.x = 0;
            ui_gongyong_yibanmubanhentiao0568Image.y = 568;
            ui_gongyong_yibanmubanhentiao0568Image.width = 490;
            ui_gongyong_yibanmubanhentiao0568Image.height = 72;
            ui_gongyong_yibanmubanhentiao0568Image.smoothing = Constants.smoothing;
//            ui_gongyong_yibanmubanhentiao0568Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao0568Image);
            var ui_gongyong_yibanmubanhentiao960568Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao960568Image:Image = new Image(ui_gongyong_yibanmubanhentiao960568Texture);
            ui_gongyong_yibanmubanhentiao960568Image.x = 960;
            ui_gongyong_yibanmubanhentiao960568Image.y = 568;
            ui_gongyong_yibanmubanhentiao960568Image.width = 490;
            ui_gongyong_yibanmubanhentiao960568Image.height = 72;
            ui_gongyong_yibanmubanhentiao960568Image.scaleX = -1;
            ui_gongyong_yibanmubanhentiao960568Image.smoothing = Constants.smoothing;
//            ui_gongyong_yibanmubanhentiao960568Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao960568Image);
            var ui_gongyong_yibanmubanhentiao070Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao070Image:Image = new Image(ui_gongyong_yibanmubanhentiao070Texture);
            ui_gongyong_yibanmubanhentiao070Image.x = 0;
            ui_gongyong_yibanmubanhentiao070Image.y = 70;
            ui_gongyong_yibanmubanhentiao070Image.width = 490;
            ui_gongyong_yibanmubanhentiao070Image.height = 72;
            ui_gongyong_yibanmubanhentiao070Image.smoothing = Constants.smoothing;
//            ui_gongyong_yibanmubanhentiao070Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao070Image);
            var ui_gongyong_yibanmubanhentiao96070Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao96070Image:Image = new Image(ui_gongyong_yibanmubanhentiao96070Texture);
            ui_gongyong_yibanmubanhentiao96070Image.x = 960;
            ui_gongyong_yibanmubanhentiao96070Image.y = 70;
            ui_gongyong_yibanmubanhentiao96070Image.width = 490;
            ui_gongyong_yibanmubanhentiao96070Image.height = 72;
            ui_gongyong_yibanmubanhentiao96070Image.scaleX = -1;
            ui_gongyong_yibanmubanhentiao96070Image.smoothing = Constants.smoothing;
//            ui_gongyong_yibanmubanhentiao96070Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao96070Image);
            var ui_gongyong_yibanmubanhentiao00Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao00Image:Image = new Image(ui_gongyong_yibanmubanhentiao00Texture);
            ui_gongyong_yibanmubanhentiao00Image.x = 0;
            ui_gongyong_yibanmubanhentiao00Image.y = 0;
            ui_gongyong_yibanmubanhentiao00Image.width = 490;
            ui_gongyong_yibanmubanhentiao00Image.height = 72;
            ui_gongyong_yibanmubanhentiao00Image.smoothing = Constants.smoothing;
//            ui_gongyong_yibanmubanhentiao00Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao00Image);
            var ui_gongyong_yibanmubanhentiao9600Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao9600Image:Image = new Image(ui_gongyong_yibanmubanhentiao9600Texture);
            ui_gongyong_yibanmubanhentiao9600Image.x = 960;
            ui_gongyong_yibanmubanhentiao9600Image.y = 0;
            ui_gongyong_yibanmubanhentiao9600Image.width = 490;
            ui_gongyong_yibanmubanhentiao9600Image.height = 72;
            ui_gongyong_yibanmubanhentiao9600Image.scaleX = -1;
            ui_gongyong_yibanmubanhentiao9600Image.smoothing = Constants.smoothing;
//            ui_gongyong_yibanmubanhentiao9600Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao9600Image);

            this.flatten(); // 这个方法很重要
        }

    }
}
