package game.view.chat.base {
    import com.utils.Constants;

    import game.base.JTSprite;
    import game.manager.AssetMgr;

    import starling.display.Image;
    import starling.textures.Texture;

    public class JTUIBackGround extends JTSprite {

        public static var isTouchable:Boolean = false;

        public function JTUIBackGround() {
            var txture_ui_gongyong_dianquanheng_di6400:Texture = AssetMgr.instance.getTexture('ui_gongyong_dianquanheng_di');
            var ui_gongyong_dianquanheng_di6400img_NaN:Image = new Image(txture_ui_gongyong_dianquanheng_di6400);
            ui_gongyong_dianquanheng_di6400img_NaN.x = 640;
            ui_gongyong_dianquanheng_di6400img_NaN.y = 0;
            ui_gongyong_dianquanheng_di6400img_NaN.width = 321;
            ui_gongyong_dianquanheng_di6400img_NaN.height = 160;
            ui_gongyong_dianquanheng_di6400img_NaN.smoothing = Constants.smoothing;
            ui_gongyong_dianquanheng_di6400img_NaN.touchable = isTouchable;
            this.addQuiackChild(ui_gongyong_dianquanheng_di6400img_NaN);
            var txture_ui_gongyong_dianquanheng_di3200:Texture = AssetMgr.instance.getTexture('ui_gongyong_dianquanheng_di');
            var ui_gongyong_dianquanheng_di3200img_NaN:Image = new Image(txture_ui_gongyong_dianquanheng_di3200);
            ui_gongyong_dianquanheng_di3200img_NaN.x = 320;
            ui_gongyong_dianquanheng_di3200img_NaN.y = 0;
            ui_gongyong_dianquanheng_di3200img_NaN.width = 321;
            ui_gongyong_dianquanheng_di3200img_NaN.height = 160;
            ui_gongyong_dianquanheng_di3200img_NaN.smoothing = Constants.smoothing;
            ui_gongyong_dianquanheng_di3200img_NaN.touchable = isTouchable;
            this.addQuiackChild(ui_gongyong_dianquanheng_di3200img_NaN);
            var txture_ui_gongyong_dianquanheng_di00:Texture = AssetMgr.instance.getTexture('ui_gongyong_dianquanheng_di');
            var ui_gongyong_dianquanheng_di00img_NaN:Image = new Image(txture_ui_gongyong_dianquanheng_di00);
            ui_gongyong_dianquanheng_di00img_NaN.x = 0;
            ui_gongyong_dianquanheng_di00img_NaN.y = 0;
            ui_gongyong_dianquanheng_di00img_NaN.width = 321;
            ui_gongyong_dianquanheng_di00img_NaN.height = 160;
            ui_gongyong_dianquanheng_di00img_NaN.smoothing = Constants.smoothing;
            ui_gongyong_dianquanheng_di00img_NaN.touchable = isTouchable;
            this.addQuiackChild(ui_gongyong_dianquanheng_di00img_NaN);
            var txture_ui_gongyong_dianquanheng_di640160:Texture = AssetMgr.instance.getTexture('ui_gongyong_dianquanheng_di');
            var ui_gongyong_dianquanheng_di640160img_NaN:Image = new Image(txture_ui_gongyong_dianquanheng_di640160);
            ui_gongyong_dianquanheng_di640160img_NaN.x = 640;
            ui_gongyong_dianquanheng_di640160img_NaN.y = 160;
            ui_gongyong_dianquanheng_di640160img_NaN.width = 321;
            ui_gongyong_dianquanheng_di640160img_NaN.height = 160;
            ui_gongyong_dianquanheng_di640160img_NaN.smoothing = Constants.smoothing;
            ui_gongyong_dianquanheng_di640160img_NaN.touchable = isTouchable;
            this.addQuiackChild(ui_gongyong_dianquanheng_di640160img_NaN);
            var txture_ui_gongyong_dianquanheng_di320160:Texture = AssetMgr.instance.getTexture('ui_gongyong_dianquanheng_di');
            var ui_gongyong_dianquanheng_di320160img_NaN:Image = new Image(txture_ui_gongyong_dianquanheng_di320160);
            ui_gongyong_dianquanheng_di320160img_NaN.x = 320;
            ui_gongyong_dianquanheng_di320160img_NaN.y = 160;
            ui_gongyong_dianquanheng_di320160img_NaN.width = 321;
            ui_gongyong_dianquanheng_di320160img_NaN.height = 160;
            ui_gongyong_dianquanheng_di320160img_NaN.smoothing = Constants.smoothing;
            ui_gongyong_dianquanheng_di320160img_NaN.touchable = isTouchable;
            this.addQuiackChild(ui_gongyong_dianquanheng_di320160img_NaN);
            var txture_ui_gongyong_dianquanheng_di0160:Texture = AssetMgr.instance.getTexture('ui_gongyong_dianquanheng_di');
            var ui_gongyong_dianquanheng_di0160img_NaN:Image = new Image(txture_ui_gongyong_dianquanheng_di0160);
            ui_gongyong_dianquanheng_di0160img_NaN.x = 0;
            ui_gongyong_dianquanheng_di0160img_NaN.y = 160;
            ui_gongyong_dianquanheng_di0160img_NaN.width = 321;
            ui_gongyong_dianquanheng_di0160img_NaN.height = 160;
            ui_gongyong_dianquanheng_di0160img_NaN.smoothing = Constants.smoothing;
            ui_gongyong_dianquanheng_di0160img_NaN.touchable = isTouchable;
            this.addQuiackChild(ui_gongyong_dianquanheng_di0160img_NaN);
            var txture_ui_gongyong_dianquanheng_di640320:Texture = AssetMgr.instance.getTexture('ui_gongyong_dianquanheng_di');
            var ui_gongyong_dianquanheng_di640320img_NaN:Image = new Image(txture_ui_gongyong_dianquanheng_di640320);
            ui_gongyong_dianquanheng_di640320img_NaN.x = 640;
            ui_gongyong_dianquanheng_di640320img_NaN.y = 320;
            ui_gongyong_dianquanheng_di640320img_NaN.width = 321;
            ui_gongyong_dianquanheng_di640320img_NaN.height = 160;
            ui_gongyong_dianquanheng_di640320img_NaN.smoothing = Constants.smoothing;
            ui_gongyong_dianquanheng_di640320img_NaN.touchable = isTouchable;
            this.addQuiackChild(ui_gongyong_dianquanheng_di640320img_NaN);
            var txture_ui_gongyong_dianquanheng_di320320:Texture = AssetMgr.instance.getTexture('ui_gongyong_dianquanheng_di');
            var ui_gongyong_dianquanheng_di320320img_NaN:Image = new Image(txture_ui_gongyong_dianquanheng_di320320);
            ui_gongyong_dianquanheng_di320320img_NaN.x = 320;
            ui_gongyong_dianquanheng_di320320img_NaN.y = 320;
            ui_gongyong_dianquanheng_di320320img_NaN.width = 321;
            ui_gongyong_dianquanheng_di320320img_NaN.height = 160;
            ui_gongyong_dianquanheng_di320320img_NaN.smoothing = Constants.smoothing;
            ui_gongyong_dianquanheng_di320320img_NaN.touchable = isTouchable;
            this.addQuiackChild(ui_gongyong_dianquanheng_di320320img_NaN);
            var txture_ui_gongyong_dianquanheng_di0320:Texture = AssetMgr.instance.getTexture('ui_gongyong_dianquanheng_di');
            var ui_gongyong_dianquanheng_di0320img_NaN:Image = new Image(txture_ui_gongyong_dianquanheng_di0320);
            ui_gongyong_dianquanheng_di0320img_NaN.x = 0;
            ui_gongyong_dianquanheng_di0320img_NaN.y = 320;
            ui_gongyong_dianquanheng_di0320img_NaN.width = 321;
            ui_gongyong_dianquanheng_di0320img_NaN.height = 160;
            ui_gongyong_dianquanheng_di0320img_NaN.smoothing = Constants.smoothing;
            ui_gongyong_dianquanheng_di0320img_NaN.touchable = isTouchable;
            this.addQuiackChild(ui_gongyong_dianquanheng_di0320img_NaN);
            var txture_ui_gongyong_dianquanheng_di640480:Texture = AssetMgr.instance.getTexture('ui_gongyong_dianquanheng_di');
            var ui_gongyong_dianquanheng_di640480img_NaN:Image = new Image(txture_ui_gongyong_dianquanheng_di640480);
            ui_gongyong_dianquanheng_di640480img_NaN.x = 640;
            ui_gongyong_dianquanheng_di640480img_NaN.y = 480;
            ui_gongyong_dianquanheng_di640480img_NaN.width = 321;
            ui_gongyong_dianquanheng_di640480img_NaN.height = 160;
            ui_gongyong_dianquanheng_di640480img_NaN.smoothing = Constants.smoothing;
            ui_gongyong_dianquanheng_di640480img_NaN.touchable = isTouchable;
            this.addQuiackChild(ui_gongyong_dianquanheng_di640480img_NaN);
            var txture_ui_gongyong_dianquanheng_di320480:Texture = AssetMgr.instance.getTexture('ui_gongyong_dianquanheng_di');
            var ui_gongyong_dianquanheng_di320480img_NaN:Image = new Image(txture_ui_gongyong_dianquanheng_di320480);
            ui_gongyong_dianquanheng_di320480img_NaN.x = 320;
            ui_gongyong_dianquanheng_di320480img_NaN.y = 480;
            ui_gongyong_dianquanheng_di320480img_NaN.width = 321;
            ui_gongyong_dianquanheng_di320480img_NaN.height = 160;
            ui_gongyong_dianquanheng_di320480img_NaN.smoothing = Constants.smoothing;
            ui_gongyong_dianquanheng_di320480img_NaN.touchable = isTouchable;
            this.addQuiackChild(ui_gongyong_dianquanheng_di320480img_NaN);
            var txture_ui_gongyong_dianquanheng_di0480:Texture = AssetMgr.instance.getTexture('ui_gongyong_dianquanheng_di');
            var ui_gongyong_dianquanheng_di0480img_NaN:Image = new Image(txture_ui_gongyong_dianquanheng_di0480);
            ui_gongyong_dianquanheng_di0480img_NaN.x = 0;
            ui_gongyong_dianquanheng_di0480img_NaN.y = 480;
            ui_gongyong_dianquanheng_di0480img_NaN.width = 321;
            ui_gongyong_dianquanheng_di0480img_NaN.height = 160;
            ui_gongyong_dianquanheng_di0480img_NaN.smoothing = Constants.smoothing;
            ui_gongyong_dianquanheng_di0480img_NaN.touchable = isTouchable;
            this.addQuiackChild(ui_gongyong_dianquanheng_di0480img_NaN);
            var txture_ui_gongyong_dianquanheng_di640156:Texture = AssetMgr.instance.getTexture('ui_gongyong_dianquanheng_di');
            var ui_gongyong_dianquanheng_di640156img_NaN:Image = new Image(txture_ui_gongyong_dianquanheng_di640156);
            ui_gongyong_dianquanheng_di640156img_NaN.x = 640;
            ui_gongyong_dianquanheng_di640156img_NaN.y = -156;
            ui_gongyong_dianquanheng_di640156img_NaN.width = 321;
            ui_gongyong_dianquanheng_di640156img_NaN.height = 160;
            ui_gongyong_dianquanheng_di640156img_NaN.smoothing = Constants.smoothing;
            ui_gongyong_dianquanheng_di640156img_NaN.touchable = isTouchable;
            this.addQuiackChild(ui_gongyong_dianquanheng_di640156img_NaN);
            var txture_ui_gongyong_dianquanheng_di320156:Texture = AssetMgr.instance.getTexture('ui_gongyong_dianquanheng_di');
            var ui_gongyong_dianquanheng_di320156img_NaN:Image = new Image(txture_ui_gongyong_dianquanheng_di320156);
            ui_gongyong_dianquanheng_di320156img_NaN.x = 320;
            ui_gongyong_dianquanheng_di320156img_NaN.y = -156;
            ui_gongyong_dianquanheng_di320156img_NaN.width = 321;
            ui_gongyong_dianquanheng_di320156img_NaN.height = 160;
            ui_gongyong_dianquanheng_di320156img_NaN.smoothing = Constants.smoothing;
            ui_gongyong_dianquanheng_di320156img_NaN.touchable = isTouchable;
            this.addQuiackChild(ui_gongyong_dianquanheng_di320156img_NaN);
            var txture_ui_gongyong_dianquanheng_di0156:Texture = AssetMgr.instance.getTexture('ui_gongyong_dianquanheng_di');
            var ui_gongyong_dianquanheng_di0156img_NaN:Image = new Image(txture_ui_gongyong_dianquanheng_di0156);
            ui_gongyong_dianquanheng_di0156img_NaN.x = 0;
            ui_gongyong_dianquanheng_di0156img_NaN.y = -156;
            ui_gongyong_dianquanheng_di0156img_NaN.width = 321;
            ui_gongyong_dianquanheng_di0156img_NaN.height = 160;
            ui_gongyong_dianquanheng_di0156img_NaN.smoothing = Constants.smoothing;
            ui_gongyong_dianquanheng_di0156img_NaN.touchable = isTouchable;
            this.addQuiackChild(ui_gongyong_dianquanheng_di0156img_NaN);
            var txture_ui_gongyong_dianquanheng_di3160:Texture = AssetMgr.instance.getTexture('ui_gongyong_dianquanheng_di');
            var ui_gongyong_dianquanheng_di3160img_NaN:Image = new Image(txture_ui_gongyong_dianquanheng_di3160);
            ui_gongyong_dianquanheng_di3160img_NaN.x = -316;
            ui_gongyong_dianquanheng_di3160img_NaN.y = 0;
            ui_gongyong_dianquanheng_di3160img_NaN.width = 321;
            ui_gongyong_dianquanheng_di3160img_NaN.height = 160;
            ui_gongyong_dianquanheng_di3160img_NaN.smoothing = Constants.smoothing;
            ui_gongyong_dianquanheng_di3160img_NaN.touchable = isTouchable;
            this.addQuiackChild(ui_gongyong_dianquanheng_di3160img_NaN);
            var txture_ui_gongyong_dianquanheng_di316160:Texture = AssetMgr.instance.getTexture('ui_gongyong_dianquanheng_di');
            var ui_gongyong_dianquanheng_di316160img_NaN:Image = new Image(txture_ui_gongyong_dianquanheng_di316160);
            ui_gongyong_dianquanheng_di316160img_NaN.x = -316;
            ui_gongyong_dianquanheng_di316160img_NaN.y = 160;
            ui_gongyong_dianquanheng_di316160img_NaN.width = 321;
            ui_gongyong_dianquanheng_di316160img_NaN.height = 160;
            ui_gongyong_dianquanheng_di316160img_NaN.smoothing = Constants.smoothing;
            ui_gongyong_dianquanheng_di316160img_NaN.touchable = isTouchable;
            this.addQuiackChild(ui_gongyong_dianquanheng_di316160img_NaN);
            var txture_ui_gongyong_dianquanheng_di316320:Texture = AssetMgr.instance.getTexture('ui_gongyong_dianquanheng_di');
            var ui_gongyong_dianquanheng_di316320img_NaN:Image = new Image(txture_ui_gongyong_dianquanheng_di316320);
            ui_gongyong_dianquanheng_di316320img_NaN.x = -316;
            ui_gongyong_dianquanheng_di316320img_NaN.y = 320;
            ui_gongyong_dianquanheng_di316320img_NaN.width = 321;
            ui_gongyong_dianquanheng_di316320img_NaN.height = 160;
            ui_gongyong_dianquanheng_di316320img_NaN.smoothing = Constants.smoothing;
            ui_gongyong_dianquanheng_di316320img_NaN.touchable = isTouchable;
            this.addQuiackChild(ui_gongyong_dianquanheng_di316320img_NaN);
            var txture_ui_gongyong_dianquanheng_di316480:Texture = AssetMgr.instance.getTexture('ui_gongyong_dianquanheng_di');
            var ui_gongyong_dianquanheng_di316480img_NaN:Image = new Image(txture_ui_gongyong_dianquanheng_di316480);
            ui_gongyong_dianquanheng_di316480img_NaN.x = -316;
            ui_gongyong_dianquanheng_di316480img_NaN.y = 480;
            ui_gongyong_dianquanheng_di316480img_NaN.width = 321;
            ui_gongyong_dianquanheng_di316480img_NaN.height = 160;
            ui_gongyong_dianquanheng_di316480img_NaN.smoothing = Constants.smoothing;
            ui_gongyong_dianquanheng_di316480img_NaN.touchable = isTouchable;
            this.addQuiackChild(ui_gongyong_dianquanheng_di316480img_NaN);
            var txture_ui_gongyong_dianquanheng_di316156:Texture = AssetMgr.instance.getTexture('ui_gongyong_dianquanheng_di');
            var ui_gongyong_dianquanheng_di316156img_NaN:Image = new Image(txture_ui_gongyong_dianquanheng_di316156);
            ui_gongyong_dianquanheng_di316156img_NaN.x = -316;
            ui_gongyong_dianquanheng_di316156img_NaN.y = -156;
            ui_gongyong_dianquanheng_di316156img_NaN.width = 321;
            ui_gongyong_dianquanheng_di316156img_NaN.height = 160;
            ui_gongyong_dianquanheng_di316156img_NaN.smoothing = Constants.smoothing;
            ui_gongyong_dianquanheng_di316156img_NaN.touchable = isTouchable;
            this.addQuiackChild(ui_gongyong_dianquanheng_di316156img_NaN);
            var txture_ui_gongyong_dianquanheng_di640638:Texture = AssetMgr.instance.getTexture('ui_gongyong_dianquanheng_di');
            var ui_gongyong_dianquanheng_di640638img_NaN:Image = new Image(txture_ui_gongyong_dianquanheng_di640638);
            ui_gongyong_dianquanheng_di640638img_NaN.x = 640;
            ui_gongyong_dianquanheng_di640638img_NaN.y = 638;
            ui_gongyong_dianquanheng_di640638img_NaN.width = 321;
            ui_gongyong_dianquanheng_di640638img_NaN.height = 160;
            ui_gongyong_dianquanheng_di640638img_NaN.smoothing = Constants.smoothing;
            ui_gongyong_dianquanheng_di640638img_NaN.touchable = isTouchable;
            this.addQuiackChild(ui_gongyong_dianquanheng_di640638img_NaN);
            var txture_ui_gongyong_dianquanheng_di320638:Texture = AssetMgr.instance.getTexture('ui_gongyong_dianquanheng_di');
            var ui_gongyong_dianquanheng_di320638img_NaN:Image = new Image(txture_ui_gongyong_dianquanheng_di320638);
            ui_gongyong_dianquanheng_di320638img_NaN.x = 320;
            ui_gongyong_dianquanheng_di320638img_NaN.y = 638;
            ui_gongyong_dianquanheng_di320638img_NaN.width = 321;
            ui_gongyong_dianquanheng_di320638img_NaN.height = 160;
            ui_gongyong_dianquanheng_di320638img_NaN.smoothing = Constants.smoothing;
            ui_gongyong_dianquanheng_di320638img_NaN.touchable = isTouchable;
            this.addQuiackChild(ui_gongyong_dianquanheng_di320638img_NaN);
            var txture_ui_gongyong_dianquanheng_di0638:Texture = AssetMgr.instance.getTexture('ui_gongyong_dianquanheng_di');
            var ui_gongyong_dianquanheng_di0638img_NaN:Image = new Image(txture_ui_gongyong_dianquanheng_di0638);
            ui_gongyong_dianquanheng_di0638img_NaN.x = 0;
            ui_gongyong_dianquanheng_di0638img_NaN.y = 638;
            ui_gongyong_dianquanheng_di0638img_NaN.width = 321;
            ui_gongyong_dianquanheng_di0638img_NaN.height = 160;
            ui_gongyong_dianquanheng_di0638img_NaN.smoothing = Constants.smoothing;
            ui_gongyong_dianquanheng_di0638img_NaN.touchable = isTouchable;
            this.addQuiackChild(ui_gongyong_dianquanheng_di0638img_NaN);
            var txture_ui_gongyong_dianquanheng_di316638:Texture = AssetMgr.instance.getTexture('ui_gongyong_dianquanheng_di');
            var ui_gongyong_dianquanheng_di316638img_NaN:Image = new Image(txture_ui_gongyong_dianquanheng_di316638);
            ui_gongyong_dianquanheng_di316638img_NaN.x = -316;
            ui_gongyong_dianquanheng_di316638img_NaN.y = 638;
            ui_gongyong_dianquanheng_di316638img_NaN.width = 321;
            ui_gongyong_dianquanheng_di316638img_NaN.height = 160;
            ui_gongyong_dianquanheng_di316638img_NaN.smoothing = Constants.smoothing;
            ui_gongyong_dianquanheng_di316638img_NaN.touchable = isTouchable;
            this.addQuiackChild(ui_gongyong_dianquanheng_di316638img_NaN);
            var txture_ui_gongyong_dianquanheng_di9560:Texture = AssetMgr.instance.getTexture('ui_gongyong_dianquanheng_di');
            var ui_gongyong_dianquanheng_di9560img_NaN:Image = new Image(txture_ui_gongyong_dianquanheng_di9560);
            ui_gongyong_dianquanheng_di9560img_NaN.x = 956;
            ui_gongyong_dianquanheng_di9560img_NaN.y = 0;
            ui_gongyong_dianquanheng_di9560img_NaN.width = 321;
            ui_gongyong_dianquanheng_di9560img_NaN.height = 160;
            ui_gongyong_dianquanheng_di9560img_NaN.smoothing = Constants.smoothing;
            ui_gongyong_dianquanheng_di9560img_NaN.touchable = isTouchable;
            this.addQuiackChild(ui_gongyong_dianquanheng_di9560img_NaN);
            var txture_ui_gongyong_dianquanheng_di956160:Texture = AssetMgr.instance.getTexture('ui_gongyong_dianquanheng_di');
            var ui_gongyong_dianquanheng_di956160img_NaN:Image = new Image(txture_ui_gongyong_dianquanheng_di956160);
            ui_gongyong_dianquanheng_di956160img_NaN.x = 956;
            ui_gongyong_dianquanheng_di956160img_NaN.y = 160;
            ui_gongyong_dianquanheng_di956160img_NaN.width = 321;
            ui_gongyong_dianquanheng_di956160img_NaN.height = 160;
            ui_gongyong_dianquanheng_di956160img_NaN.smoothing = Constants.smoothing;
            ui_gongyong_dianquanheng_di956160img_NaN.touchable = isTouchable;
            this.addQuiackChild(ui_gongyong_dianquanheng_di956160img_NaN);
            var txture_ui_gongyong_dianquanheng_di956320:Texture = AssetMgr.instance.getTexture('ui_gongyong_dianquanheng_di');
            var ui_gongyong_dianquanheng_di956320img_NaN:Image = new Image(txture_ui_gongyong_dianquanheng_di956320);
            ui_gongyong_dianquanheng_di956320img_NaN.x = 956;
            ui_gongyong_dianquanheng_di956320img_NaN.y = 320;
            ui_gongyong_dianquanheng_di956320img_NaN.width = 321;
            ui_gongyong_dianquanheng_di956320img_NaN.height = 160;
            ui_gongyong_dianquanheng_di956320img_NaN.smoothing = Constants.smoothing;
            ui_gongyong_dianquanheng_di956320img_NaN.touchable = isTouchable;
            this.addQuiackChild(ui_gongyong_dianquanheng_di956320img_NaN);
            var txture_ui_gongyong_dianquanheng_di956480:Texture = AssetMgr.instance.getTexture('ui_gongyong_dianquanheng_di');
            var ui_gongyong_dianquanheng_di956480img_NaN:Image = new Image(txture_ui_gongyong_dianquanheng_di956480);
            ui_gongyong_dianquanheng_di956480img_NaN.x = 956;
            ui_gongyong_dianquanheng_di956480img_NaN.y = 480;
            ui_gongyong_dianquanheng_di956480img_NaN.width = 321;
            ui_gongyong_dianquanheng_di956480img_NaN.height = 160;
            ui_gongyong_dianquanheng_di956480img_NaN.smoothing = Constants.smoothing;
            ui_gongyong_dianquanheng_di956480img_NaN.touchable = isTouchable;
            this.addQuiackChild(ui_gongyong_dianquanheng_di956480img_NaN);
            var txture_ui_gongyong_dianquanheng_di956156:Texture = AssetMgr.instance.getTexture('ui_gongyong_dianquanheng_di');
            var ui_gongyong_dianquanheng_di956156img_NaN:Image = new Image(txture_ui_gongyong_dianquanheng_di956156);
            ui_gongyong_dianquanheng_di956156img_NaN.x = 956;
            ui_gongyong_dianquanheng_di956156img_NaN.y = -156;
            ui_gongyong_dianquanheng_di956156img_NaN.width = 321;
            ui_gongyong_dianquanheng_di956156img_NaN.height = 160;
            ui_gongyong_dianquanheng_di956156img_NaN.smoothing = Constants.smoothing;
            ui_gongyong_dianquanheng_di956156img_NaN.touchable = isTouchable;
            this.addQuiackChild(ui_gongyong_dianquanheng_di956156img_NaN);
            var txture_ui_gongyong_dianquanheng_di956638:Texture = AssetMgr.instance.getTexture('ui_gongyong_dianquanheng_di');
            var ui_gongyong_dianquanheng_di956638img_NaN:Image = new Image(txture_ui_gongyong_dianquanheng_di956638);
            ui_gongyong_dianquanheng_di956638img_NaN.x = 956;
            ui_gongyong_dianquanheng_di956638img_NaN.y = 638;
            ui_gongyong_dianquanheng_di956638img_NaN.width = 321;
            ui_gongyong_dianquanheng_di956638img_NaN.height = 160;
            ui_gongyong_dianquanheng_di956638img_NaN.smoothing = Constants.smoothing;
            ui_gongyong_dianquanheng_di956638img_NaN.touchable = isTouchable;
            this.addQuiackChild(ui_gongyong_dianquanheng_di956638img_NaN);

        }

    }
}