package game.view.arena.base {
    import com.dialog.Dialog;
    import com.utils.Constants;

    import game.manager.AssetMgr;

    import starling.display.Button;
    import starling.display.Image;
    import starling.text.TextField;
    import starling.textures.Texture;

    public class ArenaDlgBase extends Dialog {
        public var photoBgImage:Image;
        public var closeButton:Button;
        public var nameTxt:TextField;
        public var RankTxt:TextField;
        public var diamondTxt:TextField;
        public var parImage:Image;
        public var parBgImage:Image;
        public var honorTxt:TextField;
        public var currentLevelNameTxt:TextField;
        public var RankNameTxt:TextField;
        public var progressTxt:TextField;
        public var nextLevelNameTxt:TextField;
        public var levelIconImage:Image;
        public var kTxt:TextField;
        public var k1Txt:TextField;

        public function ArenaDlgBase() {
            var photoBgTexture:Texture = AssetMgr.instance.getTexture('ui_pvp_renwuxinxi_di');
            photoBgImage = new Image(photoBgTexture);
            photoBgImage.x = 49;
            photoBgImage.y = 0;
            photoBgImage.width = 266;
            photoBgImage.height = 111;
            this.addQuiackChild(photoBgImage);
            var ui_gongyong_tielianpaizi35821Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_tielianpaizi');
            var ui_gongyong_tielianpaizi35821Image:Image = new Image(ui_gongyong_tielianpaizi35821Texture);
            ui_gongyong_tielianpaizi35821Image.x = 358;
            ui_gongyong_tielianpaizi35821Image.y = -20;
            ui_gongyong_tielianpaizi35821Image.width = 244;
            ui_gongyong_tielianpaizi35821Image.height = 137;
            ui_gongyong_tielianpaizi35821Image.smoothing = Constants.smoothing;
            ui_gongyong_tielianpaizi35821Image.touchable = false;
            this.addQuiackChild(ui_gongyong_tielianpaizi35821Image);
            var closeTexture:Texture = AssetMgr.instance.getTexture('ui_gongyong_tuichuanniiu');
            closeButton = new Button(closeTexture);
            closeButton.x = 835;
            closeButton.y = -38;
            this.addQuiackChild(closeButton);
            var ui_gongyong_yibanmubanhentiao0110Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao0110Image:Image = new Image(ui_gongyong_yibanmubanhentiao0110Texture);
            ui_gongyong_yibanmubanhentiao0110Image.x = 0;
            ui_gongyong_yibanmubanhentiao0110Image.y = 110;
            ui_gongyong_yibanmubanhentiao0110Image.width = 490;
            ui_gongyong_yibanmubanhentiao0110Image.height = 73;
            ui_gongyong_yibanmubanhentiao0110Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao0110Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao0110Image);
            var ui_gongyong_yibanmubanhentiao960110Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao960110Image:Image = new Image(ui_gongyong_yibanmubanhentiao960110Texture);
            ui_gongyong_yibanmubanhentiao960110Image.x = 960;
            ui_gongyong_yibanmubanhentiao960110Image.y = 110;
            ui_gongyong_yibanmubanhentiao960110Image.width = 490;
            ui_gongyong_yibanmubanhentiao960110Image.height = 73;
            ui_gongyong_yibanmubanhentiao960110Image.scaleX = -1;
            ui_gongyong_yibanmubanhentiao960110Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao960110Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao960110Image);
            var ui_gongyong_yibanmubanhentiao0183Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao0183Image:Image = new Image(ui_gongyong_yibanmubanhentiao0183Texture);
            ui_gongyong_yibanmubanhentiao0183Image.x = 0;
            ui_gongyong_yibanmubanhentiao0183Image.y = 183;
            ui_gongyong_yibanmubanhentiao0183Image.width = 490;
            ui_gongyong_yibanmubanhentiao0183Image.height = 73;
            ui_gongyong_yibanmubanhentiao0183Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao0183Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao0183Image);
            var ui_gongyong_yibanmubanhentiao960183Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao960183Image:Image = new Image(ui_gongyong_yibanmubanhentiao960183Texture);
            ui_gongyong_yibanmubanhentiao960183Image.x = 960;
            ui_gongyong_yibanmubanhentiao960183Image.y = 183;
            ui_gongyong_yibanmubanhentiao960183Image.width = 490;
            ui_gongyong_yibanmubanhentiao960183Image.height = 73;
            ui_gongyong_yibanmubanhentiao960183Image.scaleX = -1;
            ui_gongyong_yibanmubanhentiao960183Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao960183Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao960183Image);
            var ui_gongyong_yibanmubanhentiao0256Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao0256Image:Image = new Image(ui_gongyong_yibanmubanhentiao0256Texture);
            ui_gongyong_yibanmubanhentiao0256Image.x = 0;
            ui_gongyong_yibanmubanhentiao0256Image.y = 256;
            ui_gongyong_yibanmubanhentiao0256Image.width = 490;
            ui_gongyong_yibanmubanhentiao0256Image.height = 73;
            ui_gongyong_yibanmubanhentiao0256Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao0256Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao0256Image);
            var ui_gongyong_yibanmubanhentiao960256Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao960256Image:Image = new Image(ui_gongyong_yibanmubanhentiao960256Texture);
            ui_gongyong_yibanmubanhentiao960256Image.x = 960;
            ui_gongyong_yibanmubanhentiao960256Image.y = 256;
            ui_gongyong_yibanmubanhentiao960256Image.width = 490;
            ui_gongyong_yibanmubanhentiao960256Image.height = 73;
            ui_gongyong_yibanmubanhentiao960256Image.scaleX = -1;
            ui_gongyong_yibanmubanhentiao960256Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao960256Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao960256Image);
            var ui_gongyong_yibanmubanhentiao0329Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao0329Image:Image = new Image(ui_gongyong_yibanmubanhentiao0329Texture);
            ui_gongyong_yibanmubanhentiao0329Image.x = 0;
            ui_gongyong_yibanmubanhentiao0329Image.y = 329;
            ui_gongyong_yibanmubanhentiao0329Image.width = 490;
            ui_gongyong_yibanmubanhentiao0329Image.height = 73;
            ui_gongyong_yibanmubanhentiao0329Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao0329Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao0329Image);
            var ui_gongyong_yibanmubanhentiao960329Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao960329Image:Image = new Image(ui_gongyong_yibanmubanhentiao960329Texture);
            ui_gongyong_yibanmubanhentiao960329Image.x = 960;
            ui_gongyong_yibanmubanhentiao960329Image.y = 329;
            ui_gongyong_yibanmubanhentiao960329Image.width = 490;
            ui_gongyong_yibanmubanhentiao960329Image.height = 73;
            ui_gongyong_yibanmubanhentiao960329Image.scaleX = -1;
            ui_gongyong_yibanmubanhentiao960329Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao960329Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao960329Image);
            var ui_gongyong_yibanmubanhentiao0402Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao0402Image:Image = new Image(ui_gongyong_yibanmubanhentiao0402Texture);
            ui_gongyong_yibanmubanhentiao0402Image.x = 0;
            ui_gongyong_yibanmubanhentiao0402Image.y = 402;
            ui_gongyong_yibanmubanhentiao0402Image.width = 490;
            ui_gongyong_yibanmubanhentiao0402Image.height = 73;
            ui_gongyong_yibanmubanhentiao0402Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao0402Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao0402Image);
            var ui_gongyong_yibanmubanhentiao960402Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao960402Image:Image = new Image(ui_gongyong_yibanmubanhentiao960402Texture);
            ui_gongyong_yibanmubanhentiao960402Image.x = 960;
            ui_gongyong_yibanmubanhentiao960402Image.y = 402;
            ui_gongyong_yibanmubanhentiao960402Image.width = 490;
            ui_gongyong_yibanmubanhentiao960402Image.height = 73;
            ui_gongyong_yibanmubanhentiao960402Image.scaleX = -1;
            ui_gongyong_yibanmubanhentiao960402Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao960402Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao960402Image);
            var ui_gongyong_yibanmubanhentiao0475Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao0475Image:Image = new Image(ui_gongyong_yibanmubanhentiao0475Texture);
            ui_gongyong_yibanmubanhentiao0475Image.x = 0;
            ui_gongyong_yibanmubanhentiao0475Image.y = 475;
            ui_gongyong_yibanmubanhentiao0475Image.width = 490;
            ui_gongyong_yibanmubanhentiao0475Image.height = 73;
            ui_gongyong_yibanmubanhentiao0475Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao0475Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao0475Image);
            var ui_gongyong_yibanmubanhentiao960475Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao960475Image:Image = new Image(ui_gongyong_yibanmubanhentiao960475Texture);
            ui_gongyong_yibanmubanhentiao960475Image.x = 960;
            ui_gongyong_yibanmubanhentiao960475Image.y = 475;
            ui_gongyong_yibanmubanhentiao960475Image.width = 490;
            ui_gongyong_yibanmubanhentiao960475Image.height = 73;
            ui_gongyong_yibanmubanhentiao960475Image.scaleX = -1;
            ui_gongyong_yibanmubanhentiao960475Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao960475Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao960475Image);
            var ui_gongyong_yibanmubanhentiao0548Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao0548Image:Image = new Image(ui_gongyong_yibanmubanhentiao0548Texture);
            ui_gongyong_yibanmubanhentiao0548Image.x = 0;
            ui_gongyong_yibanmubanhentiao0548Image.y = 548;
            ui_gongyong_yibanmubanhentiao0548Image.width = 490;
            ui_gongyong_yibanmubanhentiao0548Image.height = 73;
            ui_gongyong_yibanmubanhentiao0548Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao0548Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao0548Image);
            var ui_gongyong_yibanmubanhentiao960548Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao960548Image:Image = new Image(ui_gongyong_yibanmubanhentiao960548Texture);
            ui_gongyong_yibanmubanhentiao960548Image.x = 960;
            ui_gongyong_yibanmubanhentiao960548Image.y = 548;
            ui_gongyong_yibanmubanhentiao960548Image.width = 490;
            ui_gongyong_yibanmubanhentiao960548Image.height = 73;
            ui_gongyong_yibanmubanhentiao960548Image.scaleX = -1;
            ui_gongyong_yibanmubanhentiao960548Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao960548Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao960548Image);
            var ui_gongyong_bumangdi_shangbianyikuaitie358106Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_bumangdi_shangbianyikuaitie');
            var ui_gongyong_bumangdi_shangbianyikuaitie358106Image:Image = new Image(ui_gongyong_bumangdi_shangbianyikuaitie358106Texture);
            ui_gongyong_bumangdi_shangbianyikuaitie358106Image.x = 358;
            ui_gongyong_bumangdi_shangbianyikuaitie358106Image.y = 106;
            ui_gongyong_bumangdi_shangbianyikuaitie358106Image.width = 30;
            ui_gongyong_bumangdi_shangbianyikuaitie358106Image.height = 21;
            ui_gongyong_bumangdi_shangbianyikuaitie358106Image.smoothing = Constants.smoothing;
            ui_gongyong_bumangdi_shangbianyikuaitie358106Image.touchable = false;
            this.addQuiackChild(ui_gongyong_bumangdi_shangbianyikuaitie358106Image);
            var ui_gongyong_bumangdi_shangbianyikuaitie602106Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_bumangdi_shangbianyikuaitie');
            var ui_gongyong_bumangdi_shangbianyikuaitie602106Image:Image = new Image(ui_gongyong_bumangdi_shangbianyikuaitie602106Texture);
            ui_gongyong_bumangdi_shangbianyikuaitie602106Image.x = 602;
            ui_gongyong_bumangdi_shangbianyikuaitie602106Image.y = 106;
            ui_gongyong_bumangdi_shangbianyikuaitie602106Image.width = 30;
            ui_gongyong_bumangdi_shangbianyikuaitie602106Image.height = 21;
            ui_gongyong_bumangdi_shangbianyikuaitie602106Image.scaleX = -1;
            ui_gongyong_bumangdi_shangbianyikuaitie602106Image.smoothing = Constants.smoothing;
            ui_gongyong_bumangdi_shangbianyikuaitie602106Image.touchable = false;
            this.addQuiackChild(ui_gongyong_bumangdi_shangbianyikuaitie602106Image);
            var ui_gongyong_yibanmubanhentiao_di3894170Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao_di3');
            var ui_gongyong_yibanmubanhentiao_di3894170Image:Image = new Image(ui_gongyong_yibanmubanhentiao_di3894170Texture);
            ui_gongyong_yibanmubanhentiao_di3894170Image.x = 894;
            ui_gongyong_yibanmubanhentiao_di3894170Image.y = 170;
            ui_gongyong_yibanmubanhentiao_di3894170Image.width = 32;
            ui_gongyong_yibanmubanhentiao_di3894170Image.height = 396;
            ui_gongyong_yibanmubanhentiao_di3894170Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao_di3894170Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao_di3894170Image);
            var ui_gongyong_yibanmubanhentiao_di231170Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao_di2');
            var ui_gongyong_yibanmubanhentiao_di231170Image:Image = new Image(ui_gongyong_yibanmubanhentiao_di231170Texture);
            ui_gongyong_yibanmubanhentiao_di231170Image.x = 31;
            ui_gongyong_yibanmubanhentiao_di231170Image.y = 170;
            ui_gongyong_yibanmubanhentiao_di231170Image.width = 32;
            ui_gongyong_yibanmubanhentiao_di231170Image.height = 396;
            ui_gongyong_yibanmubanhentiao_di231170Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao_di231170Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao_di231170Image);
            var ui_gongyong_yibanmubanhentiao_di463187Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao_di4');
            var ui_gongyong_yibanmubanhentiao_di463187Image:Image = new Image(ui_gongyong_yibanmubanhentiao_di463187Texture);
            ui_gongyong_yibanmubanhentiao_di463187Image.x = 63;
            ui_gongyong_yibanmubanhentiao_di463187Image.y = 187;
            ui_gongyong_yibanmubanhentiao_di463187Image.width = 848;
            ui_gongyong_yibanmubanhentiao_di463187Image.height = 368;
            ui_gongyong_yibanmubanhentiao_di463187Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao_di463187Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao_di463187Image);
            var ui_gongyong_yibanmubanhentiao_di156170Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao_di1');
            var ui_gongyong_yibanmubanhentiao_di156170Image:Image = new Image(ui_gongyong_yibanmubanhentiao_di156170Texture);
            ui_gongyong_yibanmubanhentiao_di156170Image.x = 56;
            ui_gongyong_yibanmubanhentiao_di156170Image.y = 170;
            ui_gongyong_yibanmubanhentiao_di156170Image.width = 848;
            ui_gongyong_yibanmubanhentiao_di156170Image.height = 22;
            ui_gongyong_yibanmubanhentiao_di156170Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao_di156170Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao_di156170Image);
            var ui_gongyong_yibanmubanhentiao_di156565Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao_di1');
            var ui_gongyong_yibanmubanhentiao_di156565Image:Image = new Image(ui_gongyong_yibanmubanhentiao_di156565Texture);
            ui_gongyong_yibanmubanhentiao_di156565Image.x = 56;
            ui_gongyong_yibanmubanhentiao_di156565Image.y = 565;
            ui_gongyong_yibanmubanhentiao_di156565Image.width = 848;
            ui_gongyong_yibanmubanhentiao_di156565Image.height = 22;
            ui_gongyong_yibanmubanhentiao_di156565Image.scaleY = -0.9565277099609375;
            ui_gongyong_yibanmubanhentiao_di156565Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao_di156565Image.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao_di156565Image);
            var ui_gongyong_jinbibaizidi26126Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_jinbibaizidi2');
            var ui_gongyong_jinbibaizidi26126Image:Image = new Image(ui_gongyong_jinbibaizidi26126Texture);
            ui_gongyong_jinbibaizidi26126Image.x = 612;
            ui_gongyong_jinbibaizidi26126Image.y = 6;
            ui_gongyong_jinbibaizidi26126Image.width = 197;
            ui_gongyong_jinbibaizidi26126Image.height = 99;
            ui_gongyong_jinbibaizidi26126Image.smoothing = Constants.smoothing;
            ui_gongyong_jinbibaizidi26126Image.touchable = false;
            this.addQuiackChild(ui_gongyong_jinbibaizidi26126Image);
            var ui_gongyong_zuanshi6239Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_zuanshi');
            var ui_gongyong_zuanshi6239Image:Image = new Image(ui_gongyong_zuanshi6239Texture);
            ui_gongyong_zuanshi6239Image.x = 623;
            ui_gongyong_zuanshi6239Image.y = 9;
            ui_gongyong_zuanshi6239Image.width = 46;
            ui_gongyong_zuanshi6239Image.height = 44;
            ui_gongyong_zuanshi6239Image.smoothing = Constants.smoothing;
            ui_gongyong_zuanshi6239Image.touchable = false;
            this.addQuiackChild(ui_gongyong_zuanshi6239Image);
            nameTxt = new TextField(193, 38, '', '', 24, 0xF6F0D0, false);
            nameTxt.touchable = false;
            nameTxt.hAlign = 'center';
            nameTxt.x = 135;
            nameTxt.y = 9;
            this.addQuiackChild(nameTxt);
            RankTxt = new TextField(111, 28, '', '', 18, 0xE5CF21, false);
            RankTxt.touchable = false;
            RankTxt.hAlign = 'center';
            RankTxt.x = 189;
            RankTxt.y = 69;
            this.addQuiackChild(RankTxt);
            diamondTxt = new TextField(132, 38, '', '', 24, 0xFFFFFF, false);
            diamondTxt.hAlign = "left";
            diamondTxt.touchable = false;
            diamondTxt.x = 666;
            diamondTxt.y = 14;
            this.addQuiackChild(diamondTxt);
            var parTexture:Texture = AssetMgr.instance.getTexture('ui_pvp_duanweitiao2');
            parImage = new Image(parTexture);
            parImage.x = 193;
            parImage.y = 129;
            parImage.width = 574;
            parImage.height = 27;
            this.addQuiackChild(parImage);
            var parBgTexture:Texture = AssetMgr.instance.getTexture('ui_pvp_duanweitiao1');
            parBgImage = new Image(parBgTexture);
            parBgImage.x = 197;
            parBgImage.y = 134;
            parBgImage.width = 567;
            parBgImage.height = 17;
            this.addQuiackChild(parBgImage);
            var ui_pvp_duanweitiao3197134Texture:Texture = AssetMgr.instance.getTexture('ui_pvp_duanweitiao3');
            var ui_pvp_duanweitiao3197134Image:Image = new Image(ui_pvp_duanweitiao3197134Texture);
            ui_pvp_duanweitiao3197134Image.x = 197;
            ui_pvp_duanweitiao3197134Image.y = 134;
            ui_pvp_duanweitiao3197134Image.width = 567;
            ui_pvp_duanweitiao3197134Image.height = 17;
            ui_pvp_duanweitiao3197134Image.smoothing = Constants.smoothing;
            ui_pvp_duanweitiao3197134Image.touchable = false;
            this.addQuiackChild(ui_pvp_duanweitiao3197134Image);
            honorTxt = new TextField(133, 38, '', '', 24, 0xFFFFFF, false);
            honorTxt.touchable = false;
            honorTxt.hAlign = "left";
            honorTxt.x = 666;
            honorTxt.y = 59;
            this.addQuiackChild(honorTxt);
            var ui_pvp_wenzijibie_di99126Texture:Texture = AssetMgr.instance.getTexture('ui_pvp_wenzijibie_di');
            var ui_pvp_wenzijibie_di99126Image:Image = new Image(ui_pvp_wenzijibie_di99126Texture);
            ui_pvp_wenzijibie_di99126Image.x = 99;
            ui_pvp_wenzijibie_di99126Image.y = 126;
            ui_pvp_wenzijibie_di99126Image.width = 90;
            ui_pvp_wenzijibie_di99126Image.height = 31;
            ui_pvp_wenzijibie_di99126Image.smoothing = Constants.smoothing;
            ui_pvp_wenzijibie_di99126Image.touchable = false;
            this.addQuiackChild(ui_pvp_wenzijibie_di99126Image);
            currentLevelNameTxt = new TextField(76, 28, '', '', 18, 0xFFF99B, false);
            currentLevelNameTxt.touchable = false;
            currentLevelNameTxt.hAlign = 'center';
            currentLevelNameTxt.x = 104;
            currentLevelNameTxt.y = 126;
            this.addQuiackChild(currentLevelNameTxt);
            var ui_pvp_rongyuzhibiaozhi162955Texture:Texture = AssetMgr.instance.getTexture('ui_pvp_rongyuzhibiaozhi1');
            var ui_pvp_rongyuzhibiaozhi162955Image:Image = new Image(ui_pvp_rongyuzhibiaozhi162955Texture);
            ui_pvp_rongyuzhibiaozhi162955Image.x = 629;
            ui_pvp_rongyuzhibiaozhi162955Image.y = 55;
            ui_pvp_rongyuzhibiaozhi162955Image.width = 32;
            ui_pvp_rongyuzhibiaozhi162955Image.height = 45;
            ui_pvp_rongyuzhibiaozhi162955Image.smoothing = Constants.smoothing;
            ui_pvp_rongyuzhibiaozhi162955Image.touchable = false;
            this.addQuiackChild(ui_pvp_rongyuzhibiaozhi162955Image);
            RankNameTxt = new TextField(66, 28, '', '', 18, 0xE5CF21, false);
            RankNameTxt.touchable = false;
            RankNameTxt.hAlign = 'center';
            RankNameTxt.x = 149;
            RankNameTxt.y = 67;
            this.addQuiackChild(RankNameTxt);
            var ui_gongyong_heisetongmingding20426132Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_heisetongmingding20');
            var ui_gongyong_heisetongmingding20426132Image:Image = new Image(ui_gongyong_heisetongmingding20426132Texture);
            ui_gongyong_heisetongmingding20426132Image.x = 426;
            ui_gongyong_heisetongmingding20426132Image.y = 132;
            ui_gongyong_heisetongmingding20426132Image.width = 110;
            ui_gongyong_heisetongmingding20426132Image.height = 20;
            ui_gongyong_heisetongmingding20426132Image.smoothing = Constants.smoothing;
            ui_gongyong_heisetongmingding20426132Image.touchable = false;
            this.addQuiackChild(ui_gongyong_heisetongmingding20426132Image);
            progressTxt = new TextField(146, 28, '', '', 18, 0xFFFFFF, false);
            progressTxt.touchable = false;
            progressTxt.hAlign = 'center';
            progressTxt.x = 405;
            progressTxt.y = 127;
            this.addQuiackChild(progressTxt);
            var ui_pvp_wenzijibie_di772127Texture:Texture = AssetMgr.instance.getTexture('ui_pvp_wenzijibie_di');
            var ui_pvp_wenzijibie_di772127Image:Image = new Image(ui_pvp_wenzijibie_di772127Texture);
            ui_pvp_wenzijibie_di772127Image.x = 772;
            ui_pvp_wenzijibie_di772127Image.y = 127;
            ui_pvp_wenzijibie_di772127Image.width = 90;
            ui_pvp_wenzijibie_di772127Image.height = 31;
            ui_pvp_wenzijibie_di772127Image.smoothing = Constants.smoothing;
            ui_pvp_wenzijibie_di772127Image.touchable = false;
            this.addQuiackChild(ui_pvp_wenzijibie_di772127Image);
            nextLevelNameTxt = new TextField(76, 28, '', '', 18, 0xFFF99B, false);
            nextLevelNameTxt.touchable = false;
            nextLevelNameTxt.hAlign = 'center';
            nextLevelNameTxt.x = 777;
            nextLevelNameTxt.y = 127;
            this.addQuiackChild(nextLevelNameTxt);
            var ui_wenzi_xinjingjichang42035Texture:Texture = AssetMgr.instance.getTexture('ui_wenzi_xinjingjichang');
            var ui_wenzi_xinjingjichang42035Image:Image = new Image(ui_wenzi_xinjingjichang42035Texture);
            ui_wenzi_xinjingjichang42035Image.x = 420;
            ui_wenzi_xinjingjichang42035Image.y = 35;
            ui_wenzi_xinjingjichang42035Image.width = 121;
            ui_wenzi_xinjingjichang42035Image.height = 49;
            ui_wenzi_xinjingjichang42035Image.smoothing = Constants.smoothing;
            ui_wenzi_xinjingjichang42035Image.touchable = false;
            this.addQuiackChild(ui_wenzi_xinjingjichang42035Image);
            var levelIconTexture:Texture = AssetMgr.instance.getTexture('ui_tubiao_duanwei1');
            levelIconImage = new Image(levelIconTexture);
            levelIconImage.x = 19;
            levelIconImage.y = 50;
            levelIconImage.width = 69;
            levelIconImage.height = 67;
            this.addQuiackChild(levelIconImage);
            kTxt = new TextField(104, 36, '', '', 24, 0xFF9021, false);
            kTxt.touchable = false;
            kTxt.hAlign = 'left';
            kTxt.x = 736;
            kTxt.y = 12;
            this.addQuiackChild(kTxt);
            k1Txt = new TextField(104, 36, '', '', 24, 0xFF9021, false);
            k1Txt.touchable = false;
            k1Txt.hAlign = 'left';
            k1Txt.x = 736;
            k1Txt.y = 61;
            this.addQuiackChild(k1Txt);

        }

        override public function dispose():void {
            closeButton.dispose();
            super.dispose();

        }

    }
}