package game.view.arena.base {
    import com.dialog.Dialog;
    import com.utils.Constants;

    import flash.geom.Rectangle;

    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;

    import game.manager.AssetMgr;

    import starling.display.Button;
    import starling.display.Image;
    import starling.text.TextField;
    import starling.textures.Texture;

    public class ConvertPropsDlgBase extends Dialog {
        public var bgClose9Scale:Scale9Image;
        public var sellButton:Button;
        public var equipContainerButton:Button;
        public var nameTxt:TextField;
        public var descTxt:TextField;
        public var moneyTxt:TextField;
        public var numTxt:TextField;
        public var closeButton:Button;
        public var moneyIocnImage:Image;

        public function ConvertPropsDlgBase() {
            var bgCloseTexture:Texture = AssetMgr.instance.getTexture('ui_gongyong_heisetongmingding50');
            var bgCloseRect:Rectangle = new Rectangle(18, 18, 35, 35);
            var bgClose9ScaleTexture:Scale9Textures = new Scale9Textures(bgCloseTexture, bgCloseRect);
            bgClose9Scale = new Scale9Image(bgClose9ScaleTexture);
            bgClose9Scale.x = 1;
            bgClose9Scale.y = 1;
            bgClose9Scale.width = 960;
            bgClose9Scale.height = 640;
            this.addQuiackChild(bgClose9Scale);
            var ui_gongyong_dingzimutiao60090Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_dingzimutiao');
            var ui_gongyong_dingzimutiao60090Image:Image = new Image(ui_gongyong_dingzimutiao60090Texture);
            ui_gongyong_dingzimutiao60090Image.x = 600;
            ui_gongyong_dingzimutiao60090Image.y = 90;
            ui_gongyong_dingzimutiao60090Image.width = 313;
            ui_gongyong_dingzimutiao60090Image.height = 66;
            ui_gongyong_dingzimutiao60090Image.scaleX = -0.6042327880859375;
            ui_gongyong_dingzimutiao60090Image.smoothing = Constants.smoothing;
            ui_gongyong_dingzimutiao60090Image.touchable = false;
            this.addQuiackChild(ui_gongyong_dingzimutiao60090Image);
            var ui_gongyong_dingzimutiao600155Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_dingzimutiao');
            var ui_gongyong_dingzimutiao600155Image:Image = new Image(ui_gongyong_dingzimutiao600155Texture);
            ui_gongyong_dingzimutiao600155Image.x = 600;
            ui_gongyong_dingzimutiao600155Image.y = 155;
            ui_gongyong_dingzimutiao600155Image.width = 313;
            ui_gongyong_dingzimutiao600155Image.height = 66;
            ui_gongyong_dingzimutiao600155Image.scaleX = -0.6042327880859375;
            ui_gongyong_dingzimutiao600155Image.smoothing = Constants.smoothing;
            ui_gongyong_dingzimutiao600155Image.touchable = false;
            this.addQuiackChild(ui_gongyong_dingzimutiao600155Image);
            var ui_gongyong_dingzimutiao600220Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_dingzimutiao');
            var ui_gongyong_dingzimutiao600220Image:Image = new Image(ui_gongyong_dingzimutiao600220Texture);
            ui_gongyong_dingzimutiao600220Image.x = 600;
            ui_gongyong_dingzimutiao600220Image.y = 220;
            ui_gongyong_dingzimutiao600220Image.width = 313;
            ui_gongyong_dingzimutiao600220Image.height = 66;
            ui_gongyong_dingzimutiao600220Image.scaleX = -0.6042327880859375;
            ui_gongyong_dingzimutiao600220Image.smoothing = Constants.smoothing;
            ui_gongyong_dingzimutiao600220Image.touchable = false;
            this.addQuiackChild(ui_gongyong_dingzimutiao600220Image);
            var ui_gongyong_dingzimutiao600285Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_dingzimutiao');
            var ui_gongyong_dingzimutiao600285Image:Image = new Image(ui_gongyong_dingzimutiao600285Texture);
            ui_gongyong_dingzimutiao600285Image.x = 600;
            ui_gongyong_dingzimutiao600285Image.y = 285;
            ui_gongyong_dingzimutiao600285Image.width = 313;
            ui_gongyong_dingzimutiao600285Image.height = 66;
            ui_gongyong_dingzimutiao600285Image.scaleX = -0.6042327880859375;
            ui_gongyong_dingzimutiao600285Image.smoothing = Constants.smoothing;
            ui_gongyong_dingzimutiao600285Image.touchable = false;
            this.addQuiackChild(ui_gongyong_dingzimutiao600285Image);
            var ui_gongyong_dingzimutiao600350Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_dingzimutiao');
            var ui_gongyong_dingzimutiao600350Image:Image = new Image(ui_gongyong_dingzimutiao600350Texture);
            ui_gongyong_dingzimutiao600350Image.x = 600;
            ui_gongyong_dingzimutiao600350Image.y = 350;
            ui_gongyong_dingzimutiao600350Image.width = 313;
            ui_gongyong_dingzimutiao600350Image.height = 66;
            ui_gongyong_dingzimutiao600350Image.scaleX = -0.6042327880859375;
            ui_gongyong_dingzimutiao600350Image.smoothing = Constants.smoothing;
            ui_gongyong_dingzimutiao600350Image.touchable = false;
            this.addQuiackChild(ui_gongyong_dingzimutiao600350Image);
            var ui_gongyong_dingzimutiao36390Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_dingzimutiao');
            var ui_gongyong_dingzimutiao36390Image:Image = new Image(ui_gongyong_dingzimutiao36390Texture);
            ui_gongyong_dingzimutiao36390Image.x = 363;
            ui_gongyong_dingzimutiao36390Image.y = 90;
            ui_gongyong_dingzimutiao36390Image.width = 312;
            ui_gongyong_dingzimutiao36390Image.height = 66;
            ui_gongyong_dingzimutiao36390Image.smoothing = Constants.smoothing;
            ui_gongyong_dingzimutiao36390Image.touchable = false;
            this.addQuiackChild(ui_gongyong_dingzimutiao36390Image);
            var ui_gongyong_dingzimutiao363155Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_dingzimutiao');
            var ui_gongyong_dingzimutiao363155Image:Image = new Image(ui_gongyong_dingzimutiao363155Texture);
            ui_gongyong_dingzimutiao363155Image.x = 363;
            ui_gongyong_dingzimutiao363155Image.y = 155;
            ui_gongyong_dingzimutiao363155Image.width = 312;
            ui_gongyong_dingzimutiao363155Image.height = 66;
            ui_gongyong_dingzimutiao363155Image.smoothing = Constants.smoothing;
            ui_gongyong_dingzimutiao363155Image.touchable = false;
            this.addQuiackChild(ui_gongyong_dingzimutiao363155Image);
            var ui_gongyong_dingzimutiao363220Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_dingzimutiao');
            var ui_gongyong_dingzimutiao363220Image:Image = new Image(ui_gongyong_dingzimutiao363220Texture);
            ui_gongyong_dingzimutiao363220Image.x = 363;
            ui_gongyong_dingzimutiao363220Image.y = 220;
            ui_gongyong_dingzimutiao363220Image.width = 312;
            ui_gongyong_dingzimutiao363220Image.height = 66;
            ui_gongyong_dingzimutiao363220Image.smoothing = Constants.smoothing;
            ui_gongyong_dingzimutiao363220Image.touchable = false;
            this.addQuiackChild(ui_gongyong_dingzimutiao363220Image);
            var ui_gongyong_dingzimutiao363285Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_dingzimutiao');
            var ui_gongyong_dingzimutiao363285Image:Image = new Image(ui_gongyong_dingzimutiao363285Texture);
            ui_gongyong_dingzimutiao363285Image.x = 363;
            ui_gongyong_dingzimutiao363285Image.y = 285;
            ui_gongyong_dingzimutiao363285Image.width = 312;
            ui_gongyong_dingzimutiao363285Image.height = 66;
            ui_gongyong_dingzimutiao363285Image.smoothing = Constants.smoothing;
            ui_gongyong_dingzimutiao363285Image.touchable = false;
            this.addQuiackChild(ui_gongyong_dingzimutiao363285Image);
            var ui_gongyong_dingzimutiao363350Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_dingzimutiao');
            var ui_gongyong_dingzimutiao363350Image:Image = new Image(ui_gongyong_dingzimutiao363350Texture);
            ui_gongyong_dingzimutiao363350Image.x = 363;
            ui_gongyong_dingzimutiao363350Image.y = 350;
            ui_gongyong_dingzimutiao363350Image.width = 312;
            ui_gongyong_dingzimutiao363350Image.height = 66;
            ui_gongyong_dingzimutiao363350Image.smoothing = Constants.smoothing;
            ui_gongyong_dingzimutiao363350Image.touchable = false;
            this.addQuiackChild(ui_gongyong_dingzimutiao363350Image);
            var ui_gongyong_dingzimutiao363415Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_dingzimutiao');
            var ui_gongyong_dingzimutiao363415Image:Image = new Image(ui_gongyong_dingzimutiao363415Texture);
            ui_gongyong_dingzimutiao363415Image.x = 363;
            ui_gongyong_dingzimutiao363415Image.y = 415;
            ui_gongyong_dingzimutiao363415Image.width = 312;
            ui_gongyong_dingzimutiao363415Image.height = 66;
            ui_gongyong_dingzimutiao363415Image.smoothing = Constants.smoothing;
            ui_gongyong_dingzimutiao363415Image.touchable = false;
            this.addQuiackChild(ui_gongyong_dingzimutiao363415Image);
            var ui_gongyong_dingzimutiao600415Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_dingzimutiao');
            var ui_gongyong_dingzimutiao600415Image:Image = new Image(ui_gongyong_dingzimutiao600415Texture);
            ui_gongyong_dingzimutiao600415Image.x = 600;
            ui_gongyong_dingzimutiao600415Image.y = 415;
            ui_gongyong_dingzimutiao600415Image.width = 313;
            ui_gongyong_dingzimutiao600415Image.height = 66;
            ui_gongyong_dingzimutiao600415Image.scaleX = -0.6042327880859375;
            ui_gongyong_dingzimutiao600415Image.smoothing = Constants.smoothing;
            ui_gongyong_dingzimutiao600415Image.touchable = false;
            this.addQuiackChild(ui_gongyong_dingzimutiao600415Image);
            var sellTexture:Texture = AssetMgr.instance.getTexture('ui_button_tiebaomutouanjian');
            sellButton = new Button(sellTexture);
            sellButton.x = 473;
            sellButton.y = 400;
            this.addQuiackChild(sellButton);
            var ui_shangcheng_fuhedi616110Texture:Texture = AssetMgr.instance.getTexture('ui_shangcheng_fuhedi');
            var ui_shangcheng_fuhedi616110Image:Image = new Image(ui_shangcheng_fuhedi616110Texture);
            ui_shangcheng_fuhedi616110Image.x = 616;
            ui_shangcheng_fuhedi616110Image.y = 110;
            ui_shangcheng_fuhedi616110Image.width = 135;
            ui_shangcheng_fuhedi616110Image.height = 280;
            ui_shangcheng_fuhedi616110Image.scaleX = -1;
            ui_shangcheng_fuhedi616110Image.smoothing = Constants.smoothing;
            ui_shangcheng_fuhedi616110Image.touchable = false;
            this.addQuiackChild(ui_shangcheng_fuhedi616110Image);
            var ui_shangcheng_fuhedi347110Texture:Texture = AssetMgr.instance.getTexture('ui_shangcheng_fuhedi');
            var ui_shangcheng_fuhedi347110Image:Image = new Image(ui_shangcheng_fuhedi347110Texture);
            ui_shangcheng_fuhedi347110Image.x = 347;
            ui_shangcheng_fuhedi347110Image.y = 110;
            ui_shangcheng_fuhedi347110Image.width = 135;
            ui_shangcheng_fuhedi347110Image.height = 280;
            ui_shangcheng_fuhedi347110Image.smoothing = Constants.smoothing;
            ui_shangcheng_fuhedi347110Image.touchable = false;
            this.addQuiackChild(ui_shangcheng_fuhedi347110Image);
            var equipContainerTexture:Texture = AssetMgr.instance.getTexture('ui_gongyong_90wupingkuang0');
            equipContainerButton = new Button(equipContainerTexture);
            equipContainerButton.x = 429;
            equipContainerButton.y = 170;
            this.addQuiackChild(equipContainerButton);
            var ui_shangcheng_fuhedi_mingzidi390118Texture:Texture = AssetMgr.instance.getTexture('ui_shangcheng_fuhedi_mingzidi');
            var ui_shangcheng_fuhedi_mingzidi390118Image:Image = new Image(ui_shangcheng_fuhedi_mingzidi390118Texture);
            ui_shangcheng_fuhedi_mingzidi390118Image.x = 390;
            ui_shangcheng_fuhedi_mingzidi390118Image.y = 118;
            ui_shangcheng_fuhedi_mingzidi390118Image.width = 89;
            ui_shangcheng_fuhedi_mingzidi390118Image.height = 43;
            ui_shangcheng_fuhedi_mingzidi390118Image.smoothing = Constants.smoothing;
            ui_shangcheng_fuhedi_mingzidi390118Image.touchable = false;
            this.addQuiackChild(ui_shangcheng_fuhedi_mingzidi390118Image);
            var ui_shangcheng_fuhedi_mingzidi568118Texture:Texture = AssetMgr.instance.getTexture('ui_shangcheng_fuhedi_mingzidi');
            var ui_shangcheng_fuhedi_mingzidi568118Image:Image = new Image(ui_shangcheng_fuhedi_mingzidi568118Texture);
            ui_shangcheng_fuhedi_mingzidi568118Image.x = 568;
            ui_shangcheng_fuhedi_mingzidi568118Image.y = 118;
            ui_shangcheng_fuhedi_mingzidi568118Image.width = 89;
            ui_shangcheng_fuhedi_mingzidi568118Image.height = 43;
            ui_shangcheng_fuhedi_mingzidi568118Image.scaleX = -1;
            ui_shangcheng_fuhedi_mingzidi568118Image.smoothing = Constants.smoothing;
            ui_shangcheng_fuhedi_mingzidi568118Image.touchable = false;
            this.addQuiackChild(ui_shangcheng_fuhedi_mingzidi568118Image);
            nameTxt = new TextField(182, 30, '', '', 24, 0x3d2c1c, false);
            nameTxt.touchable = false;
            nameTxt.hAlign = 'center';
            nameTxt.x = 387;
            nameTxt.y = 128;
            this.addQuiackChild(nameTxt);
            var ui_shangcheng_fuhedi1361299Texture:Texture = AssetMgr.instance.getTexture('ui_shangcheng_fuhedi1');
            var ui_shangcheng_fuhedi1361299Image:Image = new Image(ui_shangcheng_fuhedi1361299Texture);
            ui_shangcheng_fuhedi1361299Image.x = 361;
            ui_shangcheng_fuhedi1361299Image.y = 299;
            ui_shangcheng_fuhedi1361299Image.width = 121;
            ui_shangcheng_fuhedi1361299Image.height = 69;
            ui_shangcheng_fuhedi1361299Image.smoothing = Constants.smoothing;
            ui_shangcheng_fuhedi1361299Image.touchable = false;
            this.addQuiackChild(ui_shangcheng_fuhedi1361299Image);
            var ui_shangcheng_fuhedi1602299Texture:Texture = AssetMgr.instance.getTexture('ui_shangcheng_fuhedi1');
            var ui_shangcheng_fuhedi1602299Image:Image = new Image(ui_shangcheng_fuhedi1602299Texture);
            ui_shangcheng_fuhedi1602299Image.x = 602;
            ui_shangcheng_fuhedi1602299Image.y = 299;
            ui_shangcheng_fuhedi1602299Image.width = 121;
            ui_shangcheng_fuhedi1602299Image.height = 69;
            ui_shangcheng_fuhedi1602299Image.scaleX = -1;
            ui_shangcheng_fuhedi1602299Image.smoothing = Constants.smoothing;
            ui_shangcheng_fuhedi1602299Image.touchable = false;
            this.addQuiackChild(ui_shangcheng_fuhedi1602299Image);
            descTxt = new TextField(223, 81, '', '', 18, 0x351200, false);
            descTxt.touchable = false;
            descTxt.hAlign = 'left';
            descTxt.x = 369;
            descTxt.y = 276;
            this.addQuiackChild(descTxt);
            moneyTxt = new TextField(92, 33, '', '', 20, 0xfff0c5, false);
            moneyTxt.touchable = false;
            moneyTxt.hAlign = 'left';
            moneyTxt.x = 531;
            moneyTxt.y = 432;
            this.addQuiackChild(moneyTxt);
            numTxt = new TextField(76, 24, '', '', 18, 0xffffff, false);
            numTxt.touchable = false;
            numTxt.hAlign = 'left';
            numTxt.x = 480;
            numTxt.y = 238;
            this.addQuiackChild(numTxt);
            var closeTexture:Texture = AssetMgr.instance.getTexture('ui_button_tiebaomutouanjian');
            closeButton = new Button(closeTexture);
            closeButton.x = 339;
            closeButton.y = 407;
            this.addQuiackChild(closeButton);
            var moneyIocnTexture:Texture = AssetMgr.instance.getTexture('ui_gongyong_money');
            moneyIocnImage = new Image(moneyIocnTexture);
            moneyIocnImage.x = 494;
            moneyIocnImage.y = 429;
            moneyIocnImage.width = 27;
            moneyIocnImage.height = 27;
            this.addQuiackChild(moneyIocnImage);

        }

        override public function dispose():void {
            sellButton.dispose();
            equipContainerButton.dispose();
            closeButton.dispose();
            super.dispose();

        }

    }
}