package game.view.arena.base {
    import com.utils.Constants;
    import com.view.View;

    import flash.geom.Rectangle;

    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;

    import game.manager.AssetMgr;

    import starling.display.Button;
    import starling.display.Image;
    import starling.text.TextField;
    import starling.textures.Texture;

    public class DareBase extends View {
        public var targetPhoto1Button:Button;
        public var targetPhoto2Button:Button;
        public var targetPhoto3Button:Button;
        public var targetPhoto4Button:Button;
        public var name1Txt:TextField;
        public var name2Txt:TextField;
        public var name3Txt:TextField;
        public var name4Txt:TextField;
        public var targetPhoto5Button:Button;
        public var targetPhoto6Button:Button;
        public var targetPhoto7Button:Button;
        public var targetPhoto8Button:Button;
        public var name5Txt:TextField;
        public var name6Txt:TextField;
        public var name7Txt:TextField;
        public var name8Txt:TextField;
        public var cdTxt:TextField;
        public var dareNumberTxt:TextField;
        public var beat7Txt:TextField;
        public var beat5Txt:TextField;
        public var beat6Txt:TextField;
        public var beat8Txt:TextField;
        public var orbBox2Button:Button;
        public var beat1Txt:TextField;
        public var beat2Txt:TextField;
        public var beat4Txt:TextField;
        public var RefreshButton:Button;
        public var orbBox1Button:Button;
        public var dareTxt:TextField;
        public var RefreshTxt:TextField;
        public var receive1Txt:TextField;
        public var receive2Txt:TextField;
        public var beat3Txt:TextField;

        public function DareBase() {
            var ui_gongyong_jiugonggedi39186Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_jiugonggedi');
            var ui_gongyong_jiugonggedi39186Rect:Rectangle = new Rectangle(38, 37, 77, 75);
            var ui_gongyong_jiugonggedi391869ScaleTexture:Scale9Textures = new Scale9Textures(ui_gongyong_jiugonggedi39186Texture,
                                                                                              ui_gongyong_jiugonggedi39186Rect);
            var ui_gongyong_jiugonggedi391869Scale:Scale9Image = new Scale9Image(ui_gongyong_jiugonggedi391869ScaleTexture);
            ui_gongyong_jiugonggedi391869Scale.x = 39;
            ui_gongyong_jiugonggedi391869Scale.y = 186;
            ui_gongyong_jiugonggedi391869Scale.width = 738;
            ui_gongyong_jiugonggedi391869Scale.height = 175;
            this.addQuiackChild(ui_gongyong_jiugonggedi391869Scale);
            var targetPhoto1Texture:Texture = AssetMgr.instance.getTexture('ui_pvp_renwukuang');
            targetPhoto1Button = new Button(targetPhoto1Texture);
            targetPhoto1Button.x = 212;
            targetPhoto1Button.y = 239;
            this.addQuiackChild(targetPhoto1Button);
            var targetPhoto2Texture:Texture = AssetMgr.instance.getTexture('ui_pvp_renwukuang');
            targetPhoto2Button = new Button(targetPhoto2Texture);
            targetPhoto2Button.x = 354;
            targetPhoto2Button.y = 239;
            this.addQuiackChild(targetPhoto2Button);
            var targetPhoto3Texture:Texture = AssetMgr.instance.getTexture('ui_pvp_renwukuang');
            targetPhoto3Button = new Button(targetPhoto3Texture);
            targetPhoto3Button.x = 496;
            targetPhoto3Button.y = 239;
            this.addQuiackChild(targetPhoto3Button);
            var targetPhoto4Texture:Texture = AssetMgr.instance.getTexture('ui_pvp_renwukuang');
            targetPhoto4Button = new Button(targetPhoto4Texture);
            targetPhoto4Button.x = 638;
            targetPhoto4Button.y = 239;
            this.addQuiackChild(targetPhoto4Button);
            var ui_pvp_renwumingzidi619189Texture:Texture = AssetMgr.instance.getTexture('ui_pvp_renwumingzidi');
            var ui_pvp_renwumingzidi619189Image:Image = new Image(ui_pvp_renwumingzidi619189Texture);
            ui_pvp_renwumingzidi619189Image.x = 619;
            ui_pvp_renwumingzidi619189Image.y = 189;
            ui_pvp_renwumingzidi619189Image.width = 151;
            ui_pvp_renwumingzidi619189Image.height = 53;
            ui_pvp_renwumingzidi619189Image.smoothing = Constants.smoothing;
            ui_pvp_renwumingzidi619189Image.touchable = false;
            this.addQuiackChild(ui_pvp_renwumingzidi619189Image);
            var ui_pvp_renwumingzidi335189Texture:Texture = AssetMgr.instance.getTexture('ui_pvp_renwumingzidi');
            var ui_pvp_renwumingzidi335189Image:Image = new Image(ui_pvp_renwumingzidi335189Texture);
            ui_pvp_renwumingzidi335189Image.x = 335;
            ui_pvp_renwumingzidi335189Image.y = 189;
            ui_pvp_renwumingzidi335189Image.width = 151;
            ui_pvp_renwumingzidi335189Image.height = 53;
            ui_pvp_renwumingzidi335189Image.smoothing = Constants.smoothing;
            ui_pvp_renwumingzidi335189Image.touchable = false;
            this.addQuiackChild(ui_pvp_renwumingzidi335189Image);
            var ui_pvp_renwumingzidi193189Texture:Texture = AssetMgr.instance.getTexture('ui_pvp_renwumingzidi');
            var ui_pvp_renwumingzidi193189Image:Image = new Image(ui_pvp_renwumingzidi193189Texture);
            ui_pvp_renwumingzidi193189Image.x = 193;
            ui_pvp_renwumingzidi193189Image.y = 189;
            ui_pvp_renwumingzidi193189Image.width = 151;
            ui_pvp_renwumingzidi193189Image.height = 53;
            ui_pvp_renwumingzidi193189Image.smoothing = Constants.smoothing;
            ui_pvp_renwumingzidi193189Image.touchable = false;
            this.addQuiackChild(ui_pvp_renwumingzidi193189Image);
            var ui_pvp_renwumingzidi477189Texture:Texture = AssetMgr.instance.getTexture('ui_pvp_renwumingzidi');
            var ui_pvp_renwumingzidi477189Image:Image = new Image(ui_pvp_renwumingzidi477189Texture);
            ui_pvp_renwumingzidi477189Image.x = 477;
            ui_pvp_renwumingzidi477189Image.y = 189;
            ui_pvp_renwumingzidi477189Image.width = 151;
            ui_pvp_renwumingzidi477189Image.height = 53;
            ui_pvp_renwumingzidi477189Image.smoothing = Constants.smoothing;
            ui_pvp_renwumingzidi477189Image.touchable = false;
            this.addQuiackChild(ui_pvp_renwumingzidi477189Image);
            var ui_pvp_renwukuang239417Texture:Texture = AssetMgr.instance.getTexture('ui_pvp_renwukuang');
            var ui_pvp_renwukuang239417Image:Image = new Image(ui_pvp_renwukuang239417Texture);
            ui_pvp_renwukuang239417Image.x = 239;
            ui_pvp_renwukuang239417Image.y = 417;
            ui_pvp_renwukuang239417Image.width = 111;
            ui_pvp_renwukuang239417Image.height = 111;
            ui_pvp_renwukuang239417Image.smoothing = Constants.smoothing;
            ui_pvp_renwukuang239417Image.touchable = false;
            this.addQuiackChild(ui_pvp_renwukuang239417Image);
            var ui_pvp_renwukuang367417Texture:Texture = AssetMgr.instance.getTexture('ui_pvp_renwukuang');
            var ui_pvp_renwukuang367417Image:Image = new Image(ui_pvp_renwukuang367417Texture);
            ui_pvp_renwukuang367417Image.x = 367;
            ui_pvp_renwukuang367417Image.y = 417;
            ui_pvp_renwukuang367417Image.width = 111;
            ui_pvp_renwukuang367417Image.height = 111;
            ui_pvp_renwukuang367417Image.smoothing = Constants.smoothing;
            ui_pvp_renwukuang367417Image.touchable = false;
            this.addQuiackChild(ui_pvp_renwukuang367417Image);
            var ui_pvp_renwukuang494417Texture:Texture = AssetMgr.instance.getTexture('ui_pvp_renwukuang');
            var ui_pvp_renwukuang494417Image:Image = new Image(ui_pvp_renwukuang494417Texture);
            ui_pvp_renwukuang494417Image.x = 494;
            ui_pvp_renwukuang494417Image.y = 417;
            ui_pvp_renwukuang494417Image.width = 111;
            ui_pvp_renwukuang494417Image.height = 111;
            ui_pvp_renwukuang494417Image.smoothing = Constants.smoothing;
            ui_pvp_renwukuang494417Image.touchable = false;
            this.addQuiackChild(ui_pvp_renwukuang494417Image);
            var ui_pvp_renwukuang622417Texture:Texture = AssetMgr.instance.getTexture('ui_pvp_renwukuang');
            var ui_pvp_renwukuang622417Image:Image = new Image(ui_pvp_renwukuang622417Texture);
            ui_pvp_renwukuang622417Image.x = 622;
            ui_pvp_renwukuang622417Image.y = 417;
            ui_pvp_renwukuang622417Image.width = 111;
            ui_pvp_renwukuang622417Image.height = 111;
            ui_pvp_renwukuang622417Image.smoothing = Constants.smoothing;
            ui_pvp_renwukuang622417Image.touchable = false;
            this.addQuiackChild(ui_pvp_renwukuang622417Image);
            name1Txt = new TextField(133, 36, '', '', 20, 0xFFFFFF, false);
            name1Txt.touchable = false;
            name1Txt.hAlign = 'center';
            name1Txt.x = 200;
            name1Txt.y = 196;
            this.addQuiackChild(name1Txt);
            var ui_gongyong_jiugonggedi40375Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_jiugonggedi');
            var ui_gongyong_jiugonggedi40375Rect:Rectangle = new Rectangle(38, 37, 77, 75);
            var ui_gongyong_jiugonggedi403759ScaleTexture:Scale9Textures = new Scale9Textures(ui_gongyong_jiugonggedi40375Texture,
                                                                                              ui_gongyong_jiugonggedi40375Rect);
            var ui_gongyong_jiugonggedi403759Scale:Scale9Image = new Scale9Image(ui_gongyong_jiugonggedi403759ScaleTexture);
            ui_gongyong_jiugonggedi403759Scale.x = 40;
            ui_gongyong_jiugonggedi403759Scale.y = 375;
            ui_gongyong_jiugonggedi403759Scale.width = 738;
            ui_gongyong_jiugonggedi403759Scale.height = 175;
            this.addQuiackChild(ui_gongyong_jiugonggedi403759Scale);
            name2Txt = new TextField(133, 36, '', '', 20, 0xFFFFFF, false);
            name2Txt.touchable = false;
            name2Txt.hAlign = 'center';
            name2Txt.x = 342;
            name2Txt.y = 196;
            this.addQuiackChild(name2Txt);
            name3Txt = new TextField(133, 36, '', '', 20, 0xFFFFFF, false);
            name3Txt.touchable = false;
            name3Txt.hAlign = 'center';
            name3Txt.x = 484;
            name3Txt.y = 196;
            this.addQuiackChild(name3Txt);
            name4Txt = new TextField(133, 36, '', '', 20, 0xFFFFFF, false);
            name4Txt.touchable = false;
            name4Txt.hAlign = 'center';
            name4Txt.x = 626;
            name4Txt.y = 196;
            this.addQuiackChild(name4Txt);
            var targetPhoto5Texture:Texture = AssetMgr.instance.getTexture('ui_pvp_renwukuang');
            targetPhoto5Button = new Button(targetPhoto5Texture);
            targetPhoto5Button.x = 212;
            targetPhoto5Button.y = 425;
            this.addQuiackChild(targetPhoto5Button);
            var targetPhoto6Texture:Texture = AssetMgr.instance.getTexture('ui_pvp_renwukuang');
            targetPhoto6Button = new Button(targetPhoto6Texture);
            targetPhoto6Button.x = 354;
            targetPhoto6Button.y = 426;
            this.addQuiackChild(targetPhoto6Button);
            var targetPhoto7Texture:Texture = AssetMgr.instance.getTexture('ui_pvp_renwukuang');
            targetPhoto7Button = new Button(targetPhoto7Texture);
            targetPhoto7Button.x = 496;
            targetPhoto7Button.y = 427;
            this.addQuiackChild(targetPhoto7Button);
            var targetPhoto8Texture:Texture = AssetMgr.instance.getTexture('ui_pvp_renwukuang');
            targetPhoto8Button = new Button(targetPhoto8Texture);
            targetPhoto8Button.x = 638;
            targetPhoto8Button.y = 427;
            this.addQuiackChild(targetPhoto8Button);
            var ui_pvp_renwumingzidi620379Texture:Texture = AssetMgr.instance.getTexture('ui_pvp_renwumingzidi');
            var ui_pvp_renwumingzidi620379Image:Image = new Image(ui_pvp_renwumingzidi620379Texture);
            ui_pvp_renwumingzidi620379Image.x = 620;
            ui_pvp_renwumingzidi620379Image.y = 379;
            ui_pvp_renwumingzidi620379Image.width = 151;
            ui_pvp_renwumingzidi620379Image.height = 53;
            ui_pvp_renwumingzidi620379Image.smoothing = Constants.smoothing;
            ui_pvp_renwumingzidi620379Image.touchable = false;
            this.addQuiackChild(ui_pvp_renwumingzidi620379Image);
            var ui_pvp_renwumingzidi335379Texture:Texture = AssetMgr.instance.getTexture('ui_pvp_renwumingzidi');
            var ui_pvp_renwumingzidi335379Image:Image = new Image(ui_pvp_renwumingzidi335379Texture);
            ui_pvp_renwumingzidi335379Image.x = 335;
            ui_pvp_renwumingzidi335379Image.y = 379;
            ui_pvp_renwumingzidi335379Image.width = 151;
            ui_pvp_renwumingzidi335379Image.height = 53;
            ui_pvp_renwumingzidi335379Image.smoothing = Constants.smoothing;
            ui_pvp_renwumingzidi335379Image.touchable = false;
            this.addQuiackChild(ui_pvp_renwumingzidi335379Image);
            var ui_pvp_renwumingzidi193379Texture:Texture = AssetMgr.instance.getTexture('ui_pvp_renwumingzidi');
            var ui_pvp_renwumingzidi193379Image:Image = new Image(ui_pvp_renwumingzidi193379Texture);
            ui_pvp_renwumingzidi193379Image.x = 193;
            ui_pvp_renwumingzidi193379Image.y = 379;
            ui_pvp_renwumingzidi193379Image.width = 151;
            ui_pvp_renwumingzidi193379Image.height = 53;
            ui_pvp_renwumingzidi193379Image.smoothing = Constants.smoothing;
            ui_pvp_renwumingzidi193379Image.touchable = false;
            this.addQuiackChild(ui_pvp_renwumingzidi193379Image);
            var ui_pvp_renwumingzidi477379Texture:Texture = AssetMgr.instance.getTexture('ui_pvp_renwumingzidi');
            var ui_pvp_renwumingzidi477379Image:Image = new Image(ui_pvp_renwumingzidi477379Texture);
            ui_pvp_renwumingzidi477379Image.x = 477;
            ui_pvp_renwumingzidi477379Image.y = 379;
            ui_pvp_renwumingzidi477379Image.width = 151;
            ui_pvp_renwumingzidi477379Image.height = 53;
            ui_pvp_renwumingzidi477379Image.smoothing = Constants.smoothing;
            ui_pvp_renwumingzidi477379Image.touchable = false;
            this.addQuiackChild(ui_pvp_renwumingzidi477379Image);
            name5Txt = new TextField(133, 36, '', '', 20, 0xFFFFFF, false);
            name5Txt.touchable = false;
            name5Txt.hAlign = 'center';
            name5Txt.x = 200;
            name5Txt.y = 387;
            this.addQuiackChild(name5Txt);
            name6Txt = new TextField(133, 36, '', '', 20, 0xFFFFFF, false);
            name6Txt.touchable = false;
            name6Txt.hAlign = 'center';
            name6Txt.x = 343;
            name6Txt.y = 387;
            this.addQuiackChild(name6Txt);
            name7Txt = new TextField(133, 36, '', '', 20, 0xFFFFFF, false);
            name7Txt.touchable = false;
            name7Txt.hAlign = 'center';
            name7Txt.x = 477;
            name7Txt.y = 387;
            this.addQuiackChild(name7Txt);
            name8Txt = new TextField(133, 36, '', '', 20, 0xFFFFFF, false);
            name8Txt.touchable = false;
            name8Txt.hAlign = 'center';
            name8Txt.x = 626;
            name8Txt.y = 387;
            this.addQuiackChild(name8Txt);
            cdTxt = new TextField(125, 48, '', '', 28, 0xFF0000, false);
            cdTxt.touchable = false;
            cdTxt.hAlign = 'center';
            cdTxt.x = 777;
            cdTxt.y = 500;
            this.addQuiackChild(cdTxt);
            var ui_gongyong_jiugonggedi1786224Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_jiugonggedi1');
            var ui_gongyong_jiugonggedi1786224Image:Image = new Image(ui_gongyong_jiugonggedi1786224Texture);
            ui_gongyong_jiugonggedi1786224Image.x = 786;
            ui_gongyong_jiugonggedi1786224Image.y = 224;
            ui_gongyong_jiugonggedi1786224Image.width = 114;
            ui_gongyong_jiugonggedi1786224Image.height = 106;
            ui_gongyong_jiugonggedi1786224Image.smoothing = Constants.smoothing;
            ui_gongyong_jiugonggedi1786224Image.touchable = false;
            this.addQuiackChild(ui_gongyong_jiugonggedi1786224Image);
            dareNumberTxt = new TextField(196, 36, '', '', 20, 0xE6C6A3, false);
            dareNumberTxt.touchable = false;
            dareNumberTxt.hAlign = 'center';
            dareNumberTxt.x = 745;
            dareNumberTxt.y = 244;
            this.addQuiackChild(dareNumberTxt);
            beat7Txt = new TextField(119, 36, '', '', 24, 0x00FF33, false);
            beat7Txt.touchable = false;
            beat7Txt.hAlign = 'center';
            beat7Txt.x = 490;
            beat7Txt.y = 464;
            this.addQuiackChild(beat7Txt);
            beat5Txt = new TextField(119, 36, '', '', 24, 0x00FF33, false);
            beat5Txt.touchable = false;
            beat5Txt.hAlign = 'center';
            beat5Txt.x = 206;
            beat5Txt.y = 464;
            this.addQuiackChild(beat5Txt);
            beat6Txt = new TextField(119, 36, '', '', 24, 0x00FF33, false);
            beat6Txt.touchable = false;
            beat6Txt.hAlign = 'center';
            beat6Txt.x = 348;
            beat6Txt.y = 464;
            this.addQuiackChild(beat6Txt);
            beat8Txt = new TextField(119, 36, '', '', 24, 0x00FF33, false);
            beat8Txt.touchable = false;
            beat8Txt.hAlign = 'center';
            beat8Txt.x = 632;
            beat8Txt.y = 464;
            this.addQuiackChild(beat8Txt);
            var orbBox2Texture:Texture = AssetMgr.instance.getTexture('ui_shangcheng_mutouxiangzi');
            orbBox2Button = new Button(orbBox2Texture);
            orbBox2Button.x = 60;
            orbBox2Button.y = 406;
            this.addQuiackChild(orbBox2Button);
            beat1Txt = new TextField(119, 36, '', '', 24, 0x00FF33, false);
            beat1Txt.touchable = false;
            beat1Txt.hAlign = 'center';
            beat1Txt.x = 205;
            beat1Txt.y = 276;
            this.addQuiackChild(beat1Txt);
            beat2Txt = new TextField(119, 36, '', '', 24, 0x00FF33, false);
            beat2Txt.touchable = false;
            beat2Txt.hAlign = 'center';
            beat2Txt.x = 348;
            beat2Txt.y = 276;
            this.addQuiackChild(beat2Txt);
            beat4Txt = new TextField(119, 36, '', '', 24, 0x00FF33, false);
            beat4Txt.touchable = false;
            beat4Txt.hAlign = 'center';
            beat4Txt.x = 633;
            beat4Txt.y = 276;
            this.addQuiackChild(beat4Txt);
            var RefreshTexture:Texture = AssetMgr.instance.getTexture('ui_button_sifanganjian');
            RefreshButton = new Button(RefreshTexture);
            RefreshButton.x = 785;
            RefreshButton.y = 387;
            this.addQuiackChild(RefreshButton);
            var orbBox1Texture:Texture = AssetMgr.instance.getTexture('ui_shangcheng_jinxiangzi');
            orbBox1Button = new Button(orbBox1Texture);
            orbBox1Button.x = 60;
            orbBox1Button.y = 219;
            this.addQuiackChild(orbBox1Button);
            dareTxt = new TextField(117, 36, '', '', 22, 0xEFDFCE, false);
            dareTxt.touchable = false;
            dareTxt.hAlign = 'center';
            dareTxt.x = 784;
            dareTxt.y = 280;
            this.addQuiackChild(dareTxt);
            RefreshTxt = new TextField(86, 84, '', '', 28, 0xEFDFCE, false);
            RefreshTxt.touchable = false;
            RefreshTxt.hAlign = 'center';
            RefreshTxt.x = 798;
            RefreshTxt.y = 398;
            this.addQuiackChild(RefreshTxt);
            receive1Txt = new TextField(119, 36, '', '', 24, 0x00FF33, false);
            receive1Txt.touchable = false;
            receive1Txt.hAlign = 'center';
            receive1Txt.x = 60;
            receive1Txt.y = 265;
            this.addQuiackChild(receive1Txt);
            receive2Txt = new TextField(119, 36, '', '', 24, 0x00FF33, false);
            receive2Txt.touchable = false;
            receive2Txt.hAlign = 'center';
            receive2Txt.x = 60;
            receive2Txt.y = 445;
            this.addQuiackChild(receive2Txt);
            beat3Txt = new TextField(119, 36, '', '', 24, 0x00FF33, false);
            beat3Txt.touchable = false;
            beat3Txt.hAlign = 'center';
            beat3Txt.x = 490;
            beat3Txt.y = 276;
            this.addQuiackChild(beat3Txt);

        }

        override public function dispose():void {
            targetPhoto1Button.dispose();
            targetPhoto2Button.dispose();
            targetPhoto3Button.dispose();
            targetPhoto4Button.dispose();
            targetPhoto5Button.dispose();
            targetPhoto6Button.dispose();
            targetPhoto7Button.dispose();
            targetPhoto8Button.dispose();
            orbBox2Button.dispose();
            RefreshButton.dispose();
            orbBox1Button.dispose();
            super.dispose();

        }

    }
}