package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.dialog.Dialog;

    public class AchievementDlgBase extends Dialog
    {
        public var ui_gongyong_wupingkuang_baozaodibian342125:Scale9Image;
        public var btnClose:Button;
        public var menuIcon1:Image;
        public var menuTxt2:TextField;
        public var menuTxt3:TextField;
        public var menuTxt4:TextField;
        public var menuTxt1:TextField;
        public var money:TextField;
        public var k:TextField;
        public var diamond:TextField;
        public var k1:TextField;
        public var Recharge:Button;

        public function AchievementDlgBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            var assetMgr:AssetMgr = AssetMgr.instance;
            texture =assetMgr.getTexture('ui_gongyong_dianquanheng_di');
            image = new Image(texture);
            image.x = 202;
            image.y = 115;
            image.width = 320;
            image.height = 160;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_dianquanheng_di');
            image = new Image(texture);
            image.x = 202;
            image.y = 271;
            image.width = 320;
            image.height = 160;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_dianquanheng_di');
            image = new Image(texture);
            image.x = 202;
            image.y = 427;
            image.width = 320;
            image.height = 160;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_dianquanheng_di');
            image = new Image(texture);
            image.x = 515;
            image.y = 115;
            image.width = 320;
            image.height = 160;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_dianquanheng_di');
            image = new Image(texture);
            image.x = 515;
            image.y = 271;
            image.width = 320;
            image.height = 160;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_dianquanheng_di');
            image = new Image(texture);
            image.x = 515;
            image.y = 427;
            image.width = 320;
            image.height = 160;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_bumangdi_zhengqidibian2');
            image = new Image(texture);
            image.x = 819;
            image.y = 98;
            image.width = 57;
            image.height = 542;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_bumangdi_zhengqidibian1');
            image = new Image(texture);
            image.x = 873;
            image.y = 93;
            image.width = 61;
            image.height = 547;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_bumangdi_zhengqidibian2');
            image = new Image(texture);
            image.x = 769;
            image.y = 98;
            image.width = 57;
            image.height = 542;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_bumangdi_zhengqidibian2');
            image = new Image(texture);
            image.x = 717;
            image.y = 98;
            image.width = 57;
            image.height = 542;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_bumangdi_zhengqidibian2');
            image = new Image(texture);
            image.x = 666;
            image.y = 98;
            image.width = 57;
            image.height = 542;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_bumangdi_zhengqidibian2');
            image = new Image(texture);
            image.x = 616;
            image.y = 98;
            image.width = 57;
            image.height = 542;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_paizi');
            image = new Image(texture);
            image.x = 347;
            image.y = -44;
            image.width = 240;
            image.height = 151;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_bumangdi_zhengqidibian2');
            image = new Image(texture);
            image.x = 565;
            image.y = 98;
            image.width = 57;
            image.height = 542;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_bumangdi_zhengqidibian2');
            image = new Image(texture);
            image.x = 515;
            image.y = 98;
            image.width = 57;
            image.height = 542;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_bumangdi_zhengqidibian2');
            image = new Image(texture);
            image.x = 465;
            image.y = 98;
            image.width = 57;
            image.height = 542;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_bumangdi_zhengqidibian2');
            image = new Image(texture);
            image.x = 418;
            image.y = 98;
            image.width = 57;
            image.height = 542;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_bumangdi_zhengqidibian2');
            image = new Image(texture);
            image.x = 367;
            image.y = 98;
            image.width = 57;
            image.height = 542;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_bumangdi_zhengqidibian2');
            image = new Image(texture);
            image.x = 317;
            image.y = 98;
            image.width = 57;
            image.height = 542;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_bumangdi_zhengqidibian2');
            image = new Image(texture);
            image.x = 264;
            image.y = 98;
            image.width = 57;
            image.height = 542;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_bumangdi_zhengqidibian2');
            image = new Image(texture);
            image.x = 214;
            image.y = 98;
            image.width = 57;
            image.height = 542;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_bumangdi_zhengqidibian2');
            image = new Image(texture);
            image.x = 163;
            image.y = 98;
            image.width = 57;
            image.height = 542;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_bumangdi_zhengqidibian2');
            image = new Image(texture);
            image.x = 110;
            image.y = 98;
            image.width = 57;
            image.height = 542;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_bumangdi_zhengqidibian2');
            image = new Image(texture);
            image.x = 61;
            image.y = 98;
            image.width = 57;
            image.height = 542;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_bumangdi_zhengqidibian1');
            image = new Image(texture);
            image.x = 61;
            image.y = 93;
            image.width = 61;
            image.height = 547;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_ziti_rongyaozhidi');
            image = new Image(texture);
            image.x = 381;
            image.y = 26;
            image.width = 167;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian2');
            image = new Image(texture);
            image.x = 37;
            image.y = 115;
            image.width = 107;
            image.height = 19;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian1');
            image = new Image(texture);
            image.x = 21;
            image.y = 115;
            image.width = 21;
            image.height = 500;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian');
            image = new Image(texture);
            image.x = 197;
            image.y = 115;
            image.width = 37;
            image.height = 500;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian2');
            image = new Image(texture);
            image.x = 92;
            image.y = 115;
            image.width = 107;
            image.height = 19;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian3');
            var ui_gongyong_wupingkuang_baozaodibian342125Rect:Rectangle = new Rectangle(24,24,48,48);
            var ui_gongyong_wupingkuang_baozaodibian3421259ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_gongyong_wupingkuang_baozaodibian342125Rect);
            ui_gongyong_wupingkuang_baozaodibian342125 = new Scale9Image(ui_gongyong_wupingkuang_baozaodibian3421259ScaleTexture);
            ui_gongyong_wupingkuang_baozaodibian342125.x = 42;
            ui_gongyong_wupingkuang_baozaodibian342125.y = 125;
            ui_gongyong_wupingkuang_baozaodibian342125.width = 162;
            ui_gongyong_wupingkuang_baozaodibian342125.height = 478;
            this.addQuiackChild(ui_gongyong_wupingkuang_baozaodibian342125);
            texture =assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian2');
            image = new Image(texture);
            image.x = 39;
            image.y = 615;
            image.width = 107;
            image.height = 19;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian2');
            image = new Image(texture);
            image.x = 92;
            image.y = 615;
            image.width = 107;
            image.height = 19;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian3_hei');
            image = new Image(texture);
            image.x = 260;
            image.y = 182;
            image.width = 636;
            image.height = 405;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian1_hei');
            image = new Image(texture);
            image.x = 245;
            image.y = 136;
            image.width = 20;
            image.height = 479;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian_hei');
            image = new Image(texture);
            image.x = 873;
            image.y = 136;
            image.width = 40;
            image.height = 479;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian2_hei');
            image = new Image(texture);
            image.x = 261;
            image.y = 136;
            image.width = 185;
            image.height = 47;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian2_hei');
            image = new Image(texture);
            image.x = 437;
            image.y = 136;
            image.width = 185;
            image.height = 47;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian2_hei');
            image = new Image(texture);
            image.x = 616;
            image.y = 136;
            image.width = 185;
            image.height = 47;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian2_hei');
            image = new Image(texture);
            image.x = 691;
            image.y = 136;
            image.width = 185;
            image.height = 47;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian2_hei');
            image = new Image(texture);
            image.x = 261;
            image.y = 615;
            image.width = 185;
            image.height = 47;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian2_hei');
            image = new Image(texture);
            image.x = 437;
            image.y = 615;
            image.width = 185;
            image.height = 47;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian2_hei');
            image = new Image(texture);
            image.x = 616;
            image.y = 615;
            image.width = 185;
            image.height = 47;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian2_hei');
            image = new Image(texture);
            image.x = 691;
            image.y = 615;
            image.width = 185;
            image.height = 47;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_tuichuanniiu');
            btnClose = new Button(texture);
            btnClose.name= 'btnClose';
            btnClose.x = 803;
            btnClose.y = -47;
            btnClose.width = 99;
            btnClose.height = 145;
            this.addQuiackChild(btnClose);
            texture = assetMgr.getTexture('ui_tubiao_rongyufenleianniu_zhonglan')
            menuIcon1 = new Image(texture);
            menuIcon1.x = 40;
            menuIcon1.y = 132;
            menuIcon1.width = 60;
            menuIcon1.height = 57;
            this.addQuiackChild(menuIcon1);
            menuIcon1.touchable = false;
            texture =assetMgr.getTexture('ui_tubiao_rongyufenleianniu_zhandong');
            image = new Image(texture);
            image.x = 39;
            image.y = 377;
            image.width = 60;
            image.height = 57;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_tubiao_rongyufenleianniu_yingxiong');
            image = new Image(texture);
            image.x = 38;
            image.y = 296;
            image.width = 60;
            image.height = 57;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_tubiao_rongyufenleianniu_jingji');
            image = new Image(texture);
            image.x = 42;
            image.y = 214;
            image.width = 60;
            image.height = 57;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            menuTxt2 = new TextField(134,54,'','',34,0xFFFFFF,false);
            menuTxt2.touchable = false;
            menuTxt2.hAlign= 'center';
            menuTxt2.text= '日 常';
            menuTxt2.x = 82;
            menuTxt2.y = 218;
            this.addQuiackChild(menuTxt2);
            menuTxt3 = new TextField(134,50,'','',34,0xFFFFFF,false);
            menuTxt3.touchable = false;
            menuTxt3.hAlign= 'center';
            menuTxt3.text= '战 斗';
            menuTxt3.x = 82;
            menuTxt3.y = 300;
            this.addQuiackChild(menuTxt3);
            menuTxt4 = new TextField(134,60,'','',34,0xFFFFFF,false);
            menuTxt4.touchable = false;
            menuTxt4.hAlign= 'center';
            menuTxt4.text= '英 雄';
            menuTxt4.x = 82;
            menuTxt4.y = 381;
            this.addQuiackChild(menuTxt4);
            menuTxt1 = new TextField(134,51,'','',34,0xFFFFFF,false);
            menuTxt1.touchable = false;
            menuTxt1.hAlign= 'center';
            menuTxt1.text= '总 览';
            menuTxt1.x = 82;
            menuTxt1.y = 134;
            this.addQuiackChild(menuTxt1);
            texture =assetMgr.getTexture('ui_gongyong_bumangdi_shangbianyikuaitie');
            image = new Image(texture);
            image.x = 377;
            image.y = 95;
            image.width = 30;
            image.height = 21;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_bumangdi_shangbianyikuaitie');
            image = new Image(texture);
            image.x = 554;
            image.y = 95;
            image.width = 30;
            image.height = 21;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_jinbibaizidi2');
            image = new Image(texture);
            image.x = 49;
            image.y = 10;
            image.width = 197;
            image.height = 87;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_money');
            image = new Image(texture);
            image.x = 64;
            image.y = 18;
            image.width = 34;
            image.height = 34;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            money = new TextField(166,44,'','',26,0xFFFFFF,false);
            money.touchable = false;
            money.hAlign= 'left';
            money.text= '999999  ';
            money.x = 105;
            money.y = 16;
            this.addQuiackChild(money);
            k = new TextField(33,46,'','',32,0xFF9201,false);
            k.touchable = false;
            k.hAlign= 'left';
            k.text= 'k';
            k.x = 209;
            k.y = 15;
            this.addQuiackChild(k);
            diamond = new TextField(166,44,'','',26,0xFFFFFF,false);
            diamond.touchable = false;
            diamond.hAlign= 'left';
            diamond.text= '999999  ';
            diamond.x = 105;
            diamond.y = 55;
            this.addQuiackChild(diamond);
            k1 = new TextField(36,46,'','',32,0xFF9201,false);
            k1.touchable = false;
            k1.hAlign= 'left';
            k1.text= 'k';
            k1.x = 209;
            k1.y = 54;
            this.addQuiackChild(k1);
            texture =assetMgr.getTexture('ui_gongyong_zuanshi');
            image = new Image(texture);
            image.x = 62;
            image.y = 57;
            image.width = 38;
            image.height = 36;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_button_chongzhitubiao');
            Recharge = new Button(texture);
            Recharge.name= 'Recharge';
            Recharge.x = 260;
            Recharge.y = 17;
            Recharge.width = 64;
            Recharge.height = 64;
            this.addQuiackChild(Recharge);
            init();
        }
        override public function dispose():void
        {
            btnClose.dispose();
            Recharge.dispose();
            super.dispose();
        
}
    }
}
