package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.view.View;

    public class AdvanceViewBase extends View
    {
        public var ui_gongyong_di_9gongge59308:Scale9Image;
        public var ui_Setup_button_switch359181:Scale9Image;
        public var ui_Setup_button_switch3512142:Scale9Image;
        public var ui_Setup_button_switch3512297:Scale9Image;
        public var stonebg:Image;
        public var stoneImageBg:Button;
        public var stoneImage:Image;
        public var maxTis2:TextField;
        public var heroName:TextField;
        public var advanceBtn:Button;
        public var heroHead:Sprite;
        public var maxTis1:TextField;
        public var nowHeroHead:Sprite;
        public var advanceHeroHead:Sprite;
        public var advanceTitle:TextField;
        public var advanceNumTitle:TextField;
        public var advanceGlodTitle:TextField;
        public var advanceMateriaName:TextField;
        public var advanceMateriaTitle:TextField;
        public var advanceNum:TextField;
        public var advanceGlod:TextField;
        public var propertyTitle:TextField;
        public var lable1:TextField;
        public var moneyIcon:Image;
        public var advacejtBtn:Image;
        public var poxyView:Sprite;

        public function AdvanceViewBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            var assetMgr:AssetMgr = AssetMgr.instance;
            texture = assetMgr.getTexture('ui_gongyong_di_9gongge');
            var ui_gongyong_di_9gongge59308Rect:Rectangle = new Rectangle(21,21,43,41);
            var ui_gongyong_di_9gongge593089ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_gongyong_di_9gongge59308Rect);
            ui_gongyong_di_9gongge59308 = new Scale9Image(ui_gongyong_di_9gongge593089ScaleTexture);
            ui_gongyong_di_9gongge59308.x = 59;
            ui_gongyong_di_9gongge59308.y = 308;
            ui_gongyong_di_9gongge59308.width = 416;
            ui_gongyong_di_9gongge59308.height = 152;
            this.addQuiackChild(ui_gongyong_di_9gongge59308);
            texture = assetMgr.getTexture('ui_Setup_button_switch3');
            var ui_Setup_button_switch359181Rect:Rectangle = new Rectangle(14,20,180,69);
            var ui_Setup_button_switch3591819ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_Setup_button_switch359181Rect);
            ui_Setup_button_switch359181 = new Scale9Image(ui_Setup_button_switch3591819ScaleTexture);
            ui_Setup_button_switch359181.x = 59;
            ui_Setup_button_switch359181.y = 181;
            ui_Setup_button_switch359181.width = 124;
            ui_Setup_button_switch359181.height = 118;
            this.addQuiackChild(ui_Setup_button_switch359181);
            texture = assetMgr.getTexture('ui_Setup_button_switch3');
            var ui_Setup_button_switch3512142Rect:Rectangle = new Rectangle(14,20,180,69);
            var ui_Setup_button_switch35121429ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_Setup_button_switch3512142Rect);
            ui_Setup_button_switch3512142 = new Scale9Image(ui_Setup_button_switch35121429ScaleTexture);
            ui_Setup_button_switch3512142.x = 512;
            ui_Setup_button_switch3512142.y = 142;
            ui_Setup_button_switch3512142.width = 416;
            ui_Setup_button_switch3512142.height = 136;
            this.addQuiackChild(ui_Setup_button_switch3512142);
            texture = assetMgr.getTexture('ui_Setup_button_switch3');
            var ui_Setup_button_switch3512297Rect:Rectangle = new Rectangle(14,20,180,69);
            var ui_Setup_button_switch35122979ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_Setup_button_switch3512297Rect);
            ui_Setup_button_switch3512297 = new Scale9Image(ui_Setup_button_switch35122979ScaleTexture);
            ui_Setup_button_switch3512297.x = 512;
            ui_Setup_button_switch3512297.y = 297;
            ui_Setup_button_switch3512297.width = 416;
            ui_Setup_button_switch3512297.height = 136;
            this.addQuiackChild(ui_Setup_button_switch3512297);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou2');
            image = new Image(texture);
            image.x = 505;
            image.y = 168;
            image.width = 26;
            image.height = 307;
            image.scaleX = -1;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou2');
            image = new Image(texture);
            image.x = 32;
            image.y = 151;
            image.width = 26;
            image.height = 325;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou1');
            image = new Image(texture);
            image.x = 60;
            image.y = 135;
            image.width = 414;
            image.height = 24;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 27;
            image.y = 134;
            image.width = 38;
            image.height = 34;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou1');
            image = new Image(texture);
            image.x = 50;
            image.y = 495;
            image.width = 429;
            image.height = 24;
            image.scaleY = -1;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 28;
            image.y = 496;
            image.width = 38;
            image.height = 34;
            image.scaleY = -1;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 509;
            image.y = 134;
            image.width = 38;
            image.height = 34;
            image.scaleX = -1;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 509;
            image.y = 496;
            image.width = 38;
            image.height = 34;
            image.scaleX = -1;
            image.scaleY = -1;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_kuang_paizi2');
            image = new Image(texture);
            image.x = 194;
            image.y = 113;
            image.width = 138;
            image.height = 61;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_kuang_paizi1');
            image = new Image(texture);
            image.x = 320;
            image.y = 113;
            image.width = 61;
            image.height = 61;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_kuang_paizi1');
            image = new Image(texture);
            image.x = 213;
            image.y = 113;
            image.width = 61;
            image.height = 61;
            image.scaleX = -1;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_90wupingkuang')
            stonebg = new Image(texture);
            stonebg.x = 526;
            stonebg.y = 318;
            stonebg.width = 90;
            stonebg.height = 90;
            this.addQuiackChild(stonebg);
            stonebg.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_90wupingkuang0');
            stoneImageBg = new Button(texture);
            stoneImageBg.name= 'stoneImageBg';
            stoneImageBg.x = 527;
            stoneImageBg.y = 320;
            stoneImageBg.width = 90;
            stoneImageBg.height = 90;
            this.addQuiackChild(stoneImageBg);
            texture = assetMgr.getTexture('icon_10107')
            stoneImage = new Image(texture);
            stoneImage.x = 530;
            stoneImage.y = 321;
            stoneImage.width = 89;
            stoneImage.height = 89;
            this.addQuiackChild(stoneImage);
            stoneImage.touchable = false;
            maxTis2 = new TextField(409,37,'','',30,0xFFFFCC,false);
            maxTis2.touchable = false;
            maxTis2.hAlign= 'center';
            maxTis2.text= '您的英雄已经升无可升了！';
            maxTis2.x = 519;
            maxTis2.y = 346;
            this.addQuiackChild(maxTis2);
            heroName = new TextField(151,31,'','',24,0xFFFFCC,false);
            heroName.touchable = false;
            heroName.hAlign= 'center';
            heroName.text= '英雄名';
            heroName.x = 191;
            heroName.y = 128;
            this.addQuiackChild(heroName);
            texture = assetMgr.getTexture('ui_button_tiebaomutouanjian');
            advanceBtn = new Button(texture);
            advanceBtn.name= 'advanceBtn';
            advanceBtn.x = 654;
            advanceBtn.y = 438;
            advanceBtn.width = 148;
            advanceBtn.height = 65;
            this.addQuiackChild(advanceBtn);
            heroHead = new Sprite();
            heroHead.x = 71;
            heroHead.y = 189;
            heroHead.width = 100;
            heroHead.height = 100;
            this.addQuiackChild(heroHead);
            heroHead.name= 'heroHead';
            texture =assetMgr.getTexture('ui_gongyong_100yingxiongkuang_kong1');
            image = new Image(texture);
            image.width = 100;
            image.height = 100;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroHead.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_501')
            image = new Image(texture);
            image.name= 'heroIcon';
            image.width = 100;
            image.height = 100;
            heroHead.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_100yingxiongkuang_0')
            image = new Image(texture);
            image.name= 'heroBg';
            image.width = 100;
            image.height = 100;
            heroHead.addQuiackChild(image);
            image.touchable = false;
            maxTis1 = new TextField(409,37,'','',30,0xFFFFCC,false);
            maxTis1.touchable = false;
            maxTis1.hAlign= 'center';
            maxTis1.text= '您的英雄已经升无可升了！';
            maxTis1.x = 515;
            maxTis1.y = 193;
            this.addQuiackChild(maxTis1);
            nowHeroHead = new Sprite();
            nowHeroHead.x = 527;
            nowHeroHead.y = 159;
            nowHeroHead.width = 100;
            nowHeroHead.height = 100;
            this.addQuiackChild(nowHeroHead);
            nowHeroHead.name= 'nowHeroHead';
            texture =assetMgr.getTexture('ui_gongyong_100yingxiongkuang_kong1');
            image = new Image(texture);
            image.width = 100;
            image.height = 100;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            nowHeroHead.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_501')
            image = new Image(texture);
            image.name= 'heroIcon';
            image.width = 100;
            image.height = 100;
            nowHeroHead.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_100yingxiongkuang_0')
            image = new Image(texture);
            image.name= 'heroBg';
            image.width = 100;
            image.height = 100;
            nowHeroHead.addQuiackChild(image);
            image.touchable = false;
            advanceHeroHead = new Sprite();
            advanceHeroHead.x = 808;
            advanceHeroHead.y = 159;
            advanceHeroHead.width = 100;
            advanceHeroHead.height = 100;
            this.addQuiackChild(advanceHeroHead);
            advanceHeroHead.name= 'advanceHeroHead';
            texture =assetMgr.getTexture('ui_gongyong_100yingxiongkuang_kong1');
            image = new Image(texture);
            image.width = 100;
            image.height = 100;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            advanceHeroHead.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_501')
            image = new Image(texture);
            image.name= 'heroIcon';
            image.width = 100;
            image.height = 100;
            advanceHeroHead.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_100yingxiongkuang_0')
            image = new Image(texture);
            image.name= 'heroBg';
            image.width = 100;
            image.height = 100;
            advanceHeroHead.addQuiackChild(image);
            image.touchable = false;
            advanceTitle = new TextField(145,31,'','',24,0xFFFFCC,false);
            advanceTitle.touchable = false;
            advanceTitle.hAlign= 'center';
            advanceTitle.text= '净化';
            advanceTitle.x = 645;
            advanceTitle.y = 236;
            this.addQuiackChild(advanceTitle);
            advanceNumTitle = new TextField(120,31,'','',24,0xFFFFCC,false);
            advanceNumTitle.touchable = false;
            advanceNumTitle.hAlign= 'left';
            advanceNumTitle.text= '消耗数量：';
            advanceNumTitle.x = 632;
            advanceNumTitle.y = 355;
            this.addQuiackChild(advanceNumTitle);
            advanceGlodTitle = new TextField(120,31,'','',24,0xFFFFCC,false);
            advanceGlodTitle.touchable = false;
            advanceGlodTitle.hAlign= 'left';
            advanceGlodTitle.text= '消耗：';
            advanceGlodTitle.x = 632;
            advanceGlodTitle.y = 387;
            this.addQuiackChild(advanceGlodTitle);
            advanceMateriaName = new TextField(160,31,'','',24,0xFFFFCC,false);
            advanceMateriaName.touchable = false;
            advanceMateriaName.hAlign= 'right';
            advanceMateriaName.text= '净化石名字';
            advanceMateriaName.x = 758;
            advanceMateriaName.y = 311;
            this.addQuiackChild(advanceMateriaName);
            advanceMateriaTitle = new TextField(120,31,'','',24,0xFFFFCC,false);
            advanceMateriaTitle.touchable = false;
            advanceMateriaTitle.hAlign= 'left';
            advanceMateriaTitle.text= '消耗材料：';
            advanceMateriaTitle.x = 632;
            advanceMateriaTitle.y = 311;
            this.addQuiackChild(advanceMateriaTitle);
            advanceNum = new TextField(159,31,'','',24,0xFFFFCC,false);
            advanceNum.touchable = false;
            advanceNum.hAlign= 'right';
            advanceNum.text= '14/40';
            advanceNum.x = 759;
            advanceNum.y = 355;
            this.addQuiackChild(advanceNum);
            advanceGlod = new TextField(159,31,'','',24,0xFFFFCC,false);
            advanceGlod.touchable = false;
            advanceGlod.hAlign= 'right';
            advanceGlod.text= '214354';
            advanceGlod.x = 759;
            advanceGlod.y = 387;
            this.addQuiackChild(advanceGlod);
            propertyTitle = new TextField(255,31,'','',24,0xFFFFCC,false);
            propertyTitle.touchable = false;
            propertyTitle.hAlign= 'center';
            propertyTitle.text= '净化后属性变化';
            propertyTitle.x = 219;
            propertyTitle.y = 183;
            this.addQuiackChild(propertyTitle);
            lable1 = new TextField(111,31,'','',24,0xFFFFCC,false);
            lable1.touchable = false;
            lable1.hAlign= 'center';
            lable1.text= '';
            lable1.x = 669;
            lable1.y = 453;
            this.addQuiackChild(lable1);
            texture = assetMgr.getTexture('ui_gongyong_money')
            moneyIcon = new Image(texture);
            moneyIcon.x = 702;
            moneyIcon.y = 383;
            moneyIcon.width = 40;
            moneyIcon.height = 40;
            this.addQuiackChild(moneyIcon);
            moneyIcon.touchable = false;
            texture = assetMgr.getTexture('ui_background_intensify_indicate')
            advacejtBtn = new Image(texture);
            advacejtBtn.x = 689;
            advacejtBtn.y = 182;
            advacejtBtn.width = 61;
            advacejtBtn.height = 53;
            this.addQuiackChild(advacejtBtn);
            advacejtBtn.touchable = false;
            poxyView = new Sprite();
            poxyView.x = 188;
            poxyView.y = 219;
            poxyView.width = 392;
            poxyView.height = 226;
            this.addQuiackChild(poxyView);
            poxyView.name= 'poxyView';
            texture =assetMgr.getTexture('ui_gongyong_shuxingwenzidi');
            image = new Image(texture);
            image.x = 111;
            image.y = 3;
            image.width = 172;
            image.height = 27;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            poxyView.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_shuxingwenzidi');
            image = new Image(texture);
            image.x = 111;
            image.y = 43;
            image.width = 172;
            image.height = 27;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            poxyView.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_shuxingwenzidi');
            image = new Image(texture);
            image.x = 44;
            image.y = 3;
            image.width = 172;
            image.height = 27;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            poxyView.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_shuxingwenzidi');
            image = new Image(texture);
            image.x = 44;
            image.y = 43;
            image.width = 172;
            image.height = 27;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            poxyView.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_tubiao_xueliangtubiao');
            image = new Image(texture);
            image.x = 27;
            image.y = 42;
            image.width = 34;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            poxyView.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_tubiao_gongjilitubiao');
            image = new Image(texture);
            image.x = 34;
            image.width = 20;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            poxyView.addQuiackChild(image);
            textField = new TextField(81,26,'','',18,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = -70;
            textField.y = 100;
            textField.hAlign= 'right';
            textField.text= '9';
            textField.name= 'defendValue';
            poxyView.addQuiackChild(textField);
            textField = new TextField(81,26,'','',18,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = -70;
            textField.y = 131;
            textField.hAlign= 'right';
            textField.text= '99';
            textField.name= 'hitValue';
            poxyView.addQuiackChild(textField);
            textField = new TextField(81,26,'','',18,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = -70;
            textField.y = 165;
            textField.hAlign= 'right';
            textField.text= '9999';
            textField.name= 'critValue';
            poxyView.addQuiackChild(textField);
            textField = new TextField(81,26,'','',18,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = -70;
            textField.y = 199;
            textField.hAlign= 'right';
            textField.text= '999999';
            textField.name= 'anitCritValue';
            poxyView.addQuiackChild(textField);
            textField = new TextField(81,26,'','',18,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 125;
            textField.y = 101;
            textField.hAlign= 'right';
            textField.text= '9';
            textField.name= 'punctureValue';
            poxyView.addQuiackChild(textField);
            textField = new TextField(81,26,'','',18,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 125;
            textField.y = 132;
            textField.hAlign= 'right';
            textField.text= '99';
            textField.name= 'dodgeValue';
            poxyView.addQuiackChild(textField);
            textField = new TextField(81,26,'','',18,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 125;
            textField.y = 165;
            textField.hAlign= 'right';
            textField.text= '9999';
            textField.name= 'critPercentageValue';
            poxyView.addQuiackChild(textField);
            textField = new TextField(81,26,'','',18,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 125;
            textField.y = 199;
            textField.hAlign= 'right';
            textField.text= '999999';
            textField.name= 'toughnessValue';
            poxyView.addQuiackChild(textField);
            textField = new TextField(120,28,'','',22,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 57;
            textField.y = 43;
            textField.hAlign= 'right';
            textField.text= '9999999';
            textField.name= 'hpValue';
            poxyView.addQuiackChild(textField);
            textField = new TextField(120,28,'','',22,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 57;
            textField.y = 3;
            textField.hAlign= 'right';
            textField.text= '9';
            textField.name= 'attackValue';
            poxyView.addQuiackChild(textField);
            textField = new TextField(60,26,'','',18,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = -109;
            textField.y = 100;
            textField.hAlign= 'left';
            textField.text= '防御：';
            textField.name= 'defend';
            poxyView.addQuiackChild(textField);
            textField = new TextField(60,26,'','',18,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = -109;
            textField.y = 131;
            textField.hAlign= 'left';
            textField.text= '命中：';
            textField.name= 'hit';
            poxyView.addQuiackChild(textField);
            textField = new TextField(60,26,'','',18,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = -109;
            textField.y = 199;
            textField.hAlign= 'left';
            textField.text= '免爆：';
            textField.name= 'anitCrit';
            poxyView.addQuiackChild(textField);
            textField = new TextField(60,26,'','',18,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 85;
            textField.y = 100;
            textField.hAlign= 'left';
            textField.text= '穿刺：';
            textField.name= 'puncture';
            poxyView.addQuiackChild(textField);
            textField = new TextField(60,26,'','',18,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 85;
            textField.y = 132;
            textField.hAlign= 'center';
            textField.text= '闪避：';
            textField.name= 'dodge';
            poxyView.addQuiackChild(textField);
            textField = new TextField(60,26,'','',18,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 86;
            textField.y = 166;
            textField.hAlign= 'center';
            textField.text= '暴强：';
            textField.name= 'critPercentage';
            poxyView.addQuiackChild(textField);
            textField = new TextField(60,26,'','',18,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 85;
            textField.y = 199;
            textField.hAlign= 'center';
            textField.text= '韧性：';
            textField.name= 'toughness';
            poxyView.addQuiackChild(textField);
            textField = new TextField(60,26,'','',18,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = -109;
            textField.y = 167;
            textField.hAlign= 'left';
            textField.text= '暴击：';
            textField.name= 'crit';
            poxyView.addQuiackChild(textField);
            textField = new TextField(59,26,'','',18,0x00FF00,false);
            textField.touchable = false;
            textField.x = 2;
            textField.y = 100;
            textField.hAlign= 'right';
            textField.text= '+9';
            textField.name= 'defendAddValue';
            poxyView.addQuiackChild(textField);
            textField = new TextField(59,26,'','',18,0x00FF00,false);
            textField.touchable = false;
            textField.x = 2;
            textField.y = 132;
            textField.hAlign= 'right';
            textField.text= '+99';
            textField.name= 'hitAddValue';
            poxyView.addQuiackChild(textField);
            textField = new TextField(59,26,'','',18,0x00FF00,false);
            textField.touchable = false;
            textField.x = 2;
            textField.y = 166;
            textField.hAlign= 'right';
            textField.text= '+999';
            textField.name= 'critAddValue';
            poxyView.addQuiackChild(textField);
            textField = new TextField(59,26,'','',18,0x00FF00,false);
            textField.touchable = false;
            textField.x = 3;
            textField.y = 200;
            textField.hAlign= 'right';
            textField.text= '+9999';
            textField.name= 'anitCritAddValue';
            poxyView.addQuiackChild(textField);
            textField = new TextField(60,26,'','',18,0x00FF00,false);
            textField.touchable = false;
            textField.x = 197;
            textField.y = 101;
            textField.hAlign= 'right';
            textField.text= '+9';
            textField.name= 'punctureAddValue';
            poxyView.addQuiackChild(textField);
            textField = new TextField(60,26,'','',18,0x00FF00,false);
            textField.touchable = false;
            textField.x = 197;
            textField.y = 132;
            textField.hAlign= 'right';
            textField.text= '+99';
            textField.name= 'dodgeAddValue';
            poxyView.addQuiackChild(textField);
            textField = new TextField(60,26,'','',18,0x00FF00,false);
            textField.touchable = false;
            textField.x = 197;
            textField.y = 165;
            textField.hAlign= 'right';
            textField.text= '+999';
            textField.name= 'critPercentageAddValue';
            poxyView.addQuiackChild(textField);
            textField = new TextField(60,26,'','',18,0x00FF00,false);
            textField.touchable = false;
            textField.x = 197;
            textField.y = 199;
            textField.hAlign= 'right';
            textField.text= '+9999';
            textField.name= 'toughnessAddValue';
            poxyView.addQuiackChild(textField);
            textField = new TextField(80,28,'','',18,0x00FF00,false);
            textField.touchable = false;
            textField.x = 169;
            textField.y = 3;
            textField.hAlign= 'right';
            textField.text= '+9';
            textField.name= 'attackAddValue';
            poxyView.addQuiackChild(textField);
            textField = new TextField(80,28,'','',18,0x00FF00,false);
            textField.touchable = false;
            textField.x = 169;
            textField.y = 43;
            textField.hAlign= 'right';
            textField.text= '+99';
            textField.name= 'hpAddValue';
            poxyView.addQuiackChild(textField);
            init();
        }
        override public function dispose():void
        {
            stoneImageBg.dispose();
            advanceBtn.dispose();
            heroHead.dispose();
            nowHeroHead.dispose();
            advanceHeroHead.dispose();
            poxyView.dispose();
            super.dispose();
        
}
    }
}
