package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.view.View;

    public class AultivateViewBase extends View
    {
        public var ui_gongyong_di_9gongge339143:Scale9Image;
        public var ui_Setup_button_switch3546138:Scale9Image;
        public var effectbg_2:Image;
        public var effectbg_3:Image;
        public var effectbg_1:Image;
        public var proxylTitle:TextField;
        public var nowHead:Image;
        public var nextHead:Image;
        public var nextQuality:Image;
        public var nowQuality:Image;
        public var lock:Sprite;
        public var upStarTip:TextField;
        public var par:Image;
        public var txt_percent:TextField;
        public var getBtn:Button;
        public var upStarBtn:Button;
        public var enbedStarBtn:Image;
        public var moneyTxt:TextField;
        public var tipsTxt:TextField;
        public var jtBtn:Image;
        public var moneyIcon:Image;
        public var upStarTxt:TextField;
        public var getTxt:TextField;
        public var proxy:Sprite;
        public var materIcon:Image;
        public var kuang:Image;
        public var txt_heroName:TextField;
        public var textLv:TextField;

        public function AultivateViewBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            var assetMgr:AssetMgr = AssetMgr.instance;
            texture = assetMgr.getTexture('ui_gongyong_di_9gongge');
            var ui_gongyong_di_9gongge339143Rect:Rectangle = new Rectangle(21,21,43,41);
            var ui_gongyong_di_9gongge3391439ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_gongyong_di_9gongge339143Rect);
            ui_gongyong_di_9gongge339143 = new Scale9Image(ui_gongyong_di_9gongge3391439ScaleTexture);
            ui_gongyong_di_9gongge339143.x = 339;
            ui_gongyong_di_9gongge339143.y = 143;
            ui_gongyong_di_9gongge339143.width = 190;
            ui_gongyong_di_9gongge339143.height = 346;
            this.addQuiackChild(ui_gongyong_di_9gongge339143);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou2');
            image = new Image(texture);
            image.x = 330;
            image.y = 150;
            image.width = 26;
            image.height = 325;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 326;
            image.y = 133;
            image.width = 38;
            image.height = 34;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou1');
            image = new Image(texture);
            image.x = 340;
            image.y = 494;
            image.width = 173;
            image.height = 24;
            image.scaleY = -1;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 326;
            image.y = 495;
            image.width = 38;
            image.height = 34;
            image.scaleY = -1;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 543;
            image.y = 133;
            image.width = 38;
            image.height = 34;
            image.scaleX = -1;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 542;
            image.y = 495;
            image.width = 38;
            image.height = 34;
            image.scaleX = -1;
            image.scaleY = -1;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_kuang_paizi1');
            image = new Image(texture);
            image.x = 454;
            image.y = 112;
            image.width = 61;
            image.height = 61;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_kuang_paizi1');
            image = new Image(texture);
            image.x = 419;
            image.y = 112;
            image.width = 61;
            image.height = 61;
            image.scaleX = -1;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_kuang_paizi2');
            image = new Image(texture);
            image.x = 417;
            image.y = 112;
            image.width = 38;
            image.height = 61;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_Setup_button_switch3');
            var ui_Setup_button_switch3546138Rect:Rectangle = new Rectangle(14,20,180,69);
            var ui_Setup_button_switch35461389ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_Setup_button_switch3546138Rect);
            ui_Setup_button_switch3546138 = new Scale9Image(ui_Setup_button_switch35461389ScaleTexture);
            ui_Setup_button_switch3546138.x = 546;
            ui_Setup_button_switch3546138.y = 138;
            ui_Setup_button_switch3546138.width = 387;
            ui_Setup_button_switch3546138.height = 343;
            this.addQuiackChild(ui_Setup_button_switch3546138);
            texture = assetMgr.getTexture('ui_yingxiongkapaiguang_0_2')
            effectbg_2 = new Image(texture);
            effectbg_2.x = 34;
            effectbg_2.y = 151;
            effectbg_2.width = 287;
            effectbg_2.height = 320;
            this.addQuiackChild(effectbg_2);
            effectbg_2.touchable = false;
            texture = assetMgr.getTexture('ui_yingxiongkapaiguang_0_1')
            effectbg_3 = new Image(texture);
            effectbg_3.x = 34;
            effectbg_3.y = 468;
            effectbg_3.width = 287;
            effectbg_3.height = 36;
            this.addQuiackChild(effectbg_3);
            effectbg_3.touchable = false;
            texture = assetMgr.getTexture('ui_yingxiongkapaiguang_0_1')
            effectbg_1 = new Image(texture);
            effectbg_1.x = 34;
            effectbg_1.y = 119;
            effectbg_1.width = 287;
            effectbg_1.height = 36;
            this.addQuiackChild(effectbg_1);
            effectbg_1.touchable = false;
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou2');
            image = new Image(texture);
            image.x = 539;
            image.y = 167;
            image.width = 26;
            image.height = 307;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            proxylTitle = new TextField(108,24,'','',18,0xFFFFCC,false);
            proxylTitle.touchable = false;
            proxylTitle.hAlign= 'center';
            proxylTitle.text= '属性加成';
            proxylTitle.x = 382;
            proxylTitle.y = 130;
            this.addQuiackChild(proxylTitle);
            texture =assetMgr.getTexture('ui_gongyong_100yingxiongkuang_kong1');
            image = new Image(texture);
            image.x = 570;
            image.y = 178;
            image.width = 100;
            image.height = 100;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_501')
            nowHead = new Image(texture);
            nowHead.x = 569;
            nowHead.y = 178;
            nowHead.width = 100;
            nowHead.height = 100;
            this.addQuiackChild(nowHead);
            nowHead.touchable = false;
            texture =assetMgr.getTexture('ui_gongyong_100yingxiongkuang_kong1');
            image = new Image(texture);
            image.x = 813;
            image.y = 178;
            image.width = 100;
            image.height = 100;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('photo_501')
            nextHead = new Image(texture);
            nextHead.x = 813;
            nextHead.y = 177;
            nextHead.width = 100;
            nextHead.height = 100;
            this.addQuiackChild(nextHead);
            nextHead.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_100yingxiongkuang_0')
            nextQuality = new Image(texture);
            nextQuality.x = 812;
            nextQuality.y = 178;
            nextQuality.width = 100;
            nextQuality.height = 100;
            this.addQuiackChild(nextQuality);
            nextQuality.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_100yingxiongkuang_0')
            nowQuality = new Image(texture);
            nowQuality.x = 570;
            nowQuality.y = 178;
            nowQuality.width = 100;
            nowQuality.height = 100;
            this.addQuiackChild(nowQuality);
            nowQuality.touchable = false;
            lock = new Sprite();
            lock.x = 813;
            lock.y = 178;
            lock.width = 100;
            lock.height = 100;
            this.addQuiackChild(lock);
            lock.name= 'lock';
            texture =assetMgr.getTexture('ui_atlas_bottom_hero_zhezhao');
            image = new Image(texture);
            image.width = 101;
            image.height = 101;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            lock.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_world_nandusuo');
            image = new Image(texture);
            image.x = 20;
            image.y = 15;
            image.width = 59;
            image.height = 67;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            lock.addQuiackChild(image);
            upStarTip = new TextField(145,31,'','',24,0xFFFFCC,false);
            upStarTip.touchable = false;
            upStarTip.hAlign= 'center';
            upStarTip.text= '升星';
            upStarTip.x = 667;
            upStarTip.y = 235;
            this.addQuiackChild(upStarTip);
            texture =assetMgr.getTexture('ui_gongyong_jingyantiao_baidi');
            image = new Image(texture);
            image.x = 592;
            image.y = 320;
            image.width = 180;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_jingyantiao_baidi1')
            par = new Image(texture);
            par.x = 617;
            par.y = 329;
            par.width = 145;
            par.height = 15;
            this.addQuiackChild(par);
            par.touchable = false;
            txt_percent = new TextField(62,24,'','',16,0xFFFFFF,false);
            txt_percent.touchable = false;
            txt_percent.hAlign= 'center';
            txt_percent.text= '1/14';
            txt_percent.x = 655;
            txt_percent.y = 325;
            this.addQuiackChild(txt_percent);
            texture = assetMgr.getTexture('ui_button_tiebaomutouanjian');
            getBtn = new Button(texture);
            getBtn.name= 'getBtn';
            getBtn.x = 793;
            getBtn.y = 310;
            getBtn.width = 126;
            getBtn.height = 52;
            this.addQuiackChild(getBtn);
            texture = assetMgr.getTexture('ui_button_gongyong_big2');
            upStarBtn = new Button(texture);
            upStarBtn.name= 'upStarBtn';
            upStarBtn.x = 542;
            upStarBtn.y = 371;
            upStarBtn.width = 400;
            upStarBtn.height = 105;
            this.addQuiackChild(upStarBtn);
            texture = assetMgr.getTexture('ui_button_gongyong_big')
            enbedStarBtn = new Image(texture);
            enbedStarBtn.x = 572;
            enbedStarBtn.y = 390;
            enbedStarBtn.width = 340;
            enbedStarBtn.height = 64;
            this.addQuiackChild(enbedStarBtn);
            enbedStarBtn.touchable = false;
            moneyTxt = new TextField(120,36,'','',24,0xFFFFCC,false);
            moneyTxt.touchable = false;
            moneyTxt.hAlign= 'left';
            moneyTxt.text= '9999999';
            moneyTxt.x = 670;
            moneyTxt.y = 403;
            this.addQuiackChild(moneyTxt);
            tipsTxt = new TextField(153,36,'','',24,0xFFFFCC,false);
            tipsTxt.touchable = false;
            tipsTxt.hAlign= 'center';
            tipsTxt.text= '功能暂未开发';
            tipsTxt.x = 660;
            tipsTxt.y = 403;
            this.addQuiackChild(tipsTxt);
            texture = assetMgr.getTexture('ui_background_intensify_indicate')
            jtBtn = new Image(texture);
            jtBtn.x = 709;
            jtBtn.y = 180;
            jtBtn.width = 61;
            jtBtn.height = 53;
            this.addQuiackChild(jtBtn);
            jtBtn.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_money')
            moneyIcon = new Image(texture);
            moneyIcon.x = 630;
            moneyIcon.y = 402;
            moneyIcon.width = 40;
            moneyIcon.height = 40;
            this.addQuiackChild(moneyIcon);
            moneyIcon.touchable = false;
            upStarTxt = new TextField(61,36,'','',24,0xFFFFCC,false);
            upStarTxt.touchable = false;
            upStarTxt.hAlign= 'left';
            upStarTxt.text= '升星';
            upStarTxt.x = 794;
            upStarTxt.y = 403;
            this.addQuiackChild(upStarTxt);
            getTxt = new TextField(56,36,'','',24,0xFFFFCC,false);
            getTxt.touchable = false;
            getTxt.hAlign= 'center';
            getTxt.text= '获取';
            getTxt.x = 826;
            getTxt.y = 316;
            this.addQuiackChild(getTxt);
            proxy = new Sprite();
            proxy.x = 358;
            proxy.y = 172;
            proxy.width = 171;
            proxy.height = 299;
            this.addQuiackChild(proxy);
            proxy.name= 'proxy';
            texture = assetMgr.getTexture('ui_tubiao_gongjilitubiao');
            button = new Button(texture);
            button.name= 'attackIcon';
            button.x = 7;
            button.width = 20;
            button.height = 33;
            proxy.addQuiackChild(button);
            texture = assetMgr.getTexture('ui_tubiao_xueliangtubiao');
            button = new Button(texture);
            button.name= 'hpIcon';
            button.x = 1;
            button.y = 42;
            button.width = 34;
            button.height = 31;
            proxy.addQuiackChild(button);
            textField = new TextField(56,28,'','',18,0xFFFFCC,false);
            textField.touchable = false;
            textField.y = 103;
            textField.hAlign= 'left';
            textField.text= '穿刺';
            textField.name= 'punctureTitle';
            proxy.addQuiackChild(textField);
            textField = new TextField(56,28,'','',18,0xFFFFCC,false);
            textField.touchable = false;
            textField.y = 131;
            textField.hAlign= 'left';
            textField.text= '命中';
            textField.name= 'hitTitle';
            proxy.addQuiackChild(textField);
            textField = new TextField(56,28,'','',18,0xFFFFCC,false);
            textField.touchable = false;
            textField.y = 158;
            textField.hAlign= 'left';
            textField.text= '闪避';
            textField.name= 'dodgeTitle';
            proxy.addQuiackChild(textField);
            textField = new TextField(56,28,'','',18,0xFFFFCC,false);
            textField.touchable = false;
            textField.y = 186;
            textField.hAlign= 'left';
            textField.text= '暴击';
            textField.name= 'critTitle';
            proxy.addQuiackChild(textField);
            textField = new TextField(56,28,'','',18,0xFFFFCC,false);
            textField.touchable = false;
            textField.y = 214;
            textField.hAlign= 'left';
            textField.text= '暴强';
            textField.name= 'critPercentageTitle';
            proxy.addQuiackChild(textField);
            textField = new TextField(56,28,'','',18,0xFFFFCC,false);
            textField.touchable = false;
            textField.y = 242;
            textField.hAlign= 'left';
            textField.text= '免爆';
            textField.name= 'anitCritTitle';
            proxy.addQuiackChild(textField);
            textField = new TextField(56,28,'','',18,0xFFFFCC,false);
            textField.touchable = false;
            textField.y = 270;
            textField.hAlign= 'left';
            textField.text= '韧性';
            textField.name= 'toughnessTitle';
            proxy.addQuiackChild(textField);
            textField = new TextField(56,28,'','',18,0xFFFFCC,false);
            textField.touchable = false;
            textField.y = 74;
            textField.hAlign= 'left';
            textField.text= '防御';
            textField.name= 'defendTitle';
            proxy.addQuiackChild(textField);
            textField = new TextField(114,28,'','',18,0x00FF00,false);
            textField.touchable = false;
            textField.x = 57;
            textField.y = 2;
            textField.hAlign= 'left';
            textField.text= '(1.3)';
            textField.name= 'attackValue';
            proxy.addQuiackChild(textField);
            textField = new TextField(114,28,'','',18,0x00FF00,false);
            textField.touchable = false;
            textField.x = 57;
            textField.y = 40;
            textField.hAlign= 'left';
            textField.text= '(1.3)';
            textField.name= 'hpValue';
            proxy.addQuiackChild(textField);
            textField = new TextField(114,28,'','',18,0x00FF00,false);
            textField.touchable = false;
            textField.x = 57;
            textField.y = 75;
            textField.hAlign= 'left';
            textField.text= '(1.3)';
            textField.name= 'defendValue';
            proxy.addQuiackChild(textField);
            textField = new TextField(114,28,'','',18,0x00FF00,false);
            textField.touchable = false;
            textField.x = 57;
            textField.y = 103;
            textField.hAlign= 'left';
            textField.text= '(1.3)';
            textField.name= 'punctureValue';
            proxy.addQuiackChild(textField);
            textField = new TextField(114,28,'','',18,0x00FF00,false);
            textField.touchable = false;
            textField.x = 57;
            textField.y = 131;
            textField.hAlign= 'left';
            textField.text= '(1.3)';
            textField.name= 'hitValue';
            proxy.addQuiackChild(textField);
            textField = new TextField(114,28,'','',18,0x00FF00,false);
            textField.touchable = false;
            textField.x = 57;
            textField.y = 159;
            textField.hAlign= 'left';
            textField.text= '(1.3)';
            textField.name= 'dodgeValue';
            proxy.addQuiackChild(textField);
            textField = new TextField(114,28,'','',18,0x00FF00,false);
            textField.touchable = false;
            textField.x = 57;
            textField.y = 187;
            textField.hAlign= 'left';
            textField.text= '(1.3)';
            textField.name= 'critValue';
            proxy.addQuiackChild(textField);
            textField = new TextField(114,28,'','',18,0x00FF00,false);
            textField.touchable = false;
            textField.x = 57;
            textField.y = 215;
            textField.hAlign= 'left';
            textField.text= '(1.3)';
            textField.name= 'critPercentageValue';
            proxy.addQuiackChild(textField);
            textField = new TextField(114,28,'','',18,0x00FF00,false);
            textField.touchable = false;
            textField.x = 57;
            textField.y = 243;
            textField.hAlign= 'left';
            textField.text= '(1.3)';
            textField.name= 'anitCritValue';
            proxy.addQuiackChild(textField);
            textField = new TextField(114,28,'','',18,0x00FF00,false);
            textField.touchable = false;
            textField.x = 57;
            textField.y = 271;
            textField.hAlign= 'left';
            textField.text= '(1.3)';
            textField.name= 'toughnessValue';
            proxy.addQuiackChild(textField);
            texture = assetMgr.getTexture('ui_yingxionghun')
            materIcon = new Image(texture);
            materIcon.x = 575;
            materIcon.y = 294;
            materIcon.width = 60;
            materIcon.height = 60;
            this.addQuiackChild(materIcon);
            materIcon.touchable = false;
            texture =assetMgr.getTexture('ui_yingxiong_beijing');
            image = new Image(texture);
            image.x = 36;
            image.y = 113;
            image.width = 287;
            image.height = 368;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_yingxiongjiuguan_xinkapai')
            kuang = new Image(texture);
            kuang.x = 35;
            kuang.y = 125;
            kuang.width = 287;
            kuang.height = 368;
            this.addQuiackChild(kuang);
            kuang.touchable = false;
            texture =assetMgr.getTexture('ui_yingxiongkapai_yingxiongmingdi');
            image = new Image(texture);
            image.x = 47;
            image.y = 150;
            image.width = 255;
            image.height = 59;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            txt_heroName = new TextField(184,33,'','',26,0xFFFFFF,false);
            txt_heroName.touchable = false;
            txt_heroName.hAlign= 'center';
            txt_heroName.text= '阿尔萨斯啊啊';
            txt_heroName.x = 87;
            txt_heroName.y = 160;
            this.addQuiackChild(txt_heroName);
            texture =assetMgr.getTexture('ui_gongyong_kapaiyuansu1');
            image = new Image(texture);
            image.x = 28;
            image.y = 425;
            image.width = 70;
            image.height = 70;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_kapaiyuansu1');
            image = new Image(texture);
            image.x = 266;
            image.y = 425;
            image.width = 70;
            image.height = 70;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            textLv = new TextField(44,44,'','',24,0xFFFFFF,false);
            textLv.touchable = false;
            textLv.hAlign= 'center';
            textLv.text= '65';
            textLv.x = 39;
            textLv.y = 438;
            this.addQuiackChild(textLv);
            init();
        }
        override public function dispose():void
        {
            lock.dispose();
            getBtn.dispose();
            upStarBtn.dispose();
            proxy.dispose();
            super.dispose();
        
}
    }
}
