package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import com.view.View;

    public class BattleVideoRankBase extends View
    {
        public var btn_menu:Button;
        public var ico_hero2:Button;
        public var ico_hero1:Button;
        public var ico_hero0:Button;
        public var txt_0:TextField;
        public var txt_name0:TextField;
        public var txt_power0:TextField;
        public var txt_1:TextField;
        public var txt_name1:TextField;
        public var txt_power1:TextField;
        public var txt_2:TextField;
        public var txt_name2:TextField;
        public var txt_power2:TextField;
        public var btn_look0:Button;
        public var btn_look1:Button;
        public var btn_look2:Button;

        public function BattleVideoRankBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            var assetMgr:AssetMgr = AssetMgr.instance;
            texture =assetMgr.getTexture('ui_wudixingyunxing_xingxing_goumaikuang2');
            image = new Image(texture);
            image.x = -36;
            image.width = 408;
            image.height = 425;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_wudixingyunxing_xingxing_goumaikuang1');
            image = new Image(texture);
            image.x = 464;
            image.width = 102;
            image.height = 425;
            image.scaleX = -1;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_button_fenlei');
            btn_menu = new Button(texture);
            btn_menu.name= 'btn_menu';
            btn_menu.x = 462;
            btn_menu.y = 25;
            btn_menu.width = 56;
            btn_menu.height = 144;
            this.addQuiackChild(btn_menu);
            texture =assetMgr.getTexture('ui_rongyupaizi_di');
            image = new Image(texture);
            image.x = 14;
            image.y = 156;
            image.width = 381;
            image.height = 121;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_rongyupaizi_di');
            image = new Image(texture);
            image.x = 14;
            image.y = 282;
            image.width = 381;
            image.height = 121;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_rongyupaizi_di');
            image = new Image(texture);
            image.x = 427;
            image.y = 282;
            image.width = 381;
            image.height = 121;
            image.scaleX = -1.17230224609375;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_rongyupaizi_di');
            image = new Image(texture);
            image.x = 14;
            image.y = 30;
            image.width = 381;
            image.height = 121;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_rongyupaizi_di');
            image = new Image(texture);
            image.x = 427;
            image.y = 30;
            image.width = 381;
            image.height = 121;
            image.scaleX = -1.17230224609375;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_rongyupaizi_di');
            image = new Image(texture);
            image.x = 427;
            image.y = 156;
            image.width = 381;
            image.height = 121;
            image.scaleX = -1.17230224609375;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_pvp_renwutouxiang0');
            ico_hero2 = new Button(texture);
            ico_hero2.name= 'ico_hero2';
            ico_hero2.x = 26;
            ico_hero2.y = 292;
            ico_hero2.width = 100;
            ico_hero2.height = 100;
            this.addQuiackChild(ico_hero2);
            texture = assetMgr.getTexture('ui_pvp_renwutouxiang0');
            ico_hero1 = new Button(texture);
            ico_hero1.name= 'ico_hero1';
            ico_hero1.x = 26;
            ico_hero1.y = 165;
            ico_hero1.width = 100;
            ico_hero1.height = 100;
            this.addQuiackChild(ico_hero1);
            texture = assetMgr.getTexture('ui_pvp_renwutouxiang0');
            ico_hero0 = new Button(texture);
            ico_hero0.name= 'ico_hero0';
            ico_hero0.x = 26;
            ico_hero0.y = 39;
            ico_hero0.width = 100;
            ico_hero0.height = 100;
            this.addQuiackChild(ico_hero0);
            texture =assetMgr.getTexture('ui_city_head1');
            image = new Image(texture);
            image.x = 20;
            image.y = 34;
            image.width = 111;
            image.height = 111;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_city_head1');
            image = new Image(texture);
            image.x = 20;
            image.y = 160;
            image.width = 111;
            image.height = 111;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_city_head1');
            image = new Image(texture);
            image.x = 20;
            image.y = 287;
            image.width = 111;
            image.height = 111;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            txt_0 = new TextField(104,28,'','',18,0xFFFFFF,false);
            txt_0.touchable = false;
            txt_0.hAlign= 'left';
            txt_0.text= 'No.1';
            txt_0.x = 134;
            txt_0.y = 40;
            this.addQuiackChild(txt_0);
            txt_name0 = new TextField(218,36,'','',24,0xFFFFCC,false);
            txt_name0.touchable = false;
            txt_name0.hAlign= 'center';
            txt_name0.text= '';
            txt_name0.x = 118;
            txt_name0.y = 72;
            this.addQuiackChild(txt_name0);
            txt_power0 = new TextField(150,28,'','',18,0xFFFFFF,false);
            txt_power0.touchable = false;
            txt_power0.hAlign= 'right';
            txt_power0.text= '';
            txt_power0.x = 164;
            txt_power0.y = 112;
            this.addQuiackChild(txt_power0);
            texture =assetMgr.getTexture('ui_gongyong_iocn_zhandouli');
            image = new Image(texture);
            image.x = 134;
            image.y = 112;
            image.width = 32;
            image.height = 28;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            txt_1 = new TextField(104,28,'','',18,0xFFFFFF,false);
            txt_1.touchable = false;
            txt_1.hAlign= 'left';
            txt_1.text= 'No.2';
            txt_1.x = 134;
            txt_1.y = 162;
            this.addQuiackChild(txt_1);
            txt_name1 = new TextField(218,36,'','',24,0xFFFFCC,false);
            txt_name1.touchable = false;
            txt_name1.hAlign= 'center';
            txt_name1.text= '';
            txt_name1.x = 118;
            txt_name1.y = 194;
            this.addQuiackChild(txt_name1);
            txt_power1 = new TextField(150,28,'','',18,0xFFFFFF,false);
            txt_power1.touchable = false;
            txt_power1.hAlign= 'right';
            txt_power1.text= '';
            txt_power1.x = 164;
            txt_power1.y = 234;
            this.addQuiackChild(txt_power1);
            txt_2 = new TextField(104,28,'','',18,0xFFFFFF,false);
            txt_2.touchable = false;
            txt_2.hAlign= 'left';
            txt_2.text= 'No.3';
            txt_2.x = 134;
            txt_2.y = 290;
            this.addQuiackChild(txt_2);
            txt_name2 = new TextField(218,36,'','',24,0xFFFFCC,false);
            txt_name2.touchable = false;
            txt_name2.hAlign= 'center';
            txt_name2.text= '';
            txt_name2.x = 118;
            txt_name2.y = 322;
            this.addQuiackChild(txt_name2);
            txt_power2 = new TextField(150,28,'','',18,0xFFFFFF,false);
            txt_power2.touchable = false;
            txt_power2.hAlign= 'right';
            txt_power2.text= '';
            txt_power2.x = 164;
            txt_power2.y = 362;
            this.addQuiackChild(txt_power2);
            texture = assetMgr.getTexture('ui_button_look_iocn');
            btn_look0 = new Button(texture);
            btn_look0.name= 'btn_look0';
            btn_look0.x = 325;
            btn_look0.y = 45;
            btn_look0.width = 93;
            btn_look0.height = 88;
            this.addQuiackChild(btn_look0);
            texture = assetMgr.getTexture('ui_button_look_iocn');
            btn_look1 = new Button(texture);
            btn_look1.name= 'btn_look1';
            btn_look1.x = 325;
            btn_look1.y = 171;
            btn_look1.width = 93;
            btn_look1.height = 88;
            this.addQuiackChild(btn_look1);
            texture = assetMgr.getTexture('ui_button_look_iocn');
            btn_look2 = new Button(texture);
            btn_look2.name= 'btn_look2';
            btn_look2.x = 325;
            btn_look2.y = 296;
            btn_look2.width = 93;
            btn_look2.height = 88;
            this.addQuiackChild(btn_look2);
            texture =assetMgr.getTexture('ui_wenzi_zuijiatongguan');
            image = new Image(texture);
            image.x = 471;
            image.y = 46;
            image.width = 31;
            image.height = 102;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_iocn_zhandouli');
            image = new Image(texture);
            image.x = 131;
            image.y = 235;
            image.width = 32;
            image.height = 28;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_iocn_zhandouli');
            image = new Image(texture);
            image.x = 132;
            image.y = 363;
            image.width = 32;
            image.height = 28;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            init();
        }
        override public function dispose():void
        {
            btn_menu.dispose();
            ico_hero2.dispose();
            ico_hero1.dispose();
            ico_hero0.dispose();
            btn_look0.dispose();
            btn_look1.dispose();
            btn_look2.dispose();
            super.dispose();
        
}
    }
}
