package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import com.view.View;

    public class CityIconBase extends View
    {
        public var ico_hero:Button;
        public var tag_rankLevel:Image;
        public var btn_vip:Button;
        public var txt_vip:TextField;
        public var btn_welfare:Button;
        public var btn_help:Button;
        public var btn_strategy:Button;
        public var view_title:Sprite;
        public var btn_notice:Button;
        public var btn_mail:Button;
        public var btn_bag:Button;
        public var btn_pic:Button;
        public var btn_reward:Button;
        public var btn_vipReward:Button;

        public function CityIconBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            var assetMgr:AssetMgr = AssetMgr.instance;
            texture = assetMgr.getTexture('photo_501');
            ico_hero = new Button(texture);
            ico_hero.name= 'ico_hero';
            ico_hero.x = 18;
            ico_hero.y = 15;
            ico_hero.width = 86;
            ico_hero.height = 86;
            this.addQuiackChild(ico_hero);
            texture =assetMgr.getTexture('ui_city_head1');
            image = new Image(texture);
            image.x = 12;
            image.y = 6;
            image.width = 105;
            image.height = 105;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_city_head');
            image = new Image(texture);
            image.x = 8;
            image.y = 55;
            image.width = 84;
            image.height = 75;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_iocn_qualifying6')
            tag_rankLevel = new Image(texture);
            tag_rankLevel.x = 1;
            tag_rankLevel.y = 83;
            tag_rankLevel.width = 73;
            tag_rankLevel.height = 49;
            this.addQuiackChild(tag_rankLevel);
            tag_rankLevel.touchable = false;
            texture = assetMgr.getTexture('ui_icon_city_vip');
            btn_vip = new Button(texture);
            btn_vip.name= 'btn_vip';
            btn_vip.width = 56;
            btn_vip.height = 56;
            this.addQuiackChild(btn_vip);
            txt_vip = new TextField(48,25,'','',16,0xE7E5DF,false);
            txt_vip.touchable = false;
            txt_vip.hAlign= 'center';
            txt_vip.text= '0';
            txt_vip.x = 2;
            txt_vip.y = 20;
            this.addQuiackChild(txt_vip);
            texture = assetMgr.getTexture('ui_zhucheng_iocn_fuli');
            btn_welfare = new Button(texture);
            btn_welfare.name= 'btn_welfare';
            btn_welfare.x = 12;
            btn_welfare.y = 558;
            btn_welfare.width = 70;
            btn_welfare.height = 70;
            this.addQuiackChild(btn_welfare);
            texture = assetMgr.getTexture('ui_zhucheng_iocn_xiaozhushou');
            btn_help = new Button(texture);
            btn_help.name= 'btn_help';
            btn_help.x = 884;
            btn_help.y = 122;
            btn_help.width = 65;
            btn_help.height = 65;
            this.addQuiackChild(btn_help);
            texture = assetMgr.getTexture('ui_button_city_gonglue');
            btn_strategy = new Button(texture);
            btn_strategy.name= 'btn_strategy';
            btn_strategy.x = 857;
            btn_strategy.width = 95;
            btn_strategy.height = 95;
            this.addQuiackChild(btn_strategy);
            view_title = new Sprite();
            view_title.x = 478;
            view_title.y = 6;
            view_title.width = 590;
            view_title.height = 36;
            this.addQuiackChild(view_title);
            view_title.name= 'view_title';
            texture = assetMgr.getTexture('ui_gongyong_zhucheng_xinxidikuang');
            button = new Button(texture);
            button.name= 'btn_tired';
            button.x = 155;
            button.width = 140;
            button.height = 36;
            view_title.addQuiackChild(button);
            texture = assetMgr.getTexture('ui_gongyong_zhucheng_xinxidikuang');
            button = new Button(texture);
            button.name= 'btn_diamond';
            button.x = 5;
            button.width = 140;
            button.height = 36;
            view_title.addQuiackChild(button);
            texture = assetMgr.getTexture('ui_gongyong_zhucheng_xinxidikuang');
            button = new Button(texture);
            button.name= 'btn_money';
            button.x = -145;
            button.width = 140;
            button.height = 36;
            view_title.addQuiackChild(button);
            texture =assetMgr.getTexture('ui_gongyong_zhucheng_xinxidikuang');
            image = new Image(texture);
            image.x = -295;
            image.width = 140;
            image.height = 36;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_title.addQuiackChild(image);
            textField = new TextField(104,25,'','',16,0xE7E5DF,false);
            textField.touchable = false;
            textField.x = -269;
            textField.y = 6;
            textField.hAlign= 'right';
            textField.text= '';
            textField.name= 'txt_ability';
            view_title.addQuiackChild(textField);
            texture =assetMgr.getTexture('ui_icon_city_zhanli');
            image = new Image(texture);
            image.x = -290;
            image.y = 7;
            image.width = 43;
            image.height = 22;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_title.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_tubiao_zhuxianpilaozhi');
            image = new Image(texture);
            image.x = 166;
            image.y = 6;
            image.width = 20;
            image.height = 25;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_title.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_lvjiahao');
            image = new Image(texture);
            image.x = 269;
            image.y = 7;
            image.width = 18;
            image.height = 20;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_title.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_money');
            image = new Image(texture);
            image.x = -138;
            image.y = 6;
            image.width = 25;
            image.height = 25;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_title.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_zuanshi');
            image = new Image(texture);
            image.x = 11;
            image.y = 5;
            image.width = 29;
            image.height = 28;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_title.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_lvjiahao');
            image = new Image(texture);
            image.x = 119;
            image.y = 7;
            image.width = 18;
            image.height = 20;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_title.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_lvjiahao');
            image = new Image(texture);
            image.x = -31;
            image.y = 7;
            image.width = 18;
            image.height = 20;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_title.addQuiackChild(image);
            textField = new TextField(83,25,'','',16,0xE7E5DF,false);
            textField.touchable = false;
            textField.x = -117;
            textField.y = 6;
            textField.hAlign= 'right';
            textField.text= '';
            textField.name= 'txt_money';
            view_title.addQuiackChild(textField);
            textField = new TextField(104,25,'','',16,0xE7E5DF,false);
            textField.touchable = false;
            textField.x = 14;
            textField.y = 6;
            textField.hAlign= 'right';
            textField.text= '';
            textField.name= 'txt_diamond';
            view_title.addQuiackChild(textField);
            textField = new TextField(104,25,'','',16,0xE7E5DF,false);
            textField.touchable = false;
            textField.x = 164;
            textField.y = 6;
            textField.hAlign= 'right';
            textField.text= '';
            textField.name= 'txt_tired';
            view_title.addQuiackChild(textField);
            texture = assetMgr.getTexture('ui_button_city_gonggao');
            btn_notice = new Button(texture);
            btn_notice.name= 'btn_notice';
            btn_notice.x = 20;
            btn_notice.y = 144;
            btn_notice.width = 77;
            btn_notice.height = 63;
            this.addQuiackChild(btn_notice);
            texture = assetMgr.getTexture('ui_button_city_youjian');
            btn_mail = new Button(texture);
            btn_mail.name= 'btn_mail';
            btn_mail.x = 26;
            btn_mail.y = 217;
            btn_mail.width = 65;
            btn_mail.height = 65;
            this.addQuiackChild(btn_mail);
            texture = assetMgr.getTexture('ui_button_city_beibao');
            btn_bag = new Button(texture);
            btn_bag.name= 'btn_bag';
            btn_bag.x = 185;
            btn_bag.y = 558;
            btn_bag.width = 65;
            btn_bag.height = 65;
            this.addQuiackChild(btn_bag);
            texture = assetMgr.getTexture('ui_button_city_tujian');
            btn_pic = new Button(texture);
            btn_pic.name= 'btn_pic';
            btn_pic.x = 98;
            btn_pic.y = 558;
            btn_pic.width = 65;
            btn_pic.height = 65;
            this.addQuiackChild(btn_pic);
            texture = assetMgr.getTexture('ui_button_city_chengjiu');
            btn_reward = new Button(texture);
            btn_reward.name= 'btn_reward';
            btn_reward.x = 207;
            btn_reward.y = 56;
            btn_reward.width = 55;
            btn_reward.height = 55;
            this.addQuiackChild(btn_reward);
            texture = assetMgr.getTexture('ui_button_city_viplibao');
            btn_vipReward = new Button(texture);
            btn_vipReward.name= 'btn_vipReward';
            btn_vipReward.x = 276;
            btn_vipReward.y = 56;
            btn_vipReward.width = 55;
            btn_vipReward.height = 55;
            this.addQuiackChild(btn_vipReward);
            init();
        }
        override public function dispose():void
        {
            ico_hero.dispose();
            btn_vip.dispose();
            btn_welfare.dispose();
            btn_help.dispose();
            btn_strategy.dispose();
            view_title.dispose();
            btn_notice.dispose();
            btn_mail.dispose();
            btn_bag.dispose();
            btn_pic.dispose();
            btn_reward.dispose();
            btn_vipReward.dispose();
            super.dispose();
        
}
    }
}
