package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.view.View;

    public class DestinyViewBase extends View
    {
        public var heroIcon_0:Sprite;
        public var heroIcon_7:Sprite;
        public var heroIcon_6:Sprite;
        public var heroIcon_1:Sprite;
        public var heroIcon_8:Sprite;
        public var heroIcon_5:Sprite;
        public var heroIcon_2:Sprite;
        public var heroIcon_3:Sprite;
        public var heroIcon_4:Sprite;
        public var fushBtn:Button;
        public var buyBtn_0:Button;
        public var buyBtn_1:Button;
        public var buyBtn_2:Button;
        public var tag_normal:Scale9Image;
        public var fushNum:TextField;
        public var fushTitle:TextField;
        public var fushTimeTitle:TextField;
        public var fushTime:TextField;
        public var buyTitle_0:TextField;
        public var buyNum_0:TextField;
        public var buyTitle_1:TextField;
        public var buyNum_1:TextField;
        public var buyTitle_2:TextField;
        public var buyNum_2:TextField;
        public var buyTimeTitle:TextField;
        public var buyTimeNum:TextField;
        public var fushIcon:Image;
        public var buyIcon_0:Image;
        public var buyIcon_1:Image;
        public var buyIcon_2:Image;
        public var desTxt:TextField;
        public var leftTmiesTitle:TextField;
        public var leftTmies:TextField;

        public function DestinyViewBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            var assetMgr:AssetMgr = AssetMgr.instance;
            heroIcon_0 = new Sprite();
            heroIcon_0.x = 94;
            heroIcon_0.y = 108;
            heroIcon_0.width = 124;
            heroIcon_0.height = 124;
            this.addQuiackChild(heroIcon_0);
            heroIcon_0.name= 'heroIcon_0';
            texture = assetMgr.getTexture('ui_gongyong_xingyunchoujiangkuang_xuanzhong')
            image = new Image(texture);
            image.name= 'selectMc';
            image.x = -17;
            image.y = -17;
            image.width = 124;
            image.height = 124;
            heroIcon_0.addQuiackChild(image);
            image.touchable = false;
            texture =assetMgr.getTexture('ui_gongyong_90wupingkuang');
            image = new Image(texture);
            image.width = 90;
            image.height = 90;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroIcon_0.addQuiackChild(image);
            texture = assetMgr.getTexture('icon_514')
            image = new Image(texture);
            image.name= 'img';
            image.width = 90;
            image.height = 90;
            heroIcon_0.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_90wupingkuang2')
            image = new Image(texture);
            image.name= 'quaity';
            image.width = 90;
            image.height = 90;
            heroIcon_0.addQuiackChild(image);
            image.touchable = false;
            textField = new TextField(105,24,'','',18,0xFFFFCC,false);
            textField.touchable = false;
            textField.x = -10;
            textField.y = 59;
            textField.hAlign= 'center';
            textField.text= '';
            textField.name= 'txtName';
            heroIcon_0.addQuiackChild(textField);
            heroIcon_7 = new Sprite();
            heroIcon_7.x = 94;
            heroIcon_7.y = 232;
            heroIcon_7.width = 124;
            heroIcon_7.height = 124;
            this.addQuiackChild(heroIcon_7);
            heroIcon_7.name= 'heroIcon_7';
            texture = assetMgr.getTexture('ui_gongyong_xingyunchoujiangkuang_xuanzhong')
            image = new Image(texture);
            image.name= 'selectMc';
            image.x = -17;
            image.y = -17;
            image.width = 124;
            image.height = 124;
            heroIcon_7.addQuiackChild(image);
            image.touchable = false;
            texture =assetMgr.getTexture('ui_gongyong_90wupingkuang');
            image = new Image(texture);
            image.width = 90;
            image.height = 90;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroIcon_7.addQuiackChild(image);
            texture = assetMgr.getTexture('icon_514')
            image = new Image(texture);
            image.name= 'img';
            image.width = 90;
            image.height = 90;
            heroIcon_7.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_90wupingkuang2')
            image = new Image(texture);
            image.name= 'quaity';
            image.width = 90;
            image.height = 90;
            heroIcon_7.addQuiackChild(image);
            image.touchable = false;
            textField = new TextField(105,24,'','',18,0xFFFFCC,false);
            textField.touchable = false;
            textField.x = -10;
            textField.y = 59;
            textField.hAlign= 'center';
            textField.text= '';
            textField.name= 'txtName';
            heroIcon_7.addQuiackChild(textField);
            heroIcon_6 = new Sprite();
            heroIcon_6.x = 94;
            heroIcon_6.y = 363;
            heroIcon_6.width = 124;
            heroIcon_6.height = 124;
            this.addQuiackChild(heroIcon_6);
            heroIcon_6.name= 'heroIcon_6';
            texture = assetMgr.getTexture('ui_gongyong_xingyunchoujiangkuang_xuanzhong')
            image = new Image(texture);
            image.name= 'selectMc';
            image.x = -17;
            image.y = -17;
            image.width = 124;
            image.height = 124;
            heroIcon_6.addQuiackChild(image);
            image.touchable = false;
            texture =assetMgr.getTexture('ui_gongyong_90wupingkuang');
            image = new Image(texture);
            image.width = 90;
            image.height = 90;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroIcon_6.addQuiackChild(image);
            texture = assetMgr.getTexture('icon_514')
            image = new Image(texture);
            image.name= 'img';
            image.width = 90;
            image.height = 90;
            heroIcon_6.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_90wupingkuang2')
            image = new Image(texture);
            image.name= 'quaity';
            image.width = 90;
            image.height = 90;
            heroIcon_6.addQuiackChild(image);
            image.touchable = false;
            textField = new TextField(105,24,'','',18,0xFFFFCC,false);
            textField.touchable = false;
            textField.x = -10;
            textField.y = 59;
            textField.hAlign= 'center';
            textField.text= '';
            textField.name= 'txtName';
            heroIcon_6.addQuiackChild(textField);
            heroIcon_1 = new Sprite();
            heroIcon_1.x = 226;
            heroIcon_1.y = 108;
            heroIcon_1.width = 124;
            heroIcon_1.height = 124;
            this.addQuiackChild(heroIcon_1);
            heroIcon_1.name= 'heroIcon_1';
            texture = assetMgr.getTexture('ui_gongyong_xingyunchoujiangkuang_xuanzhong')
            image = new Image(texture);
            image.name= 'selectMc';
            image.x = -17;
            image.y = -17;
            image.width = 124;
            image.height = 124;
            heroIcon_1.addQuiackChild(image);
            image.touchable = false;
            texture =assetMgr.getTexture('ui_gongyong_90wupingkuang');
            image = new Image(texture);
            image.width = 90;
            image.height = 90;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroIcon_1.addQuiackChild(image);
            texture = assetMgr.getTexture('icon_514')
            image = new Image(texture);
            image.name= 'img';
            image.width = 90;
            image.height = 90;
            heroIcon_1.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_90wupingkuang2')
            image = new Image(texture);
            image.name= 'quaity';
            image.width = 90;
            image.height = 90;
            heroIcon_1.addQuiackChild(image);
            image.touchable = false;
            textField = new TextField(105,24,'','',18,0xFFFFCC,false);
            textField.touchable = false;
            textField.x = -10;
            textField.y = 59;
            textField.hAlign= 'center';
            textField.text= '';
            textField.name= 'txtName';
            heroIcon_1.addQuiackChild(textField);
            heroIcon_8 = new Sprite();
            heroIcon_8.x = 226;
            heroIcon_8.y = 232;
            heroIcon_8.width = 124;
            heroIcon_8.height = 124;
            this.addQuiackChild(heroIcon_8);
            heroIcon_8.name= 'heroIcon_8';
            texture = assetMgr.getTexture('ui_gongyong_xingyunchoujiangkuang_xuanzhong')
            image = new Image(texture);
            image.name= 'selectMc';
            image.x = -17;
            image.y = -17;
            image.width = 124;
            image.height = 124;
            heroIcon_8.addQuiackChild(image);
            image.touchable = false;
            texture =assetMgr.getTexture('ui_gongyong_90wupingkuang');
            image = new Image(texture);
            image.width = 90;
            image.height = 90;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroIcon_8.addQuiackChild(image);
            texture = assetMgr.getTexture('icon_514')
            image = new Image(texture);
            image.name= 'img';
            image.width = 90;
            image.height = 90;
            heroIcon_8.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_90wupingkuang2')
            image = new Image(texture);
            image.name= 'quaity';
            image.width = 90;
            image.height = 90;
            heroIcon_8.addQuiackChild(image);
            image.touchable = false;
            textField = new TextField(105,24,'','',18,0xFFFFCC,false);
            textField.touchable = false;
            textField.x = -10;
            textField.y = 59;
            textField.hAlign= 'center';
            textField.text= '';
            textField.name= 'txtName';
            heroIcon_8.addQuiackChild(textField);
            heroIcon_5 = new Sprite();
            heroIcon_5.x = 226;
            heroIcon_5.y = 363;
            heroIcon_5.width = 124;
            heroIcon_5.height = 124;
            this.addQuiackChild(heroIcon_5);
            heroIcon_5.name= 'heroIcon_5';
            texture = assetMgr.getTexture('ui_gongyong_xingyunchoujiangkuang_xuanzhong')
            image = new Image(texture);
            image.name= 'selectMc';
            image.x = -17;
            image.y = -17;
            image.width = 124;
            image.height = 124;
            heroIcon_5.addQuiackChild(image);
            image.touchable = false;
            texture =assetMgr.getTexture('ui_gongyong_90wupingkuang');
            image = new Image(texture);
            image.width = 90;
            image.height = 90;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroIcon_5.addQuiackChild(image);
            texture = assetMgr.getTexture('icon_514')
            image = new Image(texture);
            image.name= 'img';
            image.width = 90;
            image.height = 90;
            heroIcon_5.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_90wupingkuang2')
            image = new Image(texture);
            image.name= 'quaity';
            image.width = 90;
            image.height = 90;
            heroIcon_5.addQuiackChild(image);
            image.touchable = false;
            textField = new TextField(105,24,'','',18,0xFFFFCC,false);
            textField.touchable = false;
            textField.x = -10;
            textField.y = 59;
            textField.hAlign= 'center';
            textField.text= '';
            textField.name= 'txtName';
            heroIcon_5.addQuiackChild(textField);
            heroIcon_2 = new Sprite();
            heroIcon_2.x = 358;
            heroIcon_2.y = 108;
            heroIcon_2.width = 124;
            heroIcon_2.height = 124;
            this.addQuiackChild(heroIcon_2);
            heroIcon_2.name= 'heroIcon_2';
            texture = assetMgr.getTexture('ui_gongyong_xingyunchoujiangkuang_xuanzhong')
            image = new Image(texture);
            image.name= 'selectMc';
            image.x = -17;
            image.y = -17;
            image.width = 124;
            image.height = 124;
            heroIcon_2.addQuiackChild(image);
            image.touchable = false;
            texture =assetMgr.getTexture('ui_gongyong_90wupingkuang');
            image = new Image(texture);
            image.width = 90;
            image.height = 90;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroIcon_2.addQuiackChild(image);
            texture = assetMgr.getTexture('icon_514')
            image = new Image(texture);
            image.name= 'img';
            image.width = 90;
            image.height = 90;
            heroIcon_2.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_90wupingkuang2')
            image = new Image(texture);
            image.name= 'quaity';
            image.width = 90;
            image.height = 90;
            heroIcon_2.addQuiackChild(image);
            image.touchable = false;
            textField = new TextField(105,24,'','',18,0xFFFFCC,false);
            textField.touchable = false;
            textField.x = -10;
            textField.y = 59;
            textField.hAlign= 'center';
            textField.text= '';
            textField.name= 'txtName';
            heroIcon_2.addQuiackChild(textField);
            heroIcon_3 = new Sprite();
            heroIcon_3.x = 358;
            heroIcon_3.y = 232;
            heroIcon_3.width = 124;
            heroIcon_3.height = 124;
            this.addQuiackChild(heroIcon_3);
            heroIcon_3.name= 'heroIcon_3';
            texture = assetMgr.getTexture('ui_gongyong_xingyunchoujiangkuang_xuanzhong')
            image = new Image(texture);
            image.name= 'selectMc';
            image.x = -17;
            image.y = -17;
            image.width = 124;
            image.height = 124;
            heroIcon_3.addQuiackChild(image);
            image.touchable = false;
            texture =assetMgr.getTexture('ui_gongyong_90wupingkuang');
            image = new Image(texture);
            image.width = 90;
            image.height = 90;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroIcon_3.addQuiackChild(image);
            texture = assetMgr.getTexture('icon_514')
            image = new Image(texture);
            image.name= 'img';
            image.width = 90;
            image.height = 90;
            heroIcon_3.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_90wupingkuang2')
            image = new Image(texture);
            image.name= 'quaity';
            image.width = 90;
            image.height = 90;
            heroIcon_3.addQuiackChild(image);
            image.touchable = false;
            textField = new TextField(105,24,'','',18,0xFFFFCC,false);
            textField.touchable = false;
            textField.x = -10;
            textField.y = 59;
            textField.hAlign= 'center';
            textField.text= '';
            textField.name= 'txtName';
            heroIcon_3.addQuiackChild(textField);
            heroIcon_4 = new Sprite();
            heroIcon_4.x = 358;
            heroIcon_4.y = 363;
            heroIcon_4.width = 124;
            heroIcon_4.height = 124;
            this.addQuiackChild(heroIcon_4);
            heroIcon_4.name= 'heroIcon_4';
            texture = assetMgr.getTexture('ui_gongyong_xingyunchoujiangkuang_xuanzhong')
            image = new Image(texture);
            image.name= 'selectMc';
            image.x = -17;
            image.y = -17;
            image.width = 124;
            image.height = 124;
            heroIcon_4.addQuiackChild(image);
            image.touchable = false;
            texture =assetMgr.getTexture('ui_gongyong_90wupingkuang');
            image = new Image(texture);
            image.width = 90;
            image.height = 90;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroIcon_4.addQuiackChild(image);
            texture = assetMgr.getTexture('icon_514')
            image = new Image(texture);
            image.name= 'img';
            image.width = 90;
            image.height = 90;
            heroIcon_4.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_90wupingkuang2')
            image = new Image(texture);
            image.name= 'quaity';
            image.width = 90;
            image.height = 90;
            heroIcon_4.addQuiackChild(image);
            image.touchable = false;
            textField = new TextField(105,24,'','',18,0xFFFFCC,false);
            textField.touchable = false;
            textField.x = -10;
            textField.y = 59;
            textField.hAlign= 'center';
            textField.text= '';
            textField.name= 'txtName';
            heroIcon_4.addQuiackChild(textField);
            texture = assetMgr.getTexture('ui_button_gongyong_big');
            fushBtn = new Button(texture);
            fushBtn.name= 'fushBtn';
            fushBtn.x = 142;
            fushBtn.y = 496;
            fushBtn.width = 260;
            fushBtn.height = 64;
            this.addQuiackChild(fushBtn);
            texture = assetMgr.getTexture('ui_button_gongyong_big');
            buyBtn_0 = new Button(texture);
            buyBtn_0.name= 'buyBtn_0';
            buyBtn_0.x = 568;
            buyBtn_0.y = 280;
            buyBtn_0.width = 280;
            buyBtn_0.height = 64;
            this.addQuiackChild(buyBtn_0);
            texture = assetMgr.getTexture('ui_button_gongyong_big');
            buyBtn_1 = new Button(texture);
            buyBtn_1.name= 'buyBtn_1';
            buyBtn_1.x = 568;
            buyBtn_1.y = 388;
            buyBtn_1.width = 280;
            buyBtn_1.height = 64;
            this.addQuiackChild(buyBtn_1);
            texture = assetMgr.getTexture('ui_button_gongyong_big');
            buyBtn_2 = new Button(texture);
            buyBtn_2.name= 'buyBtn_2';
            buyBtn_2.x = 568;
            buyBtn_2.y = 496;
            buyBtn_2.width = 280;
            buyBtn_2.height = 64;
            this.addQuiackChild(buyBtn_2);
            texture = assetMgr.getTexture('ui_gongyong_hero_pub_9gongge_article');
            var tag_normalRect:Rectangle = new Rectangle(17,19,27,22);
            var tag_normal9ScaleTexture:Scale9Textures = new Scale9Textures(texture,tag_normalRect);
            tag_normal = new Scale9Image(tag_normal9ScaleTexture);
            tag_normal.x = 491;
            tag_normal.y = 100;
            tag_normal.width = 418;
            tag_normal.height = 158;
            this.addQuiackChild(tag_normal);
            fushNum = new TextField(86,31,'','',24,0xFFFFCC,false);
            fushNum.touchable = false;
            fushNum.hAlign= 'left';
            fushNum.text= '99999';
            fushNum.x = 297;
            fushNum.y = 512;
            this.addQuiackChild(fushNum);
            fushTitle = new TextField(59,31,'','',24,0xFFFFCC,false);
            fushTitle.touchable = false;
            fushTitle.hAlign= 'left';
            fushTitle.text= '刷新';
            fushTitle.x = 183;
            fushTitle.y = 512;
            this.addQuiackChild(fushTitle);
            fushTimeTitle = new TextField(113,31,'','',24,0xFFFFCC,false);
            fushTimeTitle.touchable = false;
            fushTimeTitle.hAlign= 'left';
            fushTimeTitle.text= '自动刷新:';
            fushTimeTitle.x = 164;
            fushTimeTitle.y = 573;
            this.addQuiackChild(fushTimeTitle);
            fushTime = new TextField(104,31,'','',24,0xFFFFCC,false);
            fushTime.touchable = false;
            fushTime.hAlign= 'left';
            fushTime.text= '(1:59:34)';
            fushTime.x = 283;
            fushTime.y = 573;
            this.addQuiackChild(fushTime);
            buyTitle_0 = new TextField(103,31,'','',24,0xFFFFCC,false);
            buyTitle_0.touchable = false;
            buyTitle_0.hAlign= 'left';
            buyTitle_0.text= '一键收取';
            buyTitle_0.x = 586;
            buyTitle_0.y = 296;
            this.addQuiackChild(buyTitle_0);
            buyNum_0 = new TextField(86,31,'','',24,0xFFFFCC,false);
            buyNum_0.touchable = false;
            buyNum_0.hAlign= 'left';
            buyNum_0.text= '99999';
            buyNum_0.x = 741;
            buyNum_0.y = 296;
            this.addQuiackChild(buyNum_0);
            buyTitle_1 = new TextField(103,31,'','',24,0xFFFFCC,false);
            buyTitle_1.touchable = false;
            buyTitle_1.hAlign= 'left';
            buyTitle_1.text= '钻石抽取';
            buyTitle_1.x = 587;
            buyTitle_1.y = 404;
            this.addQuiackChild(buyTitle_1);
            buyNum_1 = new TextField(86,31,'','',24,0xFFFFCC,false);
            buyNum_1.touchable = false;
            buyNum_1.hAlign= 'left';
            buyNum_1.text= '99999';
            buyNum_1.x = 742;
            buyNum_1.y = 404;
            this.addQuiackChild(buyNum_1);
            buyTitle_2 = new TextField(103,31,'','',24,0xFFFFCC,false);
            buyTitle_2.touchable = false;
            buyTitle_2.hAlign= 'left';
            buyTitle_2.text= '金币抽取';
            buyTitle_2.x = 587;
            buyTitle_2.y = 512;
            this.addQuiackChild(buyTitle_2);
            buyNum_2 = new TextField(86,31,'','',24,0xFFFFCC,false);
            buyNum_2.touchable = false;
            buyNum_2.hAlign= 'left';
            buyNum_2.text= '99999';
            buyNum_2.x = 742;
            buyNum_2.y = 512;
            this.addQuiackChild(buyNum_2);
            buyTimeTitle = new TextField(150,31,'','',24,0xFFFFCC,false);
            buyTimeTitle.touchable = false;
            buyTimeTitle.hAlign= 'left';
            buyTimeTitle.text= '激活倒计时：';
            buyTimeTitle.x = 601;
            buyTimeTitle.y = 573;
            this.addQuiackChild(buyTimeTitle);
            buyTimeNum = new TextField(104,31,'','',24,0xFFFFCC,false);
            buyTimeNum.touchable = false;
            buyTimeNum.hAlign= 'left';
            buyTimeNum.text= '(1:59:34)';
            buyTimeNum.x = 739;
            buyTimeNum.y = 572;
            this.addQuiackChild(buyTimeNum);
            texture = assetMgr.getTexture('ui_gongyong_zuanshi')
            fushIcon = new Image(texture);
            fushIcon.x = 250;
            fushIcon.y = 506;
            fushIcon.width = 46;
            fushIcon.height = 44;
            this.addQuiackChild(fushIcon);
            fushIcon.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_zuanshi')
            buyIcon_0 = new Image(texture);
            buyIcon_0.x = 694;
            buyIcon_0.y = 290;
            buyIcon_0.width = 46;
            buyIcon_0.height = 44;
            this.addQuiackChild(buyIcon_0);
            buyIcon_0.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_zuanshi')
            buyIcon_1 = new Image(texture);
            buyIcon_1.x = 695;
            buyIcon_1.y = 399;
            buyIcon_1.width = 46;
            buyIcon_1.height = 44;
            this.addQuiackChild(buyIcon_1);
            buyIcon_1.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_money')
            buyIcon_2 = new Image(texture);
            buyIcon_2.x = 695;
            buyIcon_2.y = 507;
            buyIcon_2.width = 40;
            buyIcon_2.height = 40;
            this.addQuiackChild(buyIcon_2);
            buyIcon_2.touchable = false;
            desTxt = new TextField(386,122,'','',20,0xFFFFCC,false);
            desTxt.touchable = false;
            desTxt.hAlign= 'left';
            desTxt.text= '';
            desTxt.x = 507;
            desTxt.y = 120;
            this.addQuiackChild(desTxt);
            leftTmiesTitle = new TextField(192,31,'','',22,0xFFFFCC,false);
            leftTmiesTitle.touchable = false;
            leftTmiesTitle.hAlign= 'left';
            leftTmiesTitle.text= '金币抽取次数：';
            leftTmiesTitle.x = 386;
            leftTmiesTitle.y = 573;
            this.addQuiackChild(leftTmiesTitle);
            leftTmies = new TextField(77,31,'','',24,0xFFFFCC,false);
            leftTmies.touchable = false;
            leftTmies.hAlign= 'left';
            leftTmies.text= '';
            leftTmies.x = 531;
            leftTmies.y = 573;
            this.addQuiackChild(leftTmies);
            init();
        }
        override public function dispose():void
        {
            heroIcon_0.dispose();
            heroIcon_7.dispose();
            heroIcon_6.dispose();
            heroIcon_1.dispose();
            heroIcon_8.dispose();
            heroIcon_5.dispose();
            heroIcon_2.dispose();
            heroIcon_3.dispose();
            heroIcon_4.dispose();
            fushBtn.dispose();
            buyBtn_0.dispose();
            buyBtn_1.dispose();
            buyBtn_2.dispose();
            super.dispose();
        
}
    }
}
