package game.view.viewBase
{
	import starling.display.Image;
	import game.manager.AssetMgr;
	import starling.display.Sprite;
	import starling.textures.Texture;
	import starling.text.TextField;
	import starling.display.Button;
	import flash.geom.Rectangle;
	import com.utils.Constants;
	import feathers.controls.TextInput;
	import feathers.display.Scale9Image;
	import feathers.textures.Scale9Textures;
	import com.dialog.Dialog;

	public class EmailDlgBase extends Dialog
	{
		public var ui_gongyong_di_9gongge38108:Scale9Image;
		public var ui_gongyong_di_9gongge398186:Scale9Image;
		public var txt_title:TextField;
		public var ui_gongyong_di_9gongge398475:Scale9Image;
		public var grid:Scale9Image;
		public var ui_gongyong_di_9gongge398108:Scale9Image;
		public var ui_gongyong_di_9gongge398147:Scale9Image;
		public var goods3:Sprite;
		public var goods2:Sprite;
		public var goods1:Sprite;
		public var txt_des1:TextField;
		public var txt_des2:TextField;
		public var txt_des:TextField;
		public var txt_name:TextField;
		public var txt_sender:TextField;
		public var btn_get:Button;
		public var btn_close:Button;

		public function EmailDlgBase()
		{
			super(false);
			var texture:Texture;
			var textField:TextField;
			var input_txt:TextInput;
			var image:Image;
			var button:Button;
			var assetMgr:AssetMgr=AssetMgr.instance;
			texture=assetMgr.getTexture('ui_wudixingyunxing_xingxing_goumaikuang2');
			image=new Image(texture);
			image.x=80;
			image.y=22;
			image.width=682;
			image.height=555;
			image.smoothing=Constants.NONE;
			this.addQuiackChild(image);
			texture=assetMgr.getTexture('ui_wudixingyunxing_xingxing_goumaikuang1');
			image=new Image(texture);
			image.x=810;
			image.y=22;
			image.width=102;
			image.height=555;
			image.scaleX=-1;
			image.smoothing=Constants.NONE;
			this.addQuiackChild(image);
			texture=assetMgr.getTexture('ui_wudixingyunxing_xingxing_goumaikuang1');
			image=new Image(texture);
			image.y=22;
			image.width=102;
			image.height=555;
			image.smoothing=Constants.NONE;
			this.addQuiackChild(image);
			texture=assetMgr.getTexture('ui_gongyong_di_9gongge');
			var ui_gongyong_di_9gongge38108Rect:Rectangle=new Rectangle(21, 21, 43, 41);
			var ui_gongyong_di_9gongge381089ScaleTexture:Scale9Textures=new Scale9Textures(texture, ui_gongyong_di_9gongge38108Rect);
			ui_gongyong_di_9gongge38108=new Scale9Image(ui_gongyong_di_9gongge381089ScaleTexture);
			ui_gongyong_di_9gongge38108.x=38;
			ui_gongyong_di_9gongge38108.y=108;
			ui_gongyong_di_9gongge38108.width=336;
			ui_gongyong_di_9gongge38108.height=443;
			this.addQuiackChild(ui_gongyong_di_9gongge38108);
			texture=assetMgr.getTexture('ui_Setup_title');
			image=new Image(texture);
			image.x=210;
			image.width=399;
			image.height=104;
			image.touchable=false;
			image.smoothing=Constants.smoothing;
			this.addQuiackChild(image);
			texture=assetMgr.getTexture('ui_gongyong_di_9gongge');
			var ui_gongyong_di_9gongge398186Rect:Rectangle=new Rectangle(21, 21, 43, 41);
			var ui_gongyong_di_9gongge3981869ScaleTexture:Scale9Textures=new Scale9Textures(texture, ui_gongyong_di_9gongge398186Rect);
			ui_gongyong_di_9gongge398186=new Scale9Image(ui_gongyong_di_9gongge3981869ScaleTexture);
			ui_gongyong_di_9gongge398186.x=398;
			ui_gongyong_di_9gongge398186.y=186;
			ui_gongyong_di_9gongge398186.width=372;
			ui_gongyong_di_9gongge398186.height=277;
			this.addQuiackChild(ui_gongyong_di_9gongge398186);
			txt_title=new TextField(294, 41, '', '', 28, 0x3D3125, false);
			txt_title.touchable=false;
			txt_title.hAlign='center';
			txt_title.text='邮箱';
			txt_title.x=262;
			txt_title.y=21;
			this.addQuiackChild(txt_title);
			texture=assetMgr.getTexture('ui_gongyong_di_9gongge');
			var ui_gongyong_di_9gongge398475Rect:Rectangle=new Rectangle(21, 21, 43, 41);
			var ui_gongyong_di_9gongge3984759ScaleTexture:Scale9Textures=new Scale9Textures(texture, ui_gongyong_di_9gongge398475Rect);
			ui_gongyong_di_9gongge398475=new Scale9Image(ui_gongyong_di_9gongge3984759ScaleTexture);
			ui_gongyong_di_9gongge398475.x=398;
			ui_gongyong_di_9gongge398475.y=475;
			ui_gongyong_di_9gongge398475.width=372;
			ui_gongyong_di_9gongge398475.height=78;
			this.addQuiackChild(ui_gongyong_di_9gongge398475);
			texture=assetMgr.getTexture('ui_gongyong_jiugonggedi1');
			var gridRect:Rectangle=new Rectangle(12, 12, 23, 23);
			var grid9ScaleTexture:Scale9Textures=new Scale9Textures(texture, gridRect);
			grid=new Scale9Image(grid9ScaleTexture);
			grid.x=404;
			grid.y=354;
			grid.width=359;
			grid.height=103;
			this.addQuiackChild(grid);
			texture=assetMgr.getTexture('ui_gongyong_di_9gongge');
			var ui_gongyong_di_9gongge398108Rect:Rectangle=new Rectangle(21, 21, 43, 41);
			var ui_gongyong_di_9gongge3981089ScaleTexture:Scale9Textures=new Scale9Textures(texture, ui_gongyong_di_9gongge398108Rect);
			ui_gongyong_di_9gongge398108=new Scale9Image(ui_gongyong_di_9gongge3981089ScaleTexture);
			ui_gongyong_di_9gongge398108.x=398;
			ui_gongyong_di_9gongge398108.y=108;
			ui_gongyong_di_9gongge398108.width=372;
			ui_gongyong_di_9gongge398108.height=34;
			this.addQuiackChild(ui_gongyong_di_9gongge398108);
			texture=assetMgr.getTexture('ui_gongyong_di_9gongge');
			var ui_gongyong_di_9gongge398147Rect:Rectangle=new Rectangle(21, 21, 43, 41);
			var ui_gongyong_di_9gongge3981479ScaleTexture:Scale9Textures=new Scale9Textures(texture, ui_gongyong_di_9gongge398147Rect);
			ui_gongyong_di_9gongge398147=new Scale9Image(ui_gongyong_di_9gongge3981479ScaleTexture);
			ui_gongyong_di_9gongge398147.x=398;
			ui_gongyong_di_9gongge398147.y=147;
			ui_gongyong_di_9gongge398147.width=372;
			ui_gongyong_di_9gongge398147.height=34;
			this.addQuiackChild(ui_gongyong_di_9gongge398147);
			goods3=new Sprite();
			goods3.x=650;
			goods3.y=361;
			goods3.width=90;
			goods3.height=90;
			this.addQuiackChild(goods3);
			goods3.name='goods3';
			texture=assetMgr.getTexture('ui_gongyong_90wupingkuang');
			image=new Image(texture);
			image.width=90;
			image.height=90;
			image.touchable=false;
			image.smoothing=Constants.smoothing;
			goods3.addQuiackChild(image);
			texture=assetMgr.getTexture('ui_button_mail')
			image=new Image(texture);
			image.name='icon';
			image.width=89;
			image.height=89;
			goods3.addQuiackChild(image);
			image.touchable=false;
			texture=assetMgr.getTexture('ui_gongyong_90wupingkuang0');
			button=new Button(texture);
			button.name='box';
			button.width=90;
			button.height=90;
			goods3.addQuiackChild(button);
			textField=new TextField(78, 28, '', '', 21, 0xFFFFFF, false);
			textField.touchable=false;
			textField.x=1;
			textField.y=58;
			textField.hAlign='right';
			textField.text='';
			textField.name='txt_num';
			goods3.addQuiackChild(textField);
			goods2=new Sprite();
			goods2.x=540;
			goods2.y=361;
			goods2.width=90;
			goods2.height=90;
			this.addQuiackChild(goods2);
			goods2.name='goods2';
			texture=assetMgr.getTexture('ui_gongyong_90wupingkuang');
			image=new Image(texture);
			image.width=90;
			image.height=90;
			image.touchable=false;
			image.smoothing=Constants.smoothing;
			goods2.addQuiackChild(image);
			texture=assetMgr.getTexture('ui_button_mail')
			image=new Image(texture);
			image.name='icon';
			image.width=89;
			image.height=89;
			goods2.addQuiackChild(image);
			image.touchable=false;
			texture=assetMgr.getTexture('ui_gongyong_90wupingkuang0');
			button=new Button(texture);
			button.name='box';
			button.width=90;
			button.height=90;
			goods2.addQuiackChild(button);
			textField=new TextField(78, 28, '', '', 21, 0xFFFFFF, false);
			textField.touchable=false;
			textField.x=1;
			textField.y=58;
			textField.hAlign='right';
			textField.text='';
			textField.name='txt_num';
			goods2.addQuiackChild(textField);
			goods1=new Sprite();
			goods1.x=430;
			goods1.y=361;
			goods1.width=90;
			goods1.height=90;
			this.addQuiackChild(goods1);
			goods1.name='goods1';
			texture=assetMgr.getTexture('ui_gongyong_90wupingkuang');
			image=new Image(texture);
			image.width=90;
			image.height=90;
			image.touchable=false;
			image.smoothing=Constants.smoothing;
			goods1.addQuiackChild(image);
			texture=assetMgr.getTexture('ui_button_mail')
			image=new Image(texture);
			image.name='icon';
			image.width=89;
			image.height=89;
			goods1.addQuiackChild(image);
			image.touchable=false;
			texture=assetMgr.getTexture('ui_gongyong_90wupingkuang0');
			button=new Button(texture);
			button.name='box';
			button.width=90;
			button.height=90;
			goods1.addQuiackChild(button);
			textField=new TextField(78, 28, '', '', 21, 0xFFFFFF, false);
			textField.touchable=false;
			textField.x=1;
			textField.y=58;
			textField.hAlign='right';
			textField.text='';
			textField.name='txt_num';
			goods1.addQuiackChild(textField);
			txt_des1=new TextField(115, 36, '', '', 22, 0xF4D6B2, false);
			txt_des1.touchable=false;
			txt_des1.hAlign='left';
			txt_des1.text='主   题：';
			txt_des1.x=407;
			txt_des1.y=106;
			this.addQuiackChild(txt_des1);
			txt_des2=new TextField(116, 36, '', '', 22, 0xF4D6B2, false);
			txt_des2.touchable=false;
			txt_des2.hAlign='left';
			txt_des2.text='发件人：';
			txt_des2.x=407;
			txt_des2.y=146;
			this.addQuiackChild(txt_des2);
			txt_des=new TextField(350, 161, '', '', 22, 0xFFFFFF, false);
			txt_des.touchable=false;
			txt_des.hAlign='left';
			txt_des.text='';
			txt_des.x=407;
			txt_des.y=190;
			this.addQuiackChild(txt_des);
			txt_name=new TextField(263, 36, '', '', 22, 0xF4D6B2, false);
			txt_name.touchable=false;
			txt_name.hAlign='center';
			txt_name.text='';
			txt_name.x=493;
			txt_name.y=106;
			this.addQuiackChild(txt_name);
			txt_sender=new TextField(262, 36, '', '', 22, 0xF4D6B2, false);
			txt_sender.touchable=false;
			txt_sender.hAlign='center';
			txt_sender.text='';
			txt_sender.x=495;
			txt_sender.y=146;
			this.addQuiackChild(txt_sender);
			texture=assetMgr.getTexture('ui_button_gongyong_big');
			btn_get=new Button(texture);
			btn_get.name='btn_get';
			btn_get.x=415;
			btn_get.y=480;
			btn_get.width=340;
			btn_get.height=64;
			this.addQuiackChild(btn_get);
			texture=assetMgr.getTexture('ui_Buyingdiamond_button_guanbi');
			btn_close=new Button(texture);
			btn_close.name='btn_close';
			btn_close.x=747;
			btn_close.y=44;
			btn_close.width=61;
			btn_close.height=60;
			this.addQuiackChild(btn_close);
			init();
		}

		override public function dispose():void
		{
			goods3.dispose();
			goods2.dispose();
			goods1.dispose();
			btn_get.dispose();
			btn_close.dispose();
			super.dispose();

		}
	}
}
