package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.view.View;

    public class EngageViewBase extends View
    {
        public var tag_normal:Scale9Image;
        public var text_Competence:TextField;
        public var text_heroName:TextField;
        public var text_expert:TextField;
        public var text_HabitWeapon:TextField;
        public var text_heroPresent:TextField;
        public var text_heroInfo:TextField;
        public var text_heroSkill:TextField;
        public var text_expertValue:TextField;
        public var text_HabitWeaponValue:TextField;
        public var heroIcon:Image;
        public var heroSkill_1:Button;
        public var heroPanel:Sprite;
        public var heroSkill_0:Button;
        public var heroSkill_2:Button;
        public var btn_diamond:Button;
        public var tipsText:TextField;
        public var text_num:TextField;
        public var icon:Image;

        public function EngageViewBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            var assetMgr:AssetMgr = AssetMgr.instance;
            texture =assetMgr.getTexture('ui_wudixingyunxing_xingxing_goumaikuang1');
            image = new Image(texture);
            image.x = 346;
            image.y = 85;
            image.width = 102;
            image.height = 391;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_wudixingyunxing_xingxing_goumaikuang2');
            image = new Image(texture);
            image.x = 447;
            image.y = 85;
            image.width = 373;
            image.height = 391;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_wudixingyunxing_xingxing_goumaikuang1');
            image = new Image(texture);
            image.x = 916;
            image.y = 85;
            image.width = 102;
            image.height = 391;
            image.scaleX = -1;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_hero_pub_9gongge_article');
            var tag_normalRect:Rectangle = new Rectangle(17,19,27,22);
            var tag_normal9ScaleTexture:Scale9Textures = new Scale9Textures(texture,tag_normalRect);
            tag_normal = new Scale9Image(tag_normal9ScaleTexture);
            tag_normal.x = 16;
            tag_normal.y = 530;
            tag_normal.width = 298;
            tag_normal.height = 90;
            this.addQuiackChild(tag_normal);
            text_Competence = new TextField(273,61,'','',21,0xFFFFCC,false);
            text_Competence.touchable = false;
            text_Competence.hAlign= 'left';
            text_Competence.text= '这是英雄在第{0}关卡得到的';
            text_Competence.x = 31;
            text_Competence.y = 543;
            this.addQuiackChild(text_Competence);
            texture =assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian_xiao_di');
            image = new Image(texture);
            image.x = 357;
            image.y = 496;
            image.width = 550;
            image.height = 110;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou1');
            image = new Image(texture);
            image.x = 905;
            image.y = 481;
            image.width = 540;
            image.height = 21;
            image.scaleX = -6.7488861083984375;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou1');
            image = new Image(texture);
            image.x = 905;
            image.y = 603;
            image.width = 540;
            image.height = 21;
            image.scaleX = -6.7488861083984375;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_hero_kuang_zhuangshi');
            image = new Image(texture);
            image.x = 874;
            image.y = 476;
            image.width = 71;
            image.height = 148;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_hero_kuang_zhuangshi');
            image = new Image(texture);
            image.x = 389;
            image.y = 477;
            image.width = 71;
            image.height = 148;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_atlas_bottom');
            image = new Image(texture);
            image.x = 432;
            image.y = 140;
            image.width = 108;
            image.height = 112;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            text_heroName = new TextField(148,31,'','',24,0xFFFFCC,false);
            text_heroName.touchable = false;
            text_heroName.hAlign= 'center';
            text_heroName.text= '英雄名';
            text_heroName.x = 413;
            text_heroName.y = 263;
            this.addQuiackChild(text_heroName);
            text_expert = new TextField(120,31,'','',24,0xFFFFCC,false);
            text_expert.touchable = false;
            text_expert.hAlign= 'left';
            text_expert.text= '擅长位置:';
            text_expert.x = 378;
            text_expert.y = 314;
            this.addQuiackChild(text_expert);
            text_HabitWeapon = new TextField(122,31,'','',24,0xFFFFCC,false);
            text_HabitWeapon.touchable = false;
            text_HabitWeapon.hAlign= 'left';
            text_HabitWeapon.text= '惯用武器:';
            text_HabitWeapon.x = 378;
            text_HabitWeapon.y = 356;
            this.addQuiackChild(text_HabitWeapon);
            text_heroPresent = new TextField(148,31,'','',24,0xCCFF00,false);
            text_heroPresent.touchable = false;
            text_heroPresent.hAlign= 'center';
            text_heroPresent.text= '英雄介绍';
            text_heroPresent.x = 668;
            text_heroPresent.y = 119;
            this.addQuiackChild(text_heroPresent);
            text_heroInfo = new TextField(307,143,'','',23,0xFFFFCC,false);
            text_heroInfo.touchable = false;
            text_heroInfo.hAlign= 'left';
            text_heroInfo.text= '啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊';
            text_heroInfo.x = 593;
            text_heroInfo.y = 160;
            this.addQuiackChild(text_heroInfo);
            text_heroSkill = new TextField(148,31,'','',24,0x00FF33,false);
            text_heroSkill.touchable = false;
            text_heroSkill.hAlign= 'center';
            text_heroSkill.text= '英雄技能';
            text_heroSkill.x = 671;
            text_heroSkill.y = 309;
            this.addQuiackChild(text_heroSkill);
            text_expertValue = new TextField(104,31,'','',24,0xFFFFCC,false);
            text_expertValue.touchable = false;
            text_expertValue.hAlign= 'left';
            text_expertValue.text= '擅长位置';
            text_expertValue.x = 488;
            text_expertValue.y = 314;
            this.addQuiackChild(text_expertValue);
            text_HabitWeaponValue = new TextField(104,31,'','',24,0xFFFFCC,false);
            text_HabitWeaponValue.touchable = false;
            text_HabitWeaponValue.hAlign= 'left';
            text_HabitWeaponValue.text= '擅长位置';
            text_HabitWeaponValue.x = 488;
            text_HabitWeaponValue.y = 357;
            this.addQuiackChild(text_HabitWeaponValue);
            texture = assetMgr.getTexture('photo_504')
            heroIcon = new Image(texture);
            heroIcon.x = 435;
            heroIcon.y = 146;
            heroIcon.width = 100;
            heroIcon.height = 100;
            this.addQuiackChild(heroIcon);
            heroIcon.touchable = false;
            texture = assetMgr.getTexture('icon_skill_1');
            heroSkill_1 = new Button(texture);
            heroSkill_1.name= 'heroSkill_1';
            heroSkill_1.x = 711;
            heroSkill_1.y = 354;
            heroSkill_1.width = 80;
            heroSkill_1.height = 80;
            this.addQuiackChild(heroSkill_1);
            heroPanel = new Sprite();
            heroPanel.x = 27;
            heroPanel.y = 85;
            heroPanel.width = 289;
            heroPanel.height = 377;
            this.addQuiackChild(heroPanel);
            heroPanel.name= 'heroPanel';
            texture = assetMgr.getTexture('ui_yingxiongkapaiguang_0_1')
            image = new Image(texture);
            image.name= 'effectbg_3';
            image.x = 1;
            image.y = 373;
            image.width = 287;
            image.height = 36;
            image.scaleY = -1;
            heroPanel.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_yingxiongkapaiguang_0_1')
            image = new Image(texture);
            image.name= 'effectbg_1';
            image.x = 1;
            image.width = 287;
            image.height = 36;
            heroPanel.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_yingxiongkapaiguang_0_2')
            image = new Image(texture);
            image.name= 'effectbg_2';
            image.x = 1;
            image.y = 36;
            image.width = 287;
            image.height = 302;
            heroPanel.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_yingxiong_beijing')
            image = new Image(texture);
            image.name= 'bg';
            image.x = 1;
            image.y = 8;
            image.width = 287;
            image.height = 368;
            heroPanel.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_yingxiongjiuguan_xinkapai')
            image = new Image(texture);
            image.name= 'kuang';
            image.x = -1;
            image.y = -1;
            image.width = 287;
            image.height = 368;
            heroPanel.addQuiackChild(image);
            image.touchable = false;
            texture =assetMgr.getTexture('ui_yingxiongkapai_yingxiongmingdi');
            image = new Image(texture);
            image.x = 14;
            image.y = 29;
            image.width = 255;
            image.height = 59;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            heroPanel.addQuiackChild(image);
            textField = new TextField(151,36,'','',24,0xFFFFCC,false);
            textField.touchable = false;
            textField.x = 68;
            textField.y = 36;
            textField.hAlign= 'center';
            textField.text= '英雄名称';
            textField.name= 'heroName';
            heroPanel.addQuiackChild(textField);
            texture = assetMgr.getTexture('ui_gongyong_kapaiyuansu1')
            image = new Image(texture);
            image.name= 'yuan1';
            image.x = 3;
            image.y = 300;
            image.width = 70;
            image.height = 70;
            heroPanel.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_kapaiyuansu1')
            image = new Image(texture);
            image.name= 'yuan2';
            image.x = 216;
            image.y = 300;
            image.width = 70;
            image.height = 70;
            heroPanel.addQuiackChild(image);
            image.touchable = false;
            textField = new TextField(44,44,'','',24,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 14;
            textField.y = 312;
            textField.hAlign= 'center';
            textField.text= '65';
            textField.name= 'textLv';
            heroPanel.addQuiackChild(textField);
            texture = assetMgr.getTexture('icon_skill_1');
            heroSkill_0 = new Button(texture);
            heroSkill_0.name= 'heroSkill_0';
            heroSkill_0.x = 613;
            heroSkill_0.y = 354;
            heroSkill_0.width = 80;
            heroSkill_0.height = 80;
            this.addQuiackChild(heroSkill_0);
            texture = assetMgr.getTexture('icon_skill_1');
            heroSkill_2 = new Button(texture);
            heroSkill_2.name= 'heroSkill_2';
            heroSkill_2.x = 808;
            heroSkill_2.y = 354;
            heroSkill_2.width = 80;
            heroSkill_2.height = 80;
            this.addQuiackChild(heroSkill_2);
            texture = assetMgr.getTexture('ui_button_gongyong_big');
            btn_diamond = new Button(texture);
            btn_diamond.name= 'btn_diamond';
            btn_diamond.x = 37;
            btn_diamond.y = 461;
            btn_diamond.width = 260;
            btn_diamond.height = 64;
            this.addQuiackChild(btn_diamond);
            tipsText = new TextField(227,31,'','',24,0xFFFFCC,false);
            tipsText.touchable = false;
            tipsText.hAlign= 'center';
            tipsText.text= '';
            tipsText.x = 52;
            tipsText.y = 476;
            this.addQuiackChild(tipsText);
            text_num = new TextField(125,31,'','',24,0xFFFFCC,false);
            text_num.touchable = false;
            text_num.hAlign= 'left';
            text_num.text= '';
            text_num.x = 152;
            text_num.y = 477;
            this.addQuiackChild(text_num);
            texture = assetMgr.getTexture('ui_gongyong_money')
            icon = new Image(texture);
            icon.x = 104;
            icon.y = 472;
            icon.width = 40;
            icon.height = 40;
            this.addQuiackChild(icon);
            icon.touchable = false;
            init();
        }
        override public function dispose():void
        {
            heroSkill_1.dispose();
            heroPanel.dispose();
            heroSkill_0.dispose();
            heroSkill_2.dispose();
            btn_diamond.dispose();
            super.dispose();
        
}
    }
}
