package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.controls.List;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.view.View;

    public class EquimentViewBase extends View
    {
        public var ui_gongyong_di_9gongge636157:Scale9Image;
        public var ui_Setup_button_switch358194:Scale9Image;
        public var effectbg_1:Image;
        public var effectbg_3:Image;
        public var effectbg_2:Image;
        public var kuang:Image;
        public var skillIcon_1:Sprite;
        public var skillIcon_2:Sprite;
        public var skillIcon_3:Sprite;
        public var par:Image;
        public var txt_rate:TextField;
        public var heroName:TextField;
        public var btn_blacksmith:Button;
        public var btn_atuo:Button;
        public var fieldView:Sprite;
        public var lable1:TextField;
        public var lable2:TextField;
        public var list_equip:List;
        public var list_exp:List;
        public var btn_equip5:Button;
        public var ico_equipDi:Image;
        public var ico_equip5:Image;
        public var ico_quality5:Button;
        public var equip_title:Image;
        public var tag_add:Image;
        public var txt_heroName:TextField;
        public var upgradeBtn:Button;
        public var textLv:TextField;

        public function EquimentViewBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            var assetMgr:AssetMgr = AssetMgr.instance;
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou2');
            image = new Image(texture);
            image.x = 930;
            image.y = 140;
            image.width = 26;
            image.height = 292;
            image.scaleX = -1;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_di_9gongge');
            var ui_gongyong_di_9gongge636157Rect:Rectangle = new Rectangle(21,21,43,41);
            var ui_gongyong_di_9gongge6361579ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_gongyong_di_9gongge636157Rect);
            ui_gongyong_di_9gongge636157 = new Scale9Image(ui_gongyong_di_9gongge6361579ScaleTexture);
            ui_gongyong_di_9gongge636157.x = 636;
            ui_gongyong_di_9gongge636157.y = 157;
            ui_gongyong_di_9gongge636157.width = 278;
            ui_gongyong_di_9gongge636157.height = 260;
            this.addQuiackChild(ui_gongyong_di_9gongge636157);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou1');
            image = new Image(texture);
            image.x = 51;
            image.y = 148;
            image.width = 284;
            image.height = 24;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou2');
            image = new Image(texture);
            image.x = 32;
            image.y = 171;
            image.width = 26;
            image.height = 262;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 28;
            image.y = 147;
            image.width = 38;
            image.height = 34;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou1');
            image = new Image(texture);
            image.x = 51;
            image.y = 448;
            image.width = 861;
            image.height = 24;
            image.scaleY = -1;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 28;
            image.y = 449;
            image.width = 38;
            image.height = 34;
            image.scaleY = -1;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou2');
            image = new Image(texture);
            image.x = 340;
            image.y = 170;
            image.width = 26;
            image.height = 262;
            image.scaleX = -1;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 344;
            image.y = 146;
            image.width = 38;
            image.height = 34;
            image.scaleX = -1;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 345;
            image.y = 449;
            image.width = 38;
            image.height = 34;
            image.scaleX = -1;
            image.scaleY = -1;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou1');
            image = new Image(texture);
            image.x = 651;
            image.y = 123;
            image.width = 264;
            image.height = 24;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 933;
            image.y = 449;
            image.width = 38;
            image.height = 34;
            image.scaleX = -1;
            image.scaleY = -1;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_kuang_paizi2');
            image = new Image(texture);
            image.x = 114;
            image.y = 126;
            image.width = 138;
            image.height = 61;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_kuang_paizi1');
            image = new Image(texture);
            image.x = 241;
            image.y = 126;
            image.width = 61;
            image.height = 61;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_kuang_paizi1');
            image = new Image(texture);
            image.x = 134;
            image.y = 126;
            image.width = 61;
            image.height = 61;
            image.scaleX = -1;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou2');
            image = new Image(texture);
            image.x = 617;
            image.y = 145;
            image.width = 26;
            image.height = 282;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 613;
            image.y = 122;
            image.width = 38;
            image.height = 34;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_Setup_button_switch3');
            var ui_Setup_button_switch358194Rect:Rectangle = new Rectangle(14,20,180,69);
            var ui_Setup_button_switch3581949ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_Setup_button_switch358194Rect);
            ui_Setup_button_switch358194 = new Scale9Image(ui_Setup_button_switch3581949ScaleTexture);
            ui_Setup_button_switch358194.x = 58;
            ui_Setup_button_switch358194.y = 194;
            ui_Setup_button_switch358194.width = 255;
            ui_Setup_button_switch358194.height = 223;
            this.addQuiackChild(ui_Setup_button_switch358194);
            texture = assetMgr.getTexture('ui_yingxiongkapaiguang_0_1')
            effectbg_1 = new Image(texture);
            effectbg_1.x = 336;
            effectbg_1.y = 128;
            effectbg_1.width = 287;
            effectbg_1.height = 36;
            this.addQuiackChild(effectbg_1);
            effectbg_1.touchable = false;
            texture = assetMgr.getTexture('ui_yingxiongkapaiguang_0_1')
            effectbg_3 = new Image(texture);
            effectbg_3.x = 331;
            effectbg_3.y = 465;
            effectbg_3.width = 287;
            effectbg_3.height = 36;
            this.addQuiackChild(effectbg_3);
            effectbg_3.touchable = false;
            texture = assetMgr.getTexture('ui_yingxiongkapaiguang_0_2')
            effectbg_2 = new Image(texture);
            effectbg_2.x = 336;
            effectbg_2.y = 154;
            effectbg_2.width = 287;
            effectbg_2.height = 315;
            this.addQuiackChild(effectbg_2);
            effectbg_2.touchable = false;
            texture =assetMgr.getTexture('ui_yingxiong_beijing');
            image = new Image(texture);
            image.x = 336;
            image.y = 117;
            image.width = 287;
            image.height = 368;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_yingxiongjiuguan_xinkapai')
            kuang = new Image(texture);
            kuang.x = 335;
            kuang.y = 127;
            kuang.width = 287;
            kuang.height = 368;
            this.addQuiackChild(kuang);
            kuang.touchable = false;
            skillIcon_1 = new Sprite();
            skillIcon_1.x = 52;
            skillIcon_1.y = 408;
            skillIcon_1.width = 100;
            skillIcon_1.height = 110;
            this.addQuiackChild(skillIcon_1);
            skillIcon_1.name= 'skillIcon_1';
            texture = assetMgr.getTexture('icon_skill_1')
            image = new Image(texture);
            image.name= 'skillIcon';
            image.width = 80;
            image.height = 80;
            skillIcon_1.addQuiackChild(image);
            image.touchable = false;
            texture =assetMgr.getTexture('ui_hero_icon_kuang');
            image = new Image(texture);
            image.x = -10;
            image.y = -6;
            image.width = 100;
            image.height = 110;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            skillIcon_1.addQuiackChild(image);
            skillIcon_2 = new Sprite();
            skillIcon_2.x = 147;
            skillIcon_2.y = 408;
            skillIcon_2.width = 100;
            skillIcon_2.height = 110;
            this.addQuiackChild(skillIcon_2);
            skillIcon_2.name= 'skillIcon_2';
            texture = assetMgr.getTexture('icon_skill_1')
            image = new Image(texture);
            image.name= 'skillIcon';
            image.width = 80;
            image.height = 80;
            skillIcon_2.addQuiackChild(image);
            image.touchable = false;
            texture =assetMgr.getTexture('ui_hero_icon_kuang');
            image = new Image(texture);
            image.x = -10;
            image.y = -6;
            image.width = 100;
            image.height = 110;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            skillIcon_2.addQuiackChild(image);
            skillIcon_3 = new Sprite();
            skillIcon_3.x = 242;
            skillIcon_3.y = 408;
            skillIcon_3.width = 100;
            skillIcon_3.height = 110;
            this.addQuiackChild(skillIcon_3);
            skillIcon_3.name= 'skillIcon_3';
            texture = assetMgr.getTexture('icon_skill_1')
            image = new Image(texture);
            image.name= 'skillIcon';
            image.width = 80;
            image.height = 80;
            skillIcon_3.addQuiackChild(image);
            image.touchable = false;
            texture =assetMgr.getTexture('ui_hero_icon_kuang');
            image = new Image(texture);
            image.x = -10;
            image.y = -6;
            image.width = 100;
            image.height = 110;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            skillIcon_3.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 934;
            image.y = 122;
            image.width = 38;
            image.height = 34;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_jingyantiao_baidi');
            image = new Image(texture);
            image.x = 364;
            image.y = 453;
            image.width = 180;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_jingyantiao_baidi1')
            par = new Image(texture);
            par.x = 389;
            par.y = 461;
            par.width = 145;
            par.height = 15;
            this.addQuiackChild(par);
            par.touchable = false;
            txt_rate = new TextField(62,24,'','',16,0xFFFF00,false);
            txt_rate.touchable = false;
            txt_rate.hAlign= 'center';
            txt_rate.text= '100％';
            txt_rate.x = 460;
            txt_rate.y = 459;
            this.addQuiackChild(txt_rate);
            heroName = new TextField(151,31,'','',24,0xFFFFCC,false);
            heroName.touchable = false;
            heroName.hAlign= 'center';
            heroName.text= '';
            heroName.x = 111;
            heroName.y = 141;
            this.addQuiackChild(heroName);
            texture = assetMgr.getTexture('ui_button_tiebaomutouanjian');
            btn_blacksmith = new Button(texture);
            btn_blacksmith.name= 'btn_blacksmith';
            btn_blacksmith.x = 649;
            btn_blacksmith.y = 452;
            btn_blacksmith.width = 126;
            btn_blacksmith.height = 55;
            this.addQuiackChild(btn_blacksmith);
            texture = assetMgr.getTexture('ui_button_tiebaomutouanjian');
            btn_atuo = new Button(texture);
            btn_atuo.name= 'btn_atuo';
            btn_atuo.x = 797;
            btn_atuo.y = 452;
            btn_atuo.width = 126;
            btn_atuo.height = 55;
            this.addQuiackChild(btn_atuo);
            fieldView = new Sprite();
            fieldView.x = 64;
            fieldView.y = 211;
            fieldView.width = 242;
            fieldView.height = 194;
            this.addQuiackChild(fieldView);
            fieldView.name= 'fieldView';
            texture =assetMgr.getTexture('ui_gongyong_shuxingwenzidi');
            image = new Image(texture);
            image.x = 44;
            image.y = 3;
            image.width = 172;
            image.height = 27;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            fieldView.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_shuxingwenzidi');
            image = new Image(texture);
            image.x = 44;
            image.y = 43;
            image.width = 172;
            image.height = 27;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            fieldView.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_tubiao_xueliangtubiao');
            image = new Image(texture);
            image.x = 27;
            image.y = 42;
            image.width = 34;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            fieldView.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_tubiao_gongjilitubiao');
            image = new Image(texture);
            image.x = 34;
            image.width = 20;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            fieldView.addQuiackChild(image);
            textField = new TextField(81,28,'','',18,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 39;
            textField.y = 81;
            textField.hAlign= 'center';
            textField.text= '9';
            textField.name= 'defendValue';
            fieldView.addQuiackChild(textField);
            textField = new TextField(81,28,'','',18,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 39;
            textField.y = 109;
            textField.hAlign= 'center';
            textField.text= '99';
            textField.name= 'hitValue';
            fieldView.addQuiackChild(textField);
            textField = new TextField(81,28,'','',18,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 39;
            textField.y = 137;
            textField.hAlign= 'center';
            textField.text= '9999';
            textField.name= 'critValue';
            fieldView.addQuiackChild(textField);
            textField = new TextField(81,28,'','',18,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 39;
            textField.y = 166;
            textField.hAlign= 'center';
            textField.text= '999999';
            textField.name= 'anitCritValue';
            fieldView.addQuiackChild(textField);
            textField = new TextField(81,28,'','',18,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 161;
            textField.y = 81;
            textField.hAlign= 'center';
            textField.text= '9';
            textField.name= 'punctureValue';
            fieldView.addQuiackChild(textField);
            textField = new TextField(81,28,'','',18,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 161;
            textField.y = 109;
            textField.hAlign= 'center';
            textField.text= '99';
            textField.name= 'dodgeValue';
            fieldView.addQuiackChild(textField);
            textField = new TextField(81,28,'','',18,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 161;
            textField.y = 137;
            textField.hAlign= 'center';
            textField.text= '9999';
            textField.name= 'critPercentageValue';
            fieldView.addQuiackChild(textField);
            textField = new TextField(81,28,'','',18,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 161;
            textField.y = 166;
            textField.hAlign= 'center';
            textField.text= '999999';
            textField.name= 'toughnessValue';
            fieldView.addQuiackChild(textField);
            textField = new TextField(180,31,'','',22,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 36;
            textField.y = 43;
            textField.hAlign= 'center';
            textField.text= '9999999';
            textField.name= 'hpValue';
            fieldView.addQuiackChild(textField);
            textField = new TextField(180,31,'','',22,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 38;
            textField.y = 3;
            textField.hAlign= 'center';
            textField.text= '9';
            textField.name= 'attackValue';
            fieldView.addQuiackChild(textField);
            textField = new TextField(60,28,'','',18,0xFFFFFF,false);
            textField.touchable = false;
            textField.y = 81;
            textField.hAlign= 'left';
            textField.text= '防御：';
            textField.name= 'defend';
            fieldView.addQuiackChild(textField);
            textField = new TextField(60,28,'','',18,0xFFFFFF,false);
            textField.touchable = false;
            textField.y = 109;
            textField.hAlign= 'left';
            textField.text= '命中：';
            textField.name= 'hit';
            fieldView.addQuiackChild(textField);
            textField = new TextField(60,28,'','',18,0xFFFFFF,false);
            textField.touchable = false;
            textField.y = 166;
            textField.hAlign= 'left';
            textField.text= '免爆：';
            textField.name= 'anitCrit';
            fieldView.addQuiackChild(textField);
            textField = new TextField(60,28,'','',18,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 121;
            textField.y = 80;
            textField.hAlign= 'left';
            textField.text= '穿刺：';
            textField.name= 'puncture';
            fieldView.addQuiackChild(textField);
            textField = new TextField(60,28,'','',18,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 121;
            textField.y = 109;
            textField.hAlign= 'center';
            textField.text= '闪避：';
            textField.name= 'dodge';
            fieldView.addQuiackChild(textField);
            textField = new TextField(60,28,'','',18,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 122;
            textField.y = 138;
            textField.hAlign= 'center';
            textField.text= '暴强：';
            textField.name= 'critPercentage';
            fieldView.addQuiackChild(textField);
            textField = new TextField(60,28,'','',18,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 121;
            textField.y = 166;
            textField.hAlign= 'center';
            textField.text= '韧性：';
            textField.name= 'toughness';
            fieldView.addQuiackChild(textField);
            textField = new TextField(60,28,'','',18,0xFFFFFF,false);
            textField.touchable = false;
            textField.y = 139;
            textField.hAlign= 'left';
            textField.text= '暴击：';
            textField.name= 'crit';
            fieldView.addQuiackChild(textField);
            lable1 = new TextField(102,31,'','',24,0xFFFFCC,false);
            lable1.touchable = false;
            lable1.hAlign= 'center';
            lable1.text= '';
            lable1.x = 658;
            lable1.y = 462;
            this.addQuiackChild(lable1);
            lable2 = new TextField(102,31,'','',24,0xFFFFCC,false);
            lable2.touchable = false;
            lable2.hAlign= 'center';
            lable2.text= '';
            lable2.x = 807;
            lable2.y = 463;
            this.addQuiackChild(lable2);
            list_equip = new List();
            list_equip.x = 639;
            list_equip.y = 164;
            list_equip.width = 267;
            list_equip.height = 243;
            this.addQuiackChild(list_equip);
            list_exp = new List();
            list_exp.x = 639;
            list_exp.y = 164;
            list_exp.width = 267;
            list_exp.height = 243;
            this.addQuiackChild(list_exp);
            texture = assetMgr.getTexture('ui_hero_chenghaozhuangbei_kuang');
            btn_equip5 = new Button(texture);
            btn_equip5.name= 'btn_equip5';
            btn_equip5.x = 720;
            btn_equip5.y = 238;
            btn_equip5.width = 105;
            btn_equip5.height = 103;
            this.addQuiackChild(btn_equip5);
            texture = assetMgr.getTexture('ui_gongyong_90wupingkuang')
            ico_equipDi = new Image(texture);
            ico_equipDi.x = 729;
            ico_equipDi.y = 247;
            ico_equipDi.width = 90;
            ico_equipDi.height = 90;
            this.addQuiackChild(ico_equipDi);
            ico_equipDi.touchable = false;
            texture = assetMgr.getTexture('icon_300010')
            ico_equip5 = new Image(texture);
            ico_equip5.x = 725;
            ico_equip5.y = 246;
            ico_equip5.width = 90;
            ico_equip5.height = 90;
            this.addQuiackChild(ico_equip5);
            ico_equip5.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_90wupingkuang0');
            ico_quality5 = new Button(texture);
            ico_quality5.name= 'ico_quality5';
            ico_quality5.x = 727;
            ico_quality5.y = 246;
            ico_quality5.width = 90;
            ico_quality5.height = 90;
            this.addQuiackChild(ico_quality5);
            texture = assetMgr.getTexture('ui_chenghao_zhuangbei')
            equip_title = new Image(texture);
            equip_title.x = 726;
            equip_title.y = 247;
            equip_title.width = 89;
            equip_title.height = 89;
            this.addQuiackChild(equip_title);
            equip_title.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_lvjiahao')
            tag_add = new Image(texture);
            tag_add.x = 796;
            tag_add.y = 304;
            tag_add.width = 18;
            tag_add.height = 20;
            this.addQuiackChild(tag_add);
            tag_add.touchable = false;
            texture =assetMgr.getTexture('ui_yingxiongkapai_yingxiongmingdi');
            image = new Image(texture);
            image.x = 347;
            image.y = 151;
            image.width = 255;
            image.height = 59;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 612;
            image.y = 448;
            image.width = 38;
            image.height = 34;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            txt_heroName = new TextField(184,33,'','',26,0xFFFFFF,false);
            txt_heroName.touchable = false;
            txt_heroName.hAlign= 'center';
            txt_heroName.text= '阿尔萨斯啊啊';
            txt_heroName.x = 388;
            txt_heroName.y = 161;
            this.addQuiackChild(txt_heroName);
            texture = assetMgr.getTexture('ui_button_hero_heti');
            upgradeBtn = new Button(texture);
            upgradeBtn.name= 'upgradeBtn';
            upgradeBtn.x = 347;
            upgradeBtn.y = 171;
            upgradeBtn.width = 61;
            upgradeBtn.height = 56;
            this.addQuiackChild(upgradeBtn);
            texture =assetMgr.getTexture('ui_gongyong_kapaiyuansu1');
            image = new Image(texture);
            image.x = 328;
            image.y = 426;
            image.width = 70;
            image.height = 70;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_kapaiyuansu1');
            image = new Image(texture);
            image.x = 566;
            image.y = 426;
            image.width = 70;
            image.height = 70;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_yongxiongdengji_exp');
            image = new Image(texture);
            image.x = 416;
            image.y = 459;
            image.width = 48;
            image.height = 21;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            textLv = new TextField(44,44,'','',24,0xFFFFFF,false);
            textLv.touchable = false;
            textLv.hAlign= 'center';
            textLv.text= '65';
            textLv.x = 339;
            textLv.y = 439;
            this.addQuiackChild(textLv);
            init();
        }
        override public function dispose():void
        {
            skillIcon_1.dispose();
            skillIcon_2.dispose();
            skillIcon_3.dispose();
            btn_blacksmith.dispose();
            btn_atuo.dispose();
            fieldView.dispose();
            list_equip.dispose();
            list_exp.dispose();
            btn_equip5.dispose();
            ico_quality5.dispose();
            upgradeBtn.dispose();
            super.dispose();
        
}
    }
}
