package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.view.View;

    public class ExtractViewBase extends View
    {
        public var buyHero_0:Button;
        public var tag_normal:Scale9Image;
        public var text_RefreshConsume:TextField;
        public var text_diamond:TextField;
        public var text_FreeRefreshCountdown:TextField;
        public var text_time:TextField;
        public var hero_0:Sprite;
        public var hero_2:Sprite;
        public var hero_1:Sprite;
        public var btn_Refresh:Button;
        public var buyHero_2:Button;
        public var buyHero_1:Button;
        public var textNum_0:TextField;
        public var icon_0:Image;
        public var textNum_2:TextField;
        public var icon_2:Image;
        public var textAlreadyBuy_0:TextField;
        public var textAlreadyBuy_1:TextField;
        public var textAlreadyBuy_2:TextField;
        public var textNum_1:TextField;
        public var icon_1:Image;

        public function ExtractViewBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            var assetMgr:AssetMgr = AssetMgr.instance;
            texture = assetMgr.getTexture('ui_button_gongyong_big');
            buyHero_0 = new Button(texture);
            buyHero_0.name= 'buyHero_0';
            buyHero_0.x = 32;
            buyHero_0.y = 458;
            buyHero_0.width = 260;
            buyHero_0.height = 64;
            this.addQuiackChild(buyHero_0);
            texture = assetMgr.getTexture('ui_gongyong_hero_pub_9gongge_article');
            var tag_normalRect:Rectangle = new Rectangle(17,19,27,22);
            var tag_normal9ScaleTexture:Scale9Textures = new Scale9Textures(texture,tag_normalRect);
            tag_normal = new Scale9Image(tag_normal9ScaleTexture);
            tag_normal.x = 168;
            tag_normal.y = 523;
            tag_normal.width = 615;
            tag_normal.height = 105;
            this.addQuiackChild(tag_normal);
            text_RefreshConsume = new TextField(137,35,'','',26,0xFFFFCC,false);
            text_RefreshConsume.touchable = false;
            text_RefreshConsume.hAlign= 'left';
            text_RefreshConsume.text= '刷新消耗：';
            text_RefreshConsume.x = 197;
            text_RefreshConsume.y = 540;
            this.addQuiackChild(text_RefreshConsume);
            texture =assetMgr.getTexture('ui_gongyong_zuanshi');
            image = new Image(texture);
            image.x = 322;
            image.y = 535;
            image.width = 46;
            image.height = 44;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            text_diamond = new TextField(198,36,'','',28,0xFFFFCC,false);
            text_diamond.touchable = false;
            text_diamond.hAlign= 'left';
            text_diamond.text= '';
            text_diamond.x = 372;
            text_diamond.y = 540;
            this.addQuiackChild(text_diamond);
            text_FreeRefreshCountdown = new TextField(206,35,'','',26,0xFFFFCC,false);
            text_FreeRefreshCountdown.touchable = false;
            text_FreeRefreshCountdown.hAlign= 'left';
            text_FreeRefreshCountdown.text= '免费刷新倒计时:';
            text_FreeRefreshCountdown.x = 197;
            text_FreeRefreshCountdown.y = 579;
            this.addQuiackChild(text_FreeRefreshCountdown);
            text_time = new TextField(177,36,'','',28,0xFFFFCC,false);
            text_time.touchable = false;
            text_time.hAlign= 'left';
            text_time.text= '';
            text_time.x = 403;
            text_time.y = 577;
            this.addQuiackChild(text_time);
            hero_0 = new Sprite();
            hero_0.x = 17;
            hero_0.y = 86;
            hero_0.width = 289;
            hero_0.height = 377;
            this.addQuiackChild(hero_0);
            hero_0.name= 'hero_0';
            texture = assetMgr.getTexture('ui_yingxiongkapaiguang_0_1')
            image = new Image(texture);
            image.name= 'effectbg_3';
            image.x = 1;
            image.y = 373;
            image.width = 287;
            image.height = 36;
            image.scaleY = -1;
            hero_0.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_yingxiongkapaiguang_0_1')
            image = new Image(texture);
            image.name= 'effectbg_1';
            image.x = 1;
            image.width = 287;
            image.height = 36;
            hero_0.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_yingxiongkapaiguang_0_2')
            image = new Image(texture);
            image.name= 'effectbg_2';
            image.x = 1;
            image.y = 36;
            image.width = 287;
            image.height = 302;
            hero_0.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_yingxiong_beijing')
            image = new Image(texture);
            image.name= 'bg';
            image.x = 1;
            image.y = 8;
            image.width = 287;
            image.height = 368;
            hero_0.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_yingxiongjiuguan_xinkapai')
            image = new Image(texture);
            image.name= 'kuang';
            image.x = -1;
            image.y = -1;
            image.width = 287;
            image.height = 368;
            hero_0.addQuiackChild(image);
            image.touchable = false;
            texture =assetMgr.getTexture('ui_yingxiongkapai_yingxiongmingdi');
            image = new Image(texture);
            image.x = 14;
            image.y = 29;
            image.width = 255;
            image.height = 59;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            hero_0.addQuiackChild(image);
            textField = new TextField(151,36,'','',24,0xFFFFCC,false);
            textField.touchable = false;
            textField.x = 68;
            textField.y = 36;
            textField.hAlign= 'center';
            textField.text= '英雄名称';
            textField.name= 'heroName';
            hero_0.addQuiackChild(textField);
            texture = assetMgr.getTexture('ui_gongyong_kapaiyuansu1')
            image = new Image(texture);
            image.name= 'yuan1';
            image.x = 3;
            image.y = 300;
            image.width = 70;
            image.height = 70;
            hero_0.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_kapaiyuansu1')
            image = new Image(texture);
            image.name= 'yuan2';
            image.x = 216;
            image.y = 300;
            image.width = 70;
            image.height = 70;
            hero_0.addQuiackChild(image);
            image.touchable = false;
            textField = new TextField(44,44,'','',24,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 14;
            textField.y = 312;
            textField.hAlign= 'center';
            textField.text= '65';
            textField.name= 'textLv';
            hero_0.addQuiackChild(textField);
            hero_2 = new Sprite();
            hero_2.x = 636;
            hero_2.y = 86;
            hero_2.width = 289;
            hero_2.height = 377;
            this.addQuiackChild(hero_2);
            hero_2.name= 'hero_2';
            texture = assetMgr.getTexture('ui_yingxiongkapaiguang_0_1')
            image = new Image(texture);
            image.name= 'effectbg_3';
            image.x = 1;
            image.y = 373;
            image.width = 287;
            image.height = 36;
            image.scaleY = -1;
            hero_2.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_yingxiongkapaiguang_0_1')
            image = new Image(texture);
            image.name= 'effectbg_1';
            image.x = 1;
            image.width = 287;
            image.height = 36;
            hero_2.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_yingxiongkapaiguang_0_2')
            image = new Image(texture);
            image.name= 'effectbg_2';
            image.x = 1;
            image.y = 36;
            image.width = 287;
            image.height = 302;
            hero_2.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_yingxiong_beijing')
            image = new Image(texture);
            image.name= 'bg';
            image.x = 1;
            image.y = 8;
            image.width = 287;
            image.height = 368;
            hero_2.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_yingxiongjiuguan_xinkapai')
            image = new Image(texture);
            image.name= 'kuang';
            image.x = -1;
            image.y = -1;
            image.width = 287;
            image.height = 368;
            hero_2.addQuiackChild(image);
            image.touchable = false;
            texture =assetMgr.getTexture('ui_yingxiongkapai_yingxiongmingdi');
            image = new Image(texture);
            image.x = 14;
            image.y = 29;
            image.width = 255;
            image.height = 59;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            hero_2.addQuiackChild(image);
            textField = new TextField(151,36,'','',24,0xFFFFCC,false);
            textField.touchable = false;
            textField.x = 68;
            textField.y = 36;
            textField.hAlign= 'center';
            textField.text= '英雄名称';
            textField.name= 'heroName';
            hero_2.addQuiackChild(textField);
            texture = assetMgr.getTexture('ui_gongyong_kapaiyuansu1')
            image = new Image(texture);
            image.name= 'yuan1';
            image.x = 3;
            image.y = 300;
            image.width = 70;
            image.height = 70;
            hero_2.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_kapaiyuansu1')
            image = new Image(texture);
            image.name= 'yuan2';
            image.x = 216;
            image.y = 300;
            image.width = 70;
            image.height = 70;
            hero_2.addQuiackChild(image);
            image.touchable = false;
            textField = new TextField(44,44,'','',24,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 14;
            textField.y = 312;
            textField.hAlign= 'center';
            textField.text= '65';
            textField.name= 'textLv';
            hero_2.addQuiackChild(textField);
            hero_1 = new Sprite();
            hero_1.x = 326;
            hero_1.y = 86;
            hero_1.width = 289;
            hero_1.height = 377;
            this.addQuiackChild(hero_1);
            hero_1.name= 'hero_1';
            texture = assetMgr.getTexture('ui_yingxiongkapaiguang_0_1')
            image = new Image(texture);
            image.name= 'effectbg_3';
            image.x = 1;
            image.y = 373;
            image.width = 287;
            image.height = 36;
            image.scaleY = -1;
            hero_1.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_yingxiongkapaiguang_0_1')
            image = new Image(texture);
            image.name= 'effectbg_1';
            image.x = 1;
            image.width = 287;
            image.height = 36;
            hero_1.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_yingxiongkapaiguang_0_2')
            image = new Image(texture);
            image.name= 'effectbg_2';
            image.x = 1;
            image.y = 36;
            image.width = 287;
            image.height = 302;
            hero_1.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_yingxiong_beijing')
            image = new Image(texture);
            image.name= 'bg';
            image.x = 1;
            image.y = 8;
            image.width = 287;
            image.height = 368;
            hero_1.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_yingxiongjiuguan_xinkapai')
            image = new Image(texture);
            image.name= 'kuang';
            image.x = -1;
            image.y = -1;
            image.width = 287;
            image.height = 368;
            hero_1.addQuiackChild(image);
            image.touchable = false;
            texture =assetMgr.getTexture('ui_yingxiongkapai_yingxiongmingdi');
            image = new Image(texture);
            image.x = 14;
            image.y = 29;
            image.width = 255;
            image.height = 59;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            hero_1.addQuiackChild(image);
            textField = new TextField(151,36,'','',24,0xFFFFCC,false);
            textField.touchable = false;
            textField.x = 68;
            textField.y = 36;
            textField.hAlign= 'center';
            textField.text= '英雄名称';
            textField.name= 'heroName';
            hero_1.addQuiackChild(textField);
            texture = assetMgr.getTexture('ui_gongyong_kapaiyuansu1')
            image = new Image(texture);
            image.name= 'yuan1';
            image.x = 3;
            image.y = 300;
            image.width = 70;
            image.height = 70;
            hero_1.addQuiackChild(image);
            image.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_kapaiyuansu1')
            image = new Image(texture);
            image.name= 'yuan2';
            image.x = 216;
            image.y = 300;
            image.width = 70;
            image.height = 70;
            hero_1.addQuiackChild(image);
            image.touchable = false;
            textField = new TextField(44,44,'','',24,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 14;
            textField.y = 312;
            textField.hAlign= 'center';
            textField.text= '65';
            textField.name= 'textLv';
            hero_1.addQuiackChild(textField);
            texture = assetMgr.getTexture('ui_button_tiebaomutouanjian');
            btn_Refresh = new Button(texture);
            btn_Refresh.name= 'btn_Refresh';
            btn_Refresh.x = 600;
            btn_Refresh.y = 544;
            btn_Refresh.width = 150;
            btn_Refresh.height = 64;
            this.addQuiackChild(btn_Refresh);
            texture =assetMgr.getTexture('ui_wenzi_shuaxin');
            image = new Image(texture);
            image.x = 625;
            image.y = 557;
            image.width = 100;
            image.height = 38;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_button_gongyong_big');
            buyHero_2 = new Button(texture);
            buyHero_2.name= 'buyHero_2';
            buyHero_2.x = 651;
            buyHero_2.y = 458;
            buyHero_2.width = 260;
            buyHero_2.height = 64;
            this.addQuiackChild(buyHero_2);
            texture = assetMgr.getTexture('ui_button_gongyong_big');
            buyHero_1 = new Button(texture);
            buyHero_1.name= 'buyHero_1';
            buyHero_1.x = 340;
            buyHero_1.y = 458;
            buyHero_1.width = 260;
            buyHero_1.height = 64;
            this.addQuiackChild(buyHero_1);
            textNum_0 = new TextField(125,31,'','',24,0xFFFFCC,false);
            textNum_0.touchable = false;
            textNum_0.hAlign= 'left';
            textNum_0.text= '';
            textNum_0.x = 157;
            textNum_0.y = 474;
            this.addQuiackChild(textNum_0);
            texture = assetMgr.getTexture('ui_gongyong_money')
            icon_0 = new Image(texture);
            icon_0.x = 111;
            icon_0.y = 468;
            icon_0.width = 40;
            icon_0.height = 40;
            this.addQuiackChild(icon_0);
            icon_0.touchable = false;
            textNum_2 = new TextField(125,31,'','',24,0xFFFFCC,false);
            textNum_2.touchable = false;
            textNum_2.hAlign= 'left';
            textNum_2.text= '';
            textNum_2.x = 779;
            textNum_2.y = 474;
            this.addQuiackChild(textNum_2);
            texture = assetMgr.getTexture('ui_gongyong_money')
            icon_2 = new Image(texture);
            icon_2.x = 733;
            icon_2.y = 469;
            icon_2.width = 40;
            icon_2.height = 40;
            this.addQuiackChild(icon_2);
            icon_2.touchable = false;
            textAlreadyBuy_0 = new TextField(253,31,'','',24,0xFFFFCC,false);
            textAlreadyBuy_0.touchable = false;
            textAlreadyBuy_0.hAlign= 'center';
            textAlreadyBuy_0.text= '';
            textAlreadyBuy_0.x = 33;
            textAlreadyBuy_0.y = 474;
            this.addQuiackChild(textAlreadyBuy_0);
            textAlreadyBuy_1 = new TextField(242,31,'','',24,0xFFFFCC,false);
            textAlreadyBuy_1.touchable = false;
            textAlreadyBuy_1.hAlign= 'center';
            textAlreadyBuy_1.text= '';
            textAlreadyBuy_1.x = 348;
            textAlreadyBuy_1.y = 474;
            this.addQuiackChild(textAlreadyBuy_1);
            textAlreadyBuy_2 = new TextField(245,31,'','',24,0xFFFFCC,false);
            textAlreadyBuy_2.touchable = false;
            textAlreadyBuy_2.hAlign= 'center';
            textAlreadyBuy_2.text= '';
            textAlreadyBuy_2.x = 659;
            textAlreadyBuy_2.y = 474;
            this.addQuiackChild(textAlreadyBuy_2);
            textNum_1 = new TextField(125,31,'','',24,0xFFFFCC,false);
            textNum_1.touchable = false;
            textNum_1.hAlign= 'left';
            textNum_1.text= '';
            textNum_1.x = 466;
            textNum_1.y = 473;
            this.addQuiackChild(textNum_1);
            texture = assetMgr.getTexture('ui_gongyong_money')
            icon_1 = new Image(texture);
            icon_1.x = 423;
            icon_1.y = 468;
            icon_1.width = 40;
            icon_1.height = 40;
            this.addQuiackChild(icon_1);
            icon_1.touchable = false;
            init();
        }
        override public function dispose():void
        {
            buyHero_0.dispose();
            hero_0.dispose();
            hero_2.dispose();
            hero_1.dispose();
            btn_Refresh.dispose();
            buyHero_2.dispose();
            buyHero_1.dispose();
            super.dispose();
        
}
    }
}
