package game.view.viewBase
{
	import com.utils.Constants;
	import com.view.View;

	import feathers.controls.TextInput;

	import game.manager.AssetMgr;

	import starling.display.Button;
	import starling.display.Image;
	import starling.text.TextField;
	import starling.textures.Texture;

	public class FirstPayBase extends View
	{
		public var heroDi_3:Image;
		public var box3:Button;
		public var heroDi_2:Image;
		public var box2:Button;
		public var Recharge:Button;
		public var heroDi_1:Image;
		public var box1:Button;
		public var name_1:TextField;
		public var name_2:TextField;
		public var name_4:TextField;
		public var name_3:TextField;
		public var name_5:TextField;
		public var name_6:TextField;
		public var name_8:TextField;
		public var name_7:TextField;
		public var heroDi_4:Image;
		public var box4:Button;
		public var heroDi_8:Image;
		public var box8:Button;
		public var heroDi_7:Image;
		public var box7:Button;
		public var heroDi_6:Image;
		public var box6:Button;
		public var heroDi_5:Image;
		public var box5:Button;
		public var values_1:TextField;
		public var values_2:TextField;
		public var values_3:TextField;
		public var values_4:TextField;
		public var values_5:TextField;
		public var values_6:TextField;
		public var values_7:TextField;
		public var values_8:TextField;

		public function FirstPayBase()
		{
			super(false);
			var texture:Texture;
			var textField:TextField;
			var input_txt:TextInput;
			var image:Image;
			var button:Button;
			var assetMgr:AssetMgr=AssetMgr.instance;
			texture=assetMgr.getTexture('ui_Announcement_Baseboard2');
			image=new Image(texture);
			image.x=338;
			image.y=233;
			image.width=501;
			image.height=30;
			image.touchable=false;
			image.smoothing=Constants.smoothing;
			this.addQuiackChild(image);
			texture=assetMgr.getTexture('ui_activities_recharge_wenzi1');
			image=new Image(texture);
			image.x=285;
			image.y=130;
			image.width=339;
			image.height=60;
			image.touchable=false;
			image.smoothing=Constants.smoothing;
			this.addQuiackChild(image);
			texture=assetMgr.getTexture('ui_activities_recharge_wenzi2');
			image=new Image(texture);
			image.x=443;
			image.y=171;
			image.width=450;
			image.height=75;
			image.touchable=false;
			image.smoothing=Constants.smoothing;
			this.addQuiackChild(image);
			texture=assetMgr.getTexture('ui_Announcement_Baseboard5');
			image=new Image(texture);
			image.x=289;
			image.y=257;
			image.width=602;
			image.height=251;
			image.touchable=false;
			image.smoothing=Constants.smoothing;
			this.addQuiackChild(image);
			texture=assetMgr.getTexture('ui_gongyong_90wupingkuang')
			heroDi_3=new Image(texture);
			heroDi_3.x=623;
			heroDi_3.y=252;
			heroDi_3.width=90;
			heroDi_3.height=90;
			this.addQuiackChild(heroDi_3);
			heroDi_3.touchable=false;
			texture=assetMgr.getTexture('ui_gongyong_90wupingkuang0');
			box3=new Button(texture);
			box3.name='box3';
			box3.x=623;
			box3.y=252;
			box3.width=90;
			box3.height=90;
			this.addQuiackChild(box3);
			texture=assetMgr.getTexture('ui_gongyong_90wupingkuang')
			heroDi_2=new Image(texture);
			heroDi_2.x=469;
			heroDi_2.y=252;
			heroDi_2.width=90;
			heroDi_2.height=90;
			this.addQuiackChild(heroDi_2);
			heroDi_2.touchable=false;
			texture=assetMgr.getTexture('ui_gongyong_90wupingkuang0');
			box2=new Button(texture);
			box2.name='box2';
			box2.x=469;
			box2.y=252;
			box2.width=90;
			box2.height=90;
			this.addQuiackChild(box2);
			texture=assetMgr.getTexture('ui_Announcement_Baseboard1');
			image=new Image(texture);
			image.x=916;
			image.y=233;
			image.width=145;
			image.height=66;
			image.scaleX=-1;
			image.touchable=false;
			image.smoothing=Constants.smoothing;
			this.addQuiackChild(image);
			texture=assetMgr.getTexture('ui_tubiao_zuanshi_da');
			image=new Image(texture);
			image.x=662;
			image.y=165;
			image.width=76;
			image.height=78;
			image.touchable=false;
			image.smoothing=Constants.smoothing;
			this.addQuiackChild(image);
			texture=assetMgr.getTexture('ui_Announcement_Baseboard4');
			image=new Image(texture);
			image.x=907;
			image.y=495;
			image.width=67;
			image.height=41;
			image.scaleX=-1;
			image.touchable=false;
			image.smoothing=Constants.smoothing;
			this.addQuiackChild(image);
			texture=assetMgr.getTexture('ui_Announcement_Baseboard6');
			image=new Image(texture);
			image.x=322;
			image.y=500;
			image.width=547;
			image.height=36;
			image.touchable=false;
			image.smoothing=Constants.smoothing;
			this.addQuiackChild(image);
			texture=assetMgr.getTexture('ui_butten_activities_recharge');
			Recharge=new Button(texture);
			Recharge.name='Recharge';
			Recharge.x=527;
			Recharge.y=528;
			Recharge.width=139;
			Recharge.height=72;
			this.addQuiackChild(Recharge);
			Recharge.text='充 值';
			Recharge.fontColor=0xF5EC09;
			Recharge.fontSize=28;
			texture=assetMgr.getTexture('ui_Announcement_Baseboard3');
			image=new Image(texture);
			image.x=907;
			image.y=289;
			image.width=19;
			image.height=210;
			image.scaleX=-1;
			image.touchable=false;
			image.smoothing=Constants.smoothing;
			this.addQuiackChild(image);
			texture=assetMgr.getTexture('ui_Announcement_Baseboard1');
			image=new Image(texture);
			image.x=271;
			image.y=233;
			image.width=145;
			image.height=66;
			image.touchable=false;
			image.smoothing=Constants.smoothing;
			this.addQuiackChild(image);
			texture=assetMgr.getTexture('ui_gongyong_90wupingkuang')
			heroDi_1=new Image(texture);
			heroDi_1.x=316;
			heroDi_1.y=252;
			heroDi_1.width=90;
			heroDi_1.height=90;
			this.addQuiackChild(heroDi_1);
			heroDi_1.touchable=false;
			texture=assetMgr.getTexture('ui_gongyong_90wupingkuang0');
			box1=new Button(texture);
			box1.name='box1';
			box1.x=316;
			box1.y=252;
			box1.width=90;
			box1.height=90;
			this.addQuiackChild(box1);
			texture=assetMgr.getTexture('ui_Announcement_Baseboard4');
			image=new Image(texture);
			image.x=280;
			image.y=495;
			image.width=67;
			image.height=41;
			image.touchable=false;
			image.smoothing=Constants.smoothing;
			this.addQuiackChild(image);
			texture=assetMgr.getTexture('ui_Announcement_Baseboard3');
			image=new Image(texture);
			image.x=280;
			image.y=289;
			image.width=19;
			image.height=210;
			image.touchable=false;
			image.smoothing=Constants.smoothing;
			this.addQuiackChild(image);
			name_1=new TextField(116, 26, '', '', 20, 0x210B00, false);
			name_1.touchable=false;
			name_1.hAlign='center';
			name_1.text='';
			name_1.x=303;
			name_1.y=347;
			this.addQuiackChild(name_1);
			name_2=new TextField(116, 26, '', '', 20, 0x210B00, false);
			name_2.touchable=false;
			name_2.hAlign='center';
			name_2.text='';
			name_2.x=457;
			name_2.y=347;
			this.addQuiackChild(name_2);
			name_4=new TextField(116, 26, '', '', 20, 0x210B00, false);
			name_4.touchable=false;
			name_4.hAlign='center';
			name_4.text='';
			name_4.x=764;
			name_4.y=347;
			this.addQuiackChild(name_4);
			name_3=new TextField(116, 26, '', '', 20, 0x210B00, false);
			name_3.touchable=false;
			name_3.hAlign='center';
			name_3.text='';
			name_3.x=610;
			name_3.y=347;
			this.addQuiackChild(name_3);
			name_5=new TextField(116, 26, '', '', 20, 0x210B00, false);
			name_5.touchable=false;
			name_5.hAlign='center';
			name_5.text='';
			name_5.x=303;
			name_5.y=484;
			this.addQuiackChild(name_5);
			name_6=new TextField(116, 26, '', '', 20, 0x210B00, false);
			name_6.touchable=false;
			name_6.hAlign='center';
			name_6.text='';
			name_6.x=457;
			name_6.y=484;
			this.addQuiackChild(name_6);
			name_8=new TextField(116, 26, '', '', 20, 0x210B00, false);
			name_8.touchable=false;
			name_8.hAlign='center';
			name_8.text='';
			name_8.x=764;
			name_8.y=484;
			this.addQuiackChild(name_8);
			name_7=new TextField(116, 26, '', '', 20, 0x210B00, false);
			name_7.touchable=false;
			name_7.hAlign='center';
			name_7.text='';
			name_7.x=610;
			name_7.y=484;
			this.addQuiackChild(name_7);
			texture=assetMgr.getTexture('ui_gongyong_90wupingkuang')
			heroDi_4=new Image(texture);
			heroDi_4.x=776;
			heroDi_4.y=252;
			heroDi_4.width=90;
			heroDi_4.height=90;
			this.addQuiackChild(heroDi_4);
			heroDi_4.touchable=false;
			texture=assetMgr.getTexture('ui_gongyong_90wupingkuang0');
			box4=new Button(texture);
			box4.name='box4';
			box4.x=776;
			box4.y=252;
			box4.width=90;
			box4.height=90;
			this.addQuiackChild(box4);
			texture=assetMgr.getTexture('ui_gongyong_90wupingkuang')
			heroDi_8=new Image(texture);
			heroDi_8.x=776;
			heroDi_8.y=389;
			heroDi_8.width=90;
			heroDi_8.height=90;
			this.addQuiackChild(heroDi_8);
			heroDi_8.touchable=false;
			texture=assetMgr.getTexture('ui_gongyong_90wupingkuang0');
			box8=new Button(texture);
			box8.name='box8';
			box8.x=776;
			box8.y=389;
			box8.width=90;
			box8.height=90;
			this.addQuiackChild(box8);
			texture=assetMgr.getTexture('ui_gongyong_90wupingkuang')
			heroDi_7=new Image(texture);
			heroDi_7.x=623;
			heroDi_7.y=389;
			heroDi_7.width=90;
			heroDi_7.height=90;
			this.addQuiackChild(heroDi_7);
			heroDi_7.touchable=false;
			texture=assetMgr.getTexture('ui_gongyong_90wupingkuang0');
			box7=new Button(texture);
			box7.name='box7';
			box7.x=623;
			box7.y=389;
			box7.width=90;
			box7.height=90;
			this.addQuiackChild(box7);
			texture=assetMgr.getTexture('ui_gongyong_90wupingkuang')
			heroDi_6=new Image(texture);
			heroDi_6.x=469;
			heroDi_6.y=389;
			heroDi_6.width=90;
			heroDi_6.height=90;
			this.addQuiackChild(heroDi_6);
			heroDi_6.touchable=false;
			texture=assetMgr.getTexture('ui_gongyong_90wupingkuang0');
			box6=new Button(texture);
			box6.name='box6';
			box6.x=469;
			box6.y=389;
			box6.width=90;
			box6.height=90;
			this.addQuiackChild(box6);
			texture=assetMgr.getTexture('ui_gongyong_90wupingkuang')
			heroDi_5=new Image(texture);
			heroDi_5.x=316;
			heroDi_5.y=389;
			heroDi_5.width=90;
			heroDi_5.height=90;
			this.addQuiackChild(heroDi_5);
			heroDi_5.touchable=false;
			texture=assetMgr.getTexture('ui_gongyong_90wupingkuang0');
			box5=new Button(texture);
			box5.name='box5';
			box5.x=316;
			box5.y=389;
			box5.width=90;
			box5.height=90;
			this.addQuiackChild(box5);
			values_1=new TextField(80, 25, '', '', 16, 0xFFFFFF, false);
			values_1.touchable=false;
			values_1.hAlign='right';
			values_1.text='';
			values_1.x=317;
			values_1.y=314;
			this.addQuiackChild(values_1);
			values_2=new TextField(80, 25, '', '', 16, 0xFFFFFF, false);
			values_2.touchable=false;
			values_2.hAlign='right';
			values_2.text='';
			values_2.x=469;
			values_2.y=314;
			this.addQuiackChild(values_2);
			values_3=new TextField(80, 25, '', '', 16, 0xFFFFFF, false);
			values_3.touchable=false;
			values_3.hAlign='right';
			values_3.text='';
			values_3.x=623;
			values_3.y=314;
			this.addQuiackChild(values_3);
			values_4=new TextField(80, 25, '', '', 16, 0xFFFFFF, false);
			values_4.touchable=false;
			values_4.hAlign='right';
			values_4.text='';
			values_4.x=776;
			values_4.y=314;
			this.addQuiackChild(values_4);
			values_5=new TextField(80, 25, '', '', 16, 0xFFFFFF, false);
			values_5.touchable=false;
			values_5.hAlign='right';
			values_5.text='';
			values_5.x=317;
			values_5.y=448;
			this.addQuiackChild(values_5);
			values_6=new TextField(80, 25, '', '', 16, 0xFFFFFF, false);
			values_6.touchable=false;
			values_6.hAlign='right';
			values_6.text='';
			values_6.x=469;
			values_6.y=448;
			this.addQuiackChild(values_6);
			values_7=new TextField(80, 25, '', '', 16, 0xFFFFFF, false);
			values_7.touchable=false;
			values_7.hAlign='right';
			values_7.text='';
			values_7.x=623;
			values_7.y=448;
			this.addQuiackChild(values_7);
			values_8=new TextField(80, 25, '', '', 16, 0xFFFFFF, false);
			values_8.touchable=false;
			values_8.hAlign='right';
			values_8.text='';
			values_8.x=777;
			values_8.y=448;
			this.addQuiackChild(values_8);
			init();
		}

		override public function dispose():void
		{
			box3.dispose();
			box2.dispose();
			Recharge.dispose();
			box1.dispose();
			box4.dispose();
			box8.dispose();
			box7.dispose();
			box6.dispose();
			box5.dispose();
			super.dispose();

		}
	}
}
