package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import game.view.goodsGuide.render.GoodsGuideListRender;
    import com.view.View;

    public class GoodsGuideInfoViewBase extends View
    {
        public var scale_bg2:Scale9Image;
        public var ui_gongyong_hero_pub_9gongge_article23144:Scale9Image;
        public var btn_ok:Button;
        public var btn_Swallow:Button;
        public var view_equip:Sprite;
        public var grid:GoodsGuideListRender;
        public var txt_des5:TextField;
        public var txt_price:TextField;
        public var txt_des:TextField;

        public function GoodsGuideInfoViewBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            var assetMgr:AssetMgr = AssetMgr.instance;
            texture =assetMgr.getTexture('ui_wudixingyunxing_xingxing_goumaikuang1');
            image = new Image(texture);
            image.width = 102;
            image.height = 446;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_wudixingyunxing_xingxing_goumaikuang2');
            image = new Image(texture);
            image.x = 79;
            image.width = 216;
            image.height = 446;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_wudixingyunxing_xingxing_goumaikuang1');
            image = new Image(texture);
            image.x = 350;
            image.width = 102;
            image.height = 446;
            image.scaleX = -1;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_Setup_button_switch3');
            var scale_bg2Rect:Rectangle = new Rectangle(54,26,107,52);
            var scale_bg29ScaleTexture:Scale9Textures = new Scale9Textures(texture,scale_bg2Rect);
            scale_bg2 = new Scale9Image(scale_bg29ScaleTexture);
            scale_bg2.x = 15;
            scale_bg2.y = 30;
            scale_bg2.width = 318;
            scale_bg2.height = 342;
            this.addQuiackChild(scale_bg2);
            texture = assetMgr.getTexture('ui_gongyong_hero_pub_9gongge_article');
            var ui_gongyong_hero_pub_9gongge_article23144Rect:Rectangle = new Rectangle(17,19,27,22);
            var ui_gongyong_hero_pub_9gongge_article231449ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_gongyong_hero_pub_9gongge_article23144Rect);
            ui_gongyong_hero_pub_9gongge_article23144 = new Scale9Image(ui_gongyong_hero_pub_9gongge_article231449ScaleTexture);
            ui_gongyong_hero_pub_9gongge_article23144.x = 23;
            ui_gongyong_hero_pub_9gongge_article23144.y = 144;
            ui_gongyong_hero_pub_9gongge_article23144.width = 303;
            ui_gongyong_hero_pub_9gongge_article23144.height = 220;
            this.addQuiackChild(ui_gongyong_hero_pub_9gongge_article23144);
            texture = assetMgr.getTexture('ui_button_tiebaomutouanjian');
            btn_ok = new Button(texture);
            btn_ok.name= 'btn_ok';
            btn_ok.x = 21;
            btn_ok.y = 371;
            btn_ok.width = 147;
            btn_ok.height = 63;
            this.addQuiackChild(btn_ok);
            btn_ok.text= '合成';
            btn_ok.fontColor= 0xFF9900;
            btn_ok.fontSize= 24;
            texture = assetMgr.getTexture('ui_button_tiebaomutouanjian');
            btn_Swallow = new Button(texture);
            btn_Swallow.name= 'btn_Swallow';
            btn_Swallow.x = 176;
            btn_Swallow.y = 371;
            btn_Swallow.width = 150;
            btn_Swallow.height = 64;
            this.addQuiackChild(btn_Swallow);
            btn_Swallow.text= '吞噬';
            btn_Swallow.fontColor= 0xFF9900;
            btn_Swallow.fontSize= 24;
            view_equip = new Sprite();
            view_equip.x = 37;
            view_equip.y = 148;
            view_equip.width = 278;
            view_equip.height = 183;
            this.addQuiackChild(view_equip);
            view_equip.name= 'view_equip';
            textField = new TextField(104,28,'','',18,0xE2B13B,false);
            textField.touchable = false;
            textField.hAlign= 'left';
            textField.text= '主属性';
            textField.name= 'txt_des1';
            view_equip.addQuiackChild(textField);
            textField = new TextField(104,28,'','',18,0xE2B13B,false);
            textField.touchable = false;
            textField.y = 45;
            textField.hAlign= 'left';
            textField.text= '附属性';
            textField.name= 'txt_des2';
            view_equip.addQuiackChild(textField);
            textField = new TextField(60,28,'','',16,0xFFFFFF,false);
            textField.touchable = false;
            textField.y = 25;
            textField.hAlign= 'left';
            textField.text= '攻击：';
            textField.name= 'txt_mfield0';
            view_equip.addQuiackChild(textField);
            textField = new TextField(83,28,'','',16,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 41;
            textField.y = 25;
            textField.hAlign= 'right';
            textField.text= '';
            textField.name= 'txt_attack';
            view_equip.addQuiackChild(textField);
            textField = new TextField(60,25,'','',16,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 149;
            textField.y = 25;
            textField.hAlign= 'left';
            textField.text= '血量：';
            textField.name= 'txt_mfield1';
            view_equip.addQuiackChild(textField);
            textField = new TextField(83,28,'','',16,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 190;
            textField.y = 25;
            textField.hAlign= 'right';
            textField.text= '';
            textField.name= 'txt_hp';
            view_equip.addQuiackChild(textField);
            textField = new TextField(60,25,'','',16,0xFFFFFF,false);
            textField.touchable = false;
            textField.y = 69;
            textField.hAlign= 'left';
            textField.text= '防御：';
            textField.name= 'txt_field0';
            view_equip.addQuiackChild(textField);
            textField = new TextField(83,28,'','',16,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 41;
            textField.y = 68;
            textField.hAlign= 'right';
            textField.text= '';
            textField.name= 'txt_defend';
            view_equip.addQuiackChild(textField);
            textField = new TextField(60,28,'','',16,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 149;
            textField.y = 69;
            textField.hAlign= 'left';
            textField.text= '穿刺：';
            textField.name= 'txt_field1';
            view_equip.addQuiackChild(textField);
            textField = new TextField(83,28,'','',16,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 190;
            textField.y = 68;
            textField.hAlign= 'right';
            textField.text= '';
            textField.name= 'txt_puncture';
            view_equip.addQuiackChild(textField);
            textField = new TextField(60,28,'','',16,0xFFFFFF,false);
            textField.touchable = false;
            textField.y = 89;
            textField.hAlign= 'left';
            textField.text= '命中：';
            textField.name= 'txt_field2';
            view_equip.addQuiackChild(textField);
            textField = new TextField(83,28,'','',16,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 41;
            textField.y = 88;
            textField.hAlign= 'right';
            textField.text= '';
            textField.name= 'txt_hit';
            view_equip.addQuiackChild(textField);
            textField = new TextField(60,28,'','',16,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 149;
            textField.y = 89;
            textField.hAlign= 'left';
            textField.text= '闪避：';
            textField.name= 'txt_field3';
            view_equip.addQuiackChild(textField);
            textField = new TextField(83,28,'','',16,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 190;
            textField.y = 88;
            textField.hAlign= 'right';
            textField.text= '';
            textField.name= 'txt_dodge';
            view_equip.addQuiackChild(textField);
            textField = new TextField(60,28,'','',16,0xFFFFFF,false);
            textField.touchable = false;
            textField.y = 109;
            textField.hAlign= 'left';
            textField.text= '暴击：';
            textField.name= 'txt_field4';
            view_equip.addQuiackChild(textField);
            textField = new TextField(83,28,'','',16,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 41;
            textField.y = 108;
            textField.hAlign= 'right';
            textField.text= '';
            textField.name= 'txt_crit';
            view_equip.addQuiackChild(textField);
            textField = new TextField(60,28,'','',16,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 149;
            textField.y = 109;
            textField.hAlign= 'left';
            textField.text= '暴强：';
            textField.name= 'txt_field5';
            view_equip.addQuiackChild(textField);
            textField = new TextField(83,28,'','',16,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 190;
            textField.y = 108;
            textField.hAlign= 'right';
            textField.text= '';
            textField.name= 'txt_critPercentage';
            view_equip.addQuiackChild(textField);
            textField = new TextField(60,28,'','',16,0xFFFFFF,false);
            textField.touchable = false;
            textField.y = 129;
            textField.hAlign= 'left';
            textField.text= '免爆：';
            textField.name= 'txt_field6';
            view_equip.addQuiackChild(textField);
            textField = new TextField(60,28,'','',16,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 149;
            textField.y = 129;
            textField.hAlign= 'left';
            textField.text= '韧性：';
            textField.name= 'txt_field7';
            view_equip.addQuiackChild(textField);
            textField = new TextField(83,28,'','',16,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 41;
            textField.y = 126;
            textField.hAlign= 'right';
            textField.text= '';
            textField.name= 'txt_anitCrit';
            view_equip.addQuiackChild(textField);
            textField = new TextField(83,28,'','',16,0xFFFFFF,false);
            textField.touchable = false;
            textField.x = 190;
            textField.y = 126;
            textField.hAlign= 'right';
            textField.text= '';
            textField.name= 'txt_toughness';
            view_equip.addQuiackChild(textField);
            textField = new TextField(104,32,'','',20,0xD57626,false);
            textField.touchable = false;
            textField.x = -4;
            textField.y = 152;
            textField.hAlign= 'left';
            textField.text= '装备槽位';
            textField.name= 'txt_des3';
            view_equip.addQuiackChild(textField);
            textField = new TextField(104,32,'','',20,0xD57626,false);
            textField.touchable = false;
            textField.x = 20;
            textField.y = 152;
            textField.hAlign= 'right';
            textField.text= '';
            textField.name= 'txt_solt';
            view_equip.addQuiackChild(textField);
            textField = new TextField(80,32,'','',20,0xD57626,false);
            textField.touchable = false;
            textField.x = 146;
            textField.y = 152;
            textField.hAlign= 'left';
            textField.text= '战力：';
            textField.name= 'txt_des4';
            view_equip.addQuiackChild(textField);
            textField = new TextField(104,32,'','',20,0xD57626,false);
            textField.touchable = false;
            textField.x = 170;
            textField.y = 152;
            textField.hAlign= 'right';
            textField.text= '';
            textField.name= 'txt_power';
            view_equip.addQuiackChild(textField);
            grid = new GoodsGuideListRender();
            grid.x = 24;
            grid.y = 37;
            this.addQuiackChild(grid);
            txt_des5 = new TextField(138,36,'','',24,0xFFFFFF,false);
            txt_des5.touchable = false;
            txt_des5.hAlign= 'left';
            txt_des5.text= '出售价格:';
            txt_des5.x = 32;
            txt_des5.y = 323;
            this.addQuiackChild(txt_des5);
            txt_price = new TextField(148,38,'','',24,0xFFFFFF,false);
            txt_price.touchable = false;
            txt_price.hAlign= 'right';
            txt_price.text= '';
            txt_price.x = 167;
            txt_price.y = 323;
            this.addQuiackChild(txt_price);
            texture =assetMgr.getTexture('ui_gongyong_money');
            image = new Image(texture);
            image.x = 142;
            image.y = 321;
            image.width = 38;
            image.height = 38;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            txt_des = new TextField(247,165,'','',18,0xFFFFFF,false);
            txt_des.touchable = false;
            txt_des.hAlign= 'left';
            txt_des.text= '';
            txt_des.x = 37;
            txt_des.y = 148;
            this.addQuiackChild(txt_des);
            init();
        }
        override public function dispose():void
        {
            btn_ok.dispose();
            btn_Swallow.dispose();
            view_equip.dispose();
            grid.dispose();
            super.dispose();
        
}
    }
}
