package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import game.base.JTSprite;

    public class JTPvpRegulationComponentBase extends JTSprite
    {
        public var txt_des1:TextField;
        public var txt_value0:TextField;
        public var txt_value1:TextField;
        public var txt_value2:TextField;
        public var txt_value3:TextField;
        public var txt_value4:TextField;
        public var txt_value5:TextField;
        public var txt_des2:TextField;
        public var txt_des4:TextField;
        public var txt_name2:TextField;
        public var txt_name1:TextField;
        public var txt_name4:TextField;
        public var txt_name3:TextField;
        public var txt_name5:TextField;
        public var txt_name0:TextField;

        public function JTPvpRegulationComponentBase()
        {
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            var assetMgr:AssetMgr = AssetMgr.instance;
            texture =assetMgr.getTexture('ui_gongyong_zhiwanzidi');
            image = new Image(texture);
            image.width = 704;
            image.height = 267;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_zhiwanzidi');
            image = new Image(texture);
            image.y = 526;
            image.width = 704;
            image.height = 267;
            image.scaleY = -1.77099609375;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_zhiwanzidi_tiao1');
            image = new Image(texture);
            image.x = 57;
            image.y = 132;
            image.width = 600;
            image.height = 49;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_zhiwanzidi_tiao2');
            image = new Image(texture);
            image.x = 57;
            image.y = 78;
            image.width = 600;
            image.height = 49;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_zhiwanzidi_tiao1');
            image = new Image(texture);
            image.x = 57;
            image.y = 185;
            image.width = 600;
            image.height = 49;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_zhiwanzidi_tiao1');
            image = new Image(texture);
            image.x = 57;
            image.y = 239;
            image.width = 600;
            image.height = 49;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_zhiwanzidi_tiao1');
            image = new Image(texture);
            image.x = 57;
            image.y = 293;
            image.width = 600;
            image.height = 49;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_zhiwanzidi_tiao1');
            image = new Image(texture);
            image.x = 57;
            image.y = 346;
            image.width = 600;
            image.height = 49;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_zhiwanzidi_tiao1');
            image = new Image(texture);
            image.x = 57;
            image.y = 399;
            image.width = 600;
            image.height = 49;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_zhiwanzidi_tiao4');
            image = new Image(texture);
            image.x = 364;
            image.y = 77;
            image.width = 4;
            image.height = 371;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            txt_des1 = new TextField(610,41,'','',24,0x40280E,false);
            txt_des1.touchable = false;
            txt_des1.hAlign= 'center';
            txt_des1.text= '晚上九点，根据排名结算！';
            txt_des1.x = 50;
            txt_des1.y = 451;
            this.addQuiackChild(txt_des1);
            txt_value0 = new TextField(123,41,'','',28,0x311D05,false);
            txt_value0.touchable = false;
            txt_value0.hAlign= 'center';
            txt_value0.text= '段位1';
            txt_value0.x = 149;
            txt_value0.y = 136;
            this.addQuiackChild(txt_value0);
            txt_value1 = new TextField(123,41,'','',28,0x311D05,false);
            txt_value1.touchable = false;
            txt_value1.hAlign= 'center';
            txt_value1.text= '段位1';
            txt_value1.x = 149;
            txt_value1.y = 189;
            this.addQuiackChild(txt_value1);
            txt_value2 = new TextField(123,41,'','',28,0x311D05,false);
            txt_value2.touchable = false;
            txt_value2.hAlign= 'center';
            txt_value2.text= '段位1';
            txt_value2.x = 149;
            txt_value2.y = 243;
            this.addQuiackChild(txt_value2);
            txt_value3 = new TextField(123,41,'','',28,0x311D05,false);
            txt_value3.touchable = false;
            txt_value3.hAlign= 'center';
            txt_value3.text= '段位1';
            txt_value3.x = 146;
            txt_value3.y = 296;
            this.addQuiackChild(txt_value3);
            txt_value4 = new TextField(123,41,'','',28,0x311D05,false);
            txt_value4.touchable = false;
            txt_value4.hAlign= 'center';
            txt_value4.text= '段位1';
            txt_value4.x = 146;
            txt_value4.y = 350;
            this.addQuiackChild(txt_value4);
            txt_value5 = new TextField(123,41,'','',28,0x311D05,false);
            txt_value5.touchable = false;
            txt_value5.hAlign= 'center';
            txt_value5.text= '段位1';
            txt_value5.x = 146;
            txt_value5.y = 403;
            this.addQuiackChild(txt_value5);
            txt_des2 = new TextField(128,36,'','',24,0x311D05,false);
            txt_des2.touchable = false;
            txt_des2.hAlign= 'center';
            txt_des2.text= '段位';
            txt_des2.x = 145;
            txt_des2.y = 85;
            this.addQuiackChild(txt_des2);
            txt_des4 = new TextField(91,33,'','',22,0x311D05,false);
            txt_des4.touchable = false;
            txt_des4.hAlign= 'center';
            txt_des4.text= '排名';
            txt_des4.x = 457;
            txt_des4.y = 85;
            this.addQuiackChild(txt_des4);
            txt_name2 = new TextField(130,33,'','',22,0x311D05,false);
            txt_name2.touchable = false;
            txt_name2.hAlign= 'center';
            txt_name2.text= '1-50';
            txt_name2.x = 445;
            txt_name2.y = 246;
            this.addQuiackChild(txt_name2);
            txt_name1 = new TextField(130,33,'','',22,0x311D05,false);
            txt_name1.touchable = false;
            txt_name1.hAlign= 'center';
            txt_name1.text= '1-50';
            txt_name1.x = 445;
            txt_name1.y = 189;
            this.addQuiackChild(txt_name1);
            txt_name4 = new TextField(130,33,'','',22,0x311D05,false);
            txt_name4.touchable = false;
            txt_name4.hAlign= 'center';
            txt_name4.text= '1-50';
            txt_name4.x = 445;
            txt_name4.y = 354;
            this.addQuiackChild(txt_name4);
            txt_name3 = new TextField(130,33,'','',22,0x311D05,false);
            txt_name3.touchable = false;
            txt_name3.hAlign= 'center';
            txt_name3.text= '1-50';
            txt_name3.x = 445;
            txt_name3.y = 301;
            this.addQuiackChild(txt_name3);
            txt_name5 = new TextField(130,33,'','',22,0x311D05,false);
            txt_name5.touchable = false;
            txt_name5.hAlign= 'center';
            txt_name5.text= '1-50';
            txt_name5.x = 445;
            txt_name5.y = 408;
            this.addQuiackChild(txt_name5);
            txt_name0 = new TextField(130,33,'','',22,0x311D05,false);
            txt_name0.touchable = false;
            txt_name0.hAlign= 'center';
            txt_name0.text= '1-50';
            txt_name0.x = 445;
            txt_name0.y = 139;
            this.addQuiackChild(txt_name0);
        }
    }
}
