package game.view.viewBase {
    import com.utils.Constants;

    import feathers.controls.TextInput;

    import game.base.JTSprite;
    import game.manager.AssetMgr;

    import starling.display.Button;
    import starling.display.Image;
    import starling.textures.Texture;

    public class JTUIHeroEquipmentBase extends JTSprite {
        public var look:Button;
        public var bg:Image;
        public var box1:Image;
        public var par:Image;
        public var box3:Image;
        public var box2:Image;
        public var box4:Image;
        public var Equip2:Button;
        public var Equip3:Button;
        public var Equip4:Button;
        public var sumbg3:Image;
        public var sum3:Image;
        public var sumbg4:Image;
        public var sum4:Image;
        public var sumbg2:Image;
        public var sum2:Image;
        public var attackIcon:Button;
        public var hpIcon:Button;
        public var Equip1:Button;
        public var sumbg1:Image;
        public var sum1:Image;

        public function JTUIHeroEquipmentBase() {
            var texture:Texture;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            var assetMgr:AssetMgr = AssetMgr.instance;
            texture = assetMgr.getTexture('ui_gongyong_mulianbeijingkuai2');
            image = new Image(texture);
            image.x = 86;
            image.y = 154;
            image.width = 791;
            image.height = 147;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_mulianbeijingkuai1');
            image = new Image(texture);
            image.x = 85;
            image.y = 37;
            image.width = 793;
            image.height = 122;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_dianquanheng_di');
            image = new Image(texture);
            image.x = 96;
            image.y = 437;
            image.width = 774;
            image.height = 160;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_guaijiaoshitou1');
            image = new Image(texture);
            image.x = 856;
            image.y = 599;
            image.width = 741;
            image.height = 24;
            image.scaleX = -9.263824462890625;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_guaijiaoshitou1');
            image = new Image(texture);
            image.x = 854;
            image.y = 461;
            image.width = 741;
            image.height = 24;
            image.scaleX = -9.263824462890625;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_mulianbeijingkuai1');
            image = new Image(texture);
            image.x = 877;
            image.y = 467;
            image.width = 793;
            image.height = 122;
            image.scaleX = -0.9578399658203125;
            image.scaleY = -1.100250244140625;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_mulianbeijingkuai2');
            image = new Image(texture);
            image.x = 85;
            image.y = 290;
            image.width = 791;
            image.height = 92;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_guaijiaoshitou2');
            image = new Image(texture);
            image.x = 880;
            image.y = 478;
            image.width = 26;
            image.height = 102;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_guaijiaoshitou2');
            image = new Image(texture);
            image.x = 84;
            image.y = 474;
            image.width = 26;
            image.height = 102;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 81;
            image.y = 460;
            image.width = 38;
            image.height = 34;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 81;
            image.y = 600;
            image.width = 38;
            image.height = 34;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 884;
            image.y = 460;
            image.width = 38;
            image.height = 34;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 884;
            image.y = 600;
            image.width = 38;
            image.height = 34;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_bumangdi_shangbianyikuaitie');
            image = new Image(texture);
            image.x = 244;
            image.y = 462;
            image.width = 30;
            image.height = 21;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_bumangdi_shangbianyikuaitie');
            image = new Image(texture);
            image.x = 688;
            image.y = 461;
            image.width = 30;
            image.height = 21;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_bumangdi_shangbianyikuaitie');
            image = new Image(texture);
            image.x = 244;
            image.y = 462;
            image.width = 30;
            image.height = 21;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_bumangdi_shangbianyikuaitie');
            image = new Image(texture);
            image.x = 688;
            image.y = 463;
            image.width = 30;
            image.height = 21;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_Buyingdiamond_title');
            image = new Image(texture);
            image.x = 369;
            image.y = 19;
            image.width = 223;
            image.height = 68;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_zhiwanzidi');
            image = new Image(texture);
            image.x = 532;
            image.y = 405;
            image.width = 309;
            image.height = 151;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_bumangdi_shangbianyikuaitie');
            image = new Image(texture);
            image.x = 611;
            image.y = 401;
            image.width = 30;
            image.height = 21;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_button_shuxingchakananniu');
            look = new Button(texture);
            look.name = 'look';
            look.x = 624;
            look.y = 400;
            look.width = 136;
            look.height = 39;
            this.addQuiackChild(look);
            texture = assetMgr.getTexture('ui_gongyong_bumangdi_shangbianyikuaitie');
            image = new Image(texture);
            image.x = 773;
            image.y = 401;
            image.width = 30;
            image.height = 21;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_zhiwanzidi');
            image = new Image(texture);
            image.x = 532;
            image.y = 106;
            image.width = 309;
            image.height = 151;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_zhiwanzidi1');
            image = new Image(texture);
            image.x = 539;
            image.y = 113;
            image.width = 21;
            image.height = 33;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_zhiwanzidi1');
            image = new Image(texture);
            image.x = 835;
            image.y = 113;
            image.width = 21;
            image.height = 33;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_yingxiong_beijing')
            bg = new Image(texture);
            bg.x = 166;
            bg.y = 99;
            bg.width = 300;
            bg.height = 339;
            this.addQuiackChild(bg);
            bg.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_guaijiaoshitou2');
            image = new Image(texture);
            image.x = 471;
            image.y = 127;
            image.width = 26;
            image.height = 290;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_guaijiaoshitou2');
            image = new Image(texture);
            image.x = 159;
            image.y = 124;
            image.width = 26;
            image.height = 296;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_90wupingkuang0')
            box1 = new Image(texture);
            box1.x = 109;
            box1.y = 170;
            box1.width = 92;
            box1.height = 91;
            this.addQuiackChild(box1);
            box1.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_guaijiaoshitou1');
            image = new Image(texture);
            image.x = 188;
            image.y = 96;
            image.width = 257;
            image.height = 24;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 155;
            image.y = 95;
            image.width = 38;
            image.height = 34;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 155;
            image.y = 450;
            image.width = 38;
            image.height = 34;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 475;
            image.y = 95;
            image.width = 38;
            image.height = 34;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 475;
            image.y = 450;
            image.width = 38;
            image.height = 34;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_guaijiaoshitou2');
            image = new Image(texture);
            image.x = 471;
            image.y = 127;
            image.width = 26;
            image.height = 290;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_guaijiaoshitou1');
            image = new Image(texture);
            image.x = 445;
            image.y = 452;
            image.width = 257;
            image.height = 24;
            image.scaleX = -3.21331787109375;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_jingyantiao_baidi');
            image = new Image(texture);
            image.x = 181;
            image.y = 400;
            image.width = 268;
            image.height = 20;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_jingyantiao_baidi1')
            par = new Image(texture);
            par.x = 192;
            par.y = 408;
            par.width = 251;
            par.height = 5;
            this.addQuiackChild(par);
            par.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_90wupingkuang0')
            box3 = new Image(texture);
            box3.x = 109;
            box3.y = 278;
            box3.width = 92;
            box3.height = 91;
            this.addQuiackChild(box3);
            box3.touchable = false;
            texture = assetMgr.getTexture('ui_yongxiongdengji_di');
            image = new Image(texture);
            image.x = 190;
            image.y = 360;
            image.width = 73;
            image.height = 63;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_90wupingkuang0')
            box2 = new Image(texture);
            box2.x = 427;
            box2.y = 170;
            box2.width = 92;
            box2.height = 91;
            this.addQuiackChild(box2);
            box2.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_90wupingkuang0')
            box4 = new Image(texture);
            box4.x = 426;
            box4.y = 279;
            box4.width = 92;
            box4.height = 91;
            this.addQuiackChild(box4);
            box4.touchable = false;
            texture = assetMgr.getTexture('ui_yingxiongshengdian_wuqikuangbiaozhi2');
            Equip2 = new Button(texture);
            Equip2.name = 'Equip2';
            Equip2.x = 444;
            Equip2.y = 185;
            Equip2.width = 57;
            Equip2.height = 59;
            this.addQuiackChild(Equip2);
            texture = assetMgr.getTexture('ui_yingxiongshengdian_wuqikuangbiaozhi3');
            Equip3 = new Button(texture);
            Equip3.name = 'Equip3';
            Equip3.x = 131;
            Equip3.y = 289;
            Equip3.width = 49;
            Equip3.height = 69;
            this.addQuiackChild(Equip3);
            texture = assetMgr.getTexture('ui_yingxiongshengdian_wuqikuangbiaozhi4');
            Equip4 = new Button(texture);
            Equip4.name = 'Equip4';
            Equip4.x = 444;
            Equip4.y = 294;
            Equip4.width = 56;
            Equip4.height = 59;
            this.addQuiackChild(Equip4);
            texture = assetMgr.getTexture('ui_gongyong_wenzitouming_di')
            sumbg3 = new Image(texture);
            sumbg3.x = 163;
            sumbg3.y = 332;
            sumbg3.width = 30;
            sumbg3.height = 30;
            this.addQuiackChild(sumbg3);
            sumbg3.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_lvjiahao')
            sum3 = new Image(texture);
            sum3.x = 170;
            sum3.y = 337;
            sum3.width = 18;
            sum3.height = 20;
            this.addQuiackChild(sum3);
            sum3.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_wenzitouming_di')
            sumbg4 = new Image(texture);
            sumbg4.x = 480;
            sumbg4.y = 331;
            sumbg4.width = 30;
            sumbg4.height = 30;
            this.addQuiackChild(sumbg4);
            sumbg4.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_lvjiahao')
            sum4 = new Image(texture);
            sum4.x = 487;
            sum4.y = 336;
            sum4.width = 18;
            sum4.height = 20;
            this.addQuiackChild(sum4);
            sum4.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_wenzitouming_di')
            sumbg2 = new Image(texture);
            sumbg2.x = 480;
            sumbg2.y = 222;
            sumbg2.width = 30;
            sumbg2.height = 30;
            this.addQuiackChild(sumbg2);
            sumbg2.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_lvjiahao')
            sum2 = new Image(texture);
            sum2.x = 487;
            sum2.y = 227;
            sum2.width = 18;
            sum2.height = 20;
            this.addQuiackChild(sum2);
            sum2.touchable = false;
            texture = assetMgr.getTexture('ui_yongxiongdengji_exp');
            image = new Image(texture);
            image.x = 268;
            image.y = 399;
            image.width = 95;
            image.height = 19;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_zhiwanzidi_wenzikuang');
            image = new Image(texture);
            image.x = 602;
            image.y = 121;
            image.width = 26;
            image.height = 36;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_zhiwanzidi_wenzikuang1');
            image = new Image(texture);
            image.x = 614;
            image.y = 121;
            image.width = 158;
            image.height = 36;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_zhiwanzidi_wenzikuang');
            image = new Image(texture);
            image.x = 785;
            image.y = 121;
            image.width = 26;
            image.height = 36;
            image.scaleX = -1.09063720703125;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_shuxingwenzidi');
            image = new Image(texture);
            image.x = 609;
            image.y = 166;
            image.width = 172;
            image.height = 27;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_tubiao_gongjilitubiao');
            attackIcon = new Button(texture);
            attackIcon.name = 'attackIcon';
            attackIcon.x = 599;
            attackIcon.y = 163;
            attackIcon.width = 20;
            attackIcon.height = 33;
            this.addQuiackChild(attackIcon);
            texture = assetMgr.getTexture('ui_gongyong_shuxingwenzidi');
            image = new Image(texture);
            image.x = 609;
            image.y = 206;
            image.width = 172;
            image.height = 27;
            image.touchable = false;
            image.smoothing = Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_tubiao_xueliangtubiao');
            hpIcon = new Button(texture);
            hpIcon.name = 'hpIcon';
            hpIcon.x = 592;
            hpIcon.y = 204;
            hpIcon.width = 34;
            hpIcon.height = 31;
            this.addQuiackChild(hpIcon);
            texture = assetMgr.getTexture('ui_yingxiongshengdian_wuqikuangbiaozhi1');
            Equip1 = new Button(texture);
            Equip1.name = 'Equip1';
            Equip1.x = 126;
            Equip1.y = 180;
            Equip1.width = 61;
            Equip1.height = 72;
            this.addQuiackChild(Equip1);
            texture = assetMgr.getTexture('ui_gongyong_wenzitouming_di')
            sumbg1 = new Image(texture);
            sumbg1.x = 163;
            sumbg1.y = 222;
            sumbg1.width = 30;
            sumbg1.height = 30;
            this.addQuiackChild(sumbg1);
            sumbg1.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_lvjiahao')
            sum1 = new Image(texture);
            sum1.x = 170;
            sum1.y = 227;
            sum1.width = 18;
            sum1.height = 20;
            this.addQuiackChild(sum1);
            sum1.touchable = false;
        }

        override public function dispose():void {
            look.dispose();
            Equip2.dispose();
            Equip3.dispose();
            Equip4.dispose();
            attackIcon.dispose();
            hpIcon.dispose();
            Equip1.dispose();
            super.dispose();

        }
    }
}
