package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.controls.List;
    import com.dialog.Dialog;

    public class MagicOrbDlaBGBase extends Dialog
    {
        public var btn_close:Button;
        public var text_diamond:TextField;
        public var text_coin:TextField;
        public var list_bag:List;
        public var onPage5:Image;
        public var onPage3:Image;
        public var onPage4:Image;
        public var onPage2:Image;
        public var onPage1:Image;
        public var Page1:Image;
        public var Page2:Image;
        public var Page3:Image;
        public var Page4:Image;
        public var Page5:Image;

        public function MagicOrbDlaBGBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            var assetMgr:AssetMgr = AssetMgr.instance;
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 7;
            image.y = 70;
            image.width = 490;
            image.height = 70;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 925;
            image.y = 70;
            image.width = 490;
            image.height = 70;
            image.scaleX = -0.96868896484375;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 925;
            image.width = 490;
            image.height = 70;
            image.scaleX = -0.96868896484375;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 7;
            image.width = 490;
            image.height = 70;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 7;
            image.y = 140;
            image.width = 490;
            image.height = 70;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 925;
            image.y = 140;
            image.width = 490;
            image.height = 70;
            image.scaleX = -0.96868896484375;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 7;
            image.y = 210;
            image.width = 490;
            image.height = 70;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 925;
            image.y = 210;
            image.width = 490;
            image.height = 70;
            image.scaleX = -0.96868896484375;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian_hei');
            image = new Image(texture);
            image.x = 863;
            image.y = 342;
            image.width = 40;
            image.height = 261;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 7;
            image.y = 281;
            image.width = 490;
            image.height = 70;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 925;
            image.y = 281;
            image.width = 490;
            image.height = 70;
            image.scaleX = -0.96868896484375;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 7;
            image.y = 351;
            image.width = 490;
            image.height = 70;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 925;
            image.y = 351;
            image.width = 490;
            image.height = 70;
            image.scaleX = -0.96868896484375;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 7;
            image.y = 421;
            image.width = 490;
            image.height = 70;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 925;
            image.y = 421;
            image.width = 490;
            image.height = 70;
            image.scaleX = -0.96868896484375;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian_hei');
            image = new Image(texture);
            image.x = 864;
            image.y = 214;
            image.width = 40;
            image.height = 261;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou1');
            image = new Image(texture);
            image.x = 919;
            image.y = 633;
            image.width = 896;
            image.height = 24;
            image.scaleX = -11.19488525390625;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou1');
            image = new Image(texture);
            image.x = 917;
            image.y = 495;
            image.width = 896;
            image.height = 24;
            image.scaleX = -11.19488525390625;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou2');
            image = new Image(texture);
            image.x = 928;
            image.y = 512;
            image.width = 26;
            image.height = 102;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou2');
            image = new Image(texture);
            image.x = 3;
            image.y = 508;
            image.width = 26;
            image.height = 102;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.y = 494;
            image.width = 38;
            image.height = 34;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.y = 634;
            image.width = 38;
            image.height = 34;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 932;
            image.y = 494;
            image.width = 38;
            image.height = 34;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 932;
            image.y = 634;
            image.width = 38;
            image.height = 34;
            image.scaleX = -1;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian1_hei');
            image = new Image(texture);
            image.x = 31;
            image.y = 323;
            image.width = 20;
            image.height = 242;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian1_hei');
            image = new Image(texture);
            image.x = 30;
            image.y = 233;
            image.width = 20;
            image.height = 242;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian2_hei');
            image = new Image(texture);
            image.x = 43;
            image.y = 475;
            image.width = 822;
            image.height = 47;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian3_hei');
            image = new Image(texture);
            image.x = 44;
            image.y = 116;
            image.width = 837;
            image.height = 329;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian2_hei');
            image = new Image(texture);
            image.x = 49;
            image.y = 81;
            image.width = 839;
            image.height = 47;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_bumangdi_shangbianyikuaitie');
            image = new Image(texture);
            image.x = 748;
            image.y = 495;
            image.width = 30;
            image.height = 21;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_bumangdi_shangbianyikuaitie');
            image = new Image(texture);
            image.x = 150;
            image.y = 495;
            image.width = 30;
            image.height = 21;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_bumangdi_shangbianyikuaitie');
            image = new Image(texture);
            image.x = 748;
            image.y = 496;
            image.width = 30;
            image.height = 21;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_bumangdi_shangbianyikuaitie');
            image = new Image(texture);
            image.x = 150;
            image.y = 496;
            image.width = 30;
            image.height = 21;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_lianziguanbianniu');
            btn_close = new Button(texture);
            btn_close.name= 'btn_close';
            btn_close.x = 810;
            btn_close.y = -75;
            btn_close.width = 87;
            btn_close.height = 156;
            this.addQuiackChild(btn_close);
            texture =assetMgr.getTexture('ui_gongyong_jinbibaiziwenzidi');
            image = new Image(texture);
            image.x = 491;
            image.y = 20;
            image.width = 154;
            image.height = 43;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_jinbibaiziwenzidi');
            image = new Image(texture);
            image.x = 658;
            image.y = 19;
            image.width = 154;
            image.height = 43;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_money');
            image = new Image(texture);
            image.x = 645;
            image.y = 20;
            image.width = 40;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_zuanshi');
            image = new Image(texture);
            image.x = 477;
            image.y = 19;
            image.width = 46;
            image.height = 44;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            text_diamond = new TextField(156,31,'','',21,0xFFFFFF,false);
            text_diamond.touchable = false;
            text_diamond.hAlign= 'right';
            text_diamond.text= '9999999';
            text_diamond.x = 481;
            text_diamond.y = 26;
            this.addQuiackChild(text_diamond);
            text_coin = new TextField(155,31,'','',21,0xFFFFFF,false);
            text_coin.touchable = false;
            text_coin.hAlign= 'right';
            text_coin.text= '9999999';
            text_coin.x = 650;
            text_coin.y = 26;
            this.addQuiackChild(text_coin);
            list_bag = new List();
            list_bag.x = 41;
            list_bag.y = 85;
            list_bag.width = 850;
            list_bag.height = 385;
            this.addQuiackChild(list_bag);
            texture = assetMgr.getTexture('ui_gongyong_yemianqiehuan2')
            onPage5 = new Image(texture);
            onPage5.x = 533;
            onPage5.y = 426;
            onPage5.width = 33;
            onPage5.height = 30;
            this.addQuiackChild(onPage5);
            onPage5.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_yemianqiehuan2')
            onPage3 = new Image(texture);
            onPage3.x = 450;
            onPage3.y = 426;
            onPage3.width = 33;
            onPage3.height = 30;
            this.addQuiackChild(onPage3);
            onPage3.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_yemianqiehuan2')
            onPage4 = new Image(texture);
            onPage4.x = 491;
            onPage4.y = 426;
            onPage4.width = 33;
            onPage4.height = 30;
            this.addQuiackChild(onPage4);
            onPage4.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_yemianqiehuan2')
            onPage2 = new Image(texture);
            onPage2.x = 407;
            onPage2.y = 426;
            onPage2.width = 33;
            onPage2.height = 30;
            this.addQuiackChild(onPage2);
            onPage2.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_yemianqiehuan2')
            onPage1 = new Image(texture);
            onPage1.x = 365;
            onPage1.y = 426;
            onPage1.width = 33;
            onPage1.height = 30;
            this.addQuiackChild(onPage1);
            onPage1.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_yemianqiehuan1')
            Page1 = new Image(texture);
            Page1.x = 365;
            Page1.y = 426;
            Page1.width = 33;
            Page1.height = 30;
            this.addQuiackChild(Page1);
            Page1.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_yemianqiehuan1')
            Page2 = new Image(texture);
            Page2.x = 407;
            Page2.y = 426;
            Page2.width = 33;
            Page2.height = 30;
            this.addQuiackChild(Page2);
            Page2.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_yemianqiehuan1')
            Page3 = new Image(texture);
            Page3.x = 450;
            Page3.y = 426;
            Page3.width = 33;
            Page3.height = 30;
            this.addQuiackChild(Page3);
            Page3.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_yemianqiehuan1')
            Page4 = new Image(texture);
            Page4.x = 491;
            Page4.y = 426;
            Page4.width = 33;
            Page4.height = 30;
            this.addQuiackChild(Page4);
            Page4.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_yemianqiehuan1')
            Page5 = new Image(texture);
            Page5.x = 533;
            Page5.y = 426;
            Page5.width = 33;
            Page5.height = 30;
            this.addQuiackChild(Page5);
            Page5.touchable = false;
            init();
        }
        override public function dispose():void
        {
            btn_close.dispose();
            list_bag.dispose();
            super.dispose();
        
}
    }
}
