package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import feathers.controls.renderers.DefaultListItemRenderer;

    public class MagicSwallowViewBase extends DefaultListItemRenderer
    {
        public var btn_Fix:Button;
        public var text_fixEngulfMagic:TextField;
        public var ui_gongyong_hero_pub_9gongge_article33511:Scale9Image;
        public var SelectQuality:Image;
        public var SelectIco:Image;
        public var text_Lv1:TextField;
        public var text_Lv2:TextField;
        public var bg:Scale9Image;
        public var bgNextExp:Scale9Image;
        public var bgCurrentExp:Scale9Image;
        public var text_Lv3:TextField;
        public var text_CurrentLevel:TextField;
        public var text_attack1:TextField;
        public var text_currentProperty:TextField;
        public var text_NextLevel:TextField;
        public var text_attack2:TextField;
        public var text_nextProperty:TextField;
        public var text_useup:TextField;
        public var text_money:TextField;
        public var cancel:Button;
        public var moneyIco:Image;
        public var btn_Select:Button;
        public var text_selectMagic:TextField;
        public var text_currentExp:TextField;
        public var text_addOrb:TextField;
        public var btn_addOrb:Button;
        public var text_Prompt:TextField;

        public function MagicSwallowViewBase()
        {
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            var assetMgr:AssetMgr = AssetMgr.instance;
            texture = assetMgr.getTexture('ui_button_tiebaomutouanjian');
            btn_Fix = new Button(texture);
            btn_Fix.name= 'btn_Fix';
            btn_Fix.x = 747;
            btn_Fix.y = 519;
            btn_Fix.width = 150;
            btn_Fix.height = 64;
            this.addQuiackChild(btn_Fix);
            text_fixEngulfMagic = new TextField(141,41,'','',28,0xFFECD3,false);
            text_fixEngulfMagic.touchable = false;
            text_fixEngulfMagic.hAlign= 'center';
            text_fixEngulfMagic.text= '';
            text_fixEngulfMagic.x = 751;
            text_fixEngulfMagic.y = 527;
            this.addQuiackChild(text_fixEngulfMagic);
            texture = assetMgr.getTexture('ui_gongyong_hero_pub_9gongge_article');
            var ui_gongyong_hero_pub_9gongge_article33511Rect:Rectangle = new Rectangle(16,16,31,31);
            var ui_gongyong_hero_pub_9gongge_article335119ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_gongyong_hero_pub_9gongge_article33511Rect);
            ui_gongyong_hero_pub_9gongge_article33511 = new Scale9Image(ui_gongyong_hero_pub_9gongge_article335119ScaleTexture);
            ui_gongyong_hero_pub_9gongge_article33511.x = 33;
            ui_gongyong_hero_pub_9gongge_article33511.y = 511;
            ui_gongyong_hero_pub_9gongge_article33511.width = 104;
            ui_gongyong_hero_pub_9gongge_article33511.height = 104;
            this.addQuiackChild(ui_gongyong_hero_pub_9gongge_article33511);
            texture =assetMgr.getTexture('ui_gongyong_90wupingkuang');
            image = new Image(texture);
            image.x = 40;
            image.y = 519;
            image.width = 90;
            image.height = 90;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_90wupingkuang0')
            SelectQuality = new Image(texture);
            SelectQuality.x = 40;
            SelectQuality.y = 518;
            SelectQuality.width = 90;
            SelectQuality.height = 90;
            this.addQuiackChild(SelectQuality);
            SelectQuality.touchable = false;
            texture = assetMgr.getTexture('icon_1208')
            SelectIco = new Image(texture);
            SelectIco.x = 42;
            SelectIco.y = 516;
            SelectIco.width = 89;
            SelectIco.height = 89;
            this.addQuiackChild(SelectIco);
            SelectIco.touchable = false;
            text_Lv1 = new TextField(76,32,'','',24,0xFFFFFF,false);
            text_Lv1.touchable = false;
            text_Lv1.hAlign= 'left';
            text_Lv1.text= '';
            text_Lv1.x = 48;
            text_Lv1.y = 524;
            this.addQuiackChild(text_Lv1);
            text_Lv2 = new TextField(100,36,'','',24,0xFFFFFF,false);
            text_Lv2.touchable = false;
            text_Lv2.hAlign= 'center';
            text_Lv2.text= '';
            text_Lv2.x = 143;
            text_Lv2.y = 528;
            this.addQuiackChild(text_Lv2);
            texture = assetMgr.getTexture('ui_baozhu_jingyantiao1');
            var bgRect:Rectangle = new Rectangle(24,7,49,14);
            var bg9ScaleTexture:Scale9Textures = new Scale9Textures(texture,bgRect);
            bg = new Scale9Image(bg9ScaleTexture);
            bg.x = 243;
            bg.y = 533;
            bg.width = 420;
            bg.height = 28;
            this.addQuiackChild(bg);
            texture = assetMgr.getTexture('ui_baozhu_jingyantiao3');
            var bgNextExpRect:Rectangle = new Rectangle(22,13,44,12);
            var bgNextExp9ScaleTexture:Scale9Textures = new Scale9Textures(texture,bgNextExpRect);
            bgNextExp = new Scale9Image(bgNextExp9ScaleTexture);
            bgNextExp.x = 250;
            bgNextExp.y = 529;
            bgNextExp.width = 150;
            bgNextExp.height = 37;
            this.addQuiackChild(bgNextExp);
            texture = assetMgr.getTexture('ui_baozhu_jingyantiao2');
            var bgCurrentExpRect:Rectangle = new Rectangle(22,10,44,19);
            var bgCurrentExp9ScaleTexture:Scale9Textures = new Scale9Textures(texture,bgCurrentExpRect);
            bgCurrentExp = new Scale9Image(bgCurrentExp9ScaleTexture);
            bgCurrentExp.x = 250;
            bgCurrentExp.y = 530;
            bgCurrentExp.width = 150;
            bgCurrentExp.height = 35;
            this.addQuiackChild(bgCurrentExp);
            text_Lv3 = new TextField(100,36,'','',24,0xFFFFFF,false);
            text_Lv3.touchable = false;
            text_Lv3.hAlign= 'center';
            text_Lv3.text= '';
            text_Lv3.x = 648;
            text_Lv3.y = 528;
            this.addQuiackChild(text_Lv3);
            text_CurrentLevel = new TextField(85,30,'','',20,0xFFFFCC,false);
            text_CurrentLevel.touchable = false;
            text_CurrentLevel.hAlign= 'center';
            text_CurrentLevel.text= '';
            text_CurrentLevel.x = 168;
            text_CurrentLevel.y = 576;
            this.addQuiackChild(text_CurrentLevel);
            text_attack1 = new TextField(54,36,'','',24,0xFFFFFF,false);
            text_attack1.touchable = false;
            text_attack1.hAlign= 'center';
            text_attack1.text= '';
            text_attack1.x = 256;
            text_attack1.y = 571;
            this.addQuiackChild(text_attack1);
            text_currentProperty = new TextField(104,30,'','',20,0xFFFFCC,false);
            text_currentProperty.touchable = false;
            text_currentProperty.hAlign= 'left';
            text_currentProperty.text= '';
            text_currentProperty.x = 313;
            text_currentProperty.y = 576;
            this.addQuiackChild(text_currentProperty);
            text_NextLevel = new TextField(88,30,'','',20,0xFFFFCC,false);
            text_NextLevel.touchable = false;
            text_NextLevel.hAlign= 'center';
            text_NextLevel.text= '';
            text_NextLevel.x = 418;
            text_NextLevel.y = 577;
            this.addQuiackChild(text_NextLevel);
            text_attack2 = new TextField(54,36,'','',24,0xFFFFFF,false);
            text_attack2.touchable = false;
            text_attack2.hAlign= 'center';
            text_attack2.text= '';
            text_attack2.x = 505;
            text_attack2.y = 572;
            this.addQuiackChild(text_attack2);
            text_nextProperty = new TextField(181,30,'','',20,0xFFFFCC,false);
            text_nextProperty.touchable = false;
            text_nextProperty.hAlign= 'left';
            text_nextProperty.text= '';
            text_nextProperty.x = 561;
            text_nextProperty.y = 577;
            this.addQuiackChild(text_nextProperty);
            text_useup = new TextField(50,30,'','',20,0xFF0000,false);
            text_useup.touchable = false;
            text_useup.hAlign= 'center';
            text_useup.text= '';
            text_useup.x = 747;
            text_useup.y = 583;
            this.addQuiackChild(text_useup);
            text_money = new TextField(86,30,'','',18,0xFFFFCC,false);
            text_money.touchable = false;
            text_money.hAlign= 'center';
            text_money.text= '';
            text_money.x = 821;
            text_money.y = 583;
            this.addQuiackChild(text_money);
            texture = assetMgr.getTexture('ui_button_quxiaoanniu');
            cancel = new Button(texture);
            cancel.name= 'cancel';
            cancel.x = 789;
            cancel.y = 422;
            cancel.width = 69;
            cancel.height = 44;
            this.addQuiackChild(cancel);
            texture = assetMgr.getTexture('ui_gongyong_money')
            moneyIco = new Image(texture);
            moneyIco.x = 795;
            moneyIco.y = 582;
            moneyIco.width = 30;
            moneyIco.height = 30;
            this.addQuiackChild(moneyIco);
            moneyIco.touchable = false;
            texture = assetMgr.getTexture('ui_button_tiebaomutouanjian');
            btn_Select = new Button(texture);
            btn_Select.name= 'btn_Select';
            btn_Select.x = 747;
            btn_Select.y = 533;
            btn_Select.width = 150;
            btn_Select.height = 64;
            this.addQuiackChild(btn_Select);
            text_selectMagic = new TextField(141,41,'','',28,0xFFECD3,false);
            text_selectMagic.touchable = false;
            text_selectMagic.hAlign= 'center';
            text_selectMagic.text= '';
            text_selectMagic.x = 750;
            text_selectMagic.y = 544;
            this.addQuiackChild(text_selectMagic);
            text_currentExp = new TextField(400,30,'','',20,0xFFFFFF,false);
            text_currentExp.touchable = false;
            text_currentExp.hAlign= 'center';
            text_currentExp.text= '';
            text_currentExp.x = 244;
            text_currentExp.y = 534;
            this.addQuiackChild(text_currentExp);
            text_addOrb = new TextField(104,30,'','',18,0x2AFF00,false);
            text_addOrb.touchable = false;
            text_addOrb.hAlign= 'center';
            text_addOrb.text= '';
            text_addOrb.x = 33;
            text_addOrb.y = 577;
            this.addQuiackChild(text_addOrb);
            texture = assetMgr.getTexture('ui_baozhu_tianjiabaozhu_jiahao');
            btn_addOrb = new Button(texture);
            btn_addOrb.name= 'btn_addOrb';
            btn_addOrb.x = 59;
            btn_addOrb.y = 526;
            btn_addOrb.width = 50;
            btn_addOrb.height = 50;
            this.addQuiackChild(btn_addOrb);
            text_Prompt = new TextField(766,28,'','',20,0xFAF0CD,false);
            text_Prompt.touchable = false;
            text_Prompt.hAlign= 'center';
            text_Prompt.text= '';
            text_Prompt.x = 131;
            text_Prompt.y = 546;
            this.addQuiackChild(text_Prompt);
        }
        override public function dispose():void
        {
            btn_Fix.dispose();
            cancel.dispose();
            btn_Select.dispose();
            btn_addOrb.dispose();
            super.dispose();
        
}
    }
}
