package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import game.scene.world.NewMapRender;

    public class map_world_1Base extends NewMapRender
    {
        public var view_bg:Sprite;
        public var tag_25:Button;
        public var tag_26:Button;
        public var tag_27:Button;
        public var tag_28:Button;
        public var tag_29:Button;
        public var tag_30:Button;
        public var tag_31:Button;
        public var tag_32:Button;
        public var tag_33:Button;
        public var tag_34:Button;
        public var tag_35:Button;
        public var tag_36:Button;
        public var tag_37:Button;
        public var tag_38:Button;
        public var tag_39:Button;
        public var tag_40:Button;
        public var tag_41:Button;
        public var tag_42:Button;
        public var tag_43:Button;
        public var tag_44:Button;
        public var tag_45:Button;

        public function map_world_1Base()
        {
            var texture:Texture;
            var textField:TextField;
            var image:Image;
            var button:Button;;
            var assetMgr:AssetMgr = AssetMgr.instance;
            view_bg = new Sprite();
            view_bg.width = 966;
            view_bg.height = 640;
            this.addQuiackChild(view_bg);
            view_bg.name= 'view_bg';
            texture =assetMgr.getTexture('worldmap_background2');
            image = new Image(texture);
            image.x = 221;
            image.width = 237;
            image.height = 640;
            image.smoothing= Constants.NONE;
            view_bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_background2');
            image = new Image(texture);
            image.x = 456;
            image.width = 237;
            image.height = 640;
            image.smoothing= Constants.NONE;
            view_bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_background2');
            image = new Image(texture);
            image.x = 543;
            image.width = 237;
            image.height = 640;
            image.smoothing= Constants.NONE;
            view_bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_background2');
            image = new Image(texture);
            image.width = 237;
            image.height = 640;
            image.smoothing= Constants.NONE;
            view_bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_background2');
            image = new Image(texture);
            image.x = 729;
            image.width = 237;
            image.height = 640;
            image.smoothing= Constants.NONE;
            view_bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree9');
            image = new Image(texture);
            image.x = 618;
            image.y = 177;
            image.width = 98;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree9');
            image = new Image(texture);
            image.x = 655;
            image.y = 220;
            image.width = 98;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = -70;
            image.y = 114;
            image.width = 108;
            image.height = 135;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = -74;
            image.y = 203;
            image.width = 108;
            image.height = 135;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = -60;
            image.y = 267;
            image.width = 108;
            image.height = 135;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 43;
            image.y = 350;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 177;
            image.y = 345;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 102;
            image.y = 344;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 93;
            image.y = 376;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 170;
            image.y = 388;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 261;
            image.y = 373;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 230;
            image.y = 402;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 261;
            image.y = 438;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 162;
            image.y = 435;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_rift1');
            image = new Image(texture);
            image.x = 558;
            image.y = 364;
            image.width = 257;
            image.height = 100;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert8');
            image = new Image(texture);
            image.x = 539;
            image.y = 370;
            image.width = 101;
            image.height = 63;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert7');
            image = new Image(texture);
            image.x = 489;
            image.y = 414;
            image.width = 62;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert8');
            image = new Image(texture);
            image.x = 590;
            image.y = 439;
            image.width = 101;
            image.height = 63;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert8');
            image = new Image(texture);
            image.x = 715;
            image.y = 401;
            image.width = 101;
            image.height = 63;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert8');
            image = new Image(texture);
            image.x = 507;
            image.y = 420;
            image.width = 101;
            image.height = 63;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 473;
            image.y = 534;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 621;
            image.y = 531;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 558;
            image.y = 531;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 608;
            image.y = 508;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 697;
            image.y = 531;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 372;
            image.y = 364;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 399;
            image.y = 408;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 473;
            image.y = 358;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 363;
            image.y = 448;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave3');
            image = new Image(texture);
            image.x = 522;
            image.y = 513;
            image.width = 45;
            image.height = 42;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 355;
            image.y = 391;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 307;
            image.y = 416;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 683;
            image.y = 265;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 834;
            image.y = 126;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree10');
            image = new Image(texture);
            image.x = 726;
            image.y = 142;
            image.width = 177;
            image.height = 131;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 715;
            image.y = 256;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree9');
            image = new Image(texture);
            image.x = 732;
            image.y = 220;
            image.width = 98;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 834;
            image.y = 207;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain4');
            image = new Image(texture);
            image.x = 767;
            image.y = 260;
            image.width = 136;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 707;
            image.y = 270;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 707;
            image.y = 297;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 655;
            image.y = 268;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 677;
            image.y = 285;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 635;
            image.y = 256;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 609;
            image.y = 273;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 635;
            image.y = 288;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 577;
            image.y = 263;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 551;
            image.y = 263;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_rift2');
            image = new Image(texture);
            image.x = 383;
            image.y = 203;
            image.width = 194;
            image.height = 138;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_city1');
            image = new Image(texture);
            image.x = 700;
            image.y = 185;
            image.width = 80;
            image.height = 66;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain4');
            image = new Image(texture);
            image.x = 431;
            image.y = 172;
            image.width = 136;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert7');
            image = new Image(texture);
            image.x = 481;
            image.y = 236;
            image.width = 62;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert7');
            image = new Image(texture);
            image.x = 412;
            image.y = 203;
            image.width = 62;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert7');
            image = new Image(texture);
            image.x = 387;
            image.y = 273;
            image.width = 62;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain4');
            image = new Image(texture);
            image.x = 466;
            image.y = 214;
            image.width = 136;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain9');
            image = new Image(texture);
            image.x = 590;
            image.y = 240;
            image.width = 35;
            image.height = 28;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = -55;
            image.y = 149;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = -22;
            image.y = 241;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 13;
            image.y = 335;
            image.width = 108;
            image.height = 135;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 173;
            image.y = 60;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain4');
            image = new Image(texture);
            image.x = 330;
            image.y = 149;
            image.width = 136;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 215;
            image.y = 190;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert3');
            image = new Image(texture);
            image.x = 202;
            image.y = 286;
            image.width = 105;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert3');
            image = new Image(texture);
            image.x = 232;
            image.y = 338;
            image.width = 105;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert3');
            image = new Image(texture);
            image.x = 337;
            image.y = 281;
            image.width = 105;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert3');
            image = new Image(texture);
            image.x = 121;
            image.y = 293;
            image.width = 105;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert3');
            image = new Image(texture);
            image.x = 107;
            image.y = 221;
            image.width = 105;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert3');
            image = new Image(texture);
            image.x = 147;
            image.y = 106;
            image.width = 105;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 34;
            image.y = 15;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree9');
            image = new Image(texture);
            image.x = 746;
            image.y = 16;
            image.width = 98;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree9');
            image = new Image(texture);
            image.x = 567;
            image.y = 158;
            image.width = 98;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 418;
            image.y = 559;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 524;
            image.y = 558;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 351;
            image.y = 524;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 291;
            image.y = 546;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 249;
            image.y = 60;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 330;
            image.y = 35;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 391;
            image.y = 60;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 351;
            image.y = 577;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 230;
            image.y = 564;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 220;
            image.y = 503;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 425;
            image.y = 517;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 590;
            image.y = 583;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 104;
            image.y = 567;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 226;
            image.y = 531;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 154;
            image.y = 510;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 95;
            image.y = 532;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 145;
            image.y = 544;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 34;
            image.y = 550;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 669;
            image.y = 152;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 707;
            image.y = 142;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 642;
            image.y = 138;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 579;
            image.y = 50;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 804;
            image.y = 23;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 873;
            image.y = 46;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 442;
            image.y = 16;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 514;
            image.y = 35;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 584;
            image.y = 48;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 539;
            image.y = 61;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 644;
            image.y = 16;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 655;
            image.y = 60;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 91;
            image.y = 492;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 34;
            image.y = 506;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 97;
            image.y = 408;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert8');
            image = new Image(texture);
            image.x = 204;
            image.y = 445;
            image.width = 101;
            image.height = 63;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert8');
            image = new Image(texture);
            image.x = 428;
            image.y = 454;
            image.width = 101;
            image.height = 63;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 646;
            image.y = 558;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 780;
            image.y = 536;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 750;
            image.y = 560;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 798;
            image.y = 542;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain4');
            image = new Image(texture);
            image.x = 818;
            image.y = 496;
            image.width = 136;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 849;
            image.y = 300;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 876;
            image.y = 389;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain4');
            image = new Image(texture);
            image.x = 777;
            image.y = 431;
            image.width = 136;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree9');
            image = new Image(texture);
            image.x = 775;
            image.y = 51;
            image.width = 98;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 742;
            image.y = 276;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian1');
            image = new Image(texture);
            image.x = 516;
            image.y = 488;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian1');
            image = new Image(texture);
            image.x = 395;
            image.y = 498;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian3');
            image = new Image(texture);
            image.x = 215;
            image.y = 142;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian1');
            image = new Image(texture);
            image.x = 440;
            image.y = 117;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian1');
            image = new Image(texture);
            image.x = 690;
            image.y = 116;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian2');
            image = new Image(texture);
            image.x = 736;
            image.y = 324;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian4');
            image = new Image(texture);
            image.x = 850;
            image.y = 469;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian1');
            image = new Image(texture);
            image.x = 770;
            image.y = 496;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian7');
            image = new Image(texture);
            image.x = 873;
            image.y = 379;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian1');
            image = new Image(texture);
            image.x = 518;
            image.y = 329;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian1');
            image = new Image(texture);
            image.x = 631;
            image.y = 331;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian1');
            image = new Image(texture);
            image.x = 640;
            image.y = 491;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian1');
            image = new Image(texture);
            image.x = 584;
            image.y = 115;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian1');
            image = new Image(texture);
            image.x = 326;
            image.y = 121;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian1');
            image = new Image(texture);
            image.x = 784;
            image.y = 120;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian1');
            image = new Image(texture);
            image.x = 369;
            image.y = 331;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian2');
            image = new Image(texture);
            image.x = 215;
            image.y = 250;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian5');
            image = new Image(texture);
            image.x = 290;
            image.y = 317;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian5');
            image = new Image(texture);
            image.x = 281;
            image.y = 475;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian1');
            image = new Image(texture);
            image.x = 118;
            image.y = 454;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian1');
            image = new Image(texture);
            image.x = 8;
            image.y = 448;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_25 = new Button(texture);
            tag_25.name= 'tag_25';
            tag_25.x = 84;
            tag_25.y = 470;
            tag_25.width = 90;
            tag_25.height = 90;
            this.addQuiackChild(tag_25);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_26 = new Button(texture);
            tag_26.name= 'tag_26';
            tag_26.x = 202;
            tag_26.y = 478;
            tag_26.width = 90;
            tag_26.height = 90;
            this.addQuiackChild(tag_26);
            texture = assetMgr.getTexture('ui_zhuxian_boss_baozi');
            tag_27 = new Button(texture);
            tag_27.name= 'tag_27';
            tag_27.x = 340;
            tag_27.y = 511;
            tag_27.width = 90;
            tag_27.height = 90;
            this.addQuiackChild(tag_27);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_28 = new Button(texture);
            tag_28.name= 'tag_28';
            tag_28.x = 479;
            tag_28.y = 515;
            tag_28.width = 90;
            tag_28.height = 90;
            this.addQuiackChild(tag_28);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_29 = new Button(texture);
            tag_29.name= 'tag_29';
            tag_29.x = 599;
            tag_29.y = 509;
            tag_29.width = 90;
            tag_29.height = 90;
            this.addQuiackChild(tag_29);
            texture = assetMgr.getTexture('ui_zhuxian_boss_baozi');
            tag_30 = new Button(texture);
            tag_30.name= 'tag_30';
            tag_30.x = 725;
            tag_30.y = 510;
            tag_30.width = 90;
            tag_30.height = 90;
            this.addQuiackChild(tag_30);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_31 = new Button(texture);
            tag_31.name= 'tag_31';
            tag_31.x = 834;
            tag_31.y = 512;
            tag_31.width = 90;
            tag_31.height = 90;
            this.addQuiackChild(tag_31);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_32 = new Button(texture);
            tag_32.name= 'tag_32';
            tag_32.x = 892;
            tag_32.y = 443;
            tag_32.width = 90;
            tag_32.height = 90;
            this.addQuiackChild(tag_32);
            texture = assetMgr.getTexture('ui_zhuxian_bigboss_airenguowang');
            tag_33 = new Button(texture);
            tag_33.name= 'tag_33';
            tag_33.x = 840;
            tag_33.y = 336;
            tag_33.width = 120;
            tag_33.height = 120;
            this.addQuiackChild(tag_33);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_34 = new Button(texture);
            tag_34.name= 'tag_34';
            tag_34.x = 708;
            tag_34.y = 349;
            tag_34.width = 90;
            tag_34.height = 90;
            this.addQuiackChild(tag_34);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_35 = new Button(texture);
            tag_35.name= 'tag_35';
            tag_35.x = 590;
            tag_35.y = 345;
            tag_35.width = 90;
            tag_35.height = 90;
            this.addQuiackChild(tag_35);
            texture = assetMgr.getTexture('ui_zhuxian_boss_baozi');
            tag_36 = new Button(texture);
            tag_36.name= 'tag_36';
            tag_36.x = 463;
            tag_36.y = 336;
            tag_36.width = 90;
            tag_36.height = 90;
            this.addQuiackChild(tag_36);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_37 = new Button(texture);
            tag_37.name= 'tag_37';
            tag_37.x = 330;
            tag_37.y = 349;
            tag_37.width = 90;
            tag_37.height = 90;
            this.addQuiackChild(tag_37);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_38 = new Button(texture);
            tag_38.name= 'tag_38';
            tag_38.x = 224;
            tag_38.y = 307;
            tag_38.width = 90;
            tag_38.height = 90;
            this.addQuiackChild(tag_38);
            texture = assetMgr.getTexture('ui_zhuxian_boss_baozi');
            tag_39 = new Button(texture);
            tag_39.name= 'tag_39';
            tag_39.x = 181;
            tag_39.y = 201;
            tag_39.width = 90;
            tag_39.height = 90;
            this.addQuiackChild(tag_39);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_40 = new Button(texture);
            tag_40.name= 'tag_40';
            tag_40.x = 288;
            tag_40.y = 147;
            tag_40.width = 90;
            tag_40.height = 90;
            this.addQuiackChild(tag_40);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_41 = new Button(texture);
            tag_41.name= 'tag_41';
            tag_41.x = 402;
            tag_41.y = 137;
            tag_41.width = 90;
            tag_41.height = 90;
            this.addQuiackChild(tag_41);
            texture = assetMgr.getTexture('ui_zhuxian_boss_baozi');
            tag_42 = new Button(texture);
            tag_42.name= 'tag_42';
            tag_42.x = 532;
            tag_42.y = 136;
            tag_42.width = 90;
            tag_42.height = 90;
            this.addQuiackChild(tag_42);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_43 = new Button(texture);
            tag_43.name= 'tag_43';
            tag_43.x = 659;
            tag_43.y = 131;
            tag_43.width = 90;
            tag_43.height = 90;
            this.addQuiackChild(tag_43);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_44 = new Button(texture);
            tag_44.name= 'tag_44';
            tag_44.x = 756;
            tag_44.y = 137;
            tag_44.width = 90;
            tag_44.height = 90;
            this.addQuiackChild(tag_44);
            texture = assetMgr.getTexture('ui_zhuxian_bigboss_airenguowang');
            tag_45 = new Button(texture);
            tag_45.name= 'tag_45';
            tag_45.x = 888;
            tag_45.y = 146;
            tag_45.width = 120;
            tag_45.height = 120;
            this.addQuiackChild(tag_45);
        }
        override public function dispose():void
        {
            view_bg.dispose();
            tag_25.dispose();
            tag_26.dispose();
            tag_27.dispose();
            tag_28.dispose();
            tag_29.dispose();
            tag_30.dispose();
            tag_31.dispose();
            tag_32.dispose();
            tag_33.dispose();
            tag_34.dispose();
            tag_35.dispose();
            tag_36.dispose();
            tag_37.dispose();
            tag_38.dispose();
            tag_39.dispose();
            tag_40.dispose();
            tag_41.dispose();
            tag_42.dispose();
            tag_43.dispose();
            tag_44.dispose();
            tag_45.dispose();
            super.dispose();
        
}
    }
}
