package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import game.scene.world.NewMapRender;

    public class map_world_11Base extends NewMapRender
    {
        public var view_bg:Sprite;
        public var tag_247:Button;
        public var tag_248:Button;
        public var tag_249:Button;
        public var tag_250:Button;
        public var tag_251:Button;
        public var tag_252:Button;
        public var tag_253:Button;
        public var tag_254:Button;
        public var tag_255:Button;
        public var tag_256:Button;
        public var tag_257:Button;
        public var tag_258:Button;
        public var tag_259:Button;
        public var tag_260:Button;
        public var tag_261:Button;
        public var tag_262:Button;
        public var tag_263:Button;
        public var tag_264:Button;

        public function map_world_11Base()
        {
            var texture:Texture;
            var textField:TextField;
            var image:Image;
            var button:Button;;
            var assetMgr:AssetMgr = AssetMgr.instance;
            view_bg = new Sprite();
            view_bg.width = 957;
            view_bg.height = 641;
            this.addQuiackChild(view_bg);
            view_bg.name= 'view_bg';
            texture =assetMgr.getTexture('worldmap_background2');
            image = new Image(texture);
            image.x = 221;
            image.width = 237;
            image.height = 640;
            image.smoothing= Constants.NONE;
            view_bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_background2');
            image = new Image(texture);
            image.x = 436;
            image.width = 237;
            image.height = 640;
            image.smoothing= Constants.NONE;
            view_bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_background2');
            image = new Image(texture);
            image.width = 237;
            image.height = 640;
            image.smoothing= Constants.NONE;
            view_bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_background');
            image = new Image(texture);
            image.x = 957;
            image.width = 288;
            image.height = 641;
            image.scaleX = -1;;
            image.smoothing= Constants.NONE;
            view_bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 539;
            image.y = 161;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree2');
            image = new Image(texture);
            image.x = -148;
            image.y = 39;
            image.width = 161;
            image.height = 138;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = -93;
            image.y = 124;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = -72;
            image.y = 182;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = -72;
            image.y = 245;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = -76;
            image.y = 302;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = -76;
            image.y = 361;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = -76;
            image.y = 411;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree2');
            image = new Image(texture);
            image.x = -24;
            image.y = 18;
            image.width = 161;
            image.height = 138;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree2');
            image = new Image(texture);
            image.x = -58;
            image.y = 68;
            image.width = 161;
            image.height = 138;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 79;
            image.y = 26;
            image.width = 108;
            image.height = 135;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 130;
            image.y = 8;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_lake2');
            image = new Image(texture);
            image.x = 116;
            image.y = 203;
            image.width = 130;
            image.height = 126;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree1');
            image = new Image(texture);
            image.x = -54;
            image.y = 148;
            image.width = 237;
            image.height = 155;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree1');
            image = new Image(texture);
            image.x = 17;
            image.y = 253;
            image.width = 237;
            image.height = 155;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = -19;
            image.y = 233;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.y = 282;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave5');
            image = new Image(texture);
            image.x = 575;
            image.y = 245;
            image.width = 181;
            image.height = 129;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave3');
            image = new Image(texture);
            image.x = 515;
            image.y = 228;
            image.width = 45;
            image.height = 42;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave2');
            image = new Image(texture);
            image.x = 582;
            image.y = 224;
            image.width = 34;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave3');
            image = new Image(texture);
            image.x = 438;
            image.y = 258;
            image.width = 45;
            image.height = 42;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 630;
            image.y = 203;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 701;
            image.y = 374;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 741;
            image.y = 326;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 699;
            image.y = 332;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 748;
            image.y = 382;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 654;
            image.y = 361;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 711;
            image.y = 430;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 754;
            image.y = 456;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 722;
            image.y = 502;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 771;
            image.y = 516;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 682;
            image.y = 541;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave4');
            image = new Image(texture);
            image.x = 754;
            image.y = 431;
            image.width = 51;
            image.height = 41;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave4');
            image = new Image(texture);
            image.x = 667;
            image.y = 404;
            image.width = 51;
            image.height = 41;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave4');
            image = new Image(texture);
            image.x = 714;
            image.y = 474;
            image.width = 51;
            image.height = 41;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 747;
            image.y = 542;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 801;
            image.y = 475;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave4');
            image = new Image(texture);
            image.x = 752;
            image.y = 488;
            image.width = 51;
            image.height = 41;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 784;
            image.y = 355;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave4');
            image = new Image(texture);
            image.x = 739;
            image.y = 359;
            image.width = 51;
            image.height = 41;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 801;
            image.y = 515;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.y = 347;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree2');
            image = new Image(texture);
            image.x = 54;
            image.y = 336;
            image.width = 161;
            image.height = 138;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree2');
            image = new Image(texture);
            image.x = -11;
            image.y = 488;
            image.width = 161;
            image.height = 138;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree2');
            image = new Image(texture);
            image.x = 79;
            image.y = 483;
            image.width = 161;
            image.height = 138;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 172;
            image.y = 512;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 296;
            image.y = 537;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 370;
            image.y = 533;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 457;
            image.y = 529;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 547;
            image.y = 537;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 589;
            image.y = 537;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 64;
            image.y = 74;
            image.width = 108;
            image.height = 135;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain8');
            image = new Image(texture);
            image.x = 134;
            image.y = 116;
            image.width = 129;
            image.height = 97;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 246;
            image.y = 34;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 193;
            image.y = 287;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree2');
            image = new Image(texture);
            image.x = 148;
            image.y = 313;
            image.width = 161;
            image.height = 138;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave4');
            image = new Image(texture);
            image.x = 230;
            image.y = 197;
            image.width = 51;
            image.height = 41;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain4');
            image = new Image(texture);
            image.x = 353;
            image.y = 185;
            image.width = 136;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_house1');
            image = new Image(texture);
            image.x = 307;
            image.y = 198;
            image.width = 83;
            image.height = 70;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_house1');
            image = new Image(texture);
            image.x = 469;
            image.y = 414;
            image.width = 83;
            image.height = 70;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain4');
            image = new Image(texture);
            image.x = 350;
            image.y = 411;
            image.width = 136;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 784;
            image.y = 408;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain4');
            image = new Image(texture);
            image.x = 358;
            image.y = 219;
            image.width = 136;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain4');
            image = new Image(texture);
            image.x = 397;
            image.y = 248;
            image.width = 136;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain2');
            image = new Image(texture);
            image.x = 458;
            image.y = 187;
            image.width = 134;
            image.height = 91;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain2');
            image = new Image(texture);
            image.x = 460;
            image.y = 155;
            image.width = 134;
            image.height = 91;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 506;
            image.y = 224;
            image.width = 108;
            image.height = 135;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 277;
            image.y = 390;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 309;
            image.y = 382;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 746;
            image.y = 30;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 781;
            image.y = 115;
            image.width = 108;
            image.height = 135;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 606;
            image.y = 43;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 539;
            image.y = 20;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 831;
            image.y = 191;
            image.width = 108;
            image.height = 135;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 476;
            image.y = 57;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 752;
            image.y = 241;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian2');
            image = new Image(texture);
            image.x = 469;
            image.y = 92;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian3');
            image = new Image(texture);
            image.x = 633;
            image.y = 161;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian2');
            image = new Image(texture);
            image.x = 552;
            image.y = 132;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian5');
            image = new Image(texture);
            image.x = 758;
            image.y = 270;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian5');
            image = new Image(texture);
            image.x = 807;
            image.y = 326;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian6');
            image = new Image(texture);
            image.x = 848;
            image.y = 390;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian2');
            image = new Image(texture);
            image.x = 300;
            image.y = 130;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian6');
            image = new Image(texture);
            image.x = 230;
            image.y = 191;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian5');
            image = new Image(texture);
            image.x = 246;
            image.y = 305;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian2');
            image = new Image(texture);
            image.x = 410;
            image.y = 359;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian3');
            image = new Image(texture);
            image.x = 499;
            image.y = 378;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian5');
            image = new Image(texture);
            image.x = 565;
            image.y = 417;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian1');
            image = new Image(texture);
            image.x = 515;
            image.y = 479;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian2');
            image = new Image(texture);
            image.x = 416;
            image.y = 516;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian2');
            image = new Image(texture);
            image.x = 168;
            image.y = 502;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian1');
            image = new Image(texture);
            image.x = 76;
            image.y = 461;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian2');
            image = new Image(texture);
            image.x = -23;
            image.y = 474;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian1');
            image = new Image(texture);
            image.x = 325;
            image.y = 472;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_247 = new Button(texture);
            tag_247.name= 'tag_247';
            tag_247.x = 42;
            tag_247.y = 484;
            tag_247.width = 90;
            tag_247.height = 90;
            this.addQuiackChild(tag_247);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_248 = new Button(texture);
            tag_248.name= 'tag_248';
            tag_248.x = 148;
            tag_248.y = 476;
            tag_248.width = 90;
            tag_248.height = 90;
            this.addQuiackChild(tag_248);
            texture = assetMgr.getTexture('ui_zhuxian_bigboss_airenguowang');
            tag_249 = new Button(texture);
            tag_249.name= 'tag_249';
            tag_249.x = 265;
            tag_249.y = 482;
            tag_249.width = 120;
            tag_249.height = 120;
            this.addQuiackChild(tag_249);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_250 = new Button(texture);
            tag_250.name= 'tag_250';
            tag_250.x = 386;
            tag_250.y = 494;
            tag_250.width = 90;
            tag_250.height = 90;
            this.addQuiackChild(tag_250);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_251 = new Button(texture);
            tag_251.name= 'tag_251';
            tag_251.x = 492;
            tag_251.y = 501;
            tag_251.width = 90;
            tag_251.height = 90;
            this.addQuiackChild(tag_251);
            texture = assetMgr.getTexture('ui_zhuxian_bigboss_airenguowang');
            tag_252 = new Button(texture);
            tag_252.name= 'tag_252';
            tag_252.x = 610;
            tag_252.y = 478;
            tag_252.width = 120;
            tag_252.height = 120;
            this.addQuiackChild(tag_252);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_253 = new Button(texture);
            tag_253.name= 'tag_253';
            tag_253.x = 558;
            tag_253.y = 368;
            tag_253.width = 90;
            tag_253.height = 90;
            this.addQuiackChild(tag_253);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_254 = new Button(texture);
            tag_254.name= 'tag_254';
            tag_254.x = 470;
            tag_254.y = 343;
            tag_254.width = 90;
            tag_254.height = 90;
            this.addQuiackChild(tag_254);
            texture = assetMgr.getTexture('ui_zhuxian_bigboss_airenguowang');
            tag_255 = new Button(texture);
            tag_255.name= 'tag_255';
            tag_255.x = 347;
            tag_255.y = 320;
            tag_255.width = 120;
            tag_255.height = 120;
            this.addQuiackChild(tag_255);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_256 = new Button(texture);
            tag_256.name= 'tag_256';
            tag_256.x = 242;
            tag_256.y = 254;
            tag_256.width = 90;
            tag_256.height = 90;
            this.addQuiackChild(tag_256);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_257 = new Button(texture);
            tag_257.name= 'tag_257';
            tag_257.x = 275;
            tag_257.y = 160;
            tag_257.width = 90;
            tag_257.height = 90;
            this.addQuiackChild(tag_257);
            texture = assetMgr.getTexture('ui_zhuxian_bigboss_airenguowang');
            tag_258 = new Button(texture);
            tag_258.name= 'tag_258';
            tag_258.x = 407;
            tag_258.y = 124;
            tag_258.width = 120;
            tag_258.height = 120;
            this.addQuiackChild(tag_258);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_259 = new Button(texture);
            tag_259.name= 'tag_259';
            tag_259.x = 521;
            tag_259.y = 108;
            tag_259.width = 90;
            tag_259.height = 90;
            this.addQuiackChild(tag_259);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_260 = new Button(texture);
            tag_260.name= 'tag_260';
            tag_260.x = 621;
            tag_260.y = 127;
            tag_260.width = 90;
            tag_260.height = 90;
            this.addQuiackChild(tag_260);
            texture = assetMgr.getTexture('ui_zhuxian_bigboss_airenguowang');
            tag_261 = new Button(texture);
            tag_261.name= 'tag_261';
            tag_261.x = 723;
            tag_261.y = 187;
            tag_261.width = 120;
            tag_261.height = 120;
            this.addQuiackChild(tag_261);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_262 = new Button(texture);
            tag_262.name= 'tag_262';
            tag_262.x = 799;
            tag_262.y = 278;
            tag_262.width = 90;
            tag_262.height = 90;
            this.addQuiackChild(tag_262);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_263 = new Button(texture);
            tag_263.name= 'tag_263';
            tag_263.x = 850;
            tag_263.y = 335;
            tag_263.width = 90;
            tag_263.height = 90;
            this.addQuiackChild(tag_263);
            texture = assetMgr.getTexture('ui_zhuxian_bigboss_airenguowang');
            tag_264 = new Button(texture);
            tag_264.name= 'tag_264';
            tag_264.x = 859;
            tag_264.y = 445;
            tag_264.width = 120;
            tag_264.height = 120;
            this.addQuiackChild(tag_264);
        }
        override public function dispose():void
        {
            view_bg.dispose();
            tag_247.dispose();
            tag_248.dispose();
            tag_249.dispose();
            tag_250.dispose();
            tag_251.dispose();
            tag_252.dispose();
            tag_253.dispose();
            tag_254.dispose();
            tag_255.dispose();
            tag_256.dispose();
            tag_257.dispose();
            tag_258.dispose();
            tag_259.dispose();
            tag_260.dispose();
            tag_261.dispose();
            tag_262.dispose();
            tag_263.dispose();
            tag_264.dispose();
            super.dispose();
        
}
    }
}
