package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import game.scene.world.NewMapRender;

    public class map_world_6Base extends NewMapRender
    {
        public var view_bg:Sprite;
        public var tag_130:Button;
        public var tag_131:Button;
        public var tag_132:Button;
        public var tag_133:Button;
        public var tag_134:Button;
        public var tag_135:Button;
        public var tag_136:Button;
        public var tag_137:Button;
        public var tag_138:Button;
        public var tag_139:Button;
        public var tag_140:Button;
        public var tag_141:Button;
        public var tag_142:Button;
        public var tag_143:Button;
        public var tag_144:Button;
        public var tag_145:Button;
        public var tag_146:Button;
        public var tag_147:Button;
        public var tag_148:Button;
        public var tag_149:Button;
        public var tag_150:Button;
        public var tag_151:Button;
        public var tag_152:Button;
        public var tag_153:Button;

        public function map_world_6Base()
        {
            var texture:Texture;
            var textField:TextField;
            var image:Image;
            var button:Button;;
            var assetMgr:AssetMgr = AssetMgr.instance;
            view_bg = new Sprite();
            view_bg.width = 966;
            view_bg.height = 640;
            this.addQuiackChild(view_bg);
            view_bg.name= 'view_bg';
            texture =assetMgr.getTexture('worldmap_background2');
            image = new Image(texture);
            image.x = 221;
            image.width = 237;
            image.height = 640;
            image.smoothing= Constants.NONE;
            view_bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_background2');
            image = new Image(texture);
            image.x = 456;
            image.width = 237;
            image.height = 640;
            image.smoothing= Constants.NONE;
            view_bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_background2');
            image = new Image(texture);
            image.x = 543;
            image.width = 237;
            image.height = 640;
            image.smoothing= Constants.NONE;
            view_bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_background2');
            image = new Image(texture);
            image.width = 237;
            image.height = 640;
            image.smoothing= Constants.NONE;
            view_bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_background2');
            image = new Image(texture);
            image.x = 729;
            image.width = 237;
            image.height = 640;
            image.smoothing= Constants.NONE;
            view_bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain4');
            image = new Image(texture);
            image.x = -123;
            image.y = 380;
            image.width = 136;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 36;
            image.y = 31;
            image.width = 108;
            image.height = 135;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 66;
            image.y = 85;
            image.width = 108;
            image.height = 135;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 57;
            image.y = 186;
            image.width = 108;
            image.height = 135;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain4');
            image = new Image(texture);
            image.x = 175;
            image.y = 56;
            image.width = 136;
            image.height = 74;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 4;
            image.y = 56;
            image.width = 108;
            image.height = 135;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 13;
            image.y = 114;
            image.width = 108;
            image.height = 135;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain4');
            image = new Image(texture);
            image.x = 221;
            image.y = 103;
            image.width = 136;
            image.height = 74;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain4');
            image = new Image(texture);
            image.x = 149;
            image.y = 206;
            image.width = 136;
            image.height = 74;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain4');
            image = new Image(texture);
            image.x = 69;
            image.y = 380;
            image.width = 136;
            image.height = 74;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 149;
            image.y = 401;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert1');
            image = new Image(texture);
            image.x = 133;
            image.y = 450;
            image.width = 69;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert3');
            image = new Image(texture);
            image.x = 346;
            image.y = 281;
            image.width = 105;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 13;
            image.y = 262;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 104;
            image.y = 159;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 95;
            image.y = 184;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 144;
            image.y = 220;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 186;
            image.y = 178;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 149;
            image.y = 288;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 243;
            image.y = 154;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 329;
            image.y = 151;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 243;
            image.y = 190;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 384;
            image.y = 140;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 447;
            image.y = 144;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 209;
            image.y = 39;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 365;
            image.y = 31;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 504;
            image.y = 37;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 487;
            image.y = 127;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 401;
            image.y = 175;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 146;
            image.y = 318;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 146;
            image.y = 354;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 165;
            image.y = 438;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 99;
            image.y = 482;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert1');
            image = new Image(texture);
            image.x = 197;
            image.y = 502;
            image.width = 69;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert1');
            image = new Image(texture);
            image.x = 212;
            image.y = 412;
            image.width = 69;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert1');
            image = new Image(texture);
            image.x = 329;
            image.y = 191;
            image.width = 69;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert1');
            image = new Image(texture);
            image.x = 285;
            image.y = 24;
            image.width = 69;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert1');
            image = new Image(texture);
            image.x = 430;
            image.y = 31;
            image.width = 69;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert1');
            image = new Image(texture);
            image.x = 588;
            image.y = 31;
            image.width = 69;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert1');
            image = new Image(texture);
            image.x = 540;
            image.y = 24;
            image.width = 69;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert1');
            image = new Image(texture);
            image.x = 666;
            image.y = 24;
            image.width = 69;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert1');
            image = new Image(texture);
            image.x = 725;
            image.y = 24;
            image.width = 69;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert1');
            image = new Image(texture);
            image.x = 632;
            image.y = 24;
            image.width = 69;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert3');
            image = new Image(texture);
            image.x = 329;
            image.y = 321;
            image.width = 105;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert3');
            image = new Image(texture);
            image.x = 359;
            image.y = 361;
            image.width = 105;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_boat');
            image = new Image(texture);
            image.x = 419;
            image.y = 290;
            image.width = 49;
            image.height = 43;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 392;
            image.y = 330;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert3');
            image = new Image(texture);
            image.x = 413;
            image.y = 304;
            image.width = 105;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert3');
            image = new Image(texture);
            image.x = 418;
            image.y = 367;
            image.width = 105;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert3');
            image = new Image(texture);
            image.x = 443;
            image.y = 275;
            image.width = 105;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert3');
            image = new Image(texture);
            image.x = 465;
            image.y = 304;
            image.width = 105;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert1');
            image = new Image(texture);
            image.x = 247;
            image.y = 479;
            image.width = 69;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert3');
            image = new Image(texture);
            image.x = 247;
            image.y = 509;
            image.width = 105;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert3');
            image = new Image(texture);
            image.x = 144;
            image.y = 532;
            image.width = 105;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert3');
            image = new Image(texture);
            image.x = 329;
            image.y = 509;
            image.width = 105;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert3');
            image = new Image(texture);
            image.x = 396;
            image.y = 509;
            image.width = 105;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert3');
            image = new Image(texture);
            image.x = 518;
            image.y = 445;
            image.width = 105;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert3');
            image = new Image(texture);
            image.x = 512;
            image.y = 485;
            image.width = 105;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert3');
            image = new Image(texture);
            image.x = 570;
            image.y = 481;
            image.width = 105;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert3');
            image = new Image(texture);
            image.x = 478;
            image.y = 515;
            image.width = 105;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_house1');
            image = new Image(texture);
            image.x = 149;
            image.y = 454;
            image.width = 83;
            image.height = 70;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_house1');
            image = new Image(texture);
            image.x = 186;
            image.y = 502;
            image.width = 83;
            image.height = 70;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave4');
            image = new Image(texture);
            image.x = 392;
            image.y = 321;
            image.width = 51;
            image.height = 41;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave1');
            image = new Image(texture);
            image.x = 458;
            image.y = 324;
            image.width = 38;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave1');
            image = new Image(texture);
            image.x = 430;
            image.y = 357;
            image.width = 38;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave1');
            image = new Image(texture);
            image.x = 440;
            image.y = 144;
            image.width = 38;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave1');
            image = new Image(texture);
            image.x = 331;
            image.y = 162;
            image.width = 38;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave1');
            image = new Image(texture);
            image.x = 268;
            image.y = 206;
            image.width = 38;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave1');
            image = new Image(texture);
            image.x = 183;
            image.y = 229;
            image.width = 38;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave1');
            image = new Image(texture);
            image.x = 461;
            image.y = 189;
            image.width = 38;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave1');
            image = new Image(texture);
            image.x = 427;
            image.y = 40;
            image.width = 38;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave1');
            image = new Image(texture);
            image.x = 564;
            image.y = 40;
            image.width = 38;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave1');
            image = new Image(texture);
            image.x = 291;
            image.y = 35;
            image.width = 38;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave1');
            image = new Image(texture);
            image.x = 567;
            image.y = 487;
            image.width = 38;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave1');
            image = new Image(texture);
            image.x = 511;
            image.y = 533;
            image.width = 38;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave1');
            image = new Image(texture);
            image.x = 358;
            image.y = 527;
            image.width = 38;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave1');
            image = new Image(texture);
            image.x = 183;
            image.y = 309;
            image.width = 38;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 657;
            image.y = 298;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 685;
            image.y = 288;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 709;
            image.y = 288;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 732;
            image.y = 288;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 753;
            image.y = 291;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 769;
            image.y = 300;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 776;
            image.y = 315;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 785;
            image.y = 333;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_city2');
            image = new Image(texture);
            image.x = 666;
            image.y = 304;
            image.width = 142;
            image.height = 106;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 638;
            image.y = 314;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 638;
            image.y = 338;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 651;
            image.y = 353;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 670;
            image.y = 367;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 691;
            image.y = 377;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 585;
            image.y = 300;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 602;
            image.y = 319;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 602;
            image.y = 443;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 626;
            image.y = 467;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 644;
            image.y = 488;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 632;
            image.y = 505;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 658;
            image.y = 518;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 681;
            image.y = 532;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 681;
            image.y = 494;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 705;
            image.y = 508;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 713;
            image.y = 532;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 735;
            image.y = 540;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 771;
            image.y = 540;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 708;
            image.y = 389;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 769;
            image.y = 422;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 741;
            image.y = 406;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 773;
            image.y = 445;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 788;
            image.y = 348;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 574;
            image.y = 330;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert3');
            image = new Image(texture);
            image.x = 314;
            image.y = 365;
            image.width = 105;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave4');
            image = new Image(texture);
            image.x = 386;
            image.y = 168;
            image.width = 51;
            image.height = 41;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave4');
            image = new Image(texture);
            image.x = 619;
            image.y = 31;
            image.width = 51;
            image.height = 41;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 548;
            image.y = 135;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 579;
            image.y = 412;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 522;
            image.y = 341;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 550;
            image.y = 306;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 527;
            image.y = 282;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree10');
            image = new Image(texture);
            image.x = 775;
            image.y = 229;
            image.width = 177;
            image.height = 131;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree9');
            image = new Image(texture);
            image.x = 890;
            image.y = 127;
            image.width = 98;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree10');
            image = new Image(texture);
            image.x = 769;
            image.y = 35;
            image.width = 177;
            image.height = 131;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree9');
            image = new Image(texture);
            image.x = 854;
            image.y = 126;
            image.width = 98;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree9');
            image = new Image(texture);
            image.x = 854;
            image.y = 166;
            image.width = 98;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree9');
            image = new Image(texture);
            image.x = 866;
            image.y = 209;
            image.width = 98;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree10');
            image = new Image(texture);
            image.x = 831;
            image.y = 21;
            image.width = 177;
            image.height = 131;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree9');
            image = new Image(texture);
            image.x = 882;
            image.y = 259;
            image.width = 98;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 831;
            image.y = 389;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 803;
            image.y = 373;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 835;
            image.y = 412;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 910;
            image.y = 452;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 907;
            image.y = 421;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 914;
            image.y = 475;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 895;
            image.y = 506;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 780;
            image.y = 542;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 802;
            image.y = 550;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 838;
            image.y = 550;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 835;
            image.y = 527;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 857;
            image.y = 535;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 882;
            image.y = 479;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 867;
            image.y = 508;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 808;
            image.y = 426;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 780;
            image.y = 410;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 812;
            image.y = 449;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 780;
            image.y = 441;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 753;
            image.y = 425;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 785;
            image.y = 464;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 826;
            image.y = 420;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 799;
            image.y = 404;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 831;
            image.y = 443;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 747;
            image.y = 450;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 657;
            image.y = 144;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 597;
            image.y = 130;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave1');
            image = new Image(texture);
            image.x = 679;
            image.y = 163;
            image.width = 38;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave4');
            image = new Image(texture);
            image.x = 725;
            image.y = 175;
            image.width = 51;
            image.height = 41;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 771;
            image.y = 122;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 821;
            image.y = 200;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 728;
            image.y = 37;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 915;
            image.y = 175;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 929;
            image.y = 198;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_city1');
            image = new Image(texture);
            image.x = 523;
            image.y = 140;
            image.width = 80;
            image.height = 66;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian1');
            image = new Image(texture);
            image.x = 546;
            image.y = 88;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian2');
            image = new Image(texture);
            image.x = 334;
            image.y = 227;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian4');
            image = new Image(texture);
            image.x = 790;
            image.y = 205;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian7');
            image = new Image(texture);
            image.x = 870;
            image.y = 441;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian5');
            image = new Image(texture);
            image.x = 303;
            image.y = 455;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian4');
            image = new Image(texture);
            image.x = 725;
            image.y = 517;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian2');
            image = new Image(texture);
            image.x = 810;
            image.y = 501;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian4');
            image = new Image(texture);
            image.x = 778;
            image.y = 164;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian1');
            image = new Image(texture);
            image.x = 653;
            image.y = 88;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian5');
            image = new Image(texture);
            image.x = 112;
            image.y = 220;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian4');
            image = new Image(texture);
            image.x = 164;
            image.y = 138;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian1');
            image = new Image(texture);
            image.x = 266;
            image.y = 93;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian1');
            image = new Image(texture);
            image.x = 421;
            image.y = 90;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian6');
            image = new Image(texture);
            image.x = 92;
            image.y = 390;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian4');
            image = new Image(texture);
            image.x = 633;
            image.y = 431;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian2');
            image = new Image(texture);
            image.x = 555;
            image.y = 372;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian4');
            image = new Image(texture);
            image.x = 485;
            image.y = 413;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian2');
            image = new Image(texture);
            image.x = 384;
            image.y = 502;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian7');
            image = new Image(texture);
            image.x = 266;
            image.y = 330;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian4');
            image = new Image(texture);
            image.x = 62;
            image.y = 443;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian2');
            image = new Image(texture);
            image.x = 437;
            image.y = 259;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian1');
            image = new Image(texture);
            image.x = 534;
            image.y = 229;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian1');
            image = new Image(texture);
            image.x = 708;
            image.y = 241;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian1');
            image = new Image(texture);
            image.x = -24;
            image.y = 486;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_130 = new Button(texture);
            tag_130.name= 'tag_130';
            tag_130.x = 41;
            tag_130.y = 492;
            tag_130.width = 90;
            tag_130.height = 90;
            this.addQuiackChild(tag_130);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_131 = new Button(texture);
            tag_131.name= 'tag_131';
            tag_131.x = 111;
            tag_131.y = 416;
            tag_131.width = 90;
            tag_131.height = 90;
            this.addQuiackChild(tag_131);
            texture = assetMgr.getTexture('ui_zhuxian_boss_baozi');
            tag_132 = new Button(texture);
            tag_132.name= 'tag_132';
            tag_132.x = 116;
            tag_132.y = 297;
            tag_132.width = 90;
            tag_132.height = 90;
            this.addQuiackChild(tag_132);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_133 = new Button(texture);
            tag_133.name= 'tag_133';
            tag_133.x = 150;
            tag_133.y = 197;
            tag_133.width = 90;
            tag_133.height = 90;
            this.addQuiackChild(tag_133);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_134 = new Button(texture);
            tag_134.name= 'tag_134';
            tag_134.x = 231;
            tag_134.y = 122;
            tag_134.width = 90;
            tag_134.height = 90;
            this.addQuiackChild(tag_134);
            texture = assetMgr.getTexture('ui_zhuxian_boss_baozi');
            tag_135 = new Button(texture);
            tag_135.name= 'tag_135';
            tag_135.x = 361;
            tag_135.y = 104;
            tag_135.width = 90;
            tag_135.height = 90;
            this.addQuiackChild(tag_135);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_136 = new Button(texture);
            tag_136.name= 'tag_136';
            tag_136.x = 509;
            tag_136.y = 110;
            tag_136.width = 90;
            tag_136.height = 90;
            this.addQuiackChild(tag_136);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_137 = new Button(texture);
            tag_137.name= 'tag_137';
            tag_137.x = 626;
            tag_137.y = 106;
            tag_137.width = 90;
            tag_137.height = 90;
            this.addQuiackChild(tag_137);
            texture = assetMgr.getTexture('ui_zhuxian_boss_baozi');
            tag_138 = new Button(texture);
            tag_138.name= 'tag_138';
            tag_138.x = 743;
            tag_138.y = 111;
            tag_138.width = 90;
            tag_138.height = 90;
            this.addQuiackChild(tag_138);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_139 = new Button(texture);
            tag_139.name= 'tag_139';
            tag_139.x = 825;
            tag_139.y = 182;
            tag_139.width = 90;
            tag_139.height = 90;
            this.addQuiackChild(tag_139);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_140 = new Button(texture);
            tag_140.name= 'tag_140';
            tag_140.x = 775;
            tag_140.y = 254;
            tag_140.width = 90;
            tag_140.height = 90;
            this.addQuiackChild(tag_140);
            texture = assetMgr.getTexture('ui_zhuxian_bigboss_airenguowang');
            tag_141 = new Button(texture);
            tag_141.name= 'tag_141';
            tag_141.x = 638;
            tag_141.y = 255;
            tag_141.width = 120;
            tag_141.height = 120;
            this.addQuiackChild(tag_141);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_142 = new Button(texture);
            tag_142.name= 'tag_142';
            tag_142.x = 504;
            tag_142.y = 246;
            tag_142.width = 90;
            tag_142.height = 90;
            this.addQuiackChild(tag_142);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_143 = new Button(texture);
            tag_143.name= 'tag_143';
            tag_143.x = 402;
            tag_143.y = 238;
            tag_143.width = 90;
            tag_143.height = 90;
            this.addQuiackChild(tag_143);
            texture = assetMgr.getTexture('ui_zhuxian_boss_baozi');
            tag_144 = new Button(texture);
            tag_144.name= 'tag_144';
            tag_144.x = 296;
            tag_144.y = 283;
            tag_144.width = 90;
            tag_144.height = 90;
            this.addQuiackChild(tag_144);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_145 = new Button(texture);
            tag_145.name= 'tag_145';
            tag_145.x = 298;
            tag_145.y = 395;
            tag_145.width = 90;
            tag_145.height = 90;
            this.addQuiackChild(tag_145);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_146 = new Button(texture);
            tag_146.name= 'tag_146';
            tag_146.x = 365;
            tag_146.y = 460;
            tag_146.width = 90;
            tag_146.height = 90;
            this.addQuiackChild(tag_146);
            texture = assetMgr.getTexture('ui_zhuxian_boss_baozi');
            tag_147 = new Button(texture);
            tag_147.name= 'tag_147';
            tag_147.x = 463;
            tag_147.y = 470;
            tag_147.width = 90;
            tag_147.height = 90;
            this.addQuiackChild(tag_147);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_148 = new Button(texture);
            tag_148.name= 'tag_148';
            tag_148.x = 531;
            tag_148.y = 402;
            tag_148.width = 90;
            tag_148.height = 90;
            this.addQuiackChild(tag_148);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_149 = new Button(texture);
            tag_149.name= 'tag_149';
            tag_149.x = 619;
            tag_149.y = 390;
            tag_149.width = 90;
            tag_149.height = 90;
            this.addQuiackChild(tag_149);
            texture = assetMgr.getTexture('ui_zhuxian_boss_baozi');
            tag_150 = new Button(texture);
            tag_150.name= 'tag_150';
            tag_150.x = 703;
            tag_150.y = 450;
            tag_150.width = 90;
            tag_150.height = 90;
            this.addQuiackChild(tag_150);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_151 = new Button(texture);
            tag_151.name= 'tag_151';
            tag_151.x = 785;
            tag_151.y = 521;
            tag_151.width = 90;
            tag_151.height = 90;
            this.addQuiackChild(tag_151);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_152 = new Button(texture);
            tag_152.name= 'tag_152';
            tag_152.x = 865;
            tag_152.y = 502;
            tag_152.width = 90;
            tag_152.height = 90;
            this.addQuiackChild(tag_152);
            texture = assetMgr.getTexture('ui_zhuxian_bigboss_airenguowang');
            tag_153 = new Button(texture);
            tag_153.name= 'tag_153';
            tag_153.x = 868;
            tag_153.y = 375;
            tag_153.width = 120;
            tag_153.height = 120;
            this.addQuiackChild(tag_153);
        }
        override public function dispose():void
        {
            view_bg.dispose();
            tag_130.dispose();
            tag_131.dispose();
            tag_132.dispose();
            tag_133.dispose();
            tag_134.dispose();
            tag_135.dispose();
            tag_136.dispose();
            tag_137.dispose();
            tag_138.dispose();
            tag_139.dispose();
            tag_140.dispose();
            tag_141.dispose();
            tag_142.dispose();
            tag_143.dispose();
            tag_144.dispose();
            tag_145.dispose();
            tag_146.dispose();
            tag_147.dispose();
            tag_148.dispose();
            tag_149.dispose();
            tag_150.dispose();
            tag_151.dispose();
            tag_152.dispose();
            tag_153.dispose();
            super.dispose();
        
}
    }
}
