package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import game.scene.world.NewMapRender;

    public class map_world_0Base extends NewMapRender
    {
        public var view_bg:Sprite;
        public var tag_1:Button;
        public var tag_2:Button;
        public var tag_3:Button;
        public var tag_4:Button;
        public var tag_5:Button;
        public var tag_6:Button;
        public var tag_7:Button;
        public var tag_8:Button;
        public var tag_9:Button;
        public var tag_10:Button;
        public var tag_11:Button;
        public var tag_12:Button;
        public var tag_13:Button;
        public var tag_14:Button;
        public var tag_15:Button;
        public var tag_16:Button;
        public var tag_17:Button;
        public var tag_18:Button;
        public var tag_19:Button;
        public var tag_20:Button;
        public var tag_21:Button;
        public var tag_22:Button;
        public var tag_23:Button;
        public var tag_24:Button;

        public function map_world_0Base()
        {
            var texture:Texture;
            var textField:TextField;
            var image:Image;
            var button:Button;;
            var assetMgr:AssetMgr = AssetMgr.instance;
            view_bg = new Sprite();
            view_bg.width = 967;
            view_bg.height = 641;
            this.addQuiackChild(view_bg);
            view_bg.name= 'view_bg';
            texture =assetMgr.getTexture('worldmap_background2');
            image = new Image(texture);
            image.x = 287;
            image.width = 237;
            image.height = 640;
            image.smoothing= Constants.NONE;
            view_bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_background');
            image = new Image(texture);
            image.width = 288;
            image.height = 641;
            image.smoothing= Constants.NONE;
            view_bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_background2');
            image = new Image(texture);
            image.x = 506;
            image.width = 237;
            image.height = 640;
            image.smoothing= Constants.NONE;
            view_bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_background2');
            image = new Image(texture);
            image.x = 730;
            image.width = 237;
            image.height = 640;
            image.smoothing= Constants.NONE;
            view_bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 35;
            image.y = 229;
            image.width = 108;
            image.height = 135;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 52;
            image.y = 162;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 22;
            image.y = 323;
            image.width = 108;
            image.height = 135;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert8');
            image = new Image(texture);
            image.x = 273;
            image.y = 424;
            image.width = 101;
            image.height = 63;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert8');
            image = new Image(texture);
            image.x = 226;
            image.y = 407;
            image.width = 101;
            image.height = 63;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_rift2');
            image = new Image(texture);
            image.x = 226;
            image.y = 366;
            image.width = 194;
            image.height = 138;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert8');
            image = new Image(texture);
            image.x = 243;
            image.y = 334;
            image.width = 101;
            image.height = 63;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert8');
            image = new Image(texture);
            image.x = 205;
            image.y = 306;
            image.width = 101;
            image.height = 63;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert8');
            image = new Image(texture);
            image.x = 359;
            image.y = 374;
            image.width = 101;
            image.height = 63;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 10;
            image.y = 421;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 150;
            image.y = 460;
            image.width = 108;
            image.height = 135;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain7');
            image = new Image(texture);
            image.x = 337;
            image.y = 33;
            image.width = 180;
            image.height = 103;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 87;
            image.y = 42;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 207;
            image.y = 58;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 251;
            image.y = 34;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 302;
            image.y = 79;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert6');
            image = new Image(texture);
            image.x = 378;
            image.y = 100;
            image.width = 111;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 343;
            image.y = 136;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave4');
            image = new Image(texture);
            image.x = 159;
            image.y = 67;
            image.width = 51;
            image.height = 41;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain2');
            image = new Image(texture);
            image.x = 302;
            image.y = 166;
            image.width = 134;
            image.height = 91;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain2');
            image = new Image(texture);
            image.x = 262;
            image.y = 196;
            image.width = 134;
            image.height = 91;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain2');
            image = new Image(texture);
            image.x = 243;
            image.y = 255;
            image.width = 134;
            image.height = 91;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 444;
            image.y = 384;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 481;
            image.y = 386;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 517;
            image.y = 390;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 434;
            image.y = 408;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 465;
            image.y = 410;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 507;
            image.y = 414;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 448;
            image.y = 429;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 413;
            image.y = 390;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree6');
            image = new Image(texture);
            image.x = 382;
            image.y = 384;
            image.width = 42;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_lake2');
            image = new Image(texture);
            image.x = 470;
            image.y = 197;
            image.width = 130;
            image.height = 126;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 622;
            image.y = 44;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 783;
            image.y = 56;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain2');
            image = new Image(texture);
            image.x = 571;
            image.y = 180;
            image.width = 134;
            image.height = 91;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 574;
            image.y = 226;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 529;
            image.y = 264;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 680;
            image.y = 487;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree9');
            image = new Image(texture);
            image.x = 722;
            image.y = 423;
            image.width = 98;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 874;
            image.y = 142;
            image.width = 108;
            image.height = 135;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 882;
            image.y = 239;
            image.width = 108;
            image.height = 135;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 870;
            image.y = 332;
            image.width = 108;
            image.height = 135;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 626;
            image.y = 221;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree10');
            image = new Image(texture);
            image.x = 653;
            image.y = 310;
            image.width = 177;
            image.height = 131;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 698;
            image.y = 57;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 546;
            image.y = 18;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 658;
            image.y = 20;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 757;
            image.y = 26;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave4');
            image = new Image(texture);
            image.x = 742;
            image.y = 105;
            image.width = 51;
            image.height = 41;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave4');
            image = new Image(texture);
            image.x = 282;
            image.y = 364;
            image.width = 51;
            image.height = 41;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave4');
            image = new Image(texture);
            image.x = 327;
            image.y = 374;
            image.width = 51;
            image.height = 41;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 533;
            image.y = 533;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 573;
            image.y = 549;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 501;
            image.y = 294;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 475;
            image.y = 212;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 533;
            image.y = 179;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 537;
            image.y = 301;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 440;
            image.y = 240;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain9');
            image = new Image(texture);
            image.x = 707;
            image.y = 106;
            image.width = 35;
            image.height = 28;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain9');
            image = new Image(texture);
            image.x = 757;
            image.y = 136;
            image.width = 35;
            image.height = 28;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain9');
            image = new Image(texture);
            image.x = 793;
            image.y = 145;
            image.width = 35;
            image.height = 28;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain9');
            image = new Image(texture);
            image.x = 789;
            image.y = 122;
            image.width = 35;
            image.height = 28;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 752;
            image.y = 477;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 769;
            image.y = 471;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 778;
            image.y = 555;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 626;
            image.y = 91;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_house5');
            image = new Image(texture);
            image.x = 664;
            image.y = 496;
            image.width = 30;
            image.height = 35;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_house5');
            image = new Image(texture);
            image.x = 632;
            image.y = 528;
            image.width = 30;
            image.height = 35;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_farmland2');
            image = new Image(texture);
            image.x = 651;
            image.y = 515;
            image.width = 72;
            image.height = 54;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_farmland2');
            image = new Image(texture);
            image.x = 666;
            image.y = 549;
            image.width = 72;
            image.height = 54;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_farmland2');
            image = new Image(texture);
            image.x = 562;
            image.y = 511;
            image.width = 72;
            image.height = 54;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_farmland2');
            image = new Image(texture);
            image.x = 702;
            image.y = 474;
            image.width = 72;
            image.height = 54;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_house6');
            image = new Image(texture);
            image.x = 800;
            image.y = 423;
            image.width = 44;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_house3');
            image = new Image(texture);
            image.x = 733;
            image.y = 498;
            image.width = 111;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian2');
            image = new Image(texture);
            image.x = 129;
            image.y = 118;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian2');
            image = new Image(texture);
            image.x = 256;
            image.y = 118;
            image.width = 37;
            image.height = 37;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian5');
            image = new Image(texture);
            image.x = 260;
            image.y = 188;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian5');
            image = new Image(texture);
            image.x = 216;
            image.y = 252;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian5');
            image = new Image(texture);
            image.x = 179;
            image.y = 312;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian5');
            image = new Image(texture);
            image.x = 226;
            image.y = 424;
            image.width = 37;
            image.height = 37;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian2');
            image = new Image(texture);
            image.x = 288;
            image.y = 474;
            image.width = 37;
            image.height = 37;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian2');
            image = new Image(texture);
            image.x = 355;
            image.y = 499;
            image.width = 37;
            image.height = 37;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian1');
            image = new Image(texture);
            image.x = 477;
            image.y = 517;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian2');
            image = new Image(texture);
            image.x = 558;
            image.y = 504;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian3');
            image = new Image(texture);
            image.x = 625;
            image.y = 471;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian2');
            image = new Image(texture);
            image.x = 656;
            image.y = 393;
            image.width = 37;
            image.height = 37;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian2');
            image = new Image(texture);
            image.x = 581;
            image.y = 357;
            image.width = 37;
            image.height = 37;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian1');
            image = new Image(texture);
            image.x = 454;
            image.y = 344;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian5');
            image = new Image(texture);
            image.x = 396;
            image.y = 267;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian5');
            image = new Image(texture);
            image.x = 436;
            image.y = 194;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian2');
            image = new Image(texture);
            image.x = 496;
            image.y = 136;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian2');
            image = new Image(texture);
            image.x = 683;
            image.y = 137;
            image.width = 37;
            image.height = 37;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian2');
            image = new Image(texture);
            image.x = 752;
            image.y = 155;
            image.width = 37;
            image.height = 37;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian5');
            image = new Image(texture);
            image.x = 824;
            image.y = 189;
            image.width = 37;
            image.height = 37;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian5');
            image = new Image(texture);
            image.x = 894;
            image.y = 424;
            image.width = 37;
            image.height = 37;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian7');
            image = new Image(texture);
            image.x = 834;
            image.y = 360;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian7');
            image = new Image(texture);
            image.x = 833;
            image.y = 295;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_1 = new Button(texture);
            tag_1.name= 'tag_1';
            tag_1.x = 98;
            tag_1.y = 148;
            tag_1.width = 90;
            tag_1.height = 90;
            this.addQuiackChild(tag_1);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_2 = new Button(texture);
            tag_2.name= 'tag_2';
            tag_2.x = 196;
            tag_2.y = 134;
            tag_2.width = 90;
            tag_2.height = 90;
            this.addQuiackChild(tag_2);
            texture = assetMgr.getTexture('ui_zhuxian_boss_baozi');
            tag_3 = new Button(texture);
            tag_3.name= 'tag_3';
            tag_3.x = 301;
            tag_3.y = 150;
            tag_3.width = 90;
            tag_3.height = 90;
            this.addQuiackChild(tag_3);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_4 = new Button(texture);
            tag_4.name= 'tag_4';
            tag_4.x = 260;
            tag_4.y = 240;
            tag_4.width = 90;
            tag_4.height = 90;
            this.addQuiackChild(tag_4);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_5 = new Button(texture);
            tag_5.name= 'tag_5';
            tag_5.x = 218;
            tag_5.y = 302;
            tag_5.width = 90;
            tag_5.height = 90;
            this.addQuiackChild(tag_5);
            texture = assetMgr.getTexture('ui_zhuxian_boss_baozi');
            tag_6 = new Button(texture);
            tag_6.name= 'tag_6';
            tag_6.x = 172;
            tag_6.y = 388;
            tag_6.width = 90;
            tag_6.height = 90;
            this.addQuiackChild(tag_6);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_7 = new Button(texture);
            tag_7.name= 'tag_7';
            tag_7.x = 238;
            tag_7.y = 468;
            tag_7.width = 90;
            tag_7.height = 90;
            this.addQuiackChild(tag_7);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_8 = new Button(texture);
            tag_8.name= 'tag_8';
            tag_8.x = 304;
            tag_8.y = 507;
            tag_8.width = 90;
            tag_8.height = 90;
            this.addQuiackChild(tag_8);
            texture = assetMgr.getTexture('ui_zhuxian_bigboss_airenguowang');
            tag_9 = new Button(texture);
            tag_9.name= 'tag_9';
            tag_9.x = 414;
            tag_9.y = 518;
            tag_9.width = 120;
            tag_9.height = 120;
            this.addQuiackChild(tag_9);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_10 = new Button(texture);
            tag_10.name= 'tag_10';
            tag_10.x = 533;
            tag_10.y = 533;
            tag_10.width = 90;
            tag_10.height = 90;
            this.addQuiackChild(tag_10);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_11 = new Button(texture);
            tag_11.name= 'tag_11';
            tag_11.x = 610;
            tag_11.y = 503;
            tag_11.width = 90;
            tag_11.height = 90;
            this.addQuiackChild(tag_11);
            texture = assetMgr.getTexture('ui_zhuxian_boss_baozi');
            tag_12 = new Button(texture);
            tag_12.name= 'tag_12';
            tag_12.x = 691;
            tag_12.y = 451;
            tag_12.width = 90;
            tag_12.height = 90;
            this.addQuiackChild(tag_12);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_13 = new Button(texture);
            tag_13.name= 'tag_13';
            tag_13.x = 599;
            tag_13.y = 394;
            tag_13.width = 90;
            tag_13.height = 90;
            this.addQuiackChild(tag_13);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_14 = new Button(texture);
            tag_14.name= 'tag_14';
            tag_14.x = 517;
            tag_14.y = 362;
            tag_14.width = 90;
            tag_14.height = 90;
            this.addQuiackChild(tag_14);
            texture = assetMgr.getTexture('ui_zhuxian_boss_baozi');
            tag_15 = new Button(texture);
            tag_15.name= 'tag_15';
            tag_15.x = 408;
            tag_15.y = 350;
            tag_15.width = 90;
            tag_15.height = 90;
            this.addQuiackChild(tag_15);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_16 = new Button(texture);
            tag_16.name= 'tag_16';
            tag_16.x = 435;
            tag_16.y = 246;
            tag_16.width = 90;
            tag_16.height = 90;
            this.addQuiackChild(tag_16);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_17 = new Button(texture);
            tag_17.name= 'tag_17';
            tag_17.x = 482;
            tag_17.y = 180;
            tag_17.width = 90;
            tag_17.height = 90;
            this.addQuiackChild(tag_17);
            texture = assetMgr.getTexture('ui_zhuxian_bigboss_airenguowang');
            tag_18 = new Button(texture);
            tag_18.name= 'tag_18';
            tag_18.x = 588;
            tag_18.y = 133;
            tag_18.width = 120;
            tag_18.height = 120;
            this.addQuiackChild(tag_18);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_19 = new Button(texture);
            tag_19.name= 'tag_19';
            tag_19.x = 697;
            tag_19.y = 166;
            tag_19.width = 90;
            tag_19.height = 90;
            this.addQuiackChild(tag_19);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_20 = new Button(texture);
            tag_20.name= 'tag_20';
            tag_20.x = 771;
            tag_20.y = 184;
            tag_20.width = 90;
            tag_20.height = 90;
            this.addQuiackChild(tag_20);
            texture = assetMgr.getTexture('ui_zhuxian_boss_baozi');
            tag_21 = new Button(texture);
            tag_21.name= 'tag_21';
            tag_21.x = 830;
            tag_21.y = 260;
            tag_21.width = 90;
            tag_21.height = 90;
            this.addQuiackChild(tag_21);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_22 = new Button(texture);
            tag_22.name= 'tag_22';
            tag_22.x = 854;
            tag_22.y = 346;
            tag_22.width = 90;
            tag_22.height = 90;
            this.addQuiackChild(tag_22);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_23 = new Button(texture);
            tag_23.name= 'tag_23';
            tag_23.x = 856;
            tag_23.y = 413;
            tag_23.width = 90;
            tag_23.height = 90;
            this.addQuiackChild(tag_23);
            texture = assetMgr.getTexture('ui_zhuxian_bigboss_airenguowang');
            tag_24 = new Button(texture);
            tag_24.name= 'tag_24';
            tag_24.x = 876;
            tag_24.y = 502;
            tag_24.width = 120;
            tag_24.height = 120;
            this.addQuiackChild(tag_24);
        }
        override public function dispose():void
        {
            view_bg.dispose();
            tag_1.dispose();
            tag_2.dispose();
            tag_3.dispose();
            tag_4.dispose();
            tag_5.dispose();
            tag_6.dispose();
            tag_7.dispose();
            tag_8.dispose();
            tag_9.dispose();
            tag_10.dispose();
            tag_11.dispose();
            tag_12.dispose();
            tag_13.dispose();
            tag_14.dispose();
            tag_15.dispose();
            tag_16.dispose();
            tag_17.dispose();
            tag_18.dispose();
            tag_19.dispose();
            tag_20.dispose();
            tag_21.dispose();
            tag_22.dispose();
            tag_23.dispose();
            tag_24.dispose();
            super.dispose();
        
}
    }
}
