package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import game.scene.world.NewMapRender;

    public class map_world_10Base extends NewMapRender
    {
        public var view_bg:Sprite;
        public var tag_223:Button;
        public var tag_224:Button;
        public var tag_225:Button;
        public var tag_226:Button;
        public var tag_227:Button;
        public var tag_228:Button;
        public var tag_229:Button;
        public var tag_230:Button;
        public var tag_231:Button;
        public var tag_232:Button;
        public var tag_233:Button;
        public var tag_234:Button;
        public var tag_235:Button;
        public var tag_236:Button;
        public var tag_237:Button;
        public var tag_238:Button;
        public var tag_239:Button;
        public var tag_240:Button;
        public var tag_241:Button;
        public var tag_242:Button;
        public var tag_243:Button;
        public var tag_244:Button;
        public var tag_245:Button;
        public var tag_246:Button;

        public function map_world_10Base()
        {
            var texture:Texture;
            var textField:TextField;
            var image:Image;
            var button:Button;;
            var assetMgr:AssetMgr = AssetMgr.instance;
            view_bg = new Sprite();
            view_bg.width = 964;
            view_bg.height = 640;
            this.addQuiackChild(view_bg);
            view_bg.name= 'view_bg';
            texture =assetMgr.getTexture('worldmap_background2');
            image = new Image(texture);
            image.x = 221;
            image.width = 237;
            image.height = 640;
            image.smoothing= Constants.NONE;
            view_bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_background2');
            image = new Image(texture);
            image.x = 456;
            image.width = 237;
            image.height = 640;
            image.smoothing= Constants.NONE;
            view_bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_background2');
            image = new Image(texture);
            image.x = 543;
            image.width = 237;
            image.height = 640;
            image.smoothing= Constants.NONE;
            view_bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_background2');
            image = new Image(texture);
            image.width = 237;
            image.height = 640;
            image.smoothing= Constants.NONE;
            view_bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_background2');
            image = new Image(texture);
            image.x = 727;
            image.width = 237;
            image.height = 640;
            image.smoothing= Constants.NONE;
            view_bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 38;
            image.y = 425;
            image.width = 108;
            image.height = 135;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 24;
            image.y = 319;
            image.width = 108;
            image.height = 135;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 70;
            image.y = 370;
            image.width = 108;
            image.height = 135;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = -6;
            image.y = 448;
            image.width = 108;
            image.height = 135;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 80;
            image.y = 194;
            image.width = 108;
            image.height = 135;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 101;
            image.y = 18;
            image.width = 108;
            image.height = 135;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 70;
            image.y = 77;
            image.width = 108;
            image.height = 135;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 62;
            image.y = 126;
            image.width = 108;
            image.height = 135;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 68;
            image.y = 247;
            image.width = 108;
            image.height = 135;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree5');
            image = new Image(texture);
            image.x = 328;
            image.y = 349;
            image.width = 86;
            image.height = 43;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 70;
            image.y = 2;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree2');
            image = new Image(texture);
            image.x = 227;
            image.y = 144;
            image.width = 161;
            image.height = 138;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree1');
            image = new Image(texture);
            image.x = 60;
            image.y = 157;
            image.width = 237;
            image.height = 155;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_sheep');
            image = new Image(texture);
            image.x = 565;
            image.y = 355;
            image.width = 17;
            image.height = 18;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 34;
            image.y = 198;
            image.width = 108;
            image.height = 135;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_dong');
            image = new Image(texture);
            image.x = 7;
            image.y = 112;
            image.width = 57;
            image.height = 60;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree2');
            image = new Image(texture);
            image.x = 113;
            image.y = 12;
            image.width = 161;
            image.height = 138;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree2');
            image = new Image(texture);
            image.x = 227;
            image.y = 7;
            image.width = 161;
            image.height = 138;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert4');
            image = new Image(texture);
            image.x = 50;
            image.y = 398;
            image.width = 118;
            image.height = 59;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 649;
            image.y = 118;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 735;
            image.y = 109;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_city2');
            image = new Image(texture);
            image.x = 684;
            image.y = 185;
            image.width = 142;
            image.height = 106;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_boat');
            image = new Image(texture);
            image.x = 651;
            image.y = 521;
            image.width = 49;
            image.height = 43;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_rift2');
            image = new Image(texture);
            image.x = 401;
            image.y = 77;
            image.width = 194;
            image.height = 138;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 337;
            image.y = 2;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 493;
            image.y = 158;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 546;
            image.y = 198;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 527;
            image.y = 259;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_lake2');
            image = new Image(texture);
            image.x = 204;
            image.y = 353;
            image.width = 130;
            image.height = 126;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_boat');
            image = new Image(texture);
            image.x = 278;
            image.y = 369;
            image.width = 49;
            image.height = 43;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree4');
            image = new Image(texture);
            image.x = 317;
            image.y = 385;
            image.width = 82;
            image.height = 63;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree2');
            image = new Image(texture);
            image.x = 401;
            image.y = 364;
            image.width = 161;
            image.height = 138;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 372;
            image.y = 357;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 274;
            image.y = 402;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 346;
            image.y = 412;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 453;
            image.y = 329;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 519;
            image.y = 343;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 598;
            image.y = 303;
            image.width = 116;
            image.height = 114;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert4');
            image = new Image(texture);
            image.x = 182;
            image.y = 465;
            image.width = 118;
            image.height = 59;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert4');
            image = new Image(texture);
            image.x = 22;
            image.y = 526;
            image.width = 118;
            image.height = 59;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert5');
            image = new Image(texture);
            image.x = 788;
            image.y = 344;
            image.width = 63;
            image.height = 30;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert3');
            image = new Image(texture);
            image.x = 24;
            image.y = 315;
            image.width = 105;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_lake1');
            image = new Image(texture);
            image.x = 702;
            image.y = 285;
            image.width = 126;
            image.height = 137;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 610;
            image.y = 169;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 634;
            image.y = 219;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_rift1');
            image = new Image(texture);
            image.x = 567;
            image.y = 459;
            image.width = 257;
            image.height = 100;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 418;
            image.y = 12;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 471;
            image.y = 43;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 582;
            image.y = 12;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 639;
            image.y = -11;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 720;
            image.y = 12;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree2');
            image = new Image(texture);
            image.x = 526;
            image.y = -3;
            image.width = 161;
            image.height = 138;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree2');
            image = new Image(texture);
            image.x = 781;
            image.width = 161;
            image.height = 138;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 708;
            image.y = 375;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 659;
            image.y = 382;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain6');
            image = new Image(texture);
            image.x = 251;
            image.y = 244;
            image.width = 111;
            image.height = 78;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain7');
            image = new Image(texture);
            image.x = 745;
            image.y = 513;
            image.width = 180;
            image.height = 103;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree4');
            image = new Image(texture);
            image.x = 713;
            image.y = 515;
            image.width = 82;
            image.height = 63;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 749;
            image.y = 433;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert5');
            image = new Image(texture);
            image.x = 838;
            image.y = 398;
            image.width = 63;
            image.height = 30;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert5');
            image = new Image(texture);
            image.x = 666;
            image.y = 373;
            image.width = 63;
            image.height = 30;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert5');
            image = new Image(texture);
            image.x = 802;
            image.y = 429;
            image.width = 63;
            image.height = 30;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree2');
            image = new Image(texture);
            image.x = 814;
            image.y = 47;
            image.width = 161;
            image.height = 138;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 873;
            image.y = 98;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 894;
            image.y = 156;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 894;
            image.y = 219;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 866;
            image.y = 275;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 899;
            image.y = 324;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 885;
            image.y = 384;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_sheep');
            image = new Image(texture);
            image.x = 327;
            image.y = 282;
            image.width = 17;
            image.height = 18;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_sheep');
            image = new Image(texture);
            image.x = 401;
            image.y = 229;
            image.width = 17;
            image.height = 18;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_sheep');
            image = new Image(texture);
            image.x = 396;
            image.y = 252;
            image.width = 17;
            image.height = 18;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_sheep');
            image = new Image(texture);
            image.x = 349;
            image.y = 258;
            image.width = 17;
            image.height = 18;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_sheep');
            image = new Image(texture);
            image.x = 572;
            image.y = 574;
            image.width = 17;
            image.height = 18;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_sheep');
            image = new Image(texture);
            image.x = 610;
            image.y = 574;
            image.width = 17;
            image.height = 18;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_sheep');
            image = new Image(texture);
            image.x = 693;
            image.y = 577;
            image.width = 17;
            image.height = 18;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_sheep');
            image = new Image(texture);
            image.x = 725;
            image.y = 553;
            image.width = 17;
            image.height = 18;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_sheep');
            image = new Image(texture);
            image.x = 360;
            image.y = 250;
            image.width = 17;
            image.height = 18;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = -23;
            image.y = 479;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 486;
            image.y = 481;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian2');
            image = new Image(texture);
            image.x = 659;
            image.y = 95;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian3');
            image = new Image(texture);
            image.x = 549;
            image.y = 498;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian6');
            image = new Image(texture);
            image.x = 857;
            image.y = 258;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian7');
            image = new Image(texture);
            image.x = 851;
            image.y = 329;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian1');
            image = new Image(texture);
            image.x = 248;
            image.y = 119;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian1');
            image = new Image(texture);
            image.x = 288;
            image.y = 307;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian6');
            image = new Image(texture);
            image.x = 625;
            image.y = 433;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian1');
            image = new Image(texture);
            image.x = 119;
            image.y = 116;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian3');
            image = new Image(texture);
            image.x = 396;
            image.y = 175;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian4');
            image = new Image(texture);
            image.x = 510;
            image.y = 189;
            image.width = 37;
            image.height = 37;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian6');
            image = new Image(texture);
            image.x = 489;
            image.y = 273;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian6');
            image = new Image(texture);
            image.x = 634;
            image.y = 344;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian6');
            image = new Image(texture);
            image.x = 865;
            image.y = 438;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian6');
            image = new Image(texture);
            image.x = 653;
            image.y = 242;
            image.width = 37;
            image.height = 37;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian6');
            image = new Image(texture);
            image.x = 635;
            image.y = 173;
            image.width = 37;
            image.height = 37;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian2');
            image = new Image(texture);
            image.x = 448;
            image.y = 524;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian1');
            image = new Image(texture);
            image.x = 373;
            image.y = 312;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian2');
            image = new Image(texture);
            image.x = 199;
            image.y = 312;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian6');
            image = new Image(texture);
            image.x = 152;
            image.y = 448;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian3');
            image = new Image(texture);
            image.x = 248;
            image.y = 484;
            image.width = 37;
            image.height = 37;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian1');
            image = new Image(texture);
            image.x = 312;
            image.y = 521;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian2');
            image = new Image(texture);
            image.x = 746;
            image.y = 137;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian3');
            image = new Image(texture);
            image.x = 814;
            image.y = 164;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_223 = new Button(texture);
            tag_223.name= 'tag_223';
            tag_223.x = 77;
            tag_223.y = 133;
            tag_223.width = 90;
            tag_223.height = 90;
            this.addQuiackChild(tag_223);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_224 = new Button(texture);
            tag_224.name= 'tag_224';
            tag_224.x = 206;
            tag_224.y = 137;
            tag_224.width = 90;
            tag_224.height = 90;
            this.addQuiackChild(tag_224);
            texture = assetMgr.getTexture('ui_zhuxian_boss_baozi');
            tag_225 = new Button(texture);
            tag_225.name= 'tag_225';
            tag_225.x = 349;
            tag_225.y = 136;
            tag_225.width = 90;
            tag_225.height = 90;
            this.addQuiackChild(tag_225);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_226 = new Button(texture);
            tag_226.name= 'tag_226';
            tag_226.x = 459;
            tag_226.y = 175;
            tag_226.width = 90;
            tag_226.height = 90;
            this.addQuiackChild(tag_226);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_227 = new Button(texture);
            tag_227.name= 'tag_227';
            tag_227.x = 515;
            tag_227.y = 250;
            tag_227.width = 90;
            tag_227.height = 90;
            this.addQuiackChild(tag_227);
            texture = assetMgr.getTexture('ui_zhuxian_boss_baozi');
            tag_228 = new Button(texture);
            tag_228.name= 'tag_228';
            tag_228.x = 455;
            tag_228.y = 323;
            tag_228.width = 90;
            tag_228.height = 90;
            this.addQuiackChild(tag_228);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_229 = new Button(texture);
            tag_229.name= 'tag_229';
            tag_229.x = 352;
            tag_229.y = 330;
            tag_229.width = 90;
            tag_229.height = 90;
            this.addQuiackChild(tag_229);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_230 = new Button(texture);
            tag_230.name= 'tag_230';
            tag_230.x = 261;
            tag_230.y = 321;
            tag_230.width = 90;
            tag_230.height = 90;
            this.addQuiackChild(tag_230);
            texture = assetMgr.getTexture('ui_zhuxian_boss_baozi');
            tag_231 = new Button(texture);
            tag_231.name= 'tag_231';
            tag_231.x = 161;
            tag_231.y = 361;
            tag_231.width = 90;
            tag_231.height = 90;
            this.addQuiackChild(tag_231);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_232 = new Button(texture);
            tag_232.name= 'tag_232';
            tag_232.x = 191;
            tag_232.y = 468;
            tag_232.width = 90;
            tag_232.height = 90;
            this.addQuiackChild(tag_232);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_233 = new Button(texture);
            tag_233.name= 'tag_233';
            tag_233.x = 284;
            tag_233.y = 534;
            tag_233.width = 90;
            tag_233.height = 90;
            this.addQuiackChild(tag_233);
            texture = assetMgr.getTexture('ui_zhuxian_boss_baozi');
            tag_234 = new Button(texture);
            tag_234.name= 'tag_234';
            tag_234.x = 400;
            tag_234.y = 536;
            tag_234.width = 90;
            tag_234.height = 90;
            this.addQuiackChild(tag_234);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_235 = new Button(texture);
            tag_235.name= 'tag_235';
            tag_235.x = 519;
            tag_235.y = 533;
            tag_235.width = 90;
            tag_235.height = 90;
            this.addQuiackChild(tag_235);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_236 = new Button(texture);
            tag_236.name= 'tag_236';
            tag_236.x = 610;
            tag_236.y = 493;
            tag_236.width = 90;
            tag_236.height = 90;
            this.addQuiackChild(tag_236);
            texture = assetMgr.getTexture('ui_zhuxian_boss_baozi');
            tag_237 = new Button(texture);
            tag_237.name= 'tag_237';
            tag_237.x = 653;
            tag_237.y = 388;
            tag_237.width = 90;
            tag_237.height = 90;
            this.addQuiackChild(tag_237);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_238 = new Button(texture);
            tag_238.name= 'tag_238';
            tag_238.x = 645;
            tag_238.y = 295;
            tag_238.width = 90;
            tag_238.height = 90;
            this.addQuiackChild(tag_238);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_239 = new Button(texture);
            tag_239.name= 'tag_239';
            tag_239.x = 623;
            tag_239.y = 226;
            tag_239.width = 90;
            tag_239.height = 90;
            this.addQuiackChild(tag_239);
            texture = assetMgr.getTexture('ui_zhuxian_boss_baozi');
            tag_240 = new Button(texture);
            tag_240.name= 'tag_240';
            tag_240.x = 610;
            tag_240.y = 128;
            tag_240.width = 90;
            tag_240.height = 90;
            this.addQuiackChild(tag_240);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_241 = new Button(texture);
            tag_241.name= 'tag_241';
            tag_241.x = 720;
            tag_241.y = 112;
            tag_241.width = 90;
            tag_241.height = 90;
            this.addQuiackChild(tag_241);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_242 = new Button(texture);
            tag_242.name= 'tag_242';
            tag_242.x = 803;
            tag_242.y = 130;
            tag_242.width = 90;
            tag_242.height = 90;
            this.addQuiackChild(tag_242);
            texture = assetMgr.getTexture('ui_zhuxian_bigboss_airenguowang');
            tag_243 = new Button(texture);
            tag_243.name= 'tag_243';
            tag_243.x = 898;
            tag_243.y = 195;
            tag_243.width = 120;
            tag_243.height = 120;
            this.addQuiackChild(tag_243);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_244 = new Button(texture);
            tag_244.name= 'tag_244';
            tag_244.x = 871;
            tag_244.y = 314;
            tag_244.width = 90;
            tag_244.height = 90;
            this.addQuiackChild(tag_244);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_245 = new Button(texture);
            tag_245.name= 'tag_245';
            tag_245.x = 875;
            tag_245.y = 384;
            tag_245.width = 90;
            tag_245.height = 90;
            this.addQuiackChild(tag_245);
            texture = assetMgr.getTexture('ui_zhuxian_bigboss_airenguowang');
            tag_246 = new Button(texture);
            tag_246.name= 'tag_246';
            tag_246.x = 904;
            tag_246.y = 493;
            tag_246.width = 120;
            tag_246.height = 120;
            this.addQuiackChild(tag_246);
        }
        override public function dispose():void
        {
            view_bg.dispose();
            tag_223.dispose();
            tag_224.dispose();
            tag_225.dispose();
            tag_226.dispose();
            tag_227.dispose();
            tag_228.dispose();
            tag_229.dispose();
            tag_230.dispose();
            tag_231.dispose();
            tag_232.dispose();
            tag_233.dispose();
            tag_234.dispose();
            tag_235.dispose();
            tag_236.dispose();
            tag_237.dispose();
            tag_238.dispose();
            tag_239.dispose();
            tag_240.dispose();
            tag_241.dispose();
            tag_242.dispose();
            tag_243.dispose();
            tag_244.dispose();
            tag_245.dispose();
            tag_246.dispose();
            super.dispose();
        
}
    }
}
