package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import game.scene.world.NewMapRender;

    public class map_world_3Base extends NewMapRender
    {
        public var view_bg:Sprite;
        public var tag_67:Button;
        public var tag_68:Button;
        public var tag_69:Button;
        public var tag_70:Button;
        public var tag_71:Button;
        public var tag_72:Button;
        public var tag_73:Button;
        public var tag_74:Button;
        public var tag_75:Button;
        public var tag_76:Button;
        public var tag_77:Button;
        public var tag_78:Button;
        public var tag_79:Button;
        public var tag_80:Button;
        public var tag_81:Button;
        public var tag_82:Button;
        public var tag_83:Button;
        public var tag_84:Button;
        public var tag_85:Button;
        public var tag_86:Button;
        public var tag_87:Button;

        public function map_world_3Base()
        {
            var texture:Texture;
            var textField:TextField;
            var image:Image;
            var button:Button;;
            var assetMgr:AssetMgr = AssetMgr.instance;
            view_bg = new Sprite();
            view_bg.width = 969;
            view_bg.height = 640;
            this.addQuiackChild(view_bg);
            view_bg.name= 'view_bg';
            texture =assetMgr.getTexture('worldmap_background2');
            image = new Image(texture);
            image.x = 221;
            image.width = 237;
            image.height = 640;
            image.smoothing= Constants.NONE;
            view_bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_background2');
            image = new Image(texture);
            image.x = 456;
            image.width = 237;
            image.height = 640;
            image.smoothing= Constants.NONE;
            view_bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_background2');
            image = new Image(texture);
            image.x = 543;
            image.width = 237;
            image.height = 640;
            image.smoothing= Constants.NONE;
            view_bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_background2');
            image = new Image(texture);
            image.width = 237;
            image.height = 640;
            image.smoothing= Constants.NONE;
            view_bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_background2');
            image = new Image(texture);
            image.x = 732;
            image.width = 237;
            image.height = 640;
            image.smoothing= Constants.NONE;
            view_bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 48;
            image.y = 15;
            image.width = 108;
            image.height = 135;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 74;
            image.y = 76;
            image.width = 108;
            image.height = 135;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 62;
            image.y = 130;
            image.width = 108;
            image.height = 135;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 58;
            image.y = 199;
            image.width = 108;
            image.height = 135;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain2');
            image = new Image(texture);
            image.x = 9;
            image.y = 32;
            image.width = 134;
            image.height = 91;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree2');
            image = new Image(texture);
            image.x = 787;
            image.y = 12;
            image.width = 161;
            image.height = 138;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree2');
            image = new Image(texture);
            image.x = 858;
            image.y = 23;
            image.width = 161;
            image.height = 138;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree1');
            image = new Image(texture);
            image.x = 610;
            image.y = 123;
            image.width = 237;
            image.height = 155;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 880;
            image.y = 102;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree2');
            image = new Image(texture);
            image.x = 862;
            image.y = 144;
            image.width = 161;
            image.height = 138;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 495;
            image.y = 292;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 547;
            image.y = 426;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave4');
            image = new Image(texture);
            image.x = 607;
            image.y = 420;
            image.width = 51;
            image.height = 41;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave5');
            image = new Image(texture);
            image.x = 787;
            image.y = 313;
            image.width = 181;
            image.height = 129;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 528;
            image.y = 486;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave3');
            image = new Image(texture);
            image.x = 578;
            image.y = 469;
            image.width = 45;
            image.height = 42;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave2');
            image = new Image(texture);
            image.x = 650;
            image.y = 475;
            image.width = 34;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert4');
            image = new Image(texture);
            image.x = 410;
            image.y = 381;
            image.width = 118;
            image.height = 59;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert5');
            image = new Image(texture);
            image.x = 427;
            image.y = 234;
            image.width = 63;
            image.height = 30;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert4');
            image = new Image(texture);
            image.x = 566;
            image.y = 546;
            image.width = 118;
            image.height = 59;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert3');
            image = new Image(texture);
            image.x = 31;
            image.y = 399;
            image.width = 105;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert1');
            image = new Image(texture);
            image.x = 160;
            image.y = 207;
            image.width = 69;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave3');
            image = new Image(texture);
            image.x = 607;
            image.y = 515;
            image.width = 45;
            image.height = 42;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 621;
            image.y = 489;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 495;
            image.y = 518;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 650;
            image.y = 546;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 664;
            image.y = 239;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 885;
            image.y = 229;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 906;
            image.y = 235;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 919;
            image.y = 255;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 885;
            image.y = 268;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 906;
            image.y = 292;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 932;
            image.y = 308;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 862;
            image.y = 271;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 748;
            image.y = 247;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 780;
            image.y = 229;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 776;
            image.y = 247;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 716;
            image.y = 255;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 689;
            image.y = 292;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 756;
            image.y = 278;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 689;
            image.y = 330;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 658;
            image.y = 308;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 684;
            image.y = 255;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 776;
            image.y = 387;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 781;
            image.y = 416;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 811;
            image.y = 394;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 895;
            image.y = 404;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 916;
            image.y = 426;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = -12;
            image.y = 432;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = -12;
            image.y = 485;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 38;
            image.y = 475;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert4');
            image = new Image(texture);
            image.x = 499;
            image.y = 541;
            image.width = 118;
            image.height = 59;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert4');
            image = new Image(texture);
            image.x = 27;
            image.y = 532;
            image.width = 118;
            image.height = 59;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert5');
            image = new Image(texture);
            image.x = 141;
            image.y = 481;
            image.width = 63;
            image.height = 30;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_lake2');
            image = new Image(texture);
            image.x = 249;
            image.y = 118;
            image.width = 130;
            image.height = 126;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree2');
            image = new Image(texture);
            image.x = 386;
            image.y = 6;
            image.width = 161;
            image.height = 138;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree2');
            image = new Image(texture);
            image.x = 479;
            image.y = 12;
            image.width = 161;
            image.height = 138;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree2');
            image = new Image(texture);
            image.x = 422;
            image.y = 69;
            image.width = 161;
            image.height = 138;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree3');
            image = new Image(texture);
            image.x = 439;
            image.y = 148;
            image.width = 116;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 452;
            image.y = 298;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 474;
            image.y = 236;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 505;
            image.y = 232;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 490;
            image.y = 253;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 422;
            image.y = 268;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 410;
            image.y = 308;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain2');
            image = new Image(texture);
            image.x = 20;
            image.y = 89;
            image.width = 134;
            image.height = 91;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain2');
            image = new Image(texture);
            image.x = 62;
            image.y = 36;
            image.width = 134;
            image.height = 91;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 135;
            image.y = 112;
            image.width = 108;
            image.height = 135;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert1');
            image = new Image(texture);
            image.x = 196;
            image.y = 241;
            image.width = 69;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert1');
            image = new Image(texture);
            image.x = 127;
            image.y = 268;
            image.width = 69;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert1');
            image = new Image(texture);
            image.x = 135;
            image.y = 308;
            image.width = 69;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert1');
            image = new Image(texture);
            image.x = 74;
            image.y = 334;
            image.width = 69;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert1');
            image = new Image(texture);
            image.x = 107;
            image.y = 370;
            image.width = 69;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert1');
            image = new Image(texture);
            image.x = 168;
            image.y = 363;
            image.width = 69;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert1');
            image = new Image(texture);
            image.x = 142;
            image.y = 396;
            image.width = 69;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave1');
            image = new Image(texture);
            image.x = 154;
            image.y = 285;
            image.width = 38;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave1');
            image = new Image(texture);
            image.x = 52;
            image.y = 432;
            image.width = 38;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave1');
            image = new Image(texture);
            image.x = 191;
            image.y = 234;
            image.width = 38;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave1');
            image = new Image(texture);
            image.x = 191;
            image.y = 329;
            image.width = 38;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert1');
            image = new Image(texture);
            image.x = 196;
            image.y = 281;
            image.width = 69;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 647;
            image.y = 356;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 652;
            image.y = 404;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 617;
            image.y = 378;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 673;
            image.y = 361;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 665;
            image.y = 330;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 636;
            image.y = 330;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 658;
            image.y = 277;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert4');
            image = new Image(texture);
            image.x = 299;
            image.y = 337;
            image.width = 118;
            image.height = 59;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_city1');
            image = new Image(texture);
            image.x = 377;
            image.y = 354;
            image.width = 80;
            image.height = 66;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert4');
            image = new Image(texture);
            image.x = 312;
            image.y = 384;
            image.width = 118;
            image.height = 59;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 452;
            image.y = 332;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave3');
            image = new Image(texture);
            image.x = 483;
            image.y = 354;
            image.width = 45;
            image.height = 42;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave3');
            image = new Image(texture);
            image.x = 365;
            image.y = 309;
            image.width = 45;
            image.height = 42;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 495;
            image.y = 318;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 458;
            image.y = 265;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree7');
            image = new Image(texture);
            image.x = 392;
            image.y = 241;
            image.width = 47;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert4');
            image = new Image(texture);
            image.x = 116;
            image.y = 532;
            image.width = 118;
            image.height = 59;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert4');
            image = new Image(texture);
            image.x = 190;
            image.y = 532;
            image.width = 118;
            image.height = 59;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 99;
            image.y = 475;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 122;
            image.y = 428;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert1');
            image = new Image(texture);
            image.x = 243;
            image.y = 250;
            image.width = 69;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert1');
            image = new Image(texture);
            image.x = 84;
            image.y = 294;
            image.width = 69;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert1');
            image = new Image(texture);
            image.x = 27;
            image.y = 354;
            image.width = 69;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave1');
            image = new Image(texture);
            image.x = 117;
            image.y = 381;
            image.width = 38;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_house1');
            image = new Image(texture);
            image.x = 103;
            image.y = 308;
            image.width = 83;
            image.height = 70;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_house1');
            image = new Image(texture);
            image.x = 96;
            image.y = 428;
            image.width = 83;
            image.height = 70;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave4');
            image = new Image(texture);
            image.x = 160;
            image.y = 384;
            image.width = 51;
            image.height = 41;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree4');
            image = new Image(texture);
            image.x = 427;
            image.y = 532;
            image.width = 82;
            image.height = 63;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 450;
            image.y = 479;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 690;
            image.y = 524;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert4');
            image = new Image(texture);
            image.x = 766;
            image.y = 546;
            image.width = 118;
            image.height = 59;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert1');
            image = new Image(texture);
            image.x = 220;
            image.y = 211;
            image.width = 69;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert1');
            image = new Image(texture);
            image.x = 230;
            image.y = 281;
            image.width = 69;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian1');
            image = new Image(texture);
            image.x = 683;
            image.y = 90;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian4');
            image = new Image(texture);
            image.x = 603;
            image.y = 130;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian7');
            image = new Image(texture);
            image.x = 575;
            image.y = 216;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian2');
            image = new Image(texture);
            image.x = 289;
            image.y = 91;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian3');
            image = new Image(texture);
            image.x = 450;
            image.y = 485;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian7');
            image = new Image(texture);
            image.x = 837;
            image.y = 227;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian5');
            image = new Image(texture);
            image.x = 810;
            image.y = 171;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian4');
            image = new Image(texture);
            image.x = 806;
            image.y = 308;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian6');
            image = new Image(texture);
            image.x = 720;
            image.y = 396;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian5');
            image = new Image(texture);
            image.x = 726;
            image.y = 516;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian1');
            image = new Image(texture);
            image.x = 795;
            image.y = 524;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian4');
            image = new Image(texture);
            image.x = 533;
            image.y = 438;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian6');
            image = new Image(texture);
            image.x = 578;
            image.y = 358;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian4');
            image = new Image(texture);
            image.x = 383;
            image.y = 219;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian5');
            image = new Image(texture);
            image.x = 389;
            image.y = 164;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian5');
            image = new Image(texture);
            image.x = 167;
            image.y = 179;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian4');
            image = new Image(texture);
            image.x = 90;
            image.y = 269;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian4');
            image = new Image(texture);
            image.x = 281;
            image.y = 319;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian7');
            image = new Image(texture);
            image.x = 229;
            image.y = 418;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian2');
            image = new Image(texture);
            image.x = 274;
            image.y = 543;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian3');
            image = new Image(texture);
            image.x = 6;
            image.y = 333;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_67 = new Button(texture);
            tag_67.name= 'tag_67';
            tag_67.x = 66;
            tag_67.y = 326;
            tag_67.width = 90;
            tag_67.height = 90;
            this.addQuiackChild(tag_67);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_68 = new Button(texture);
            tag_68.name= 'tag_68';
            tag_68.x = 146;
            tag_68.y = 242;
            tag_68.width = 90;
            tag_68.height = 90;
            this.addQuiackChild(tag_68);
            texture = assetMgr.getTexture('ui_zhuxian_boss_baozi');
            tag_69 = new Button(texture);
            tag_69.name= 'tag_69';
            tag_69.x = 238;
            tag_69.y = 129;
            tag_69.width = 90;
            tag_69.height = 90;
            this.addQuiackChild(tag_69);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_70 = new Button(texture);
            tag_70.name= 'tag_70';
            tag_70.x = 366;
            tag_70.y = 106;
            tag_70.width = 90;
            tag_70.height = 90;
            this.addQuiackChild(tag_70);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_71 = new Button(texture);
            tag_71.name= 'tag_71';
            tag_71.x = 428;
            tag_71.y = 190;
            tag_71.width = 90;
            tag_71.height = 90;
            this.addQuiackChild(tag_71);
            texture = assetMgr.getTexture('ui_zhuxian_boss_baozi');
            tag_72 = new Button(texture);
            tag_72.name= 'tag_72';
            tag_72.x = 351;
            tag_72.y = 285;
            tag_72.width = 90;
            tag_72.height = 90;
            this.addQuiackChild(tag_72);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_73 = new Button(texture);
            tag_73.name= 'tag_73';
            tag_73.x = 266;
            tag_73.y = 382;
            tag_73.width = 90;
            tag_73.height = 90;
            this.addQuiackChild(tag_73);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_74 = new Button(texture);
            tag_74.name= 'tag_74';
            tag_74.x = 252;
            tag_74.y = 495;
            tag_74.width = 90;
            tag_74.height = 90;
            this.addQuiackChild(tag_74);
            texture = assetMgr.getTexture('ui_zhuxian_bigboss_airenguowang');
            tag_75 = new Button(texture);
            tag_75.name= 'tag_75';
            tag_75.x = 379;
            tag_75.y = 521;
            tag_75.width = 120;
            tag_75.height = 120;
            this.addQuiackChild(tag_75);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_76 = new Button(texture);
            tag_76.name= 'tag_76';
            tag_76.x = 519;
            tag_76.y = 486;
            tag_76.width = 90;
            tag_76.height = 90;
            this.addQuiackChild(tag_76);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_77 = new Button(texture);
            tag_77.name= 'tag_77';
            tag_77.x = 578;
            tag_77.y = 418;
            tag_77.width = 90;
            tag_77.height = 90;
            this.addQuiackChild(tag_77);
            texture = assetMgr.getTexture('ui_zhuxian_boss_baozi');
            tag_78 = new Button(texture);
            tag_78.name= 'tag_78';
            tag_78.x = 599;
            tag_78.y = 301;
            tag_78.width = 90;
            tag_78.height = 90;
            this.addQuiackChild(tag_78);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_79 = new Button(texture);
            tag_79.name= 'tag_79';
            tag_79.x = 593;
            tag_79.y = 189;
            tag_79.width = 90;
            tag_79.height = 90;
            this.addQuiackChild(tag_79);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_80 = new Button(texture);
            tag_80.name= 'tag_80';
            tag_80.x = 661;
            tag_80.y = 118;
            tag_80.width = 90;
            tag_80.height = 90;
            this.addQuiackChild(tag_80);
            texture = assetMgr.getTexture('ui_zhuxian_boss_baozi');
            tag_81 = new Button(texture);
            tag_81.name= 'tag_81';
            tag_81.x = 767;
            tag_81.y = 111;
            tag_81.width = 90;
            tag_81.height = 90;
            this.addQuiackChild(tag_81);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_82 = new Button(texture);
            tag_82.name= 'tag_82';
            tag_82.x = 851;
            tag_82.y = 192;
            tag_82.width = 90;
            tag_82.height = 90;
            this.addQuiackChild(tag_82);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_83 = new Button(texture);
            tag_83.name= 'tag_83';
            tag_83.x = 854;
            tag_83.y = 294;
            tag_83.width = 90;
            tag_83.height = 90;
            this.addQuiackChild(tag_83);
            texture = assetMgr.getTexture('ui_zhuxian_boss_baozi');
            tag_84 = new Button(texture);
            tag_84.name= 'tag_84';
            tag_84.x = 767;
            tag_84.y = 355;
            tag_84.width = 90;
            tag_84.height = 90;
            this.addQuiackChild(tag_84);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_85 = new Button(texture);
            tag_85.name= 'tag_85';
            tag_85.x = 730;
            tag_85.y = 452;
            tag_85.width = 90;
            tag_85.height = 90;
            this.addQuiackChild(tag_85);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_86 = new Button(texture);
            tag_86.name= 'tag_86';
            tag_86.x = 771;
            tag_86.y = 536;
            tag_86.width = 90;
            tag_86.height = 90;
            this.addQuiackChild(tag_86);
            texture = assetMgr.getTexture('ui_zhuxian_bigboss_airenguowang');
            tag_87 = new Button(texture);
            tag_87.name= 'tag_87';
            tag_87.x = 881;
            tag_87.y = 522;
            tag_87.width = 120;
            tag_87.height = 120;
            this.addQuiackChild(tag_87);
        }
        override public function dispose():void
        {
            view_bg.dispose();
            tag_67.dispose();
            tag_68.dispose();
            tag_69.dispose();
            tag_70.dispose();
            tag_71.dispose();
            tag_72.dispose();
            tag_73.dispose();
            tag_74.dispose();
            tag_75.dispose();
            tag_76.dispose();
            tag_77.dispose();
            tag_78.dispose();
            tag_79.dispose();
            tag_80.dispose();
            tag_81.dispose();
            tag_82.dispose();
            tag_83.dispose();
            tag_84.dispose();
            tag_85.dispose();
            tag_86.dispose();
            tag_87.dispose();
            super.dispose();
        
}
    }
}
