package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import game.scene.world.NewMapRender;

    public class map_world_2Base extends NewMapRender
    {
        public var view_bg:Sprite;
        public var tag_46:Button;
        public var tag_47:Button;
        public var tag_48:Button;
        public var tag_49:Button;
        public var tag_50:Button;
        public var tag_51:Button;
        public var tag_52:Button;
        public var tag_53:Button;
        public var tag_54:Button;
        public var tag_55:Button;
        public var tag_56:Button;
        public var tag_57:Button;
        public var tag_58:Button;
        public var tag_59:Button;
        public var tag_60:Button;
        public var tag_61:Button;
        public var tag_62:Button;
        public var tag_63:Button;
        public var tag_64:Button;
        public var tag_65:Button;
        public var tag_66:Button;

        public function map_world_2Base()
        {
            var texture:Texture;
            var textField:TextField;
            var image:Image;
            var button:Button;;
            var assetMgr:AssetMgr = AssetMgr.instance;
            view_bg = new Sprite();
            view_bg.width = 969;
            view_bg.height = 640;
            this.addQuiackChild(view_bg);
            view_bg.name= 'view_bg';
            texture =assetMgr.getTexture('worldmap_background2');
            image = new Image(texture);
            image.x = 221;
            image.width = 237;
            image.height = 640;
            image.smoothing= Constants.NONE;
            view_bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_background2');
            image = new Image(texture);
            image.x = 456;
            image.width = 237;
            image.height = 640;
            image.smoothing= Constants.NONE;
            view_bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_background2');
            image = new Image(texture);
            image.x = 543;
            image.width = 237;
            image.height = 640;
            image.smoothing= Constants.NONE;
            view_bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_background2');
            image = new Image(texture);
            image.width = 237;
            image.height = 640;
            image.smoothing= Constants.NONE;
            view_bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_background2');
            image = new Image(texture);
            image.x = 732;
            image.width = 237;
            image.height = 640;
            image.smoothing= Constants.NONE;
            view_bg.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = -136;
            image.y = 145;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = -136;
            image.y = 226;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = -121;
            image.y = 319;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = -97;
            image.y = 422;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_house5');
            image = new Image(texture);
            image.x = 282;
            image.y = 401;
            image.width = 30;
            image.height = 35;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_farmland1');
            image = new Image(texture);
            image.x = 183;
            image.y = 361;
            image.width = 87;
            image.height = 61;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 516;
            image.y = 145;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_lake2');
            image = new Image(texture);
            image.x = 356;
            image.y = 145;
            image.width = 130;
            image.height = 126;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain2');
            image = new Image(texture);
            image.x = -54;
            image.y = 214;
            image.width = 134;
            image.height = 91;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = -19;
            image.y = 268;
            image.width = 108;
            image.height = 135;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree12');
            image = new Image(texture);
            image.x = 486;
            image.y = 148;
            image.width = 43;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 553;
            image.y = 137;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_farmland1');
            image = new Image(texture);
            image.x = 161;
            image.y = 401;
            image.width = 87;
            image.height = 61;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_house5');
            image = new Image(texture);
            image.x = 260;
            image.y = 379;
            image.width = 30;
            image.height = 35;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_house5');
            image = new Image(texture);
            image.x = 240;
            image.y = 416;
            image.width = 30;
            image.height = 35;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 126;
            image.y = 38;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 26;
            image.y = 38;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree10');
            image = new Image(texture);
            image.x = 83;
            image.y = 129;
            image.width = 177;
            image.height = 131;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 492;
            image.y = 169;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 599;
            image.y = 247;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 629;
            image.y = 239;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 687;
            image.y = 185;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 679;
            image.y = 158;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 657;
            image.y = 142;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 632;
            image.y = 134;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 600;
            image.y = 129;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 576;
            image.y = 129;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_city3');
            image = new Image(texture);
            image.x = 505;
            image.y = 134;
            image.width = 225;
            image.height = 143;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 563;
            image.y = 247;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 513;
            image.y = 220;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 535;
            image.y = 236;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 492;
            image.y = 199;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 484;
            image.y = 231;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 506;
            image.y = 247;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 463;
            image.y = 211;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree12');
            image = new Image(texture);
            image.x = 473;
            image.y = 189;
            image.width = 43;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree12');
            image = new Image(texture);
            image.x = 473;
            image.y = 161;
            image.width = 43;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree10');
            image = new Image(texture);
            image.x = 321;
            image.y = 252;
            image.width = 177;
            image.height = 131;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree9');
            image = new Image(texture);
            image.x = 415;
            image.y = 342;
            image.width = 98;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree9');
            image = new Image(texture);
            image.x = 421;
            image.y = 388;
            image.width = 98;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 648;
            image.y = 349;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 560;
            image.y = 328;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 667;
            image.y = 300;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 401;
            image.y = 414;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 364;
            image.y = 466;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = 439;
            image.y = 486;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree9');
            image = new Image(texture);
            image.x = 164;
            image.y = 245;
            image.width = 98;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_house2');
            image = new Image(texture);
            image.x = 156;
            image.y = 290;
            image.width = 87;
            image.height = 77;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 141;
            image.y = 247;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 244;
            image.y = 309;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree8');
            image = new Image(texture);
            image.x = 208;
            image.y = 219;
            image.width = 46;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 421;
            image.y = 226;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 445;
            image.y = 233;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 379;
            image.y = 193;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 282;
            image.y = 113;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 248;
            image.y = 129;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 317;
            image.y = 231;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 305;
            image.y = 83;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_house6');
            image = new Image(texture);
            image.x = 463;
            image.y = 63;
            image.width = 44;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_house4');
            image = new Image(texture);
            image.x = 763;
            image.y = 226;
            image.width = 115;
            image.height = 76;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_house2');
            image = new Image(texture);
            image.x = 665;
            image.y = 19;
            image.width = 87;
            image.height = 77;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_house6');
            image = new Image(texture);
            image.x = 498;
            image.y = 47;
            image.width = 44;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_dong');
            image = new Image(texture);
            image.x = 788;
            image.y = 364;
            image.width = 57;
            image.height = 60;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_house6');
            image = new Image(texture);
            image.x = 616;
            image.y = 53;
            image.width = 44;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_farmland1');
            image = new Image(texture);
            image.x = 529;
            image.y = 47;
            image.width = 87;
            image.height = 61;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_farmland1');
            image = new Image(texture);
            image.x = 758;
            image.y = 33;
            image.width = 87;
            image.height = 61;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_house6');
            image = new Image(texture);
            image.x = 415;
            image.y = 45;
            image.width = 44;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 377;
            image.y = 38;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 329;
            image.y = 32;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 287;
            image.y = 42;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 315;
            image.y = 52;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 353;
            image.y = 56;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 585;
            image.y = 19;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_house6');
            image = new Image(texture);
            image.x = 604;
            image.y = 76;
            image.width = 44;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_house6');
            image = new Image(texture);
            image.x = 851;
            image.y = 80;
            image.width = 44;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_house6');
            image = new Image(texture);
            image.x = 867;
            image.y = 119;
            image.width = 44;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_house6');
            image = new Image(texture);
            image.x = 863;
            image.y = 149;
            image.width = 44;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_house6');
            image = new Image(texture);
            image.x = 863;
            image.y = 183;
            image.width = 44;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 993;
            image.y = 14;
            image.width = 108;
            image.height = 135;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 1019;
            image.y = 75;
            image.width = 108;
            image.height = 135;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 1007;
            image.y = 129;
            image.width = 108;
            image.height = 135;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain3');
            image = new Image(texture);
            image.x = 1003;
            image.y = 198;
            image.width = 108;
            image.height = 135;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 738;
            image.y = 274;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 878;
            image.y = 212;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 824;
            image.y = 199;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 852;
            image.y = 38;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree13');
            image = new Image(texture);
            image.x = 887;
            image.y = 118;
            image.width = 47;
            image.height = 48;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_grave4');
            image = new Image(texture);
            image.x = 762;
            image.y = 437;
            image.width = 51;
            image.height = 41;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 793;
            image.y = 414;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 726;
            image.y = 469;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert2');
            image = new Image(texture);
            image.x = 802;
            image.y = 469;
            image.width = 122;
            image.height = 71;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_desert1');
            image = new Image(texture);
            image.x = 625;
            image.y = 521;
            image.width = 69;
            image.height = 53;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_farmland2');
            image = new Image(texture);
            image.x = 856;
            image.y = 514;
            image.width = 72;
            image.height = 54;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_farmland2');
            image = new Image(texture);
            image.x = 773;
            image.y = 533;
            image.width = 72;
            image.height = 54;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_boat');
            image = new Image(texture);
            image.x = 428;
            image.y = 180;
            image.width = 49;
            image.height = 43;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree9');
            image = new Image(texture);
            image.x = 329;
            image.y = 535;
            image.width = 98;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree9');
            image = new Image(texture);
            image.x = 264;
            image.y = 544;
            image.width = 98;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_tree9');
            image = new Image(texture);
            image.x = 212;
            image.y = 526;
            image.width = 98;
            image.height = 74;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain5');
            image = new Image(texture);
            image.x = -18;
            image.y = 480;
            image.width = 184;
            image.height = 134;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('worldmap_mountain1');
            image = new Image(texture);
            image.x = 128;
            image.y = 530;
            image.width = 120;
            image.height = 64;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian1');
            image = new Image(texture);
            image.x = 585;
            image.y = 90;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian2');
            image = new Image(texture);
            image.x = 587;
            image.y = 285;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian3');
            image = new Image(texture);
            image.x = 687;
            image.y = 249;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian4');
            image = new Image(texture);
            image.x = 757;
            image.y = 199;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian3');
            image = new Image(texture);
            image.x = 800;
            image.y = 507;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian4');
            image = new Image(texture);
            image.x = 874;
            image.y = 457;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian7');
            image = new Image(texture);
            image.x = 899;
            image.y = 383;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian2');
            image = new Image(texture);
            image.x = 665;
            image.y = 540;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian3');
            image = new Image(texture);
            image.x = 582;
            image.y = 499;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian5');
            image = new Image(texture);
            image.x = 531;
            image.y = 415;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian3');
            image = new Image(texture);
            image.x = 731;
            image.y = 105;
            image.width = 37;
            image.height = 37;
            image.scaleX = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian4');
            image = new Image(texture);
            image.x = 338;
            image.y = 154;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian5');
            image = new Image(texture);
            image.x = 48;
            image.y = 203;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian6');
            image = new Image(texture);
            image.x = 109;
            image.y = 434;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian7');
            image = new Image(texture);
            image.x = 87;
            image.y = 258;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian5');
            image = new Image(texture);
            image.x = 280;
            image.y = 234;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian6');
            image = new Image(texture);
            image.x = 295;
            image.y = 375;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian2');
            image = new Image(texture);
            image.x = 180;
            image.y = 506;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian2');
            image = new Image(texture);
            image.x = 471;
            image.y = 100;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian3');
            image = new Image(texture);
            image.x = 284;
            image.y = 464;
            image.width = 37;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_zhuxian_luxian5');
            image = new Image(texture);
            image.x = -7;
            image.y = 118;
            image.width = 37;
            image.height = 37;
            image.scaleY = -1;;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_46 = new Button(texture);
            tag_46.name= 'tag_46';
            tag_46.x = 38;
            tag_46.y = 137;
            tag_46.width = 90;
            tag_46.height = 90;
            this.addQuiackChild(tag_46);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_47 = new Button(texture);
            tag_47.name= 'tag_47';
            tag_47.x = 92;
            tag_47.y = 226;
            tag_47.width = 90;
            tag_47.height = 90;
            this.addQuiackChild(tag_47);
            texture = assetMgr.getTexture('ui_zhuxian_boss_baozi');
            tag_48 = new Button(texture);
            tag_48.name= 'tag_48';
            tag_48.x = 116;
            tag_48.y = 340;
            tag_48.width = 90;
            tag_48.height = 90;
            this.addQuiackChild(tag_48);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_49 = new Button(texture);
            tag_49.name= 'tag_49';
            tag_49.x = 148;
            tag_49.y = 465;
            tag_49.width = 90;
            tag_49.height = 90;
            this.addQuiackChild(tag_49);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_50 = new Button(texture);
            tag_50.name= 'tag_50';
            tag_50.x = 260;
            tag_50.y = 495;
            tag_50.width = 90;
            tag_50.height = 90;
            this.addQuiackChild(tag_50);
            texture = assetMgr.getTexture('ui_zhuxian_boss_baozi');
            tag_51 = new Button(texture);
            tag_51.name= 'tag_51';
            tag_51.x = 339;
            tag_51.y = 423;
            tag_51.width = 90;
            tag_51.height = 90;
            this.addQuiackChild(tag_51);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_52 = new Button(texture);
            tag_52.name= 'tag_52';
            tag_52.x = 297;
            tag_52.y = 303;
            tag_52.width = 90;
            tag_52.height = 90;
            this.addQuiackChild(tag_52);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_53 = new Button(texture);
            tag_53.name= 'tag_53';
            tag_53.x = 323;
            tag_53.y = 203;
            tag_53.width = 90;
            tag_53.height = 90;
            this.addQuiackChild(tag_53);
            texture = assetMgr.getTexture('ui_zhuxian_boss_baozi');
            tag_54 = new Button(texture);
            tag_54.name= 'tag_54';
            tag_54.x = 418;
            tag_54.y = 133;
            tag_54.width = 90;
            tag_54.height = 90;
            this.addQuiackChild(tag_54);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_55 = new Button(texture);
            tag_55.name= 'tag_55';
            tag_55.x = 542;
            tag_55.y = 112;
            tag_55.width = 90;
            tag_55.height = 90;
            this.addQuiackChild(tag_55);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_56 = new Button(texture);
            tag_56.name= 'tag_56';
            tag_56.x = 661;
            tag_56.y = 110;
            tag_56.width = 90;
            tag_56.height = 90;
            this.addQuiackChild(tag_56);
            texture = assetMgr.getTexture('ui_zhuxian_bigboss_airenguowang');
            tag_57 = new Button(texture);
            tag_57.name= 'tag_57';
            tag_57.x = 805;
            tag_57.y = 143;
            tag_57.width = 120;
            tag_57.height = 120;
            this.addQuiackChild(tag_57);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_58 = new Button(texture);
            tag_58.name= 'tag_58';
            tag_58.x = 749;
            tag_58.y = 245;
            tag_58.width = 90;
            tag_58.height = 90;
            this.addQuiackChild(tag_58);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_59 = new Button(texture);
            tag_59.name= 'tag_59';
            tag_59.x = 659;
            tag_59.y = 288;
            tag_59.width = 90;
            tag_59.height = 90;
            this.addQuiackChild(tag_59);
            texture = assetMgr.getTexture('ui_zhuxian_boss_baozi');
            tag_60 = new Button(texture);
            tag_60.name= 'tag_60';
            tag_60.x = 544;
            tag_60.y = 325;
            tag_60.width = 90;
            tag_60.height = 90;
            this.addQuiackChild(tag_60);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_61 = new Button(texture);
            tag_61.name= 'tag_61';
            tag_61.x = 571;
            tag_61.y = 440;
            tag_61.width = 90;
            tag_61.height = 90;
            this.addQuiackChild(tag_61);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_62 = new Button(texture);
            tag_62.name= 'tag_62';
            tag_62.x = 645;
            tag_62.y = 502;
            tag_62.width = 90;
            tag_62.height = 90;
            this.addQuiackChild(tag_62);
            texture = assetMgr.getTexture('ui_zhuxian_boss_baozi');
            tag_63 = new Button(texture);
            tag_63.name= 'tag_63';
            tag_63.x = 750;
            tag_63.y = 533;
            tag_63.width = 90;
            tag_63.height = 90;
            this.addQuiackChild(tag_63);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_64 = new Button(texture);
            tag_64.name= 'tag_64';
            tag_64.x = 858;
            tag_64.y = 507;
            tag_64.width = 90;
            tag_64.height = 90;
            this.addQuiackChild(tag_64);
            texture = assetMgr.getTexture('ui_zhuxian_xiaoguanka');
            tag_65 = new Button(texture);
            tag_65.name= 'tag_65';
            tag_65.x = 917;
            tag_65.y = 440;
            tag_65.width = 90;
            tag_65.height = 90;
            this.addQuiackChild(tag_65);
            texture = assetMgr.getTexture('ui_zhuxian_bigboss_airenguowang');
            tag_66 = new Button(texture);
            tag_66.name= 'tag_66';
            tag_66.x = 870;
            tag_66.y = 325;
            tag_66.width = 120;
            tag_66.height = 120;
            this.addQuiackChild(tag_66);
        }
        override public function dispose():void
        {
            view_bg.dispose();
            tag_46.dispose();
            tag_47.dispose();
            tag_48.dispose();
            tag_49.dispose();
            tag_50.dispose();
            tag_51.dispose();
            tag_52.dispose();
            tag_53.dispose();
            tag_54.dispose();
            tag_55.dispose();
            tag_56.dispose();
            tag_57.dispose();
            tag_58.dispose();
            tag_59.dispose();
            tag_60.dispose();
            tag_61.dispose();
            tag_62.dispose();
            tag_63.dispose();
            tag_64.dispose();
            tag_65.dispose();
            tag_66.dispose();
            super.dispose();
        
}
    }
}
