package game.view.viewBase {
    import com.components.TabButton;
    import com.components.TabMenu;
    import com.dialog.Dialog;
    import com.utils.Constants;

    import feathers.controls.List;
    import feathers.controls.TextInput;

    import game.manager.AssetMgr;

    import starling.display.Button;
    import starling.display.Image;
    import starling.text.TextField;
    import starling.textures.Texture;

    public class NewBlacksmithDlgBase extends Dialog {
        public var text_diamond:TextField;
        public var text_coin:TextField;
        public var btn_close:Button;
        public var btn_click:Button;
        public var txt_money:TextField;
        public var txt_diamond:TextField;
        public var tab_1:TabButton;
        public var tab_2:TabButton;
        public var tab_3:TabButton;
        public var tab_4:TabButton;
        public var list_equip:List;
        public var tabMenu_hero:TabMenu;
        public var tag_diamond:Button;
        public var tag_money:Button;
        public var list_bag:List;

        public function NewBlacksmithDlgBase() {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            var assetMgr:AssetMgr = AssetMgr.instance;
            texture = assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.y = 1;
            image.width = 490;
            image.height = 71;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.y = 72;
            image.width = 490;
            image.height = 71;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.y = 143;
            image.width = 490;
            image.height = 71;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.y = 213;
            image.width = 490;
            image.height = 71;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.y = 284;
            image.width = 490;
            image.height = 71;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.y = 355;
            image.width = 490;
            image.height = 71;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.y = 425;
            image.width = 490;
            image.height = 71;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 918;
            image.y = 1;
            image.width = 490;
            image.height = 71;
            image.scaleX = -0.96868896484375;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 918;
            image.y = 72;
            image.width = 490;
            image.height = 71;
            image.scaleX = -0.96868896484375;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 918;
            image.y = 143;
            image.width = 490;
            image.height = 71;
            image.scaleX = -0.96868896484375;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 918;
            image.y = 213;
            image.width = 490;
            image.height = 71;
            image.scaleX = -0.96868896484375;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 918;
            image.y = 284;
            image.width = 490;
            image.height = 71;
            image.scaleX = -0.96868896484375;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 918;
            image.y = 355;
            image.width = 490;
            image.height = 71;
            image.scaleX = -0.96868896484375;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 918;
            image.y = 425;
            image.width = 490;
            image.height = 71;
            image.scaleX = -0.96868896484375;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian3_hei');
            image = new Image(texture);
            image.x = 471;
            image.y = 105;
            image.width = 413;
            image.height = 267;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian1_hei');
            image = new Image(texture);
            image.x = 463;
            image.y = 323;
            image.width = 20;
            image.height = 242;
            image.scaleY = -1;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian1_hei');
            image = new Image(texture);
            image.x = 462;
            image.y = 155;
            image.width = 20;
            image.height = 242;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian2_hei');
            image = new Image(texture);
            image.x = 480;
            image.y = 82;
            image.width = 401;
            image.height = 47;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian2_hei');
            image = new Image(texture);
            image.x = 482;
            image.y = 396;
            image.width = 393;
            image.height = 47;
            image.scaleY = -1;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian_hei');
            image = new Image(texture);
            image.x = 850;
            image.y = 343;
            image.width = 40;
            image.height = 261;
            image.scaleY = -1;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian_hei');
            image = new Image(texture);
            image.x = 851;
            image.y = 135;
            image.width = 40;
            image.height = 261;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_yingxiongshengdian_wenzikuang2');
            image = new Image(texture);
            image.x = 480;
            image.y = 397;
            image.width = 393;
            image.height = 94;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_yingxiongshengdian_wenzikuang1');
            image = new Image(texture);
            image.x = 461;
            image.y = 396;
            image.width = 31;
            image.height = 97;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_yingxiongshengdian_wenzikuang3');
            image = new Image(texture);
            image.x = 857;
            image.y = 396;
            image.width = 34;
            image.height = 95;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian3_hei');
            image = new Image(texture);
            image.x = 36;
            image.y = 105;
            image.width = 413;
            image.height = 267;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian1_hei');
            image = new Image(texture);
            image.x = 28;
            image.y = 323;
            image.width = 20;
            image.height = 242;
            image.scaleY = -1;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian1_hei');
            image = new Image(texture);
            image.x = 27;
            image.y = 155;
            image.width = 20;
            image.height = 242;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian2_hei');
            image = new Image(texture);
            image.x = 45;
            image.y = 82;
            image.width = 401;
            image.height = 47;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian2_hei');
            image = new Image(texture);
            image.x = 47;
            image.y = 396;
            image.width = 393;
            image.height = 47;
            image.scaleY = -1;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian_hei');
            image = new Image(texture);
            image.x = 415;
            image.y = 343;
            image.width = 40;
            image.height = 261;
            image.scaleY = -1;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian_hei');
            image = new Image(texture);
            image.x = 415;
            image.y = 135;
            image.width = 40;
            image.height = 261;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian_xiao_di');
            image = new Image(texture);
            image.x = 14;
            image.y = 512;
            image.width = 888;
            image.height = 117;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_guaijiaoshitou2');
            image = new Image(texture);
            image.x = 910;
            image.y = 515;
            image.width = 26;
            image.height = 102;
            image.scaleX = -0.997528076171875;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_guaijiaoshitou2');
            image = new Image(texture);
            image.x = 7;
            image.y = 511;
            image.width = 26;
            image.height = 102;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_guaijiaoshitou1');
            image = new Image(texture);
            image.x = 890;
            image.y = 498;
            image.width = 860;
            image.height = 24;
            image.scaleX = -10.749908447265625;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 4;
            image.y = 497;
            image.width = 38;
            image.height = 34;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_guaijiaoshitou1');
            image = new Image(texture);
            image.x = 890;
            image.y = 636;
            image.width = 860;
            image.height = 24;
            image.scaleX = -10.749801635742188;
            image.scaleY = -0.99786376953125;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 4;
            image.y = 637;
            image.width = 38;
            image.height = 34;
            image.scaleY = -0.99786376953125;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 914;
            image.y = 497;
            image.width = 38;
            image.height = 34;
            image.scaleX = -0.997528076171875;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 914;
            image.y = 637;
            image.width = 38;
            image.height = 34;
            image.scaleX = -0.997528076171875;
            image.scaleY = -0.99786376953125;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_jinbibaiziwenzidi');
            image = new Image(texture);
            image.x = 647;
            image.y = 4;
            image.width = 154;
            image.height = 43;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_jinbibaiziwenzidi');
            image = new Image(texture);
            image.x = 647;
            image.y = 42;
            image.width = 154;
            image.height = 43;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_money');
            image = new Image(texture);
            image.x = 634;
            image.y = 43;
            image.width = 40;
            image.height = 40;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_zuanshi');
            image = new Image(texture);
            image.x = 633;
            image.y = -1;
            image.width = 46;
            image.height = 44;
            image.smoothing = Constants.NONE;
            this.addQuiackChild(image);
            text_diamond = new TextField(160, 31, '', '', 21, 0xFFFFFF, false);
            text_diamond.touchable = false;
            text_diamond.hAlign = 'right';
            text_diamond.text = '9999999';
            text_diamond.x = 633;
            text_diamond.y = 9;
            this.addQuiackChild(text_diamond);
            text_coin = new TextField(160, 31, '', '', 21, 0xFFFFFF, false);
            text_coin.touchable = false;
            text_coin.hAlign = 'right';
            text_coin.text = '9999999';
            text_coin.x = 634;
            text_coin.y = 48;
            this.addQuiackChild(text_coin);
            texture = assetMgr.getTexture('ui_gongyong_tuichuanniiu');
            btn_close = new Button(texture);
            btn_close.name = 'btn_close';
            btn_close.x = 798;
            btn_close.y = -52;
            btn_close.width = 99;
            btn_close.height = 145;
            this.addQuiackChild(btn_close);
            texture = assetMgr.getTexture('ui_button_tiebaomutouanjian');
            btn_click = new Button(texture);
            btn_click.name = 'btn_click';
            btn_click.x = 725;
            btn_click.y = 413;
            btn_click.width = 150;
            btn_click.height = 64;
            this.addQuiackChild(btn_click);
            btn_click.text = '镶 嵌';
            btn_click.fontColor = 0xFFFFCC;
            btn_click.fontSize = 28;
            txt_money = new TextField(135, 30, '', '', 20, 0xFFFFCC, false);
            txt_money.touchable = false;
            txt_money.hAlign = 'left';
            txt_money.text = '';
            txt_money.x = 528;
            txt_money.y = 408;
            this.addQuiackChild(txt_money);
            txt_diamond = new TextField(136, 30, '', '', 20, 0xFFFFCC, false);
            txt_diamond.touchable = false;
            txt_diamond.hAlign = 'left';
            txt_diamond.text = '';
            txt_diamond.x = 528;
            txt_diamond.y = 448;
            this.addQuiackChild(txt_diamond);
            tab_1 = new TabButton(assetMgr.getTexture('ui_button_tiebaomutouanjian'), assetMgr.getTexture('ui_button_tiebaomutouanjian_liang'));
            tab_1.x = 26;
            tab_1.y = 7;
            tab_1.width = 150;
            tab_1.height = 64;
            this.addQuiackChild(tab_1);
            tab_1.text = '装 备';
            tab_1.fontColor = 0xFFE7D0;
            tab_1.fontSize = 28;
            tab_2 = new TabButton(assetMgr.getTexture('ui_button_tiebaomutouanjian'), assetMgr.getTexture('ui_button_tiebaomutouanjian_liang'));
            tab_2.x = 173;
            tab_2.y = 7;
            tab_2.width = 150;
            tab_2.height = 64;
            this.addQuiackChild(tab_2);
            tab_2.text = '合成';
            tab_2.fontColor = 0xFFE7D0;
            tab_2.fontSize = 28;
            tab_3 = new TabButton(assetMgr.getTexture('ui_button_tiebaomutouanjian'), assetMgr.getTexture('ui_button_tiebaomutouanjian_liang'));
            tab_3.x = 321;
            tab_3.y = 7;
            tab_3.width = 150;
            tab_3.height = 64;
            this.addQuiackChild(tab_3);
            tab_3.text = '强化';
            tab_3.fontColor = 0xFFE7D0;
            tab_3.fontSize = 28;
            tab_4 = new TabButton(assetMgr.getTexture('ui_button_tiebaomutouanjian'), assetMgr.getTexture('ui_button_tiebaomutouanjian_liang'));
            tab_4.x = 468;
            tab_4.y = 7;
            tab_4.width = 150;
            tab_4.height = 64;
            this.addQuiackChild(tab_4);
            tab_4.text = '镶嵌';
            tab_4.fontColor = 0xFFE7D0;
            tab_4.fontSize = 28;
            list_equip = new List();
            list_equip.x = 28;
            list_equip.y = 396;
            list_equip.width = 434;
            list_equip.height = 96;
            this.addQuiackChild(list_equip);
            tabMenu_hero = new TabMenu([tab_1, tab_2, tab_3, tab_4]);
            tabMenu_hero.x = 27;
            tabMenu_hero.y = 7;
            this.addQuiackChild(tabMenu_hero);
            texture = assetMgr.getTexture('ui_gongyong_zuanshi');
            tag_diamond = new Button(texture);
            tag_diamond.name = 'tag_diamond';
            tag_diamond.x = 484;
            tag_diamond.y = 444;
            tag_diamond.width = 46;
            tag_diamond.height = 44;
            this.addQuiackChild(tag_diamond);
            texture = assetMgr.getTexture('ui_gongyong_money');
            tag_money = new Button(texture);
            tag_money.name = 'tag_money';
            tag_money.x = 487;
            tag_money.y = 404;
            tag_money.width = 40;
            tag_money.height = 40;
            this.addQuiackChild(tag_money);
            list_bag = new List();
            list_bag.x = 39;
            list_bag.y = 88;
            list_bag.width = 410;
            list_bag.height = 304;
            this.addQuiackChild(list_bag);
            init();
        }

        override public function dispose():void {
            btn_close.dispose();
            btn_click.dispose();
            tab_1.dispose();
            tab_2.dispose();
            tab_3.dispose();
            tab_4.dispose();
            list_equip.dispose();
            tabMenu_hero.dispose();
            tag_diamond.dispose();
            tag_money.dispose();
            list_bag.dispose();
            super.dispose();

        }
    }
}
