package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import game.view.embattle.BattleVideoRank;
    import game.view.embattle.EmbattleGrid;
    import com.dialog.Dialog;

    public class NewEmBattleDlgBase extends Dialog
    {
        public var view:Sprite;
        public var view_rank:BattleVideoRank;
        public var btn_close:Button;
        public var btn_tired:Button;
        public var txt_tired:TextField;
        public var view_title:Sprite;
        public var view_list:Sprite;
        public var pos1:EmbattleGrid;
        public var pos4:EmbattleGrid;
        public var pos7:EmbattleGrid;
        public var pos8:EmbattleGrid;
        public var pos5:EmbattleGrid;
        public var pos2:EmbattleGrid;
        public var pos3:EmbattleGrid;
        public var pos6:EmbattleGrid;
        public var pos9:EmbattleGrid;

        public function NewEmBattleDlgBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            var assetMgr:AssetMgr = AssetMgr.instance;
            view = new Sprite();
            view.x = 512;
            view.y = 495;
            view.width = 1605;
            view.height = 174;
            this.addQuiackChild(view);
            view.name= 'view';
            texture =assetMgr.getTexture('ui_gongyong_dianquanheng_di');
            image = new Image(texture);
            image.x = 479;
            image.y = 10;
            image.width = 324;
            image.height = 162;
            image.smoothing= Constants.NONE;
            view.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_dianquanheng_di');
            image = new Image(texture);
            image.x = -800;
            image.y = 10;
            image.width = 324;
            image.height = 162;
            image.smoothing= Constants.NONE;
            view.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_dingzimutiao');
            image = new Image(texture);
            image.y = 14;
            image.width = 518;
            image.height = 66;
            image.smoothing= Constants.NONE;
            view.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_dingzimutiao');
            image = new Image(texture);
            image.y = 14;
            image.width = 518;
            image.height = 66;
            image.scaleX = -1;
            image.smoothing= Constants.NONE;
            view.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_dingzimutiao');
            image = new Image(texture);
            image.y = 79;
            image.width = 518;
            image.height = 66;
            image.smoothing= Constants.NONE;
            view.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_dingzimutiao');
            image = new Image(texture);
            image.y = 79;
            image.width = 518;
            image.height = 66;
            image.scaleX = -1;
            image.smoothing= Constants.NONE;
            view.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_biankuang_jinshubaisi1');
            image = new Image(texture);
            image.x = -802;
            image.y = -2;
            image.width = 1597;
            image.height = 18;
            image.smoothing= Constants.NONE;
            view.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_yingxiongshengdian_wenzikuang1');
            image = new Image(texture);
            image.x = -267;
            image.y = 34;
            image.width = 31;
            image.height = 97;
            image.smoothing= Constants.NONE;
            view.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_yingxiongshengdian_wenzikuang2');
            image = new Image(texture);
            image.x = -236;
            image.y = 34;
            image.width = 483;
            image.height = 94;
            image.smoothing= Constants.NONE;
            view.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_yingxiongshengdian_wenzikuang3');
            image = new Image(texture);
            image.x = 233;
            image.y = 34;
            image.width = 34;
            image.height = 95;
            image.smoothing= Constants.NONE;
            view.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_button_tiebaomutouanjian');
            button = new Button(texture);
            button.name= 'btn_auto';
            button.x = -440;
            button.y = 47;
            button.width = 150;
            button.height = 64;
            view.addQuiackChild(button);
            button.text= '自动布阵';
            button.fontColor= 0xFFFFCC;
            button.fontSize= 28;
            texture = assetMgr.getTexture('ui_button_tiebaomutouanjian');
            button = new Button(texture);
            button.name= 'btn_battle';
            button.x = 295;
            button.y = 47;
            button.width = 150;
            button.height = 64;
            view.addQuiackChild(button);
            button.text= '进入战斗';
            button.fontColor= 0xFFFFCC;
            button.fontSize= 28;
            texture =assetMgr.getTexture('ui_tubiao_rongyufenleianniu_zhandong');
            image = new Image(texture);
            image.x = -188;
            image.y = 44;
            image.width = 40;
            image.height = 38;
            image.smoothing= Constants.NONE;
            view.addQuiackChild(image);
            textField = new TextField(149,36,'','',22,0xFFFDD9,false);
            textField.touchable = false;
            textField.x = 104;
            textField.y = 86;
            textField.hAlign= 'left';
            textField.text= '';
            textField.name= 'txt_power1';
            view.addQuiackChild(textField);
            texture =assetMgr.getTexture('ui_gongyong_iocn_zhandouli');
            image = new Image(texture);
            image.x = 64;
            image.y = 90;
            image.width = 32;
            image.height = 28;
            image.smoothing= Constants.NONE;
            view.addQuiackChild(image);
            textField = new TextField(140,36,'','',24,0xFFFDD9,false);
            textField.touchable = false;
            textField.x = -77;
            textField.y = 40;
            textField.hAlign= 'center';
            textField.text= '我方战力';
            textField.name= 'txt_des3';
            view.addQuiackChild(textField);
            textField = new TextField(140,36,'','',24,0xFFFDD9,false);
            textField.touchable = false;
            textField.x = -77;
            textField.y = 86;
            textField.hAlign= 'center';
            textField.text= '敌方战力';
            textField.name= 'txt_des4';
            view.addQuiackChild(textField);
            textField = new TextField(68,36,'','',24,0xFFFDD9,false);
            textField.touchable = false;
            textField.x = -145;
            textField.y = 42;
            textField.hAlign= 'center';
            textField.text= '';
            textField.name= 'txt_count';
            view.addQuiackChild(textField);
            textField = new TextField(68,36,'','',24,0xFFFDD9,false);
            textField.touchable = false;
            textField.x = -145;
            textField.y = 80;
            textField.hAlign= 'center';
            textField.text= '';
            textField.name= 'txt_tired';
            view.addQuiackChild(textField);
            textField = new TextField(58,36,'','',24,0xFFFDD9,false);
            textField.touchable = false;
            textField.x = -249;
            textField.y = 42;
            textField.hAlign= 'right';
            textField.text= '英雄';
            textField.name= 'txt_des1';
            view.addQuiackChild(textField);
            textField = new TextField(60,36,'','',24,0xFFFDD9,false);
            textField.touchable = false;
            textField.x = -251;
            textField.y = 82;
            textField.hAlign= 'right';
            textField.text= '消耗';
            textField.name= 'txt_des2';
            view.addQuiackChild(textField);
            texture =assetMgr.getTexture('ui_gongyong_iocn_zhandouli');
            image = new Image(texture);
            image.x = 62;
            image.y = 44;
            image.width = 32;
            image.height = 28;
            image.smoothing= Constants.NONE;
            view.addQuiackChild(image);
            textField = new TextField(30,24,'','',14,0xFFFF00,false);
            textField.touchable = false;
            textField.x = 64;
            textField.y = 50;
            textField.hAlign= 'center';
            textField.text= '队';
            textField.name= 'txt_des5';
            view.addQuiackChild(textField);
            textField = new TextField(150,36,'','',22,0xFFFDD9,false);
            textField.touchable = false;
            textField.x = 103;
            textField.y = 40;
            textField.hAlign= 'left';
            textField.text= '';
            textField.name= 'txt_power';
            view.addQuiackChild(textField);
            textField = new TextField(42,22,'','',14,0xFFFF00,false);
            textField.touchable = false;
            textField.x = 60;
            textField.y = 97;
            textField.hAlign= 'center';
            textField.text= '推荐';
            textField.name= 'txt_des6';
            view.addQuiackChild(textField);
            texture =assetMgr.getTexture('ui_tubiao_zhuxianpilaozhi');
            image = new Image(texture);
            image.x = -180;
            image.y = 89;
            image.width = 26;
            image.height = 33;
            image.smoothing= Constants.NONE;
            view.addQuiackChild(image);
            view_rank = new BattleVideoRank();
            view_rank.x = -464;
            view_rank.y = 48;
            this.addQuiackChild(view_rank);
            texture = assetMgr.getTexture('ui_button_fanhui_iocn');
            btn_close = new Button(texture);
            btn_close.name= 'btn_close';
            btn_close.x = 918;
            btn_close.y = 20;
            btn_close.width = 86;
            btn_close.height = 81;
            this.addQuiackChild(btn_close);
            texture = assetMgr.getTexture('ui_gongyong_zhucheng_xinxidikuang');
            btn_tired = new Button(texture);
            btn_tired.name= 'btn_tired';
            btn_tired.x = 16;
            btn_tired.y = 10;
            btn_tired.width = 175;
            btn_tired.height = 45;
            this.addQuiackChild(btn_tired);
            texture =assetMgr.getTexture('ui_gongyong_lvjiahao');
            image = new Image(texture);
            image.x = 161;
            image.y = 22;
            image.width = 18;
            image.height = 20;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            txt_tired = new TextField(118,36,'','',24,0xFFFFFF,false);
            txt_tired.touchable = false;
            txt_tired.hAlign= 'right';
            txt_tired.text= '100/100';
            txt_tired.x = 40;
            txt_tired.y = 13;
            this.addQuiackChild(txt_tired);
            texture =assetMgr.getTexture('ui_tubiao_zhuxianpilaozhi');
            image = new Image(texture);
            image.x = 29;
            image.y = 17;
            image.width = 25;
            image.height = 31;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            view_title = new Sprite();
            view_title.x = 484;
            view_title.y = 3;
            view_title.width = 293;
            view_title.height = 68;
            this.addQuiackChild(view_title);
            view_title.name= 'view_title';
            texture =assetMgr.getTexture('ui_yingxiongkapai_yingxiongmingdi');
            image = new Image(texture);
            image.x = -146;
            image.width = 293;
            image.height = 68;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_title.addQuiackChild(image);
            textField = new TextField(293,36,'','',24,0x6A3C00,false);
            textField.touchable = false;
            textField.x = -146;
            textField.y = 11;
            textField.hAlign= 'center';
            textField.text= '';
            textField.name= 'text';
            view_title.addQuiackChild(textField);
            view_list = new Sprite();
            view_list.x = 5;
            view_list.y = 495;
            view_list.width = 910;
            view_list.height = 140;
            this.addQuiackChild(view_list);
            view_list.name= 'view_list';
            texture =assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian2');
            image = new Image(texture);
            image.x = 69;
            image.y = 27;
            image.width = 352;
            image.height = 18;
            image.scaleY = -0.96551513671875;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_list.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_wupingkuang_baozaodibian_xiao_di');
            image = new Image(texture);
            image.x = 12;
            image.y = 12;
            image.width = 889;
            image.height = 113;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_list.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou2');
            image = new Image(texture);
            image.x = 4;
            image.y = 14;
            image.width = 25;
            image.height = 113;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_list.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou1');
            image = new Image(texture);
            image.x = 31;
            image.y = 2;
            image.width = 843;
            image.height = 23;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_list.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.y = 1;
            image.width = 36;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_list.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou2');
            image = new Image(texture);
            image.x = 906;
            image.y = 30;
            image.width = 25;
            image.height = 96;
            image.scaleX = -0.9526214599609375;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_list.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 910;
            image.width = 36;
            image.height = 33;
            image.scaleX = -0.9526214599609375;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_list.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou1');
            image = new Image(texture);
            image.x = 30;
            image.y = 139;
            image.width = 843;
            image.height = 23;
            image.scaleY = -0.96551513671875;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_list.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.y = 140;
            image.width = 36;
            image.height = 33;
            image.scaleY = -0.96551513671875;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_list.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 910;
            image.y = 140;
            image.width = 36;
            image.height = 33;
            image.scaleX = -0.9526214599609375;
            image.scaleY = -0.96551513671875;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_list.addQuiackChild(image);
            pos1 = new EmbattleGrid();
            pos1.x = 320;
            pos1.y = 195;
            this.addQuiackChild(pos1);
            pos4 = new EmbattleGrid();
            pos4.x = 178;
            pos4.y = 195;
            this.addQuiackChild(pos4);
            pos7 = new EmbattleGrid();
            pos7.x = 40;
            pos7.y = 195;
            this.addQuiackChild(pos7);
            pos8 = new EmbattleGrid();
            pos8.x = 13;
            pos8.y = 285;
            this.addQuiackChild(pos8);
            pos5 = new EmbattleGrid();
            pos5.x = 151;
            pos5.y = 285;
            this.addQuiackChild(pos5);
            pos2 = new EmbattleGrid();
            pos2.x = 291;
            pos2.y = 285;
            this.addQuiackChild(pos2);
            pos3 = new EmbattleGrid();
            pos3.x = 264;
            pos3.y = 375;
            this.addQuiackChild(pos3);
            pos6 = new EmbattleGrid();
            pos6.x = 125;
            pos6.y = 375;
            this.addQuiackChild(pos6);
            pos9 = new EmbattleGrid();
            pos9.x = -17;
            pos9.y = 375;
            this.addQuiackChild(pos9);
            init();
        }
        override public function dispose():void
        {
            view.dispose();
            view_rank.dispose();
            btn_close.dispose();
            btn_tired.dispose();
            view_title.dispose();
            view_list.dispose();
            pos1.dispose();
            pos4.dispose();
            pos7.dispose();
            pos8.dispose();
            pos5.dispose();
            pos2.dispose();
            pos3.dispose();
            pos6.dispose();
            pos9.dispose();
            super.dispose();
        
}
    }
}
