package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.controls.List;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.scene.BaseScene;

    public class NewMainWorldBase extends BaseScene
    {
        public var list_map:List;
        public var btn_add:Button;
        public var btn_return:Button;
        public var txt_power:TextField;
        public var view_reward:Sprite;
        public var list_reward:List;
        public var tag_return:Image;
        public var view_title:Sprite;

        public function NewMainWorldBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            var assetMgr:AssetMgr = AssetMgr.instance;
            list_map = new List();
            list_map.width = 960;
            list_map.height = 640;
            this.addQuiackChild(list_map);
            texture = assetMgr.getTexture('ui_gongyong_zhucheng_xinxidikuang');
            btn_add = new Button(texture);
            btn_add.name= 'btn_add';
            btn_add.x = 16;
            btn_add.y = 12;
            btn_add.width = 175;
            btn_add.height = 45;
            this.addQuiackChild(btn_add);
            texture =assetMgr.getTexture('ui_gongyong_lvjiahao');
            image = new Image(texture);
            image.x = 161;
            image.y = 24;
            image.width = 18;
            image.height = 20;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_button_fanhui_iocn');
            btn_return = new Button(texture);
            btn_return.name= 'btn_return';
            btn_return.x = 865;
            btn_return.y = 25;
            btn_return.width = 86;
            btn_return.height = 81;
            this.addQuiackChild(btn_return);
            texture =assetMgr.getTexture('ui_tubiao_zhuxianpilaozhi');
            image = new Image(texture);
            image.x = 27;
            image.y = 18;
            image.width = 26;
            image.height = 33;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            txt_power = new TextField(107,36,'','',24,0xFFFFFF,false);
            txt_power.touchable = false;
            txt_power.hAlign= 'right';
            txt_power.text= '';
            txt_power.x = 51;
            txt_power.y = 15;
            this.addQuiackChild(txt_power);
            view_reward = new Sprite();
            view_reward.x = 480;
            view_reward.y = 495;
            view_reward.width = 1610;
            view_reward.height = 166;
            this.addQuiackChild(view_reward);
            view_reward.name= 'view_reward';
            texture =assetMgr.getTexture('ui_gongyong_dianquanheng_di');
            image = new Image(texture);
            image.x = -164;
            image.y = 4;
            image.width = 324;
            image.height = 162;
            image.smoothing= Constants.NONE;
            view_reward.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_dianquanheng_di');
            image = new Image(texture);
            image.x = -485;
            image.y = 4;
            image.width = 324;
            image.height = 162;
            image.smoothing= Constants.NONE;
            view_reward.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_dianquanheng_di');
            image = new Image(texture);
            image.x = 157;
            image.y = 4;
            image.width = 324;
            image.height = 162;
            image.smoothing= Constants.NONE;
            view_reward.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_dianquanheng_di');
            image = new Image(texture);
            image.x = 481;
            image.y = 4;
            image.width = 324;
            image.height = 162;
            image.smoothing= Constants.NONE;
            view_reward.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_dingzimutiao');
            image = new Image(texture);
            image.x = -2;
            image.y = 16;
            image.width = 518;
            image.height = 66;
            image.smoothing= Constants.NONE;
            view_reward.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_dingzimutiao');
            image = new Image(texture);
            image.x = -2;
            image.y = 16;
            image.width = 518;
            image.height = 66;
            image.scaleX = -1;
            image.smoothing= Constants.NONE;
            view_reward.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_dingzimutiao');
            image = new Image(texture);
            image.x = -2;
            image.y = 79;
            image.width = 518;
            image.height = 66;
            image.smoothing= Constants.NONE;
            view_reward.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_dingzimutiao');
            image = new Image(texture);
            image.x = -2;
            image.y = 79;
            image.width = 518;
            image.height = 66;
            image.scaleX = -1;
            image.smoothing= Constants.NONE;
            view_reward.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_biankuang_jinshubaisi1');
            image = new Image(texture);
            image.x = -801;
            image.width = 1597;
            image.height = 18;
            image.smoothing= Constants.NONE;
            view_reward.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_dianquanheng_di');
            image = new Image(texture);
            image.x = -805;
            image.y = 4;
            image.width = 324;
            image.height = 162;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_reward.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_Setup_button_switch3');
            var ui_Setup_button_switch37927Rect:Rectangle = new Rectangle(54,26,107,52);
            var ui_Setup_button_switch379279ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_Setup_button_switch37927Rect);
            var ui_Setup_button_switch37927 : Scale9Image = new Scale9Image(ui_Setup_button_switch379279ScaleTexture);
            ui_Setup_button_switch37927.x = 79;
            ui_Setup_button_switch37927.y = 27;
            ui_Setup_button_switch37927.width = 393;
            ui_Setup_button_switch37927.height = 103;
            view_reward.addQuiackChild(ui_Setup_button_switch37927);
            texture =assetMgr.getTexture('ui_yingxiongshengdian_wenzikuang1');
            image = new Image(texture);
            image.x = -470;
            image.y = 25;
            image.width = 31;
            image.height = 110;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_reward.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_yingxiongshengdian_wenzikuang2');
            image = new Image(texture);
            image.x = -452;
            image.y = 26;
            image.width = 475;
            image.height = 106;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_reward.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_yingxiongshengdian_wenzikuang3');
            image = new Image(texture);
            image.x = 10;
            image.y = 24;
            image.width = 34;
            image.height = 108;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_reward.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_button_tiebaomutouanjian');
            button = new Button(texture);
            button.name= 'btn_battle';
            button.x = 301;
            button.y = 56;
            button.width = 150;
            button.height = 64;
            view_reward.addQuiackChild(button);
            textField = new TextField(67,45,'','',28,0xFFFFCC,false);
            textField.touchable = false;
            textField.x = 307;
            textField.y = 67;
            textField.hAlign= 'right';
            textField.text= '战斗';
            textField.name= 'txt_des1';
            view_reward.addQuiackChild(textField);
            textField = new TextField(65,36,'','',24,0xFFFFCC,false);
            textField.touchable = false;
            textField.x = 375;
            textField.y = 73;
            textField.hAlign= 'right';
            textField.text= '';
            textField.name= 'txt_castPower';
            view_reward.addQuiackChild(textField);
            texture =assetMgr.getTexture('ui_tubiao_zhuxianpilaozhi');
            image = new Image(texture);
            image.x = 372;
            image.y = 74;
            image.width = 28;
            image.height = 35;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_reward.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_button_switch');
            button = new Button(texture);
            button.name= 'btn_modle';
            button.x = 110;
            button.y = 56;
            button.width = 163;
            button.height = 75;
            view_reward.addQuiackChild(button);
            texture = assetMgr.getTexture('ui_button_switch1')
            image = new Image(texture);
            image.name= 'tag_modle';
            image.x = 121;
            image.y = 67;
            image.width = 133;
            image.height = 43;
            view_reward.addQuiackChild(image);
            image.touchable = false;
            textField = new TextField(139,41,'','',24,0xFFFFCC,false);
            textField.touchable = false;
            textField.x = 115;
            textField.y = 27;
            textField.hAlign= 'center';
            textField.text= '噩梦模式';
            textField.name= 'txt_des2';
            view_reward.addQuiackChild(textField);
            list_reward = new List();
            list_reward.x = -452;
            list_reward.y = 33;
            list_reward.width = 480;
            list_reward.height = 90;
            view_reward.addQuiackChild(list_reward);
            texture = assetMgr.getTexture('ui_gongyong_mulianpaizi_lianzi_xiao')
            tag_return = new Image(texture);
            tag_return.x = 901;
            tag_return.y = -48;
            tag_return.width = 21;
            tag_return.height = 76;
            this.addQuiackChild(tag_return);
            tag_return.touchable = false;
            view_title = new Sprite();
            view_title.x = 482;
            view_title.y = -3;
            view_title.width = 293;
            view_title.height = 68;
            this.addQuiackChild(view_title);
            view_title.name= 'view_title';
            texture =assetMgr.getTexture('ui_yingxiongkapai_yingxiongmingdi');
            image = new Image(texture);
            image.x = -146;
            image.width = 293;
            image.height = 68;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            view_title.addQuiackChild(image);
            textField = new TextField(271,36,'','',24,0x6A3C00,false);
            textField.touchable = false;
            textField.x = -130;
            textField.y = 13;
            textField.hAlign= 'center';
            textField.text= '';
            textField.name= 'text';
            view_title.addQuiackChild(textField);
            init();
        }
        override public function dispose():void
        {
            list_map.dispose();
            btn_add.dispose();
            btn_return.dispose();
            list_reward.dispose();
            view_reward.dispose();
            view_title.dispose();
            super.dispose();
        
}
    }
}
