package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import com.dialog.Dialog;

    public class PackDlgBase extends Dialog
    {
        public var btn_close:Button;
        public var diamond:TextField;
        public var k1:TextField;
        public var Recharge:Button;
        public var dsf2234:Image;
        public var k:TextField;
        public var money:TextField;
        public var sxxx:Image;
        public var sell:Button;
        public var over:TextField;
        public var page1:Image;
        public var page5:Image;
        public var page3:Image;
        public var page4:Image;
        public var page2:Image;
        public var cancel:Button;

        public function PackDlgBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            var assetMgr:AssetMgr = AssetMgr.instance;
            texture =assetMgr.getTexture('ui_gongyong_tielianpaizi');
            image = new Image(texture);
            image.x = 356;
            image.y = -25;
            image.width = 244;
            image.height = 137;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_tuichuanniiu');
            btn_close = new Button(texture);
            btn_close.name= 'btn_close';
            btn_close.x = 807;
            btn_close.y = -44;
            btn_close.width = 99;
            btn_close.height = 145;
            this.addQuiackChild(btn_close);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.y = 110;
            image.width = 490;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 954;
            image.y = 110;
            image.width = 490;
            image.height = 73;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_background_intensify3');
            image = new Image(texture);
            image.x = 10;
            image.y = 119;
            image.width = 934;
            image.height = 1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.y = 183;
            image.width = 490;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 954;
            image.y = 183;
            image.width = 490;
            image.height = 73;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.y = 256;
            image.width = 490;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 954;
            image.y = 256;
            image.width = 490;
            image.height = 73;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.y = 329;
            image.width = 490;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 954;
            image.y = 329;
            image.width = 490;
            image.height = 73;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.y = 402;
            image.width = 490;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 954;
            image.y = 402;
            image.width = 490;
            image.height = 73;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.y = 475;
            image.width = 490;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 954;
            image.y = 475;
            image.width = 490;
            image.height = 73;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.y = 548;
            image.width = 490;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 954;
            image.y = 548;
            image.width = 490;
            image.height = 73;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_wenzi_beibao');
            image = new Image(texture);
            image.x = 427;
            image.y = 28;
            image.width = 102;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_jinbibaizidi2');
            image = new Image(texture);
            image.x = 38;
            image.y = 5;
            image.width = 197;
            image.height = 99;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            diamond = new TextField(136,32,'','',21,0xFFFFFF,false);
            diamond.touchable = false;
            diamond.hAlign= 'left';
            diamond.text= '999999  ';
            diamond.x = 88;
            diamond.y = 61;
            this.addQuiackChild(diamond);
            k1 = new TextField(34,46,'','',32,0xFF9201,false);
            k1.touchable = false;
            k1.hAlign= 'left';
            k1.text= 'k';
            k1.x = 189;
            k1.y = 54;
            this.addQuiackChild(k1);
            texture = assetMgr.getTexture('ui_button_chongzhitubiao');
            Recharge = new Button(texture);
            Recharge.name= 'Recharge';
            Recharge.x = 243;
            Recharge.y = 44;
            Recharge.width = 64;
            Recharge.height = 64;
            this.addQuiackChild(Recharge);
            texture = assetMgr.getTexture('ui_gongyong_zuanshi')
            dsf2234 = new Image(texture);
            dsf2234.x = 47;
            dsf2234.y = 55;
            dsf2234.width = 46;
            dsf2234.height = 44;
            this.addQuiackChild(dsf2234);
            dsf2234.touchable = false;
            texture =assetMgr.getTexture('ui_gongyong_bumangdi_shangbianyikuaitie');
            image = new Image(texture);
            image.x = 356;
            image.y = 101;
            image.width = 30;
            image.height = 21;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_bumangdi_shangbianyikuaitie');
            image = new Image(texture);
            image.x = 600;
            image.y = 101;
            image.width = 30;
            image.height = 21;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_jinbi');
            image = new Image(texture);
            image.x = 48;
            image.y = 17;
            image.width = 40;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            k = new TextField(30,46,'','',32,0xFF9201,false);
            k.touchable = false;
            k.hAlign= 'left';
            k.text= 'k';
            k.x = 189;
            k.y = 10;
            this.addQuiackChild(k);
            money = new TextField(138,32,'','',21,0xFFFFFF,false);
            money.touchable = false;
            money.hAlign= 'left';
            money.text= '999999  ';
            money.x = 88;
            money.y = 19;
            this.addQuiackChild(money);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao_di3');
            image = new Image(texture);
            image.x = 892;
            image.y = 144;
            image.width = 32;
            image.height = 414;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao_di2');
            image = new Image(texture);
            image.x = 29;
            image.y = 144;
            image.width = 32;
            image.height = 414;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao_di1');
            image = new Image(texture);
            image.x = 54;
            image.y = 144;
            image.width = 848;
            image.height = 23;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao_di1');
            image = new Image(texture);
            image.x = 54;
            image.y = 557;
            image.width = 848;
            image.height = 23;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_yibanmubanhentiao_di4')
            sxxx = new Image(texture);
            sxxx.x = 54;
            sxxx.y = 158;
            sxxx.width = 848;
            sxxx.height = 385;
            this.addQuiackChild(sxxx);
            sxxx.touchable = false;
            texture = assetMgr.getTexture('ui_button_xinshanchuanniu');
            sell = new Button(texture);
            sell.name= 'sell';
            sell.x = 771;
            sell.y = 494;
            sell.width = 131;
            sell.height = 113;
            this.addQuiackChild(sell);
            over = new TextField(116,38,'','',26,0xFEF4CC,false);
            over.touchable = false;
            over.hAlign= 'center';
            over.text= '批量出售';
            over.x = 776;
            over.y = 561;
            this.addQuiackChild(over);
            texture = assetMgr.getTexture('ui_gongyong_yemianqiehuan1')
            page1 = new Image(texture);
            page1.x = 373;
            page1.y = 499;
            page1.width = 33;
            page1.height = 30;
            this.addQuiackChild(page1);
            page1.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_yemianqiehuan2')
            page5 = new Image(texture);
            page5.x = 550;
            page5.y = 499;
            page5.width = 33;
            page5.height = 30;
            this.addQuiackChild(page5);
            page5.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_yemianqiehuan2')
            page3 = new Image(texture);
            page3.x = 462;
            page3.y = 499;
            page3.width = 33;
            page3.height = 30;
            this.addQuiackChild(page3);
            page3.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_yemianqiehuan2')
            page4 = new Image(texture);
            page4.x = 506;
            page4.y = 499;
            page4.width = 33;
            page4.height = 30;
            this.addQuiackChild(page4);
            page4.touchable = false;
            texture = assetMgr.getTexture('ui_gongyong_yemianqiehuan2')
            page2 = new Image(texture);
            page2.x = 417;
            page2.y = 499;
            page2.width = 33;
            page2.height = 30;
            this.addQuiackChild(page2);
            page2.touchable = false;
            texture = assetMgr.getTexture('ui_button_quxiaoanniu');
            cancel = new Button(texture);
            cancel.name= 'cancel';
            cancel.x = 646;
            cancel.y = 534;
            cancel.width = 99;
            cancel.height = 63;
            this.addQuiackChild(cancel);
            texture =assetMgr.getTexture('ui_background_intensify3');
            image = new Image(texture);
            image.x = 10;
            image.y = 610;
            image.width = 934;
            image.height = 1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            init();
        }
        override public function dispose():void
        {
            btn_close.dispose();
            Recharge.dispose();
            sell.dispose();
            cancel.dispose();
            super.dispose();
        
}
    }
}
