package  game.view.viewBase
{
    import com.dialog.Dialog;
    import com.utils.Constants;
    
    import game.manager.AssetMgr;
    
    import starling.display.Button;
    import starling.display.Image;
    import starling.text.TextField;
    import starling.textures.Texture;

    public class PictureInfoViewBase extends Dialog
    {
        public var txt_des5:TextField;
        public var txt_skill1:TextField;
        public var txt_skill2:TextField;
        public var txt_skill3:TextField;
        public var txt_skillName1:TextField;
        public var txt_skillName2:TextField;
        public var txt_skillName3:TextField;
        public var tag:Image;
        public var ico_hero:Button;
        public var star_bg:Image;
        public var txt_des1:TextField;
        public var txt_des2:TextField;
        public var txt_des3:TextField;
        public var txt_des4:TextField;
        public var txt_des10:TextField;
        public var txt_pos:TextField;
        public var txt_weapon:TextField;
        public var txt_born:TextField;
        public var stars1:Image;
        public var stars2:Image;
        public var stars5:Image;
        public var stars4:Image;
        public var stars3:Image;
        public var txt_des:TextField;
        public var txt_des8:TextField;
        public var txt_name:TextField;

        public function PictureInfoViewBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var image:Image;
            var button:Button;;
            var assetMgr:AssetMgr = AssetMgr.instance;
            texture =assetMgr.getTexture('ui_gongyong_zhiwanzidi');
            image = new Image(texture);
            image.y = 538;
            image.width = 718;
            image.height = 274;
            image.scaleY = -1.8115234375;;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_zhiwanzidi');
            image = new Image(texture);
            image.width = 718;
            image.height = 274;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            txt_des5 = new TextField(218,36,'','',24,0x501900,false);
            txt_des5.touchable = false;
            txt_des5.hAlign= 'center';
            txt_des5.text= '英雄技能';
            txt_des5.x = 387;
            txt_des5.y = 213;
            this.addQuiackChild(txt_des5);
            txt_skill1 = new TextField(357,58,'','',18,0x492D06,false);
            txt_skill1.touchable = false;
            txt_skill1.hAlign= 'left';
            txt_skill1.text= '';
            txt_skill1.x = 324;
            txt_skill1.y = 282;
            this.addQuiackChild(txt_skill1);
            txt_skill2 = new TextField(355,58,'','',18,0x492D06,false);
            txt_skill2.touchable = false;
            txt_skill2.hAlign= 'left';
            txt_skill2.text= '';
            txt_skill2.x = 324;
            txt_skill2.y = 367;
            this.addQuiackChild(txt_skill2);
            txt_skill3 = new TextField(358,58,'','',18,0x492D06,false);
            txt_skill3.touchable = false;
            txt_skill3.hAlign= 'left';
            txt_skill3.text= '';
            txt_skill3.x = 324;
            txt_skill3.y = 449;
            this.addQuiackChild(txt_skill3);
            txt_skillName1 = new TextField(288,33,'','',22,0xE31E0D,false);
            txt_skillName1.touchable = false;
            txt_skillName1.hAlign= 'left';
            txt_skillName1.text= '技能名字';
            txt_skillName1.x = 324;
            txt_skillName1.y = 251;
            this.addQuiackChild(txt_skillName1);
            txt_skillName2 = new TextField(290,33,'','',22,0x0063CD,false);
            txt_skillName2.touchable = false;
            txt_skillName2.hAlign= 'left';
            txt_skillName2.text= '技能名字';
            txt_skillName2.x = 324;
            txt_skillName2.y = 336;
            this.addQuiackChild(txt_skillName2);
            txt_skillName3 = new TextField(291,33,'','',22,0xC506E0,false);
            txt_skillName3.touchable = false;
            txt_skillName3.hAlign= 'left';
            txt_skillName3.text= '技能名字';
            txt_skillName3.x = 324;
            txt_skillName3.y = 419;
            this.addQuiackChild(txt_skillName3);
            texture =assetMgr.getTexture('ui_atlas_bottom');
            image = new Image(texture);
            image.x = 125;
            image.y = 104;
            image.width = 108;
            image.height = 112;
            image.smoothing= Constants.smoothing;
            image.touchable = false;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_atlas_decoration')
            tag = new Image(texture);
            tag.x = 58;
            tag.y = 398;
            tag.width = 104;
            tag.height = 104;
            this.addQuiackChild(tag);
            tag.touchable = false;
            texture = assetMgr.getTexture('photo_513');
            ico_hero = new Button(texture);
            ico_hero.name= 'ico_hero';
            ico_hero.x = 127;
            ico_hero.y = 109;
            ico_hero.width = 100;
            ico_hero.height = 100;
            this.addQuiackChild(ico_hero);
            texture = assetMgr.getTexture('ui_atlas_stars')
            star_bg = new Image(texture);
            star_bg.x = 151;
            star_bg.y = 352;
            star_bg.width = 149;
            star_bg.height = 26;
            this.addQuiackChild(star_bg);
            star_bg.touchable = false;
            txt_des1 = new TextField(115,33,'','',20,0xA07847,false);
            txt_des1.touchable = false;
            txt_des1.hAlign= 'left';
            txt_des1.text= '擅长位置：';
            txt_des1.x = 50;
            txt_des1.y = 248;
            this.addQuiackChild(txt_des1);
            txt_des2 = new TextField(115,33,'','',20,0xA07847,false);
            txt_des2.touchable = false;
            txt_des2.hAlign= 'left';
            txt_des2.text= '惯用武器：';
            txt_des2.x = 50;
            txt_des2.y = 281;
            this.addQuiackChild(txt_des2);
            txt_des3 = new TextField(54,33,'','',20,0xA07847,false);
            txt_des3.touchable = false;
            txt_des3.hAlign= 'left';
            txt_des3.text= '常在';
            txt_des3.x = 50;
            txt_des3.y = 314;
            this.addQuiackChild(txt_des3);
            txt_des4 = new TextField(115,33,'','',20,0xA07847,false);
            txt_des4.touchable = false;
            txt_des4.hAlign= 'left';
            txt_des4.text= '获取难度：';
            txt_des4.x = 50;
            txt_des4.y = 347;
            this.addQuiackChild(txt_des4);
            txt_des10 = new TextField(54,33,'','',20,0xA07847,false);
            txt_des10.touchable = false;
            txt_des10.hAlign= 'left';
            txt_des10.text= '出现';
            txt_des10.x = 257;
            txt_des10.y = 313;
            this.addQuiackChild(txt_des10);
            txt_pos = new TextField(175,36,'','',24,0xF78D1D,false);
            txt_pos.touchable = false;
            txt_pos.hAlign= 'left';
            txt_pos.text= '';
            txt_pos.x = 170;
            txt_pos.y = 245;
            this.addQuiackChild(txt_pos);
            txt_weapon = new TextField(173,36,'','',24,0xF78D1D,false);
            txt_weapon.touchable = false;
            txt_weapon.hAlign= 'left';
            txt_weapon.text= '';
            txt_weapon.x = 171;
            txt_weapon.y = 281;
            this.addQuiackChild(txt_weapon);
            txt_born = new TextField(145,36,'','',24,0xF78D1D,false);
            txt_born.touchable = false;
            txt_born.hAlign= 'center';
            txt_born.text= '英雄酒馆';
            txt_born.x = 107;
            txt_born.y = 312;
            this.addQuiackChild(txt_born);
            texture = assetMgr.getTexture('icon_3')
            stars1 = new Image(texture);
            stars1.x = 150;
            stars1.y = 349;
            stars1.width = 26;
            stars1.height = 25;
            this.addQuiackChild(stars1);
            stars1.touchable = false;
            texture = assetMgr.getTexture('icon_3')
            stars2 = new Image(texture);
            stars2.x = 181;
            stars2.y = 349;
            stars2.width = 26;
            stars2.height = 25;
            this.addQuiackChild(stars2);
            stars2.touchable = false;
            texture = assetMgr.getTexture('icon_3')
            stars5 = new Image(texture);
            stars5.x = 273;
            stars5.y = 349;
            stars5.width = 26;
            stars5.height = 25;
            this.addQuiackChild(stars5);
            stars5.touchable = false;
            texture = assetMgr.getTexture('icon_3')
            stars4 = new Image(texture);
            stars4.x = 242;
            stars4.y = 349;
            stars4.width = 26;
            stars4.height = 25;
            this.addQuiackChild(stars4);
            stars4.touchable = false;
            texture = assetMgr.getTexture('icon_3')
            stars3 = new Image(texture);
            stars3.x = 212;
            stars3.y = 349;
            stars3.width = 26;
            stars3.height = 25;
            this.addQuiackChild(stars3);
            stars3.touchable = false;
            txt_des = new TextField(357,142,'','',20,0x695434,false);
            txt_des.touchable = false;
            txt_des.hAlign= 'left';
            txt_des.text= '';
            txt_des.x = 318;
            txt_des.y = 75;
            this.addQuiackChild(txt_des);
            txt_des8 = new TextField(218,36,'','',24,0x501900,false);
            txt_des8.touchable = false;
            txt_des8.hAlign= 'center';
            txt_des8.text= '英雄介绍';
            txt_des8.x = 387;
            txt_des8.y = 38;
            this.addQuiackChild(txt_des8);
            txt_name = new TextField(218,36,'','',24,0x501900,false);
            txt_name.touchable = false;
            txt_name.hAlign= 'center';
            txt_name.text= '';
            txt_name.x = 69;
            txt_name.y = 58;
            this.addQuiackChild(txt_name);
            init();
        }
        override public function dispose():void
        {
            ico_hero.dispose();
            super.dispose();
        
}
    }
}
