package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import com.dialog.Dialog;

    public class ShopDlgBase extends Dialog
    {
        public var Recharge:Button;
        public var btn_close:Button;
        public var diamond:TextField;
        public var dsf2234:Image;
        public var coin:TextField;
        public var sxxx:Image;
        public var k:TextField;
        public var k1:TextField;

        public function ShopDlgBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            var assetMgr:AssetMgr = AssetMgr.instance;
            texture = assetMgr.getTexture('ui_button_chongzhitubiao');
            Recharge = new Button(texture);
            Recharge.name= 'Recharge';
            Recharge.x = 231;
            Recharge.y = 42;
            Recharge.width = 64;
            Recharge.height = 64;
            this.addQuiackChild(Recharge);
            texture =assetMgr.getTexture('ui_gongyong_tielianpaizi');
            image = new Image(texture);
            image.x = 354;
            image.y = -29;
            image.width = 244;
            image.height = 137;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_tuichuanniiu');
            btn_close = new Button(texture);
            btn_close.name= 'btn_close';
            btn_close.x = 809;
            btn_close.y = -46;
            btn_close.width = 99;
            btn_close.height = 145;
            this.addQuiackChild(btn_close);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.y = 104;
            image.width = 490;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 950;
            image.y = 104;
            image.width = 490;
            image.height = 73;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_background_intensify3');
            image = new Image(texture);
            image.x = 10;
            image.y = 119;
            image.width = 934;
            image.height = 1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_bumangdi_shangbianyikuaitie');
            image = new Image(texture);
            image.x = 354;
            image.y = 101;
            image.width = 30;
            image.height = 21;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_bumangdi_shangbianyikuaitie');
            image = new Image(texture);
            image.x = 598;
            image.y = 101;
            image.width = 30;
            image.height = 21;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.y = 177;
            image.width = 490;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 950;
            image.y = 177;
            image.width = 490;
            image.height = 73;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.y = 250;
            image.width = 490;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 950;
            image.y = 250;
            image.width = 490;
            image.height = 73;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.y = 323;
            image.width = 490;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 950;
            image.y = 323;
            image.width = 490;
            image.height = 73;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.y = 396;
            image.width = 490;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 950;
            image.y = 396;
            image.width = 490;
            image.height = 73;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.y = 469;
            image.width = 490;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 950;
            image.y = 469;
            image.width = 490;
            image.height = 73;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.y = 542;
            image.width = 490;
            image.height = 73;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao');
            image = new Image(texture);
            image.x = 950;
            image.y = 542;
            image.width = 490;
            image.height = 73;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_jinbibaizidi2');
            image = new Image(texture);
            image.x = 29;
            image.y = 3;
            image.width = 197;
            image.height = 99;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            diamond = new TextField(138,32,'','',21,0xFFFFFF,false);
            diamond.touchable = false;
            diamond.hAlign= 'left';
            diamond.text= '999999  ';
            diamond.x = 79;
            diamond.y = 61;
            this.addQuiackChild(diamond);
            texture = assetMgr.getTexture('ui_gongyong_zuanshi')
            dsf2234 = new Image(texture);
            dsf2234.x = 38;
            dsf2234.y = 53;
            dsf2234.width = 46;
            dsf2234.height = 44;
            this.addQuiackChild(dsf2234);
            dsf2234.touchable = false;
            texture =assetMgr.getTexture('ui_gongyong_jinbi');
            image = new Image(texture);
            image.x = 39;
            image.y = 15;
            image.width = 40;
            image.height = 40;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            coin = new TextField(133,32,'','',21,0xFFFFFF,false);
            coin.touchable = false;
            coin.hAlign= 'left';
            coin.text= '999999  ';
            coin.x = 81;
            coin.y = 18;
            this.addQuiackChild(coin);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao_di3');
            image = new Image(texture);
            image.x = 890;
            image.y = 140;
            image.width = 32;
            image.height = 414;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao_di2');
            image = new Image(texture);
            image.x = 27;
            image.y = 140;
            image.width = 32;
            image.height = 414;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao_di1');
            image = new Image(texture);
            image.x = 52;
            image.y = 140;
            image.width = 848;
            image.height = 23;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_yibanmubanhentiao_di1');
            image = new Image(texture);
            image.x = 52;
            image.y = 553;
            image.width = 848;
            image.height = 23;
            image.scaleY = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_yibanmubanhentiao_di4')
            sxxx = new Image(texture);
            sxxx.x = 52;
            sxxx.y = 154;
            sxxx.width = 848;
            sxxx.height = 385;
            this.addQuiackChild(sxxx);
            sxxx.touchable = false;
            texture =assetMgr.getTexture('ui_wenzi_shangcheng');
            image = new Image(texture);
            image.x = 426;
            image.y = 25;
            image.width = 101;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            k = new TextField(104,38,'','',26,0xFF9021,false);
            k.touchable = false;
            k.hAlign= 'left';
            k.text= '';
            k.x = 180;
            k.y = 15;
            this.addQuiackChild(k);
            k1 = new TextField(104,38,'','',26,0xFF9021,false);
            k1.touchable = false;
            k1.hAlign= 'left';
            k1.text= '';
            k1.x = 183;
            k1.y = 58;
            this.addQuiackChild(k1);
            init();
        }
        override public function dispose():void
        {
            Recharge.dispose();
            btn_close.dispose();
            super.dispose();
        
}
    }
}
