package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.dialog.Dialog;

    public class SystemSetDlgBase extends Dialog
    {
        public var ui_Setup_button_switch355129:Scale9Image;
        public var btn_change:Button;
        public var ui_Setup_button_switch3585123:Scale9Image;
        public var btn_feed:Button;
        public var ui_city_wenzidi259345:Scale9Image;
        public var ui_city_wenzidi259290:Scale9Image;
        public var ui_city_wenzidi259235:Scale9Image;
        public var ico_hero:Button;
        public var txt_title:TextField;
        public var ui_city_wenzidi259400:Scale9Image;
        public var ui_city_wenzidi259180:Scale9Image;
        public var txt_des3:TextField;
        public var txt_des4:TextField;
        public var txt_des5:TextField;
        public var txt_des6:TextField;
        public var txt_des7:TextField;
        public var txt_power:TextField;
        public var txt_rank:TextField;
        public var txt_tollgate:TextField;
        public var txt_herocount:TextField;
        public var txt_code:TextField;
        public var txt_des1:TextField;
        public var txt_des2:TextField;
        public var btn_close:Button;
        public var btn_out:Button;
        public var btn_bgMusic:Button;
        public var btn_effectMusic:Button;
        public var tag_rankLevel:Image;
        public var txt_des8:TextField;
        public var txt_version:TextField;
        public var txt:TextField;
        public var txt_name:TextField;
        public var txt_vip:TextField;

        public function SystemSetDlgBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            var assetMgr:AssetMgr = AssetMgr.instance;
            texture =assetMgr.getTexture('ui_wudixingyunxing_xingxing_goumaikuang2');
            image = new Image(texture);
            image.x = 87;
            image.y = 26;
            image.width = 679;
            image.height = 503;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_wudixingyunxing_xingxing_goumaikuang1');
            image = new Image(texture);
            image.y = 26;
            image.width = 102;
            image.height = 503;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_wudixingyunxing_xingxing_goumaikuang1');
            image = new Image(texture);
            image.x = 842;
            image.y = 26;
            image.width = 102;
            image.height = 503;
            image.scaleX = -1;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_Setup_button_switch3');
            var ui_Setup_button_switch355129Rect:Rectangle = new Rectangle(54,26,107,52);
            var ui_Setup_button_switch3551299ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_Setup_button_switch355129Rect);
            ui_Setup_button_switch355129 = new Scale9Image(ui_Setup_button_switch3551299ScaleTexture);
            ui_Setup_button_switch355129.x = 55;
            ui_Setup_button_switch355129.y = 129;
            ui_Setup_button_switch355129.width = 498;
            ui_Setup_button_switch355129.height = 363;
            this.addQuiackChild(ui_Setup_button_switch355129);
            texture =assetMgr.getTexture('ui_gongyong_kuang_paizi2');
            image = new Image(texture);
            image.x = 185;
            image.y = 103;
            image.width = 237;
            image.height = 61;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou1');
            image = new Image(texture);
            image.x = 542;
            image.y = 122;
            image.width = 80;
            image.height = 24;
            image.scaleX = -1;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou1');
            image = new Image(texture);
            image.x = 72;
            image.y = 481;
            image.width = 470;
            image.height = 24;
            image.scaleY = -1;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou2');
            image = new Image(texture);
            image.x = 568;
            image.y = 145;
            image.width = 26;
            image.height = 325;
            image.scaleX = -1;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 572;
            image.y = 121;
            image.width = 38;
            image.height = 34;
            image.scaleX = -1;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_kuang_paizi1');
            image = new Image(texture);
            image.x = 411;
            image.y = 103;
            image.width = 61;
            image.height = 61;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou1');
            image = new Image(texture);
            image.x = 72;
            image.y = 122;
            image.width = 80;
            image.height = 24;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou2');
            image = new Image(texture);
            image.x = 44;
            image.y = 145;
            image.width = 26;
            image.height = 325;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 40;
            image.y = 121;
            image.width = 38;
            image.height = 34;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 572;
            image.y = 482;
            image.width = 38;
            image.height = 34;
            image.scaleX = -1;
            image.scaleY = -1;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_guaijiaoshitou');
            image = new Image(texture);
            image.x = 40;
            image.y = 482;
            image.width = 38;
            image.height = 34;
            image.scaleY = -1;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_Setup_title');
            image = new Image(texture);
            image.x = 222;
            image.width = 399;
            image.height = 104;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_button_zhuxianfubenpaizidi');
            btn_change = new Button(texture);
            btn_change.name= 'btn_change';
            btn_change.x = 80;
            btn_change.y = 197;
            btn_change.width = 162;
            btn_change.height = 240;
            this.addQuiackChild(btn_change);
            texture =assetMgr.getTexture('ui_Setup_button_switch3');
            image = new Image(texture);
            image.x = 585;
            image.y = 231;
            image.width = 214;
            image.height = 103;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_Setup_button_switch3');
            var ui_Setup_button_switch3585123Rect:Rectangle = new Rectangle(54,26,107,52);
            var ui_Setup_button_switch35851239ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_Setup_button_switch3585123Rect);
            ui_Setup_button_switch3585123 = new Scale9Image(ui_Setup_button_switch35851239ScaleTexture);
            ui_Setup_button_switch3585123.x = 585;
            ui_Setup_button_switch3585123.y = 123;
            ui_Setup_button_switch3585123.width = 214;
            ui_Setup_button_switch3585123.height = 103;
            this.addQuiackChild(ui_Setup_button_switch3585123);
            texture =assetMgr.getTexture('ui_button_switch');
            image = new Image(texture);
            image.x = 616;
            image.y = 154;
            image.width = 163;
            image.height = 75;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_button_switch');
            image = new Image(texture);
            image.x = 616;
            image.y = 263;
            image.width = 163;
            image.height = 75;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_Setup_button_tiebian');
            btn_feed = new Button(texture);
            btn_feed.name= 'btn_feed';
            btn_feed.x = 585;
            btn_feed.y = 342;
            btn_feed.width = 217;
            btn_feed.height = 66;
            this.addQuiackChild(btn_feed);
            btn_feed.text= '意见反馈';
            btn_feed.fontColor= 0xE7E5DF;
            btn_feed.fontSize= 24;
            texture = assetMgr.getTexture('ui_city_wenzidi');
            var ui_city_wenzidi259345Rect:Rectangle = new Rectangle(69,11,138,22);
            var ui_city_wenzidi2593459ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_city_wenzidi259345Rect);
            ui_city_wenzidi259345 = new Scale9Image(ui_city_wenzidi2593459ScaleTexture);
            ui_city_wenzidi259345.x = 259;
            ui_city_wenzidi259345.y = 345;
            ui_city_wenzidi259345.width = 275;
            ui_city_wenzidi259345.height = 44;
            this.addQuiackChild(ui_city_wenzidi259345);
            texture = assetMgr.getTexture('ui_city_wenzidi');
            var ui_city_wenzidi259290Rect:Rectangle = new Rectangle(69,11,138,22);
            var ui_city_wenzidi2592909ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_city_wenzidi259290Rect);
            ui_city_wenzidi259290 = new Scale9Image(ui_city_wenzidi2592909ScaleTexture);
            ui_city_wenzidi259290.x = 259;
            ui_city_wenzidi259290.y = 290;
            ui_city_wenzidi259290.width = 275;
            ui_city_wenzidi259290.height = 44;
            this.addQuiackChild(ui_city_wenzidi259290);
            texture = assetMgr.getTexture('ui_city_wenzidi');
            var ui_city_wenzidi259235Rect:Rectangle = new Rectangle(69,11,138,22);
            var ui_city_wenzidi2592359ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_city_wenzidi259235Rect);
            ui_city_wenzidi259235 = new Scale9Image(ui_city_wenzidi2592359ScaleTexture);
            ui_city_wenzidi259235.x = 259;
            ui_city_wenzidi259235.y = 235;
            ui_city_wenzidi259235.width = 275;
            ui_city_wenzidi259235.height = 44;
            this.addQuiackChild(ui_city_wenzidi259235);
            texture = assetMgr.getTexture('photo_501');
            ico_hero = new Button(texture);
            ico_hero.name= 'ico_hero';
            ico_hero.x = 108;
            ico_hero.y = 233;
            ico_hero.width = 100;
            ico_hero.height = 100;
            this.addQuiackChild(ico_hero);
            texture =assetMgr.getTexture('ui_city_head1');
            image = new Image(texture);
            image.x = 101;
            image.y = 223;
            image.width = 122;
            image.height = 122;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_city_head');
            image = new Image(texture);
            image.x = 97;
            image.y = 280;
            image.width = 98;
            image.height = 88;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            txt_title = new TextField(248,46,'','',32,0x342E22,false);
            txt_title.touchable = false;
            txt_title.hAlign= 'center';
            txt_title.text= '角色信息';
            txt_title.x = 296;
            txt_title.y = 22;
            this.addQuiackChild(txt_title);
            texture = assetMgr.getTexture('ui_city_wenzidi');
            var ui_city_wenzidi259400Rect:Rectangle = new Rectangle(69,11,138,22);
            var ui_city_wenzidi2594009ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_city_wenzidi259400Rect);
            ui_city_wenzidi259400 = new Scale9Image(ui_city_wenzidi2594009ScaleTexture);
            ui_city_wenzidi259400.x = 259;
            ui_city_wenzidi259400.y = 400;
            ui_city_wenzidi259400.width = 275;
            ui_city_wenzidi259400.height = 44;
            this.addQuiackChild(ui_city_wenzidi259400);
            texture = assetMgr.getTexture('ui_city_wenzidi');
            var ui_city_wenzidi259180Rect:Rectangle = new Rectangle(69,11,138,22);
            var ui_city_wenzidi2591809ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_city_wenzidi259180Rect);
            ui_city_wenzidi259180 = new Scale9Image(ui_city_wenzidi2591809ScaleTexture);
            ui_city_wenzidi259180.x = 259;
            ui_city_wenzidi259180.y = 180;
            ui_city_wenzidi259180.width = 275;
            ui_city_wenzidi259180.height = 44;
            this.addQuiackChild(ui_city_wenzidi259180);
            txt_des3 = new TextField(141,36,'','',24,0xFAEEC6,false);
            txt_des3.touchable = false;
            txt_des3.hAlign= 'left';
            txt_des3.text= '总战斗力:';
            txt_des3.x = 265;
            txt_des3.y = 180;
            this.addQuiackChild(txt_des3);
            txt_des4 = new TextField(141,36,'','',24,0xFAEEC6,false);
            txt_des4.touchable = false;
            txt_des4.hAlign= 'left';
            txt_des4.text= '角斗场段位:';
            txt_des4.x = 265;
            txt_des4.y = 236;
            this.addQuiackChild(txt_des4);
            txt_des5 = new TextField(141,36,'','',24,0xFAEEC6,false);
            txt_des5.touchable = false;
            txt_des5.hAlign= 'left';
            txt_des5.text= '开启关卡:';
            txt_des5.x = 265;
            txt_des5.y = 291;
            this.addQuiackChild(txt_des5);
            txt_des6 = new TextField(141,36,'','',24,0xFAEEC6,false);
            txt_des6.touchable = false;
            txt_des6.hAlign= 'left';
            txt_des6.text= '英雄总数:';
            txt_des6.x = 265;
            txt_des6.y = 346;
            this.addQuiackChild(txt_des6);
            txt_des7 = new TextField(141,36,'','',24,0xFAEEC6,false);
            txt_des7.touchable = false;
            txt_des7.hAlign= 'left';
            txt_des7.text= '邀请码:';
            txt_des7.x = 265;
            txt_des7.y = 402;
            this.addQuiackChild(txt_des7);
            txt_power = new TextField(141,36,'','',24,0xFAEEC6,false);
            txt_power.touchable = false;
            txt_power.hAlign= 'right';
            txt_power.text= '0';
            txt_power.x = 388;
            txt_power.y = 180;
            this.addQuiackChild(txt_power);
            txt_rank = new TextField(141,36,'','',24,0xFAEEC6,false);
            txt_rank.touchable = false;
            txt_rank.hAlign= 'right';
            txt_rank.text= '0';
            txt_rank.x = 388;
            txt_rank.y = 235;
            this.addQuiackChild(txt_rank);
            txt_tollgate = new TextField(141,36,'','',24,0xFAEEC6,false);
            txt_tollgate.touchable = false;
            txt_tollgate.hAlign= 'right';
            txt_tollgate.text= '0/0';
            txt_tollgate.x = 388;
            txt_tollgate.y = 291;
            this.addQuiackChild(txt_tollgate);
            txt_herocount = new TextField(141,36,'','',24,0xFAEEC6,false);
            txt_herocount.touchable = false;
            txt_herocount.hAlign= 'right';
            txt_herocount.text= '0/0';
            txt_herocount.x = 388;
            txt_herocount.y = 346;
            this.addQuiackChild(txt_herocount);
            txt_code = new TextField(141,36,'','',24,0xFAEEC6,false);
            txt_code.touchable = false;
            txt_code.hAlign= 'right';
            txt_code.text= '0';
            txt_code.x = 388;
            txt_code.y = 401;
            this.addQuiackChild(txt_code);
            txt_des1 = new TextField(210,36,'','',24,0xFFFF98,false);
            txt_des1.touchable = false;
            txt_des1.hAlign= 'center';
            txt_des1.text= '背景音乐';
            txt_des1.x = 585;
            txt_des1.y = 124;
            this.addQuiackChild(txt_des1);
            txt_des2 = new TextField(211,36,'','',24,0xFFFF98,false);
            txt_des2.touchable = false;
            txt_des2.hAlign= 'center';
            txt_des2.text= '游戏音效';
            txt_des2.x = 583;
            txt_des2.y = 233;
            this.addQuiackChild(txt_des2);
            texture = assetMgr.getTexture('ui_Buyingdiamond_button_guanbi');
            btn_close = new Button(texture);
            btn_close.name= 'btn_close';
            btn_close.x = 765;
            btn_close.y = 51;
            btn_close.width = 61;
            btn_close.height = 60;
            this.addQuiackChild(btn_close);
            texture = assetMgr.getTexture('ui_Setup_button_tiebian');
            btn_out = new Button(texture);
            btn_out.name= 'btn_out';
            btn_out.x = 585;
            btn_out.y = 420;
            btn_out.width = 217;
            btn_out.height = 66;
            this.addQuiackChild(btn_out);
            btn_out.text= '账号注销';
            btn_out.fontColor= 0xE7E5DF;
            btn_out.fontSize= 24;
            texture = assetMgr.getTexture('ui_button_switch1');
            btn_bgMusic = new Button(texture);
            btn_bgMusic.name= 'btn_bgMusic';
            btn_bgMusic.x = 629;
            btn_bgMusic.y = 164;
            btn_bgMusic.width = 133;
            btn_bgMusic.height = 43;
            this.addQuiackChild(btn_bgMusic);
            texture = assetMgr.getTexture('ui_button_switch1');
            btn_effectMusic = new Button(texture);
            btn_effectMusic.name= 'btn_effectMusic';
            btn_effectMusic.x = 629;
            btn_effectMusic.y = 274;
            btn_effectMusic.width = 133;
            btn_effectMusic.height = 43;
            this.addQuiackChild(btn_effectMusic);
            texture = assetMgr.getTexture('ui_iocn_qualifying6')
            tag_rankLevel = new Image(texture);
            tag_rankLevel.x = 89;
            tag_rankLevel.y = 313;
            tag_rankLevel.width = 85;
            tag_rankLevel.height = 57;
            this.addQuiackChild(tag_rankLevel);
            tag_rankLevel.touchable = false;
            txt_des8 = new TextField(141,36,'','',24,0xFAEEC6,false);
            txt_des8.touchable = false;
            txt_des8.hAlign= 'left';
            txt_des8.text= '版本号:';
            txt_des8.x = 19;
            txt_des8.y = 58;
            this.addQuiackChild(txt_des8);
            txt_version = new TextField(141,36,'','',24,0xFAEEC6,false);
            txt_version.touchable = false;
            txt_version.hAlign= 'right';
            txt_version.text= '1.0.3';
            txt_version.x = 72;
            txt_version.y = 58;
            this.addQuiackChild(txt_version);
            txt = new TextField(141,36,'','',24,0xFFCC00,false);
            txt.touchable = false;
            txt.hAlign= 'center';
            txt.text= '更换头像';
            txt.x = 86;
            txt.y = 370;
            this.addQuiackChild(txt);
            texture =assetMgr.getTexture('ui_gongyong_kuang_paizi1');
            image = new Image(texture);
            image.x = 203;
            image.y = 103;
            image.width = 61;
            image.height = 61;
            image.scaleX = -1;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_icon_city_vip');
            image = new Image(texture);
            image.x = 187;
            image.y = 105;
            image.width = 65;
            image.height = 65;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            txt_name = new TextField(198,36,'','',24,0xF2CA13,false);
            txt_name.touchable = false;
            txt_name.hAlign= 'center';
            txt_name.text= '';
            txt_name.x = 249;
            txt_name.y = 117;
            this.addQuiackChild(txt_name);
            txt_vip = new TextField(42,25,'','',16,0xE7E5DF,false);
            txt_vip.touchable = false;
            txt_vip.hAlign= 'center';
            txt_vip.text= '0';
            txt_vip.x = 196;
            txt_vip.y = 133;
            this.addQuiackChild(txt_vip);
            init();
        }
        override public function dispose():void
        {
            btn_change.dispose();
            btn_feed.dispose();
            ico_hero.dispose();
            btn_close.dispose();
            btn_out.dispose();
            btn_bgMusic.dispose();
            btn_effectMusic.dispose();
            super.dispose();
        
}
    }
}
