package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import com.dialog.Dialog;

    public class UiAndroidPayBase extends Dialog
    {
        public var box1:Button;
        public var box2:Button;
        public var box3:Button;
        public var box4:Button;
        public var txt_des3:TextField;
        public var txt_3:TextField;
        public var txt_des2:TextField;
        public var txt_2:TextField;
        public var txt_des1:TextField;
        public var txt_1:TextField;
        public var txt_des4:TextField;
        public var txt_4:TextField;
        public var btn_close:Button;

        public function UiAndroidPayBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            var assetMgr:AssetMgr = AssetMgr.instance;
            texture =assetMgr.getTexture('ui_dimian');
            image = new Image(texture);
            image.y = 51;
            image.width = 584;
            image.height = 603;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_danyuange');
            box1 = new Button(texture);
            box1.name= 'box1';
            box1.x = 46;
            box1.y = 93;
            box1.width = 491;
            box1.height = 121;
            this.addQuiackChild(box1);
            texture = assetMgr.getTexture('ui_danyuange');
            box2 = new Button(texture);
            box2.name= 'box2';
            box2.x = 46;
            box2.y = 229;
            box2.width = 491;
            box2.height = 121;
            this.addQuiackChild(box2);
            texture = assetMgr.getTexture('ui_danyuange');
            box3 = new Button(texture);
            box3.name= 'box3';
            box3.x = 46;
            box3.y = 365;
            box3.width = 491;
            box3.height = 121;
            this.addQuiackChild(box3);
            texture = assetMgr.getTexture('ui_danyuange');
            box4 = new Button(texture);
            box4.name= 'box4';
            box4.x = 46;
            box4.y = 501;
            box4.width = 491;
            box4.height = 121;
            this.addQuiackChild(box4);
            texture =assetMgr.getTexture('ui_chongzhijiekou_01');
            image = new Image(texture);
            image.x = 75;
            image.y = 109;
            image.width = 106;
            image.height = 86;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_chongzhijiekou_02');
            image = new Image(texture);
            image.x = 75;
            image.y = 245;
            image.width = 106;
            image.height = 86;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_chongzhijiekou_03');
            image = new Image(texture);
            image.x = 75;
            image.y = 381;
            image.width = 106;
            image.height = 86;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_chongzhijiekou_04');
            image = new Image(texture);
            image.x = 75;
            image.y = 517;
            image.width = 106;
            image.height = 86;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            txt_des3 = new TextField(180,36,'','',24,0xFFFFFF,false);
            txt_des3.touchable = false;
            txt_des3.hAlign= 'center';
            txt_des3.text= 'paypal线上购买';
            txt_des3.x = 242;
            txt_des3.y = 380;
            this.addQuiackChild(txt_des3);
            txt_3 = new TextField(280,52,'','',36,0xFFFFFF,false);
            txt_3.touchable = false;
            txt_3.hAlign= 'center';
            txt_3.text= '';
            txt_3.x = 200;
            txt_3.y = 419;
            this.addQuiackChild(txt_3);
            txt_des2 = new TextField(180,36,'','',24,0xFFFFFF,false);
            txt_des2.touchable = false;
            txt_des2.hAlign= 'center';
            txt_des2.text= 'MyCard实体卡';
            txt_des2.x = 242;
            txt_des2.y = 245;
            this.addQuiackChild(txt_des2);
            txt_2 = new TextField(280,52,'','',36,0xFFFFFF,false);
            txt_2.touchable = false;
            txt_2.hAlign= 'center';
            txt_2.text= '';
            txt_2.x = 200;
            txt_2.y = 284;
            this.addQuiackChild(txt_2);
            txt_des1 = new TextField(180,36,'','',24,0xFFFFFF,false);
            txt_des1.touchable = false;
            txt_des1.hAlign= 'center';
            txt_des1.text= 'fun点支付';
            txt_des1.x = 242;
            txt_des1.y = 109;
            this.addQuiackChild(txt_des1);
            txt_1 = new TextField(280,52,'','',36,0xFFFFFF,false);
            txt_1.touchable = false;
            txt_1.hAlign= 'center';
            txt_1.text= '';
            txt_1.x = 200;
            txt_1.y = 148;
            this.addQuiackChild(txt_1);
            txt_des4 = new TextField(180,36,'','',24,0xFFFFFF,false);
            txt_des4.touchable = false;
            txt_des4.hAlign= 'center';
            txt_des4.text= 'Google  play';
            txt_des4.x = 242;
            txt_des4.y = 517;
            this.addQuiackChild(txt_des4);
            txt_4 = new TextField(280,52,'','',36,0xFFFFFF,false);
            txt_4.touchable = false;
            txt_4.hAlign= 'center';
            txt_4.text= '';
            txt_4.x = 200;
            txt_4.y = 556;
            this.addQuiackChild(txt_4);
            texture = assetMgr.getTexture('ui_gongyong_tuichuanniiu');
            btn_close = new Button(texture);
            btn_close.name= 'btn_close';
            btn_close.x = 532;
            btn_close.y = -36;
            btn_close.width = 99;
            btn_close.height = 145;
            this.addQuiackChild(btn_close);
            init();
        }
        override public function dispose():void
        {
            box1.dispose();
            box2.dispose();
            box3.dispose();
            box4.dispose();
            btn_close.dispose();
            super.dispose();
        
}
    }
}
