package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import com.view.View;

    public class VipChargeRenderBase extends View
    {
        public var box0:Button;
        public var itemNum0:TextField;
        public var box1:Button;
        public var itemNum1:TextField;
        public var box2:Button;
        public var itemNum2:TextField;
        public var box3:Button;
        public var itemNum3:TextField;
        public var box4:Button;
        public var itemNum4:TextField;
        public var box5:Button;
        public var itemNum5:TextField;
        public var box6:Button;
        public var itemNum6:TextField;
        public var box7:Button;
        public var itemNum7:TextField;
        public var txt_reward:TextField;
        public var tag_double1:Image;
        public var tag_double2:Image;
        public var tag_double3:Image;
        public var tag_double4:Image;
        public var tag_double5:Image;
        public var tag_double6:Image;
        public var tag_double0:Image;
        public var txt_des1:TextField;
        public var box8:Button;
        public var itemNum8:TextField;

        public function VipChargeRenderBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            var assetMgr:AssetMgr = AssetMgr.instance;
            texture = assetMgr.getTexture('ui_button_zhuxianfubenpaizidi');
            box0 = new Button(texture);
            box0.name= 'box0';
            box0.x = 341;
            box0.y = 29;
            box0.width = 162;
            box0.height = 240;
            this.addQuiackChild(box0);
            texture =assetMgr.getTexture('ui_Buyingdiamond_tubiao1 ');
            image = new Image(texture);
            image.x = 344;
            image.y = 82;
            image.width = 150;
            image.height = 122;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            itemNum0 = new TextField(135,31,'','',24,0x000000,false);
            itemNum0.touchable = false;
            itemNum0.hAlign= 'left';
            itemNum0.text= '100钻石';
            itemNum0.x = 351;
            itemNum0.y = 44;
            this.addQuiackChild(itemNum0);
            texture = assetMgr.getTexture('ui_button_zhuxianfubenpaizidi');
            box1 = new Button(texture);
            box1.name= 'box1';
            box1.x = 504;
            box1.y = 29;
            box1.width = 162;
            box1.height = 240;
            this.addQuiackChild(box1);
            texture =assetMgr.getTexture('ui_Buyingdiamond_tubiao2');
            image = new Image(texture);
            image.x = 509;
            image.y = 84;
            image.width = 150;
            image.height = 122;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            itemNum1 = new TextField(139,31,'','',24,0x000000,false);
            itemNum1.touchable = false;
            itemNum1.hAlign= 'left';
            itemNum1.text= '100钻石';
            itemNum1.x = 514;
            itemNum1.y = 44;
            this.addQuiackChild(itemNum1);
            texture =assetMgr.getTexture('ui_Buyingdiamond_dazhe');
            image = new Image(texture);
            image.x = 586;
            image.y = 30;
            image.width = 75;
            image.height = 75;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_Buyingdiamond_dazhe6');
            image = new Image(texture);
            image.x = 607;
            image.y = 32;
            image.width = 50;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_button_zhuxianfubenpaizidi');
            box2 = new Button(texture);
            box2.name= 'box2';
            box2.x = 667;
            box2.y = 29;
            box2.width = 162;
            box2.height = 240;
            this.addQuiackChild(box2);
            itemNum2 = new TextField(141,31,'','',24,0x000000,false);
            itemNum2.touchable = false;
            itemNum2.hAlign= 'left';
            itemNum2.text= '100钻石';
            itemNum2.x = 676;
            itemNum2.y = 44;
            this.addQuiackChild(itemNum2);
            texture =assetMgr.getTexture('ui_Buyingdiamond_dazhe');
            image = new Image(texture);
            image.x = 747;
            image.y = 30;
            image.width = 75;
            image.height = 75;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_Buyingdiamond_tubiao3');
            image = new Image(texture);
            image.x = 663;
            image.y = 84;
            image.width = 167;
            image.height = 127;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_Buyingdiamond_dazhe5');
            image = new Image(texture);
            image.x = 767;
            image.y = 33;
            image.width = 52;
            image.height = 51;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_button_zhuxianfubenpaizidi');
            box3 = new Button(texture);
            box3.name= 'box3';
            box3.x = 830;
            box3.y = 29;
            box3.width = 162;
            box3.height = 240;
            this.addQuiackChild(box3);
            itemNum3 = new TextField(146,31,'','',24,0x000000,false);
            itemNum3.touchable = false;
            itemNum3.hAlign= 'left';
            itemNum3.text= '100钻石';
            itemNum3.x = 839;
            itemNum3.y = 44;
            this.addQuiackChild(itemNum3);
            texture =assetMgr.getTexture('ui_Buyingdiamond_dazhe');
            image = new Image(texture);
            image.x = 909;
            image.y = 30;
            image.width = 75;
            image.height = 75;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_Buyingdiamond_dazhe4');
            image = new Image(texture);
            image.x = 933;
            image.y = 32;
            image.width = 49;
            image.height = 52;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_Buyingdiamond_tubiao4');
            image = new Image(texture);
            image.x = 853;
            image.y = 92;
            image.width = 115;
            image.height = 106;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_button_zhuxianfubenpaizidi');
            box4 = new Button(texture);
            box4.name= 'box4';
            box4.x = 994;
            box4.y = 29;
            box4.width = 162;
            box4.height = 240;
            this.addQuiackChild(box4);
            texture =assetMgr.getTexture('ui_Buyingdiamond_tubiao5');
            image = new Image(texture);
            image.x = 993;
            image.y = 70;
            image.width = 156;
            image.height = 120;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            itemNum4 = new TextField(145,31,'','',24,0x000000,false);
            itemNum4.touchable = false;
            itemNum4.hAlign= 'left';
            itemNum4.text= '100钻石';
            itemNum4.x = 1002;
            itemNum4.y = 45;
            this.addQuiackChild(itemNum4);
            texture =assetMgr.getTexture('ui_Buyingdiamond_dazhe');
            image = new Image(texture);
            image.x = 1074;
            image.y = 29;
            image.width = 75;
            image.height = 75;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_Buyingdiamond_dazhe3');
            image = new Image(texture);
            image.x = 1096;
            image.y = 31;
            image.width = 49;
            image.height = 52;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_button_zhuxianfubenpaizidi');
            box5 = new Button(texture);
            box5.name= 'box5';
            box5.x = 1154;
            box5.y = 29;
            box5.width = 162;
            box5.height = 240;
            this.addQuiackChild(box5);
            texture =assetMgr.getTexture('ui_Buyingdiamond_tubiao6');
            image = new Image(texture);
            image.x = 1179;
            image.y = 78;
            image.width = 112;
            image.height = 111;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            itemNum5 = new TextField(145,31,'','',24,0x000000,false);
            itemNum5.touchable = false;
            itemNum5.hAlign= 'left';
            itemNum5.text= '100钻石';
            itemNum5.x = 1163;
            itemNum5.y = 45;
            this.addQuiackChild(itemNum5);
            texture =assetMgr.getTexture('ui_Buyingdiamond_dazhe');
            image = new Image(texture);
            image.x = 1234;
            image.y = 29;
            image.width = 75;
            image.height = 75;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_Buyingdiamond_dazhe2');
            image = new Image(texture);
            image.x = 1255;
            image.y = 31;
            image.width = 52;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_button_zhuxianfubenpaizidi');
            box6 = new Button(texture);
            box6.name= 'box6';
            box6.x = 1317;
            box6.y = 29;
            box6.width = 162;
            box6.height = 240;
            this.addQuiackChild(box6);
            texture =assetMgr.getTexture('ui_Buyingdiamond_tubiao7');
            image = new Image(texture);
            image.x = 1325;
            image.y = 73;
            image.width = 144;
            image.height = 114;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            itemNum6 = new TextField(143,31,'','',24,0x000000,false);
            itemNum6.touchable = false;
            itemNum6.hAlign= 'left';
            itemNum6.text= '15968钻石';
            itemNum6.x = 1327;
            itemNum6.y = 45;
            this.addQuiackChild(itemNum6);
            texture =assetMgr.getTexture('ui_Buyingdiamond_dazhe');
            image = new Image(texture);
            image.x = 1398;
            image.y = 29;
            image.width = 75;
            image.height = 75;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_Buyingdiamond_dazhe1');
            image = new Image(texture);
            image.x = 1419;
            image.y = 30;
            image.width = 52;
            image.height = 50;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_button_zhuxianfubenpaizidi');
            box7 = new Button(texture);
            box7.name= 'box7';
            box7.x = 170;
            box7.y = 29;
            box7.width = 162;
            box7.height = 240;
            this.addQuiackChild(box7);
            itemNum7 = new TextField(135,31,'','',24,0x000000,false);
            itemNum7.touchable = false;
            itemNum7.hAlign= 'left';
            itemNum7.text= '100钻石';
            itemNum7.x = 180;
            itemNum7.y = 44;
            this.addQuiackChild(itemNum7);
            texture =assetMgr.getTexture('ui_recharge_monthly');
            image = new Image(texture);
            image.x = 176;
            image.y = 80;
            image.width = 142;
            image.height = 119;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_recharge_label_meiri');
            image = new Image(texture);
            image.x = 232;
            image.width = 110;
            image.height = 81;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_zuanshi');
            image = new Image(texture);
            image.x = 300;
            image.y = 27;
            image.width = 24;
            image.height = 23;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            txt_reward = new TextField(107,28,'','',22,0xFFFFFF,false);
            txt_reward.touchable = false;
            txt_reward.hAlign= 'right';
            txt_reward.text= '';
            txt_reward.x = 196;
            txt_reward.y = 21;
            this.addQuiackChild(txt_reward);
            texture = assetMgr.getTexture('ui_recharge_fanbeilingqu')
            tag_double1 = new Image(texture);
            tag_double1.x = 546;
            tag_double1.y = 110;
            tag_double1.width = 112;
            tag_double1.height = 89;
            this.addQuiackChild(tag_double1);
            tag_double1.touchable = false;
            texture = assetMgr.getTexture('ui_recharge_fanbeilingqu')
            tag_double2 = new Image(texture);
            tag_double2.x = 707;
            tag_double2.y = 110;
            tag_double2.width = 112;
            tag_double2.height = 89;
            this.addQuiackChild(tag_double2);
            tag_double2.touchable = false;
            texture = assetMgr.getTexture('ui_recharge_fanbeilingqu')
            tag_double3 = new Image(texture);
            tag_double3.x = 870;
            tag_double3.y = 110;
            tag_double3.width = 112;
            tag_double3.height = 89;
            this.addQuiackChild(tag_double3);
            tag_double3.touchable = false;
            texture = assetMgr.getTexture('ui_recharge_fanbeilingqu')
            tag_double4 = new Image(texture);
            tag_double4.x = 1034;
            tag_double4.y = 110;
            tag_double4.width = 112;
            tag_double4.height = 89;
            this.addQuiackChild(tag_double4);
            tag_double4.touchable = false;
            texture = assetMgr.getTexture('ui_recharge_fanbeilingqu')
            tag_double5 = new Image(texture);
            tag_double5.x = 1194;
            tag_double5.y = 110;
            tag_double5.width = 112;
            tag_double5.height = 89;
            this.addQuiackChild(tag_double5);
            tag_double5.touchable = false;
            texture = assetMgr.getTexture('ui_recharge_fanbeilingqu')
            tag_double6 = new Image(texture);
            tag_double6.x = 1359;
            tag_double6.y = 110;
            tag_double6.width = 112;
            tag_double6.height = 89;
            this.addQuiackChild(tag_double6);
            tag_double6.touchable = false;
            texture = assetMgr.getTexture('ui_recharge_fanbeilingqu')
            tag_double0 = new Image(texture);
            tag_double0.x = 381;
            tag_double0.y = 110;
            tag_double0.width = 112;
            tag_double0.height = 89;
            this.addQuiackChild(tag_double0);
            tag_double0.touchable = false;
            txt_des1 = new TextField(107,28,'','',16,0xFFFFFF,false);
            txt_des1.touchable = false;
            txt_des1.hAlign= 'right';
            txt_des1.text= '/日';
            txt_des1.x = 211;
            txt_des1.y = 46;
            this.addQuiackChild(txt_des1);
            texture = assetMgr.getTexture('ui_button_zhuxianfubenpaizidi');
            box8 = new Button(texture);
            box8.name= 'box8';
            box8.y = 29;
            box8.width = 162;
            box8.height = 240;
            this.addQuiackChild(box8);
            texture =assetMgr.getTexture('ui_MYCARD');
            image = new Image(texture);
            image.x = 7;
            image.y = 74;
            image.width = 142;
            image.height = 119;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            itemNum8 = new TextField(143,36,'','',24,0x000000,false);
            itemNum8.touchable = false;
            itemNum8.hAlign= 'center';
            itemNum8.text= '面值*2';
            itemNum8.x = 12;
            itemNum8.y = 43;
            this.addQuiackChild(itemNum8);
            init();
        }
        override public function dispose():void
        {
            box0.dispose();
            box1.dispose();
            box2.dispose();
            box3.dispose();
            box4.dispose();
            box5.dispose();
            box6.dispose();
            box7.dispose();
            box8.dispose();
            super.dispose();
        
}
    }
}
