package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.dialog.Dialog;

    public class VipDlgBase extends Dialog
    {
        public var ui_gongyong_di_9gongge233114:Scale9Image;
        public var ui_gongyong_di_9gongge46281:Scale9Image;
        public var exp_curr:Scale9Image;
        public var exp_send:Scale9Image;
        public var ui_gongyong_9gongge_vip_tiao251153:Scale9Image;
        public var txt_vip:TextField;
        public var txt_des1:TextField;
        public var txt_currlv:TextField;
        public var txt_nextlv:TextField;
        public var txt_money:TextField;
        public var txt_currMoney:TextField;
        public var txt_des2:TextField;
        public var txt_needMoney:TextField;
        public var btn_look:Button;
        public var btn_close:Button;
        public var txt_tile:TextField;

        public function VipDlgBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            var assetMgr:AssetMgr = AssetMgr.instance;
            texture =assetMgr.getTexture('ui_wudixingyunxing_xingxing_goumaikuang2');
            image = new Image(texture);
            image.x = 88;
            image.y = 22;
            image.width = 682;
            image.height = 557;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_wudixingyunxing_xingxing_goumaikuang1');
            image = new Image(texture);
            image.x = 862;
            image.y = 22;
            image.width = 102;
            image.height = 557;
            image.scaleX = -1;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_wudixingyunxing_xingxing_goumaikuang1');
            image = new Image(texture);
            image.y = 22;
            image.width = 102;
            image.height = 557;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_di_9gongge');
            var ui_gongyong_di_9gongge233114Rect:Rectangle = new Rectangle(21,21,43,41);
            var ui_gongyong_di_9gongge2331149ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_gongyong_di_9gongge233114Rect);
            ui_gongyong_di_9gongge233114 = new Scale9Image(ui_gongyong_di_9gongge2331149ScaleTexture);
            ui_gongyong_di_9gongge233114.x = 233;
            ui_gongyong_di_9gongge233114.y = 114;
            ui_gongyong_di_9gongge233114.width = 595;
            ui_gongyong_di_9gongge233114.height = 88;
            this.addQuiackChild(ui_gongyong_di_9gongge233114);
            texture =assetMgr.getTexture('ui_Setup_title');
            image = new Image(texture);
            image.x = 239;
            image.width = 399;
            image.height = 104;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_di_9gongge');
            var ui_gongyong_di_9gongge46281Rect:Rectangle = new Rectangle(21,21,43,41);
            var ui_gongyong_di_9gongge462819ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_gongyong_di_9gongge46281Rect);
            ui_gongyong_di_9gongge46281 = new Scale9Image(ui_gongyong_di_9gongge462819ScaleTexture);
            ui_gongyong_di_9gongge46281.x = 46;
            ui_gongyong_di_9gongge46281.y = 281;
            ui_gongyong_di_9gongge46281.width = 781;
            ui_gongyong_di_9gongge46281.height = 264;
            this.addQuiackChild(ui_gongyong_di_9gongge46281);
            texture =assetMgr.getTexture('ui_Buyingdiamond_diamond_di');
            image = new Image(texture);
            image.x = 53;
            image.y = 54;
            image.width = 146;
            image.height = 37;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_zuanshi');
            image = new Image(texture);
            image.x = 35;
            image.y = 50;
            image.width = 46;
            image.height = 44;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_zuanshi');
            image = new Image(texture);
            image.x = 148;
            image.y = 219;
            image.width = 38;
            image.height = 36;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_gongyong_zuanshi');
            image = new Image(texture);
            image.x = 500;
            image.y = 219;
            image.width = 38;
            image.height = 36;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_9gongge_vip_tiao1');
            var exp_currRect:Rectangle = new Rectangle(11,6,22,12);
            var exp_curr9ScaleTexture:Scale9Textures = new Scale9Textures(texture,exp_currRect);
            exp_curr = new Scale9Image(exp_curr9ScaleTexture);
            exp_curr.x = 256;
            exp_curr.y = 158;
            exp_curr.width = 540;
            exp_curr.height = 24;
            this.addQuiackChild(exp_curr);
            texture = assetMgr.getTexture('ui_gongyong_9gongge_vip_tiao2');
            var exp_sendRect:Rectangle = new Rectangle(11,6,22,12);
            var exp_send9ScaleTexture:Scale9Textures = new Scale9Textures(texture,exp_sendRect);
            exp_send = new Scale9Image(exp_send9ScaleTexture);
            exp_send.x = 256;
            exp_send.y = 158;
            exp_send.width = 43;
            exp_send.height = 24;
            this.addQuiackChild(exp_send);
            texture = assetMgr.getTexture('ui_gongyong_9gongge_vip_tiao');
            var ui_gongyong_9gongge_vip_tiao251153Rect:Rectangle = new Rectangle(21,9,41,17);
            var ui_gongyong_9gongge_vip_tiao2511539ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_gongyong_9gongge_vip_tiao251153Rect);
            ui_gongyong_9gongge_vip_tiao251153 = new Scale9Image(ui_gongyong_9gongge_vip_tiao2511539ScaleTexture);
            ui_gongyong_9gongge_vip_tiao251153.x = 251;
            ui_gongyong_9gongge_vip_tiao251153.y = 153;
            ui_gongyong_9gongge_vip_tiao251153.width = 559;
            ui_gongyong_9gongge_vip_tiao251153.height = 34;
            this.addQuiackChild(ui_gongyong_9gongge_vip_tiao251153);
            texture =assetMgr.getTexture('ui_wenzi_vip_ziti');
            image = new Image(texture);
            image.x = 276;
            image.y = 123;
            image.width = 54;
            image.height = 23;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_icon_city_vip');
            image = new Image(texture);
            image.x = 74;
            image.y = 90;
            image.width = 97;
            image.height = 97;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_wenzi_nindevipdengji');
            image = new Image(texture);
            image.x = 47;
            image.y = 167;
            image.width = 151;
            image.height = 29;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_wenzi_vip_ziti');
            image = new Image(texture);
            image.x = 648;
            image.y = 123;
            image.width = 54;
            image.height = 23;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            txt_vip = new TextField(104,38,'','',26,0xFFFF00,false);
            txt_vip.touchable = false;
            txt_vip.hAlign= 'center';
            txt_vip.text= '0';
            txt_vip.x = 67;
            txt_vip.y = 128;
            this.addQuiackChild(txt_vip);
            txt_des1 = new TextField(110,36,'','',20,0xFFFFCC,false);
            txt_des1.touchable = false;
            txt_des1.hAlign= 'left';
            txt_des1.text= '当前充值';
            txt_des1.x = 48;
            txt_des1.y = 218;
            this.addQuiackChild(txt_des1);
            txt_currlv = new TextField(104,38,'','',25,0xFFFF00,false);
            txt_currlv.touchable = false;
            txt_currlv.hAlign= 'center';
            txt_currlv.text= '0';
            txt_currlv.x = 320;
            txt_currlv.y = 112;
            this.addQuiackChild(txt_currlv);
            txt_nextlv = new TextField(104,38,'','',25,0xFFFF00,false);
            txt_nextlv.touchable = false;
            txt_nextlv.hAlign= 'center';
            txt_nextlv.text= '1';
            txt_nextlv.x = 692;
            txt_nextlv.y = 112;
            this.addQuiackChild(txt_nextlv);
            txt_money = new TextField(122,30,'','',20,0xFFFFFF,false);
            txt_money.touchable = false;
            txt_money.hAlign= 'right';
            txt_money.text= '0';
            txt_money.x = 72;
            txt_money.y = 58;
            this.addQuiackChild(txt_money);
            txt_currMoney = new TextField(104,30,'','',20,0xFFEA00,false);
            txt_currMoney.touchable = false;
            txt_currMoney.hAlign= 'left';
            txt_currMoney.text= '0';
            txt_currMoney.x = 190;
            txt_currMoney.y = 222;
            this.addQuiackChild(txt_currMoney);
            txt_des2 = new TextField(156,36,'','',20,0xFFFFCC,false);
            txt_des2.touchable = false;
            txt_des2.hAlign= 'right';
            txt_des2.text= '升级需要充值';
            txt_des2.x = 336;
            txt_des2.y = 218;
            this.addQuiackChild(txt_des2);
            txt_needMoney = new TextField(118,30,'','',20,0xECAA3A,false);
            txt_needMoney.touchable = false;
            txt_needMoney.hAlign= 'right';
            txt_needMoney.text= '0';
            txt_needMoney.x = 534;
            txt_needMoney.y = 222;
            this.addQuiackChild(txt_needMoney);
            texture = assetMgr.getTexture('ui_button_tiebaomutouanjian');
            btn_look = new Button(texture);
            btn_look.name= 'btn_look';
            btn_look.x = 674;
            btn_look.y = 207;
            btn_look.width = 150;
            btn_look.height = 64;
            this.addQuiackChild(btn_look);
            btn_look.text= '查看特权';
            btn_look.fontColor= 0xFFFFFF;
            btn_look.fontSize= 24;
            texture = assetMgr.getTexture('ui_Buyingdiamond_button_guanbi');
            btn_close = new Button(texture);
            btn_close.name= 'btn_close';
            btn_close.x = 781;
            btn_close.y = 50;
            btn_close.width = 61;
            btn_close.height = 60;
            this.addQuiackChild(btn_close);
            txt_tile = new TextField(294,41,'','',28,0x3D3125,false);
            txt_tile.touchable = false;
            txt_tile.hAlign= 'center';
            txt_tile.text= '充值&VIP';
            txt_tile.x = 292;
            txt_tile.y = 23;
            this.addQuiackChild(txt_tile);
            init();
        }
        override public function dispose():void
        {
            btn_look.dispose();
            btn_close.dispose();
            super.dispose();
        
}
    }
}
