package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import com.components.TabMenu;
    import com.components.TabButton;
    import feathers.controls.List;
    import com.components.TabMenu;
    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;
    import com.dialog.Dialog;

    public class VipRewardDlgBase extends Dialog
    {
        public var ui_gongyong_di_9gongge28180:Scale9Image;
        public var list_reward:List;
        public var tab_1:TabButton;
        public var tab_2:TabButton;
        public var txt_tile:TextField;
        public var txt_des:TextField;
        public var btn_close:Button;
        public var tab_3:TabButton;
        public var tab_4:TabButton;
        public var tab_5:TabButton;
        public var tabMenu_hero:TabMenu;
        public var btn_get:Button;

        public function VipRewardDlgBase()
        {
            super(false);
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            var assetMgr:AssetMgr = AssetMgr.instance;
            texture =assetMgr.getTexture('ui_wudixingyunxing_xingxing_goumaikuang2');
            image = new Image(texture);
            image.x = 68;
            image.y = 24;
            image.width = 682;
            image.height = 451;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_wudixingyunxing_xingxing_goumaikuang1');
            image = new Image(texture);
            image.x = 810;
            image.y = 24;
            image.width = 102;
            image.height = 451;
            image.scaleX = -1;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_wudixingyunxing_xingxing_goumaikuang1');
            image = new Image(texture);
            image.y = 24;
            image.width = 102;
            image.height = 451;
            image.smoothing= Constants.NONE;
            this.addQuiackChild(image);
            texture = assetMgr.getTexture('ui_gongyong_di_9gongge');
            var ui_gongyong_di_9gongge28180Rect:Rectangle = new Rectangle(21,21,43,41);
            var ui_gongyong_di_9gongge281809ScaleTexture:Scale9Textures = new Scale9Textures(texture,ui_gongyong_di_9gongge28180Rect);
            ui_gongyong_di_9gongge28180 = new Scale9Image(ui_gongyong_di_9gongge281809ScaleTexture);
            ui_gongyong_di_9gongge28180.x = 28;
            ui_gongyong_di_9gongge28180.y = 180;
            ui_gongyong_di_9gongge28180.width = 754;
            ui_gongyong_di_9gongge28180.height = 200;
            this.addQuiackChild(ui_gongyong_di_9gongge28180);
            list_reward = new List();
            list_reward.x = 40;
            list_reward.y = 200;
            list_reward.width = 720;
            list_reward.height = 200;
            this.addQuiackChild(list_reward);
            texture =assetMgr.getTexture('ui_Setup_title');
            image = new Image(texture);
            image.x = 208;
            image.width = 399;
            image.height = 104;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            tab_1 = new TabButton(assetMgr.getTexture('ui_button_tiebaomutouanjian'),assetMgr.getTexture('ui_button_tiebaomutouanjian_liang'));
            tab_1.x = 26;
            tab_1.y = 113;
            tab_1.width = 152;
            tab_1.height = 64;
            this.addQuiackChild(tab_1);
            tab_1.text= '领取';
            tab_1.fontColor= 0xFFFFCC;
            tab_1.fontSize= 24;
            tab_2 = new TabButton(assetMgr.getTexture('ui_button_tiebaomutouanjian'),assetMgr.getTexture('ui_button_tiebaomutouanjian_liang'));
            tab_2.x = 175;
            tab_2.y = 113;
            tab_2.width = 152;
            tab_2.height = 64;
            this.addQuiackChild(tab_2);
            tab_2.text= '领取';
            tab_2.fontColor= 0xFFFFCC;
            tab_2.fontSize= 24;
            txt_tile = new TextField(294,41,'','',28,0x3D3125,false);
            txt_tile.touchable = false;
            txt_tile.hAlign= 'center';
            txt_tile.text= 'vip每日大礼包';
            txt_tile.x = 260;
            txt_tile.y = 21;
            this.addQuiackChild(txt_tile);
            txt_des = new TextField(572,41,'','',28,0xED7C16,false);
            txt_des.touchable = false;
            txt_des.hAlign= 'left';
            txt_des.text= '更高的vip等级可以获得更丰厚的奖励哦！';
            txt_des.x = 31;
            txt_des.y = 395;
            this.addQuiackChild(txt_des);
            texture = assetMgr.getTexture('ui_Buyingdiamond_button_guanbi');
            btn_close = new Button(texture);
            btn_close.name= 'btn_close';
            btn_close.x = 737;
            btn_close.y = 42;
            btn_close.width = 61;
            btn_close.height = 60;
            this.addQuiackChild(btn_close);
            tab_3 = new TabButton(assetMgr.getTexture('ui_button_tiebaomutouanjian'),assetMgr.getTexture('ui_button_tiebaomutouanjian_liang'));
            tab_3.x = 324;
            tab_3.y = 113;
            tab_3.width = 152;
            tab_3.height = 64;
            this.addQuiackChild(tab_3);
            tab_3.text= '领取';
            tab_3.fontColor= 0xFFFFCC;
            tab_3.fontSize= 24;
            tab_4 = new TabButton(assetMgr.getTexture('ui_button_tiebaomutouanjian'),assetMgr.getTexture('ui_button_tiebaomutouanjian_liang'));
            tab_4.x = 473;
            tab_4.y = 113;
            tab_4.width = 152;
            tab_4.height = 64;
            this.addQuiackChild(tab_4);
            tab_4.text= '领取';
            tab_4.fontColor= 0xFFFFCC;
            tab_4.fontSize= 24;
            tab_5 = new TabButton(assetMgr.getTexture('ui_button_tiebaomutouanjian'),assetMgr.getTexture('ui_button_tiebaomutouanjian_liang'));
            tab_5.x = 622;
            tab_5.y = 113;
            tab_5.width = 152;
            tab_5.height = 64;
            this.addQuiackChild(tab_5);
            tab_5.text= '领取';
            tab_5.fontColor= 0xFFFFCC;
            tab_5.fontSize= 24;
            tabMenu_hero = new TabMenu([tab_1,tab_2,tab_3,tab_4,tab_5]);
            tabMenu_hero.x = 26;
            tabMenu_hero.y = 113;
            this.addQuiackChild(tabMenu_hero);
            texture = assetMgr.getTexture('ui_button_tiebaomutouanjian');
            btn_get = new Button(texture);
            btn_get.name= 'btn_get';
            btn_get.x = 634;
            btn_get.y = 391;
            btn_get.width = 152;
            btn_get.height = 64;
            this.addQuiackChild(btn_get);
            btn_get.text= '领取';
            btn_get.fontColor= 0xFFFFCC;
            btn_get.fontSize= 24;
            init();
        }
        override public function dispose():void
        {
            list_reward.dispose();
            tab_1.dispose();
            tab_2.dispose();
            btn_close.dispose();
            tab_3.dispose();
            tab_4.dispose();
            tab_5.dispose();
            tabMenu_hero.dispose();
            btn_get.dispose();
            super.dispose();
        
}
    }
}
