package  game.view.viewBase
{
    import starling.display.Image;
    import game.manager.AssetMgr;
    import starling.display.Sprite;
    import starling.textures.Texture;
    import starling.text.TextField;
    import starling.display.Button;
    import flash.geom.Rectangle;
    import com.utils.Constants;
    import feathers.controls.TextInput;
    import feathers.controls.renderers.DefaultListItemRenderer;

    public class VipRenderBase extends DefaultListItemRenderer
    {
        public var txt_vip:TextField;
        public var txt_vipLevel1:TextField;
        public var txt_vipLevel2:TextField;
        public var txt_des17:TextField;
        public var txt_best:TextField;
        public var txt_des5:TextField;
        public var txt_des10:TextField;
        public var txt_speed:TextField;
        public var txt_des6:TextField;
        public var txt_des2:TextField;
        public var txt_day:TextField;
        public var txt_des7:TextField;
        public var txt_chat:TextField;
        public var txt_des8:TextField;
        public var txt_des9:TextField;
        public var txt_des13:TextField;
        public var txt_des15:TextField;
        public var txt_tired:TextField;
        public var txt_des14:TextField;
        public var txt_des16:TextField;
        public var txt_jingji:TextField;

        public function VipRenderBase()
        {
            var texture:Texture;
            var textField:TextField;
            var input_txt:TextInput;
            var image:Image;
            var button:Button;
            var assetMgr:AssetMgr = AssetMgr.instance;
            texture =assetMgr.getTexture('ui_wenzi_dengjitequan');
            image = new Image(texture);
            image.x = 347;
            image.y = 10;
            image.width = 103;
            image.height = 29;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            texture =assetMgr.getTexture('ui_wenzi_vip_ziti');
            image = new Image(texture);
            image.x = 250;
            image.y = 13;
            image.width = 54;
            image.height = 23;
            image.touchable = false;
            image.smoothing= Constants.smoothing;
            this.addQuiackChild(image);
            txt_vip = new TextField(104,38,'','',26,0xFFFF00,false);
            txt_vip.touchable = false;
            txt_vip.hAlign= 'center';
            txt_vip.text= '0';
            txt_vip.x = 273;
            this.addQuiackChild(txt_vip);
            txt_vipLevel1 = new TextField(75,30,'','',20,0xECAA3A,false);
            txt_vipLevel1.touchable = false;
            txt_vipLevel1.hAlign= 'left';
            txt_vipLevel1.text= 'vip1';
            txt_vipLevel1.x = 18;
            txt_vipLevel1.y = 51;
            this.addQuiackChild(txt_vipLevel1);
            txt_vipLevel2 = new TextField(184,30,'','',20,0xECAA3A,false);
            txt_vipLevel2.touchable = false;
            txt_vipLevel2.hAlign= 'left';
            txt_vipLevel2.text= '';
            txt_vipLevel2.x = 18;
            txt_vipLevel2.y = 91;
            this.addQuiackChild(txt_vipLevel2);
            txt_des17 = new TextField(75,33,'','',22,0xF4FC11,false);
            txt_des17.touchable = false;
            txt_des17.hAlign= 'left';
            txt_des17.text= '豪华';
            txt_des17.x = 80;
            txt_des17.y = 49;
            this.addQuiackChild(txt_des17);
            txt_best = new TextField(400,30,'','',16,0xECAA3A,false);
            txt_best.touchable = false;
            txt_best.hAlign= 'left';
            txt_best.text= '';
            txt_best.x = 204;
            txt_best.y = 51;
            this.addQuiackChild(txt_best);
            txt_des5 = new TextField(171,30,'','',20,0xECAA3A,false);
            txt_des5.touchable = false;
            txt_des5.hAlign= 'left';
            txt_des5.text= '战斗加速提升至';
            txt_des5.x = 18;
            txt_des5.y = 141;
            this.addQuiackChild(txt_des5);
            txt_des10 = new TextField(75,30,'','',20,0x66FF00,false);
            txt_des10.touchable = false;
            txt_des10.hAlign= 'left';
            txt_des10.text= '每日';
            txt_des10.x = 18;
            txt_des10.y = 215;
            this.addQuiackChild(txt_des10);
            txt_speed = new TextField(75,30,'','',20,0xFFFF00,false);
            txt_speed.touchable = false;
            txt_speed.hAlign= 'center';
            txt_speed.text= '';
            txt_speed.x = 166;
            txt_speed.y = 141;
            this.addQuiackChild(txt_speed);
            txt_des6 = new TextField(75,30,'','',20,0xECAA3A,false);
            txt_des6.touchable = false;
            txt_des6.hAlign= 'left';
            txt_des6.text= '倍速。';
            txt_des6.x = 238;
            txt_des6.y = 141;
            this.addQuiackChild(txt_des6);
            txt_des2 = new TextField(75,30,'','',20,0xECAA3A,false);
            txt_des2.touchable = false;
            txt_des2.hAlign= 'left';
            txt_des2.text= '大礼包';
            txt_des2.x = 131;
            txt_des2.y = 51;
            this.addQuiackChild(txt_des2);
            txt_day = new TextField(400,55,'','',16,0xECAA3A,false);
            txt_day.touchable = false;
            txt_day.hAlign= 'left';
            txt_day.text= '';
            txt_day.x = 205;
            txt_day.y = 88;
            this.addQuiackChild(txt_day);
            txt_des7 = new TextField(171,30,'','',20,0xECAA3A,false);
            txt_des7.touchable = false;
            txt_des7.hAlign= 'left';
            txt_des7.text= '聊天显示缩短为';
            txt_des7.x = 18;
            txt_des7.y = 177;
            this.addQuiackChild(txt_des7);
            txt_chat = new TextField(75,30,'','',20,0xFFFF00,false);
            txt_chat.touchable = false;
            txt_chat.hAlign= 'center';
            txt_chat.text= '';
            txt_chat.x = 166;
            txt_chat.y = 178;
            this.addQuiackChild(txt_chat);
            txt_des8 = new TextField(75,30,'','',20,0xECAA3A,false);
            txt_des8.touchable = false;
            txt_des8.hAlign= 'left';
            txt_des8.text= '秒。';
            txt_des8.x = 238;
            txt_des8.y = 178;
            this.addQuiackChild(txt_des8);
            txt_des9 = new TextField(106,30,'','',20,0xECAA3A,false);
            txt_des9.touchable = false;
            txt_des9.hAlign= 'right';
            txt_des9.text= '可以购买：';
            txt_des9.x = 65;
            txt_des9.y = 214;
            this.addQuiackChild(txt_des9);
            txt_des13 = new TextField(101,30,'','',20,0xECAA3A,false);
            txt_des13.touchable = false;
            txt_des13.hAlign= 'left';
            txt_des13.text= '疲劳值';
            txt_des13.x = 183;
            txt_des13.y = 215;
            this.addQuiackChild(txt_des13);
            txt_des15 = new TextField(75,30,'','',20,0xECAA3A,false);
            txt_des15.touchable = false;
            txt_des15.hAlign= 'left';
            txt_des15.text= '次。';
            txt_des15.x = 293;
            txt_des15.y = 215;
            this.addQuiackChild(txt_des15);
            txt_tired = new TextField(75,30,'','',20,0xFFFF00,false);
            txt_tired.touchable = false;
            txt_tired.hAlign= 'center';
            txt_tired.text= '';
            txt_tired.x = 232;
            txt_tired.y = 215;
            this.addQuiackChild(txt_tired);
            txt_des14 = new TextField(105,30,'','',20,0xECAA3A,false);
            txt_des14.touchable = false;
            txt_des14.hAlign= 'right';
            txt_des14.text= '竞技场挑战';
            txt_des14.x = 330;
            txt_des14.y = 215;
            this.addQuiackChild(txt_des14);
            txt_des16 = new TextField(50,30,'','',20,0xECAA3A,false);
            txt_des16.touchable = false;
            txt_des16.hAlign= 'left';
            txt_des16.text= '次。';
            txt_des16.x = 478;
            txt_des16.y = 215;
            this.addQuiackChild(txt_des16);
            txt_jingji = new TextField(75,30,'','',20,0xFFFF00,false);
            txt_jingji.touchable = false;
            txt_jingji.hAlign= 'center';
            txt_jingji.text= '';
            txt_jingji.x = 422;
            txt_jingji.y = 215;
            this.addQuiackChild(txt_jingji);
        }
    }
}
