package game.view.FeedBack {
    import com.dialog.Dialog;
    import com.utils.Constants;

    import game.manager.AssetMgr;

    import starling.display.Button;
    import starling.display.Image;
    import starling.display.QuadBatch;
    import starling.text.TextField;
    import starling.textures.Texture;

    public class FeedBackDlgBase extends Dialog {
        public var suggsetionImage:Image;
        public var suggestionTxt:TextField;
        public var bugImage:Image;
        public var bugTxt:TextField;
        public var tips1Txt:TextField;
        public var tips2Txt:TextField;
        public var titleTxt:TextField;
        public var closeButton:Button;
        public var submitButton:Button;
        public var submitImage:Image;

        private var quadBatch:QuadBatch;

        public function FeedBackDlgBase() {
            quadBatch = new QuadBatch();
            this.addQuiackChild(quadBatch);
            var ui_gongyong_yibanmubanhentiao0152Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao0152Image:Image = new Image(ui_gongyong_yibanmubanhentiao0152Texture);
            ui_gongyong_yibanmubanhentiao0152Image.x = 0;
            ui_gongyong_yibanmubanhentiao0152Image.y = 152;
            ui_gongyong_yibanmubanhentiao0152Image.width = 490;
            ui_gongyong_yibanmubanhentiao0152Image.height = 73;
            ui_gongyong_yibanmubanhentiao0152Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao0152Image.touchable = false;
            quadBatch.addImage(ui_gongyong_yibanmubanhentiao0152Image);
            var ui_gongyong_yibanmubanhentiao696152Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao696152Image:Image = new Image(ui_gongyong_yibanmubanhentiao696152Texture);
            ui_gongyong_yibanmubanhentiao696152Image.x = 696;
            ui_gongyong_yibanmubanhentiao696152Image.y = 152;
            ui_gongyong_yibanmubanhentiao696152Image.width = 490;
            ui_gongyong_yibanmubanhentiao696152Image.height = 73;
            ui_gongyong_yibanmubanhentiao696152Image.scaleX = -1;
            ui_gongyong_yibanmubanhentiao696152Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao696152Image.touchable = false;
            quadBatch.addImage(ui_gongyong_yibanmubanhentiao696152Image);
            var ui_gongyong_yibanmubanhentiao0224Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao0224Image:Image = new Image(ui_gongyong_yibanmubanhentiao0224Texture);
            ui_gongyong_yibanmubanhentiao0224Image.x = 0;
            ui_gongyong_yibanmubanhentiao0224Image.y = 224;
            ui_gongyong_yibanmubanhentiao0224Image.width = 490;
            ui_gongyong_yibanmubanhentiao0224Image.height = 73;
            ui_gongyong_yibanmubanhentiao0224Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao0224Image.touchable = false;
            quadBatch.addImage(ui_gongyong_yibanmubanhentiao0224Image);
            var ui_gongyong_yibanmubanhentiao696224Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao696224Image:Image = new Image(ui_gongyong_yibanmubanhentiao696224Texture);
            ui_gongyong_yibanmubanhentiao696224Image.x = 696;
            ui_gongyong_yibanmubanhentiao696224Image.y = 224;
            ui_gongyong_yibanmubanhentiao696224Image.width = 490;
            ui_gongyong_yibanmubanhentiao696224Image.height = 73;
            ui_gongyong_yibanmubanhentiao696224Image.scaleX = -1;
            ui_gongyong_yibanmubanhentiao696224Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao696224Image.touchable = false;
            quadBatch.addImage(ui_gongyong_yibanmubanhentiao696224Image);
            var ui_gongyong_yibanmubanhentiao0296Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao0296Image:Image = new Image(ui_gongyong_yibanmubanhentiao0296Texture);
            ui_gongyong_yibanmubanhentiao0296Image.x = 0;
            ui_gongyong_yibanmubanhentiao0296Image.y = 296;
            ui_gongyong_yibanmubanhentiao0296Image.width = 490;
            ui_gongyong_yibanmubanhentiao0296Image.height = 73;
            ui_gongyong_yibanmubanhentiao0296Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao0296Image.touchable = false;
            quadBatch.addImage(ui_gongyong_yibanmubanhentiao0296Image);
            var ui_gongyong_yibanmubanhentiao696296Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao696296Image:Image = new Image(ui_gongyong_yibanmubanhentiao696296Texture);
            ui_gongyong_yibanmubanhentiao696296Image.x = 696;
            ui_gongyong_yibanmubanhentiao696296Image.y = 296;
            ui_gongyong_yibanmubanhentiao696296Image.width = 490;
            ui_gongyong_yibanmubanhentiao696296Image.height = 73;
            ui_gongyong_yibanmubanhentiao696296Image.scaleX = -1;
            ui_gongyong_yibanmubanhentiao696296Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao696296Image.touchable = false;
            quadBatch.addImage(ui_gongyong_yibanmubanhentiao696296Image);
            var ui_gongyong_yibanmubanhentiao0368Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao0368Image:Image = new Image(ui_gongyong_yibanmubanhentiao0368Texture);
            ui_gongyong_yibanmubanhentiao0368Image.x = 0;
            ui_gongyong_yibanmubanhentiao0368Image.y = 368;
            ui_gongyong_yibanmubanhentiao0368Image.width = 490;
            ui_gongyong_yibanmubanhentiao0368Image.height = 73;
            ui_gongyong_yibanmubanhentiao0368Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao0368Image.touchable = false;
            quadBatch.addImage(ui_gongyong_yibanmubanhentiao0368Image);
            var ui_gongyong_yibanmubanhentiao696368Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao696368Image:Image = new Image(ui_gongyong_yibanmubanhentiao696368Texture);
            ui_gongyong_yibanmubanhentiao696368Image.x = 696;
            ui_gongyong_yibanmubanhentiao696368Image.y = 368;
            ui_gongyong_yibanmubanhentiao696368Image.width = 490;
            ui_gongyong_yibanmubanhentiao696368Image.height = 73;
            ui_gongyong_yibanmubanhentiao696368Image.scaleX = -1;
            ui_gongyong_yibanmubanhentiao696368Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao696368Image.touchable = false;
            quadBatch.addImage(ui_gongyong_yibanmubanhentiao696368Image);
            var ui_gongyong_yibanmubanhentiao08Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao08Image:Image = new Image(ui_gongyong_yibanmubanhentiao08Texture);
            ui_gongyong_yibanmubanhentiao08Image.x = 0;
            ui_gongyong_yibanmubanhentiao08Image.y = 8;
            ui_gongyong_yibanmubanhentiao08Image.width = 490;
            ui_gongyong_yibanmubanhentiao08Image.height = 73;
            ui_gongyong_yibanmubanhentiao08Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao08Image.touchable = false;
            quadBatch.addImage(ui_gongyong_yibanmubanhentiao08Image);
            var ui_gongyong_yibanmubanhentiao6968Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao6968Image:Image = new Image(ui_gongyong_yibanmubanhentiao6968Texture);
            ui_gongyong_yibanmubanhentiao6968Image.x = 696;
            ui_gongyong_yibanmubanhentiao6968Image.y = 8;
            ui_gongyong_yibanmubanhentiao6968Image.width = 490;
            ui_gongyong_yibanmubanhentiao6968Image.height = 73;
            ui_gongyong_yibanmubanhentiao6968Image.scaleX = -1;
            ui_gongyong_yibanmubanhentiao6968Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao6968Image.touchable = false;
            quadBatch.addImage(ui_gongyong_yibanmubanhentiao6968Image);
            var ui_gongyong_yibanmubanhentiao080Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao080Image:Image = new Image(ui_gongyong_yibanmubanhentiao080Texture);
            ui_gongyong_yibanmubanhentiao080Image.x = 0;
            ui_gongyong_yibanmubanhentiao080Image.y = 80;
            ui_gongyong_yibanmubanhentiao080Image.width = 490;
            ui_gongyong_yibanmubanhentiao080Image.height = 73;
            ui_gongyong_yibanmubanhentiao080Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao080Image.touchable = false;
            quadBatch.addImage(ui_gongyong_yibanmubanhentiao080Image);
            var ui_gongyong_yibanmubanhentiao69680Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao69680Image:Image = new Image(ui_gongyong_yibanmubanhentiao69680Texture);
            ui_gongyong_yibanmubanhentiao69680Image.x = 696;
            ui_gongyong_yibanmubanhentiao69680Image.y = 80;
            ui_gongyong_yibanmubanhentiao69680Image.width = 490;
            ui_gongyong_yibanmubanhentiao69680Image.height = 73;
            ui_gongyong_yibanmubanhentiao69680Image.scaleX = -1;
            ui_gongyong_yibanmubanhentiao69680Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao69680Image.touchable = false;
            quadBatch.addImage(ui_gongyong_yibanmubanhentiao69680Image);
            var ui_Buyingdiamond_title2230Texture:Texture = AssetMgr.instance.getTexture('ui_Buyingdiamond_title');
            var ui_Buyingdiamond_title2230Image:Image = new Image(ui_Buyingdiamond_title2230Texture);
            ui_Buyingdiamond_title2230Image.x = 223;
            ui_Buyingdiamond_title2230Image.y = 0;
            ui_Buyingdiamond_title2230Image.width = 262;
            ui_Buyingdiamond_title2230Image.height = 80;
            ui_Buyingdiamond_title2230Image.smoothing = Constants.smoothing;
            ui_Buyingdiamond_title2230Image.touchable = false;
            quadBatch.addImage(ui_Buyingdiamond_title2230Image);
            var ui_gongyong_wupingkuang_baozaodibian2_hei10288Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_wupingkuang_baozaodibian2_hei');
            var ui_gongyong_wupingkuang_baozaodibian2_hei10288Image:Image = new Image(ui_gongyong_wupingkuang_baozaodibian2_hei10288Texture);
            ui_gongyong_wupingkuang_baozaodibian2_hei10288Image.x = 102;
            ui_gongyong_wupingkuang_baozaodibian2_hei10288Image.y = 88;
            ui_gongyong_wupingkuang_baozaodibian2_hei10288Image.width = 534;
            ui_gongyong_wupingkuang_baozaodibian2_hei10288Image.height = 47;
            ui_gongyong_wupingkuang_baozaodibian2_hei10288Image.smoothing = Constants.smoothing;
            ui_gongyong_wupingkuang_baozaodibian2_hei10288Image.touchable = false;
            quadBatch.addImage(ui_gongyong_wupingkuang_baozaodibian2_hei10288Image);
            var ui_gongyong_wupingkuang_baozaodibian3_hei101116Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_wupingkuang_baozaodibian3_hei');
            var ui_gongyong_wupingkuang_baozaodibian3_hei101116Image:Image = new Image(ui_gongyong_wupingkuang_baozaodibian3_hei101116Texture);
            ui_gongyong_wupingkuang_baozaodibian3_hei101116Image.x = 101;
            ui_gongyong_wupingkuang_baozaodibian3_hei101116Image.y = 116;
            ui_gongyong_wupingkuang_baozaodibian3_hei101116Image.width = 535;
            ui_gongyong_wupingkuang_baozaodibian3_hei101116Image.height = 211;
            ui_gongyong_wupingkuang_baozaodibian3_hei101116Image.smoothing = Constants.smoothing;
            ui_gongyong_wupingkuang_baozaodibian3_hei101116Image.touchable = false;
            quadBatch.addImage(ui_gongyong_wupingkuang_baozaodibian3_hei101116Image);
            var ui_gongyong_wupingkuang_baozaodibian2_hei102361Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_wupingkuang_baozaodibian2_hei');
            var ui_gongyong_wupingkuang_baozaodibian2_hei102361Image:Image = new Image(ui_gongyong_wupingkuang_baozaodibian2_hei102361Texture);
            ui_gongyong_wupingkuang_baozaodibian2_hei102361Image.x = 102;
            ui_gongyong_wupingkuang_baozaodibian2_hei102361Image.y = 361;
            ui_gongyong_wupingkuang_baozaodibian2_hei102361Image.width = 534;
            ui_gongyong_wupingkuang_baozaodibian2_hei102361Image.height = 47;
            ui_gongyong_wupingkuang_baozaodibian2_hei102361Image.scaleY = -1;
            ui_gongyong_wupingkuang_baozaodibian2_hei102361Image.smoothing = Constants.smoothing;
            ui_gongyong_wupingkuang_baozaodibian2_hei102361Image.touchable = false;
            quadBatch.addImage(ui_gongyong_wupingkuang_baozaodibian2_hei102361Image);
            var ui_gongyong_wupingkuang_baozaodibian_hei611100Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_wupingkuang_baozaodibian_hei');
            var ui_gongyong_wupingkuang_baozaodibian_hei611100Image:Image = new Image(ui_gongyong_wupingkuang_baozaodibian_hei611100Texture);
            ui_gongyong_wupingkuang_baozaodibian_hei611100Image.x = 611;
            ui_gongyong_wupingkuang_baozaodibian_hei611100Image.y = 100;
            ui_gongyong_wupingkuang_baozaodibian_hei611100Image.width = 40;
            ui_gongyong_wupingkuang_baozaodibian_hei611100Image.height = 261;
            ui_gongyong_wupingkuang_baozaodibian_hei611100Image.smoothing = Constants.smoothing;
            ui_gongyong_wupingkuang_baozaodibian_hei611100Image.touchable = false;
            quadBatch.addImage(ui_gongyong_wupingkuang_baozaodibian_hei611100Image);
            var ui_gongyong_wupingkuang_baozaodibian1_hei649330Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_wupingkuang_baozaodibian1_hei');
            var ui_gongyong_wupingkuang_baozaodibian1_hei649330Image:Image = new Image(ui_gongyong_wupingkuang_baozaodibian1_hei649330Texture);
            ui_gongyong_wupingkuang_baozaodibian1_hei649330Image.x = 649;
            ui_gongyong_wupingkuang_baozaodibian1_hei649330Image.y = 330;
            ui_gongyong_wupingkuang_baozaodibian1_hei649330Image.width = 20;
            ui_gongyong_wupingkuang_baozaodibian1_hei649330Image.height = 242;
            ui_gongyong_wupingkuang_baozaodibian1_hei649330Image.scaleX = -1;
            ui_gongyong_wupingkuang_baozaodibian1_hei649330Image.scaleY = -1;
            ui_gongyong_wupingkuang_baozaodibian1_hei649330Image.smoothing = Constants.smoothing;
            ui_gongyong_wupingkuang_baozaodibian1_hei649330Image.touchable = false;
            quadBatch.addImage(ui_gongyong_wupingkuang_baozaodibian1_hei649330Image);
            var ui_Feedback_button_Bottom8989Texture:Texture = AssetMgr.instance.getTexture('ui_Feedback_button_Bottom');
            var ui_Feedback_button_Bottom8989Image:Image = new Image(ui_Feedback_button_Bottom8989Texture);
            ui_Feedback_button_Bottom8989Image.x = 89;
            ui_Feedback_button_Bottom8989Image.y = 89;
            ui_Feedback_button_Bottom8989Image.width = 20;
            ui_Feedback_button_Bottom8989Image.height = 274;
            ui_Feedback_button_Bottom8989Image.smoothing = Constants.smoothing;
            ui_Feedback_button_Bottom8989Image.touchable = false;
            quadBatch.addImage(ui_Feedback_button_Bottom8989Image);
            var ui_gongyong_yibanmubanhentiao0438Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao0438Image:Image = new Image(ui_gongyong_yibanmubanhentiao0438Texture);
            ui_gongyong_yibanmubanhentiao0438Image.x = 0;
            ui_gongyong_yibanmubanhentiao0438Image.y = 438;
            ui_gongyong_yibanmubanhentiao0438Image.width = 490;
            ui_gongyong_yibanmubanhentiao0438Image.height = 73;
            ui_gongyong_yibanmubanhentiao0438Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao0438Image.touchable = false;
            quadBatch.addImage(ui_gongyong_yibanmubanhentiao0438Image);
            var ui_gongyong_yibanmubanhentiao696438Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao696438Image:Image = new Image(ui_gongyong_yibanmubanhentiao696438Texture);
            ui_gongyong_yibanmubanhentiao696438Image.x = 696;
            ui_gongyong_yibanmubanhentiao696438Image.y = 438;
            ui_gongyong_yibanmubanhentiao696438Image.width = 490;
            ui_gongyong_yibanmubanhentiao696438Image.height = 73;
            ui_gongyong_yibanmubanhentiao696438Image.scaleX = -1;
            ui_gongyong_yibanmubanhentiao696438Image.smoothing = Constants.smoothing;
            ui_gongyong_yibanmubanhentiao696438Image.touchable = false;
            quadBatch.addImage(ui_gongyong_yibanmubanhentiao696438Image);
            var suggsetionTexture:Texture = AssetMgr.instance.getTexture('ui_Feedback_button1');
            suggsetionImage = new Image(suggsetionTexture);
            suggsetionImage.x = 47;
            suggsetionImage.y = 110;
            suggsetionImage.width = 50;
            suggsetionImage.height = 123;
            this.addQuiackChild(suggsetionImage);
            suggestionTxt = new TextField(31, 76, '', '', 22, 0xFFF6E3, false);
            suggestionTxt.touchable = false;
            suggestionTxt.hAlign = 'left';
            suggestionTxt.x = 57;
            suggestionTxt.y = 132;
            this.addQuiackChild(suggestionTxt);
            var bugTexture:Texture = AssetMgr.instance.getTexture('ui_Feedback_button2');
            bugImage = new Image(bugTexture);
            bugImage.x = 47;
            bugImage.y = 233;
            bugImage.width = 46;
            bugImage.height = 123;
            this.addQuiackChild(bugImage);
            bugTxt = new TextField(28, 95, '', '', 22, 0xFFF6E3, false);
            bugTxt.touchable = false;
            bugTxt.hAlign = 'left';
            bugTxt.x = 59;
            bugTxt.y = 245;
            this.addQuiackChild(bugTxt);
            tips1Txt = new TextField(620, 80, '', '', 20, 0xFFF6E3, false);
            tips1Txt.touchable = false;
            tips1Txt.hAlign = 'left';
            tips1Txt.x = 36;
            tips1Txt.y = 371;
            this.addQuiackChild(tips1Txt);
            tips2Txt = new TextField(400, 43, '', '', 20, 0x0033CC, false);
            tips2Txt.touchable = false;
            tips2Txt.hAlign = 'right';
            tips2Txt.x = 280;
            tips2Txt.y = 403;
            this.addQuiackChild(tips2Txt);
            titleTxt = new TextField(226, 46, '', '', 38, 0x363F3A, false);
            titleTxt.touchable = false;
            titleTxt.hAlign = 'center';
            titleTxt.x = 240;
            titleTxt.y = 20;
            this.addQuiackChild(titleTxt);
            var closeTexture:Texture = AssetMgr.instance.getTexture('ui_Buyingdiamond_button_guanbi');
            closeButton = new Button(closeTexture);
            closeButton.x = 591;
            closeButton.y = 16;
            this.addQuiackChild(closeButton);
            var submitTexture:Texture = AssetMgr.instance.getTexture('ui_button_tiebaomutouanjian');
            submitButton = new Button(submitTexture);
            submitButton.x = 278;
            submitButton.y = 444;
            this.addQuiackChild(submitButton);
            submitTexture = AssetMgr.instance.getTexture('ui_Feedback_submit');
            submitImage = new Image(submitTexture);
            submitImage.x = 308;
            submitImage.y = 458;
            submitImage.width = 88;
            submitImage.height = 40;
            this.addQuiackChild(submitImage);

        }

        override public function dispose():void {
            closeButton.dispose();
            submitButton.dispose();
            super.dispose();

        }

    }
}
