package game.view.notice {
    import com.dialog.Dialog;
    import com.utils.Constants;

    import flash.geom.Rectangle;

    import game.manager.AssetMgr;

    import starling.display.Button;
    import starling.display.Image;
    import starling.text.TextField;
    import starling.textures.Texture;

    public class NoticeDlgBase extends Dialog {
        public var closeButton:Button;
        public var titleTxt:TextField;
        public var infoTxt:TextField;

        public function NoticeDlgBase() {
            var ui_Announcement_Baseboard52263Texture:Texture = AssetMgr.instance.getTexture('ui_Announcement_Baseboard5');
            var ui_Announcement_Baseboard52263Image:Image = new Image(ui_Announcement_Baseboard52263Texture);
            ui_Announcement_Baseboard52263Image.x = 22;
            ui_Announcement_Baseboard52263Image.y = 63;
            ui_Announcement_Baseboard52263Image.width = 781;
            ui_Announcement_Baseboard52263Image.height = 515;
            ui_Announcement_Baseboard52263Image.smoothing = Constants.smoothing;
            ui_Announcement_Baseboard52263Image.touchable = false;
            this.addQuiackChild(ui_Announcement_Baseboard52263Image);
            var ui_Announcement_Baseboard48552Texture:Texture = AssetMgr.instance.getTexture('ui_Announcement_Baseboard4');
            var ui_Announcement_Baseboard48552Image:Image = new Image(ui_Announcement_Baseboard48552Texture);
            ui_Announcement_Baseboard48552Image.x = 8;
            ui_Announcement_Baseboard48552Image.y = 552;
            ui_Announcement_Baseboard48552Image.width = 67;
            ui_Announcement_Baseboard48552Image.height = 41;
            ui_Announcement_Baseboard48552Image.smoothing = Constants.smoothing;
            ui_Announcement_Baseboard48552Image.touchable = false;
            this.addQuiackChild(ui_Announcement_Baseboard48552Image);
            var ui_Announcement_Baseboard38100Texture:Texture = AssetMgr.instance.getTexture('ui_Announcement_Baseboard3');
            var ui_Announcement_Baseboard38100Image:Image = new Image(ui_Announcement_Baseboard38100Texture);
            ui_Announcement_Baseboard38100Image.x = 8;
            ui_Announcement_Baseboard38100Image.y = 100;
            ui_Announcement_Baseboard38100Image.width = 19;
            ui_Announcement_Baseboard38100Image.height = 453;
            ui_Announcement_Baseboard38100Image.smoothing = Constants.smoothing;
            ui_Announcement_Baseboard38100Image.touchable = false;
            this.addQuiackChild(ui_Announcement_Baseboard38100Image);
            var ui_Announcement_Baseboard29254Texture:Texture = AssetMgr.instance.getTexture('ui_Announcement_Baseboard2');
            var ui_Announcement_Baseboard29254Image:Image = new Image(ui_Announcement_Baseboard29254Texture);
            ui_Announcement_Baseboard29254Image.x = 92;
            ui_Announcement_Baseboard29254Image.y = 54;
            ui_Announcement_Baseboard29254Image.width = 648;
            ui_Announcement_Baseboard29254Image.height = 30;
            ui_Announcement_Baseboard29254Image.smoothing = Constants.smoothing;
            ui_Announcement_Baseboard29254Image.touchable = false;
            this.addQuiackChild(ui_Announcement_Baseboard29254Image);
            var ui_Announcement_Baseboard1053Texture:Texture = AssetMgr.instance.getTexture('ui_Announcement_Baseboard1');
            var ui_Announcement_Baseboard1053Image:Image = new Image(ui_Announcement_Baseboard1053Texture);
            ui_Announcement_Baseboard1053Image.x = 0;
            ui_Announcement_Baseboard1053Image.y = 53;
            ui_Announcement_Baseboard1053Image.width = 145;
            ui_Announcement_Baseboard1053Image.height = 66;
            ui_Announcement_Baseboard1053Image.smoothing = Constants.smoothing;
            ui_Announcement_Baseboard1053Image.touchable = false;
            this.addQuiackChild(ui_Announcement_Baseboard1053Image);
            var ui_Announcement_Baseboard4818552Texture:Texture = AssetMgr.instance.getTexture('ui_Announcement_Baseboard4');
            var ui_Announcement_Baseboard4818552Image:Image = new Image(ui_Announcement_Baseboard4818552Texture);
            ui_Announcement_Baseboard4818552Image.x = 818;
            ui_Announcement_Baseboard4818552Image.y = 552;
            ui_Announcement_Baseboard4818552Image.width = 67;
            ui_Announcement_Baseboard4818552Image.height = 41;
            ui_Announcement_Baseboard4818552Image.scaleX = -1;
            ui_Announcement_Baseboard4818552Image.smoothing = Constants.smoothing;
            ui_Announcement_Baseboard4818552Image.touchable = false;
            this.addQuiackChild(ui_Announcement_Baseboard4818552Image);
            var ui_Announcement_Baseboard3818100Texture:Texture = AssetMgr.instance.getTexture('ui_Announcement_Baseboard3');
            var ui_Announcement_Baseboard3818100Image:Image = new Image(ui_Announcement_Baseboard3818100Texture);
            ui_Announcement_Baseboard3818100Image.x = 818;
            ui_Announcement_Baseboard3818100Image.y = 100;
            ui_Announcement_Baseboard3818100Image.width = 19;
            ui_Announcement_Baseboard3818100Image.height = 453;
            ui_Announcement_Baseboard3818100Image.scaleX = -1;
            ui_Announcement_Baseboard3818100Image.smoothing = Constants.smoothing;
            ui_Announcement_Baseboard3818100Image.touchable = false;
            this.addQuiackChild(ui_Announcement_Baseboard3818100Image);
            var ui_Announcement_Baseboard182853Texture:Texture = AssetMgr.instance.getTexture('ui_Announcement_Baseboard1');
            var ui_Announcement_Baseboard182853Image:Image = new Image(ui_Announcement_Baseboard182853Texture);
            ui_Announcement_Baseboard182853Image.x = 828;
            ui_Announcement_Baseboard182853Image.y = 53;
            ui_Announcement_Baseboard182853Image.width = 145;
            ui_Announcement_Baseboard182853Image.height = 66;
            ui_Announcement_Baseboard182853Image.scaleX = -1;
            ui_Announcement_Baseboard182853Image.smoothing = Constants.smoothing;
            ui_Announcement_Baseboard182853Image.touchable = false;
            this.addQuiackChild(ui_Announcement_Baseboard182853Image);
            var ui_Announcement_Baseboard674556Texture:Texture = AssetMgr.instance.getTexture('ui_Announcement_Baseboard6');
            var ui_Announcement_Baseboard674556Image:Image = new Image(ui_Announcement_Baseboard674556Texture);
            ui_Announcement_Baseboard674556Image.x = 74;
            ui_Announcement_Baseboard674556Image.y = 556;
            ui_Announcement_Baseboard674556Image.width = 678;
            ui_Announcement_Baseboard674556Image.height = 36;
            ui_Announcement_Baseboard674556Image.smoothing = Constants.smoothing;
            ui_Announcement_Baseboard674556Image.touchable = false;
            this.addQuiackChild(ui_Announcement_Baseboard674556Image);
            var ui_Announcement_title7956Texture:Texture = AssetMgr.instance.getTexture('ui_Announcement_title');
            var ui_Announcement_title7956Image:Image = new Image(ui_Announcement_title7956Texture);
            ui_Announcement_title7956Image.x = 79;
            ui_Announcement_title7956Image.y = 56;
            ui_Announcement_title7956Image.width = 665;
            ui_Announcement_title7956Image.height = 87;
            ui_Announcement_title7956Image.smoothing = Constants.smoothing;
            ui_Announcement_title7956Image.touchable = false;
            this.addQuiackChild(ui_Announcement_title7956Image);
            var ui_gongyong_mulianpaizi_lianzi_xiao6919Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_mulianpaizi_lianzi_xiao');
            var ui_gongyong_mulianpaizi_lianzi_xiao6919Image:Image = new Image(ui_gongyong_mulianpaizi_lianzi_xiao6919Texture);
            ui_gongyong_mulianpaizi_lianzi_xiao6919Image.x = 69;
            ui_gongyong_mulianpaizi_lianzi_xiao6919Image.y = -19;
            ui_gongyong_mulianpaizi_lianzi_xiao6919Image.width = 21;
            ui_gongyong_mulianpaizi_lianzi_xiao6919Image.height = 76;
            ui_gongyong_mulianpaizi_lianzi_xiao6919Image.smoothing = Constants.smoothing;
            ui_gongyong_mulianpaizi_lianzi_xiao6919Image.touchable = false;
            this.addQuiackChild(ui_gongyong_mulianpaizi_lianzi_xiao6919Image);
            var ui_gongyong_bumangdi_shangbianyikuaitie6254Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_bumangdi_shangbianyikuaitie');
            var ui_gongyong_bumangdi_shangbianyikuaitie6254Image:Image = new Image(ui_gongyong_bumangdi_shangbianyikuaitie6254Texture);
            ui_gongyong_bumangdi_shangbianyikuaitie6254Image.x = 62;
            ui_gongyong_bumangdi_shangbianyikuaitie6254Image.y = 54;
            ui_gongyong_bumangdi_shangbianyikuaitie6254Image.width = 30;
            ui_gongyong_bumangdi_shangbianyikuaitie6254Image.height = 21;
            ui_gongyong_bumangdi_shangbianyikuaitie6254Image.smoothing = Constants.smoothing;
            ui_gongyong_bumangdi_shangbianyikuaitie6254Image.touchable = false;
            this.addQuiackChild(ui_gongyong_bumangdi_shangbianyikuaitie6254Image);
            var ui_gongyong_mulianpaizi_lianzi_xiao75519Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_mulianpaizi_lianzi_xiao');
            var ui_gongyong_mulianpaizi_lianzi_xiao75519Image:Image = new Image(ui_gongyong_mulianpaizi_lianzi_xiao75519Texture);
            ui_gongyong_mulianpaizi_lianzi_xiao75519Image.x = 755;
            ui_gongyong_mulianpaizi_lianzi_xiao75519Image.y = -19;
            ui_gongyong_mulianpaizi_lianzi_xiao75519Image.width = 21;
            ui_gongyong_mulianpaizi_lianzi_xiao75519Image.height = 76;
            ui_gongyong_mulianpaizi_lianzi_xiao75519Image.scaleX = -1;
            ui_gongyong_mulianpaizi_lianzi_xiao75519Image.smoothing = Constants.smoothing;
            ui_gongyong_mulianpaizi_lianzi_xiao75519Image.touchable = false;
            this.addQuiackChild(ui_gongyong_mulianpaizi_lianzi_xiao75519Image);
            var ui_gongyong_bumangdi_shangbianyikuaitie76154Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_bumangdi_shangbianyikuaitie');
            var ui_gongyong_bumangdi_shangbianyikuaitie76154Image:Image = new Image(ui_gongyong_bumangdi_shangbianyikuaitie76154Texture);
            ui_gongyong_bumangdi_shangbianyikuaitie76154Image.x = 761;
            ui_gongyong_bumangdi_shangbianyikuaitie76154Image.y = 54;
            ui_gongyong_bumangdi_shangbianyikuaitie76154Image.width = 30;
            ui_gongyong_bumangdi_shangbianyikuaitie76154Image.height = 21;
            ui_gongyong_bumangdi_shangbianyikuaitie76154Image.scaleX = -1;
            ui_gongyong_bumangdi_shangbianyikuaitie76154Image.smoothing = Constants.smoothing;
            ui_gongyong_bumangdi_shangbianyikuaitie76154Image.touchable = false;
            this.addQuiackChild(ui_gongyong_bumangdi_shangbianyikuaitie76154Image);
            var ui_gongyong_bumangdi_shangbianyikuaitie64587Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_bumangdi_shangbianyikuaitie');
            var ui_gongyong_bumangdi_shangbianyikuaitie64587Image:Image = new Image(ui_gongyong_bumangdi_shangbianyikuaitie64587Texture);
            ui_gongyong_bumangdi_shangbianyikuaitie64587Image.x = 64;
            ui_gongyong_bumangdi_shangbianyikuaitie64587Image.y = 587;
            ui_gongyong_bumangdi_shangbianyikuaitie64587Image.width = 30;
            ui_gongyong_bumangdi_shangbianyikuaitie64587Image.height = 21;
            ui_gongyong_bumangdi_shangbianyikuaitie64587Image.scaleY = -1;
            ui_gongyong_bumangdi_shangbianyikuaitie64587Image.smoothing = Constants.smoothing;
            ui_gongyong_bumangdi_shangbianyikuaitie64587Image.touchable = false;
            this.addQuiackChild(ui_gongyong_bumangdi_shangbianyikuaitie64587Image);
            var ui_gongyong_bumangdi_shangbianyikuaitie763587Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_bumangdi_shangbianyikuaitie');
            var ui_gongyong_bumangdi_shangbianyikuaitie763587Image:Image = new Image(ui_gongyong_bumangdi_shangbianyikuaitie763587Texture);
            ui_gongyong_bumangdi_shangbianyikuaitie763587Image.x = 763;
            ui_gongyong_bumangdi_shangbianyikuaitie763587Image.y = 587;
            ui_gongyong_bumangdi_shangbianyikuaitie763587Image.width = 30;
            ui_gongyong_bumangdi_shangbianyikuaitie763587Image.height = 21;
            ui_gongyong_bumangdi_shangbianyikuaitie763587Image.scaleX = -1;
            ui_gongyong_bumangdi_shangbianyikuaitie763587Image.scaleY = -1;
            ui_gongyong_bumangdi_shangbianyikuaitie763587Image.smoothing = Constants.smoothing;
            ui_gongyong_bumangdi_shangbianyikuaitie763587Image.touchable = false;
            this.addQuiackChild(ui_gongyong_bumangdi_shangbianyikuaitie763587Image);
            var closeTexture:Texture = AssetMgr.instance.getTexture('ui_button_tiebaomutouanjian');
            closeButton = new Button(closeTexture);
            closeButton.x = 341;
            closeButton.y = 511;
            this.addQuiackChild(closeButton);
            closeButton.textBounds = new Rectangle(8, 15, 138, 36);
            closeButton.fontSize = 30;
            closeButton.fontColor = 0xF5E9C3;
            closeButton.fontBold = false;
            titleTxt = new TextField(412, 61, '', '', 40, 0x6A3509, false);
            titleTxt.touchable = false;
            titleTxt.hAlign = 'center';
            titleTxt.x = 228;
            titleTxt.y = 78;
            this.addQuiackChild(titleTxt);
            infoTxt = new TextField(722, 335, '', '', 20, 0x4D1F09, false);
            infoTxt.touchable = false;
            infoTxt.hAlign = 'left';
            infoTxt.x = 52;
            infoTxt.y = 159;
            this.addQuiackChild(infoTxt);
            var ui_gongyong_mulianpaizi_lianzi_xiao6990Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_mulianpaizi_lianzi_xiao');
            var ui_gongyong_mulianpaizi_lianzi_xiao6990Image:Image = new Image(ui_gongyong_mulianpaizi_lianzi_xiao6990Texture);
            ui_gongyong_mulianpaizi_lianzi_xiao6990Image.x = 69;
            ui_gongyong_mulianpaizi_lianzi_xiao6990Image.y = -90;
            ui_gongyong_mulianpaizi_lianzi_xiao6990Image.width = 21;
            ui_gongyong_mulianpaizi_lianzi_xiao6990Image.height = 76;
            ui_gongyong_mulianpaizi_lianzi_xiao6990Image.smoothing = Constants.smoothing;
            ui_gongyong_mulianpaizi_lianzi_xiao6990Image.touchable = false;
            this.addQuiackChild(ui_gongyong_mulianpaizi_lianzi_xiao6990Image);
            var ui_gongyong_mulianpaizi_lianzi_xiao75590Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_mulianpaizi_lianzi_xiao');
            var ui_gongyong_mulianpaizi_lianzi_xiao75590Image:Image = new Image(ui_gongyong_mulianpaizi_lianzi_xiao75590Texture);
            ui_gongyong_mulianpaizi_lianzi_xiao75590Image.x = 755;
            ui_gongyong_mulianpaizi_lianzi_xiao75590Image.y = -90;
            ui_gongyong_mulianpaizi_lianzi_xiao75590Image.width = 21;
            ui_gongyong_mulianpaizi_lianzi_xiao75590Image.height = 76;
            ui_gongyong_mulianpaizi_lianzi_xiao75590Image.scaleX = -1;
            ui_gongyong_mulianpaizi_lianzi_xiao75590Image.smoothing = Constants.smoothing;
            ui_gongyong_mulianpaizi_lianzi_xiao75590Image.touchable = false;
            this.addQuiackChild(ui_gongyong_mulianpaizi_lianzi_xiao75590Image);

        }

        override public function dispose():void {
            closeButton.dispose();
            super.dispose();

        }

    }
}