package game.view.PVP.ui {
    import com.components.TabButton;
    import com.components.TabMenu;

    import flash.geom.Rectangle;

    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;

    import game.base.JTPanel;
    import game.manager.AssetMgr;

    import starling.display.Button;
    import starling.display.Image;
    import starling.text.TextField;
    import starling.textures.Texture;
    import starling.textures.TextureSmoothing;

    public class JTUIPlayerRanksBackground extends JTPanel {
        public var btn_close:Button = null;
        public var img_mc_ranks:Image = null;
        public var img_sxxx:Image = null;
        public var tabbtn_regulation0:Button = null;
        public var txt_horn:TextField = null;
        public var txt_time:TextField = null;
        public var txt_rank:TextField = null;
        public var txt_money:TextField = null;
        public var btn_head:Button = null;
        public var txt_lvl_title:TextField = null;
        public var img_mc_progress:Image = null;
        public var scale_mc_progress:Scale9Image = null;
        public var txt_name:TextField = null;
        public var txt_fight:TextField = null;
        public var txt_pvp_count:TextField = null;
        public var txt_count:TextField = null;
        public var img_img_lvl:Image = null;
        public var tabbtn_pvp0:TabButton = null;
        public var tabbtn_fight1:TabButton = null;
        public var tabbtn_buy2:TabButton = null;
        public var menu_bars:TabMenu = null;
        public var img_mc_quality_1:Image = null;
        public var img_mc_quality_2:Image = null;
        public var img_mc_quality_3:Image = null;
        public var img_mc_quality_4:Image = null;
        public var img_mc_quality_5:Image = null;
        public var img_mc_quality_6:Image = null;
        public var textField:TextField;

        public function JTUIPlayerRanksBackground() {
            var txture_ui_gongyong_tielianpaizi35826:Texture = AssetMgr.instance.getTexture('ui_gongyong_tielianpaizi');
            var ui_gongyong_tielianpaizi35826img_2:Image = new Image(txture_ui_gongyong_tielianpaizi35826);
            ui_gongyong_tielianpaizi35826img_2.x = 358;
            ui_gongyong_tielianpaizi35826img_2.y = -25;
            ui_gongyong_tielianpaizi35826img_2.width = 244;
            ui_gongyong_tielianpaizi35826img_2.height = 137;
            ui_gongyong_tielianpaizi35826img_2.smoothing = TextureSmoothing.BILINEAR;
            ui_gongyong_tielianpaizi35826img_2.touchable = false;
            this.addQuiackChild(ui_gongyong_tielianpaizi35826img_2);
            var btn_close_txture:Texture = AssetMgr.instance.getTexture('ui_gongyong_tuichuanniiu');
            btn_close = new Button(btn_close_txture);
            btn_close.x = 829;
            btn_close.y = -44;
            this.addQuiackChild(btn_close);
            var txture_ui_gongyong_yibanmubanhentiao0110:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao0110img_3:Image = new Image(txture_ui_gongyong_yibanmubanhentiao0110);
            ui_gongyong_yibanmubanhentiao0110img_3.x = 0;
            ui_gongyong_yibanmubanhentiao0110img_3.y = 110;
            ui_gongyong_yibanmubanhentiao0110img_3.width = 490;
            ui_gongyong_yibanmubanhentiao0110img_3.height = 73;
            ui_gongyong_yibanmubanhentiao0110img_3.smoothing = TextureSmoothing.BILINEAR;
            ui_gongyong_yibanmubanhentiao0110img_3.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao0110img_3);
            var txture_ui_gongyong_yibanmubanhentiao960110:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao960110img_4:Image = new Image(txture_ui_gongyong_yibanmubanhentiao960110);
            ui_gongyong_yibanmubanhentiao960110img_4.x = 960;
            ui_gongyong_yibanmubanhentiao960110img_4.y = 110;
            ui_gongyong_yibanmubanhentiao960110img_4.width = 490;
            ui_gongyong_yibanmubanhentiao960110img_4.height = 73;
            ui_gongyong_yibanmubanhentiao960110img_4.scaleX = -1;
            ui_gongyong_yibanmubanhentiao960110img_4.smoothing = TextureSmoothing.BILINEAR;
            ui_gongyong_yibanmubanhentiao960110img_4.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao960110img_4);
            var txture_ui_gongyong_yibanmubanhentiao0183:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao0183img_5:Image = new Image(txture_ui_gongyong_yibanmubanhentiao0183);
            ui_gongyong_yibanmubanhentiao0183img_5.x = 0;
            ui_gongyong_yibanmubanhentiao0183img_5.y = 183;
            ui_gongyong_yibanmubanhentiao0183img_5.width = 490;
            ui_gongyong_yibanmubanhentiao0183img_5.height = 73;
            ui_gongyong_yibanmubanhentiao0183img_5.smoothing = TextureSmoothing.BILINEAR;
            ui_gongyong_yibanmubanhentiao0183img_5.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao0183img_5);
            var txture_ui_gongyong_yibanmubanhentiao960183:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao960183img_6:Image = new Image(txture_ui_gongyong_yibanmubanhentiao960183);
            ui_gongyong_yibanmubanhentiao960183img_6.x = 960;
            ui_gongyong_yibanmubanhentiao960183img_6.y = 183;
            ui_gongyong_yibanmubanhentiao960183img_6.width = 490;
            ui_gongyong_yibanmubanhentiao960183img_6.height = 73;
            ui_gongyong_yibanmubanhentiao960183img_6.scaleX = -1;
            ui_gongyong_yibanmubanhentiao960183img_6.smoothing = TextureSmoothing.BILINEAR;
            ui_gongyong_yibanmubanhentiao960183img_6.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao960183img_6);
            var txture_ui_gongyong_yibanmubanhentiao0256:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao0256img_7:Image = new Image(txture_ui_gongyong_yibanmubanhentiao0256);
            ui_gongyong_yibanmubanhentiao0256img_7.x = 0;
            ui_gongyong_yibanmubanhentiao0256img_7.y = 256;
            ui_gongyong_yibanmubanhentiao0256img_7.width = 490;
            ui_gongyong_yibanmubanhentiao0256img_7.height = 73;
            ui_gongyong_yibanmubanhentiao0256img_7.smoothing = TextureSmoothing.BILINEAR;
            ui_gongyong_yibanmubanhentiao0256img_7.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao0256img_7);
            var txture_ui_gongyong_yibanmubanhentiao960256:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao960256img_8:Image = new Image(txture_ui_gongyong_yibanmubanhentiao960256);
            ui_gongyong_yibanmubanhentiao960256img_8.x = 960;
            ui_gongyong_yibanmubanhentiao960256img_8.y = 256;
            ui_gongyong_yibanmubanhentiao960256img_8.width = 490;
            ui_gongyong_yibanmubanhentiao960256img_8.height = 73;
            ui_gongyong_yibanmubanhentiao960256img_8.scaleX = -1;
            ui_gongyong_yibanmubanhentiao960256img_8.smoothing = TextureSmoothing.BILINEAR;
            ui_gongyong_yibanmubanhentiao960256img_8.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao960256img_8);
            var txture_ui_gongyong_yibanmubanhentiao0329:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao0329img_9:Image = new Image(txture_ui_gongyong_yibanmubanhentiao0329);
            ui_gongyong_yibanmubanhentiao0329img_9.x = 0;
            ui_gongyong_yibanmubanhentiao0329img_9.y = 329;
            ui_gongyong_yibanmubanhentiao0329img_9.width = 490;
            ui_gongyong_yibanmubanhentiao0329img_9.height = 73;
            ui_gongyong_yibanmubanhentiao0329img_9.smoothing = TextureSmoothing.BILINEAR;
            ui_gongyong_yibanmubanhentiao0329img_9.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao0329img_9);
            var txture_ui_gongyong_yibanmubanhentiao960329:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao960329img_10:Image = new Image(txture_ui_gongyong_yibanmubanhentiao960329);
            ui_gongyong_yibanmubanhentiao960329img_10.x = 960;
            ui_gongyong_yibanmubanhentiao960329img_10.y = 329;
            ui_gongyong_yibanmubanhentiao960329img_10.width = 490;
            ui_gongyong_yibanmubanhentiao960329img_10.height = 73;
            ui_gongyong_yibanmubanhentiao960329img_10.scaleX = -1;
            ui_gongyong_yibanmubanhentiao960329img_10.smoothing = TextureSmoothing.BILINEAR;
            ui_gongyong_yibanmubanhentiao960329img_10.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao960329img_10);
            var txture_ui_gongyong_yibanmubanhentiao0402:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao0402img_11:Image = new Image(txture_ui_gongyong_yibanmubanhentiao0402);
            ui_gongyong_yibanmubanhentiao0402img_11.x = 0;
            ui_gongyong_yibanmubanhentiao0402img_11.y = 402;
            ui_gongyong_yibanmubanhentiao0402img_11.width = 490;
            ui_gongyong_yibanmubanhentiao0402img_11.height = 73;
            ui_gongyong_yibanmubanhentiao0402img_11.smoothing = TextureSmoothing.BILINEAR;
            ui_gongyong_yibanmubanhentiao0402img_11.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao0402img_11);
            var txture_ui_gongyong_yibanmubanhentiao960402:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao960402img_12:Image = new Image(txture_ui_gongyong_yibanmubanhentiao960402);
            ui_gongyong_yibanmubanhentiao960402img_12.x = 960;
            ui_gongyong_yibanmubanhentiao960402img_12.y = 402;
            ui_gongyong_yibanmubanhentiao960402img_12.width = 490;
            ui_gongyong_yibanmubanhentiao960402img_12.height = 73;
            ui_gongyong_yibanmubanhentiao960402img_12.scaleX = -1;
            ui_gongyong_yibanmubanhentiao960402img_12.smoothing = TextureSmoothing.BILINEAR;
            ui_gongyong_yibanmubanhentiao960402img_12.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao960402img_12);
            var txture_ui_gongyong_yibanmubanhentiao0475:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao0475img_13:Image = new Image(txture_ui_gongyong_yibanmubanhentiao0475);
            ui_gongyong_yibanmubanhentiao0475img_13.x = 0;
            ui_gongyong_yibanmubanhentiao0475img_13.y = 475;
            ui_gongyong_yibanmubanhentiao0475img_13.width = 490;
            ui_gongyong_yibanmubanhentiao0475img_13.height = 73;
            ui_gongyong_yibanmubanhentiao0475img_13.smoothing = TextureSmoothing.BILINEAR;
            ui_gongyong_yibanmubanhentiao0475img_13.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao0475img_13);
            var txture_ui_gongyong_yibanmubanhentiao960475:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao960475img_14:Image = new Image(txture_ui_gongyong_yibanmubanhentiao960475);
            ui_gongyong_yibanmubanhentiao960475img_14.x = 960;
            ui_gongyong_yibanmubanhentiao960475img_14.y = 475;
            ui_gongyong_yibanmubanhentiao960475img_14.width = 490;
            ui_gongyong_yibanmubanhentiao960475img_14.height = 73;
            ui_gongyong_yibanmubanhentiao960475img_14.scaleX = -1;
            ui_gongyong_yibanmubanhentiao960475img_14.smoothing = TextureSmoothing.BILINEAR;
            ui_gongyong_yibanmubanhentiao960475img_14.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao960475img_14);
            var txture_ui_gongyong_yibanmubanhentiao0548:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao0548img_15:Image = new Image(txture_ui_gongyong_yibanmubanhentiao0548);
            ui_gongyong_yibanmubanhentiao0548img_15.x = 0;
            ui_gongyong_yibanmubanhentiao0548img_15.y = 548;
            ui_gongyong_yibanmubanhentiao0548img_15.width = 490;
            ui_gongyong_yibanmubanhentiao0548img_15.height = 73;
            ui_gongyong_yibanmubanhentiao0548img_15.smoothing = TextureSmoothing.BILINEAR;
            ui_gongyong_yibanmubanhentiao0548img_15.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao0548img_15);
            var txture_ui_gongyong_yibanmubanhentiao960548:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao');
            var ui_gongyong_yibanmubanhentiao960548img_16:Image = new Image(txture_ui_gongyong_yibanmubanhentiao960548);
            ui_gongyong_yibanmubanhentiao960548img_16.x = 960;
            ui_gongyong_yibanmubanhentiao960548img_16.y = 548;
            ui_gongyong_yibanmubanhentiao960548img_16.width = 490;
            ui_gongyong_yibanmubanhentiao960548img_16.height = 73;
            ui_gongyong_yibanmubanhentiao960548img_16.scaleX = -1;
            ui_gongyong_yibanmubanhentiao960548img_16.smoothing = TextureSmoothing.BILINEAR;
            ui_gongyong_yibanmubanhentiao960548img_16.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao960548img_16);
            var txture_ui_gongyong_yibanmubanhentiao_di3899168:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao_di3');
            var ui_gongyong_yibanmubanhentiao_di3899168img_17:Image = new Image(txture_ui_gongyong_yibanmubanhentiao_di3899168);
            ui_gongyong_yibanmubanhentiao_di3899168img_17.x = 899;
            ui_gongyong_yibanmubanhentiao_di3899168img_17.y = 168;
            ui_gongyong_yibanmubanhentiao_di3899168img_17.width = 32;
            ui_gongyong_yibanmubanhentiao_di3899168img_17.height = 435;
            ui_gongyong_yibanmubanhentiao_di3899168img_17.smoothing = TextureSmoothing.BILINEAR;
            ui_gongyong_yibanmubanhentiao_di3899168img_17.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao_di3899168img_17);
            var txture_ui_gongyong_yibanmubanhentiao_di2354168:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao_di2');
            var ui_gongyong_yibanmubanhentiao_di2354168img_18:Image = new Image(txture_ui_gongyong_yibanmubanhentiao_di2354168);
            ui_gongyong_yibanmubanhentiao_di2354168img_18.x = 354;
            ui_gongyong_yibanmubanhentiao_di2354168img_18.y = 168;
            ui_gongyong_yibanmubanhentiao_di2354168img_18.width = 32;
            ui_gongyong_yibanmubanhentiao_di2354168img_18.height = 435;
            ui_gongyong_yibanmubanhentiao_di2354168img_18.smoothing = TextureSmoothing.BILINEAR;
            ui_gongyong_yibanmubanhentiao_di2354168img_18.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao_di2354168img_18);
            var txture_ui_gongyong_yibanmubanhentiao_di1374168:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao_di1');
            var ui_gongyong_yibanmubanhentiao_di1374168img_19:Image = new Image(txture_ui_gongyong_yibanmubanhentiao_di1374168);
            ui_gongyong_yibanmubanhentiao_di1374168img_19.x = 374;
            ui_gongyong_yibanmubanhentiao_di1374168img_19.y = 168;
            ui_gongyong_yibanmubanhentiao_di1374168img_19.width = 535;
            ui_gongyong_yibanmubanhentiao_di1374168img_19.height = 22;
            ui_gongyong_yibanmubanhentiao_di1374168img_19.smoothing = TextureSmoothing.BILINEAR;
            ui_gongyong_yibanmubanhentiao_di1374168img_19.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao_di1374168img_19);
            var txture_ui_gongyong_yibanmubanhentiao_di1374602:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao_di1');
            var ui_gongyong_yibanmubanhentiao_di1374602img_20:Image = new Image(txture_ui_gongyong_yibanmubanhentiao_di1374602);
            ui_gongyong_yibanmubanhentiao_di1374602img_20.x = 374;
            ui_gongyong_yibanmubanhentiao_di1374602img_20.y = 602;
            ui_gongyong_yibanmubanhentiao_di1374602img_20.width = 535;
            ui_gongyong_yibanmubanhentiao_di1374602img_20.height = 23;
            ui_gongyong_yibanmubanhentiao_di1374602img_20.scaleY = -1;
            ui_gongyong_yibanmubanhentiao_di1374602img_20.smoothing = TextureSmoothing.BILINEAR;
            ui_gongyong_yibanmubanhentiao_di1374602img_20.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao_di1374602img_20);
            var txture_mc_ranks:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao_di4');
            img_mc_ranks = new Image(txture_mc_ranks);
            img_mc_ranks.x = 368;
            img_mc_ranks.y = 173;
            img_mc_ranks.width = 549;
            img_mc_ranks.height = 422;
            this.addQuiackChild(img_mc_ranks);
            var txture_ui_background_intensify313119:Texture = AssetMgr.instance.getTexture('ui_background_intensify3');
            var ui_background_intensify313119img_21:Image = new Image(txture_ui_background_intensify313119);
            ui_background_intensify313119img_21.x = 13;
            ui_background_intensify313119img_21.y = 119;
            ui_background_intensify313119img_21.width = 934;
            ui_background_intensify313119img_21.height = 1;
            ui_background_intensify313119img_21.smoothing = TextureSmoothing.BILINEAR;
            ui_background_intensify313119img_21.touchable = false;
            this.addQuiackChild(ui_background_intensify313119img_21);
            var txture_ui_gongyong_bumangdi_shangbianyikuaitie358107:Texture = AssetMgr.instance.getTexture('ui_gongyong_bumangdi_shangbianyikuaitie');
            var ui_gongyong_bumangdi_shangbianyikuaitie358107img_22:Image = new Image(txture_ui_gongyong_bumangdi_shangbianyikuaitie358107);
            ui_gongyong_bumangdi_shangbianyikuaitie358107img_22.x = 358;
            ui_gongyong_bumangdi_shangbianyikuaitie358107img_22.y = 107;
            ui_gongyong_bumangdi_shangbianyikuaitie358107img_22.width = 30;
            ui_gongyong_bumangdi_shangbianyikuaitie358107img_22.height = 21;
            ui_gongyong_bumangdi_shangbianyikuaitie358107img_22.smoothing = TextureSmoothing.BILINEAR;
            ui_gongyong_bumangdi_shangbianyikuaitie358107img_22.touchable = false;
            this.addQuiackChild(ui_gongyong_bumangdi_shangbianyikuaitie358107img_22);
            var txture_ui_gongyong_bumangdi_shangbianyikuaitie602107:Texture = AssetMgr.instance.getTexture('ui_gongyong_bumangdi_shangbianyikuaitie');
            var ui_gongyong_bumangdi_shangbianyikuaitie602107img_23:Image = new Image(txture_ui_gongyong_bumangdi_shangbianyikuaitie602107);
            ui_gongyong_bumangdi_shangbianyikuaitie602107img_23.x = 602;
            ui_gongyong_bumangdi_shangbianyikuaitie602107img_23.y = 107;
            ui_gongyong_bumangdi_shangbianyikuaitie602107img_23.width = 30;
            ui_gongyong_bumangdi_shangbianyikuaitie602107img_23.height = 21;
            ui_gongyong_bumangdi_shangbianyikuaitie602107img_23.scaleX = -1;
            ui_gongyong_bumangdi_shangbianyikuaitie602107img_23.smoothing = TextureSmoothing.BILINEAR;
            ui_gongyong_bumangdi_shangbianyikuaitie602107img_23.touchable = false;
            this.addQuiackChild(ui_gongyong_bumangdi_shangbianyikuaitie602107img_23);
            var txture_ui_background_intensify313609:Texture = AssetMgr.instance.getTexture('ui_background_intensify3');
            var ui_background_intensify313609img_24:Image = new Image(txture_ui_background_intensify313609);
            ui_background_intensify313609img_24.x = 13;
            ui_background_intensify313609img_24.y = 609;
            ui_background_intensify313609img_24.width = 934;
            ui_background_intensify313609img_24.height = 1;
            ui_background_intensify313609img_24.smoothing = TextureSmoothing.BILINEAR;
            ui_background_intensify313609img_24.touchable = false;
            this.addQuiackChild(ui_background_intensify313609img_24);
            var txture_ui_wenzi_xinjingjichang41732:Texture = AssetMgr.instance.getTexture('ui_wenzi_xinjingjichang');
            var ui_wenzi_xinjingjichang41732img_25:Image = new Image(txture_ui_wenzi_xinjingjichang41732);
            ui_wenzi_xinjingjichang41732img_25.x = 417;
            ui_wenzi_xinjingjichang41732img_25.y = 32;
            ui_wenzi_xinjingjichang41732img_25.width = 133;
            ui_wenzi_xinjingjichang41732img_25.height = 44;
            ui_wenzi_xinjingjichang41732img_25.smoothing = TextureSmoothing.BILINEAR;
            ui_wenzi_xinjingjichang41732img_25.touchable = false;
            this.addQuiackChild(ui_wenzi_xinjingjichang41732img_25);
            var txture_ui_gongyong_yibanmubanhentiao_di3315171:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao_di3');
            var ui_gongyong_yibanmubanhentiao_di3315171img_26:Image = new Image(txture_ui_gongyong_yibanmubanhentiao_di3315171);
            ui_gongyong_yibanmubanhentiao_di3315171img_26.x = 315;
            ui_gongyong_yibanmubanhentiao_di3315171img_26.y = 171;
            ui_gongyong_yibanmubanhentiao_di3315171img_26.width = 32;
            ui_gongyong_yibanmubanhentiao_di3315171img_26.height = 355;
            ui_gongyong_yibanmubanhentiao_di3315171img_26.smoothing = TextureSmoothing.BILINEAR;
            ui_gongyong_yibanmubanhentiao_di3315171img_26.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao_di3315171img_26);
            var txture_ui_gongyong_yibanmubanhentiao_di222171:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao_di2');
            var ui_gongyong_yibanmubanhentiao_di222171img_27:Image = new Image(txture_ui_gongyong_yibanmubanhentiao_di222171);
            ui_gongyong_yibanmubanhentiao_di222171img_27.x = 22;
            ui_gongyong_yibanmubanhentiao_di222171img_27.y = 171;
            ui_gongyong_yibanmubanhentiao_di222171img_27.width = 32;
            ui_gongyong_yibanmubanhentiao_di222171img_27.height = 355;
            ui_gongyong_yibanmubanhentiao_di222171img_27.smoothing = TextureSmoothing.BILINEAR;
            ui_gongyong_yibanmubanhentiao_di222171img_27.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao_di222171img_27);
            var txture_ui_gongyong_yibanmubanhentiao_di140171:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao_di1');
            var ui_gongyong_yibanmubanhentiao_di140171img_28:Image = new Image(txture_ui_gongyong_yibanmubanhentiao_di140171);
            ui_gongyong_yibanmubanhentiao_di140171img_28.x = 40;
            ui_gongyong_yibanmubanhentiao_di140171img_28.y = 171;
            ui_gongyong_yibanmubanhentiao_di140171img_28.width = 295;
            ui_gongyong_yibanmubanhentiao_di140171img_28.height = 21;
            ui_gongyong_yibanmubanhentiao_di140171img_28.smoothing = TextureSmoothing.BILINEAR;
            ui_gongyong_yibanmubanhentiao_di140171img_28.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao_di140171img_28);
            var txture_ui_gongyong_yibanmubanhentiao_di140525:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao_di1');
            var ui_gongyong_yibanmubanhentiao_di140525img_29:Image = new Image(txture_ui_gongyong_yibanmubanhentiao_di140525);
            ui_gongyong_yibanmubanhentiao_di140525img_29.x = 40;
            ui_gongyong_yibanmubanhentiao_di140525img_29.y = 525;
            ui_gongyong_yibanmubanhentiao_di140525img_29.width = 295;
            ui_gongyong_yibanmubanhentiao_di140525img_29.height = 23;
            ui_gongyong_yibanmubanhentiao_di140525img_29.scaleY = -1;
            ui_gongyong_yibanmubanhentiao_di140525img_29.smoothing = TextureSmoothing.BILINEAR;
            ui_gongyong_yibanmubanhentiao_di140525img_29.touchable = false;
            this.addQuiackChild(ui_gongyong_yibanmubanhentiao_di140525img_29);
            var txture_sxxx:Texture = AssetMgr.instance.getTexture('ui_gongyong_yibanmubanhentiao_di4');
            img_sxxx = new Image(txture_sxxx);
            img_sxxx.x = 40;
            img_sxxx.y = 176;
            img_sxxx.width = 287;
            img_sxxx.height = 342;
            this.addQuiackChild(img_sxxx);
            var txture_ui_pvp_rongyuzhibiaozhi3044:Texture = AssetMgr.instance.getTexture('ui_pvp_rongyuzhibiaozhi');
            var ui_pvp_rongyuzhibiaozhi3044img_30:Image = new Image(txture_ui_pvp_rongyuzhibiaozhi3044);
            ui_pvp_rongyuzhibiaozhi3044img_30.x = 30;
            ui_pvp_rongyuzhibiaozhi3044img_30.y = 44;
            ui_pvp_rongyuzhibiaozhi3044img_30.width = 31;
            ui_pvp_rongyuzhibiaozhi3044img_30.height = 43;
            ui_pvp_rongyuzhibiaozhi3044img_30.smoothing = TextureSmoothing.BILINEAR;
            ui_pvp_rongyuzhibiaozhi3044img_30.touchable = false;
            this.addQuiackChild(ui_pvp_rongyuzhibiaozhi3044img_30);
            var txture_ui_gongyong_zhiwanzidi_tiao541370:Texture = AssetMgr.instance.getTexture('ui_gongyong_zhiwanzidi_tiao5');
            var ui_gongyong_zhiwanzidi_tiao541370img_31:Image = new Image(txture_ui_gongyong_zhiwanzidi_tiao541370);
            ui_gongyong_zhiwanzidi_tiao541370img_31.x = 41;
            ui_gongyong_zhiwanzidi_tiao541370img_31.y = 370;
            ui_gongyong_zhiwanzidi_tiao541370img_31.width = 280;
            ui_gongyong_zhiwanzidi_tiao541370img_31.height = 3;
            ui_gongyong_zhiwanzidi_tiao541370img_31.smoothing = TextureSmoothing.BILINEAR;
            ui_gongyong_zhiwanzidi_tiao541370img_31.touchable = false;
            this.addQuiackChild(ui_gongyong_zhiwanzidi_tiao541370img_31);
            var txture_ui_button_abattoir_bar2372131:Texture = AssetMgr.instance.getTexture('ui_button_abattoir_bar2');
            var ui_button_abattoir_bar2372131img_34:Image = new Image(txture_ui_button_abattoir_bar2372131);
            ui_button_abattoir_bar2372131img_34.x = 372;
            ui_button_abattoir_bar2372131img_34.y = 131;
            ui_button_abattoir_bar2372131img_34.width = 541;
            ui_button_abattoir_bar2372131img_34.height = 29;
            ui_button_abattoir_bar2372131img_34.smoothing = TextureSmoothing.BILINEAR;
            ui_button_abattoir_bar2372131img_34.touchable = false;
            this.addQuiackChild(ui_button_abattoir_bar2372131img_34);
            var txture_ui_button_abattoir_bar1354131:Texture = AssetMgr.instance.getTexture('ui_button_abattoir_bar1');
            var ui_button_abattoir_bar1354131img_35:Image = new Image(txture_ui_button_abattoir_bar1354131);
            ui_button_abattoir_bar1354131img_35.x = 354;
            ui_button_abattoir_bar1354131img_35.y = 131;
            ui_button_abattoir_bar1354131img_35.width = 18;
            ui_button_abattoir_bar1354131img_35.height = 29;
            ui_button_abattoir_bar1354131img_35.smoothing = TextureSmoothing.BILINEAR;
            ui_button_abattoir_bar1354131img_35.touchable = false;
            this.addQuiackChild(ui_button_abattoir_bar1354131img_35);
            var txture_ui_button_abattoir_bar1926131:Texture = AssetMgr.instance.getTexture('ui_button_abattoir_bar1');
            var ui_button_abattoir_bar1926131img_36:Image = new Image(txture_ui_button_abattoir_bar1926131);
            ui_button_abattoir_bar1926131img_36.x = 926;
            ui_button_abattoir_bar1926131img_36.y = 131;
            ui_button_abattoir_bar1926131img_36.width = 18;
            ui_button_abattoir_bar1926131img_36.height = 29;
            ui_button_abattoir_bar1926131img_36.scaleX = -1;
            ui_button_abattoir_bar1926131img_36.smoothing = TextureSmoothing.BILINEAR;
            ui_button_abattoir_bar1926131img_36.touchable = false;
            this.addQuiackChild(ui_button_abattoir_bar1926131img_36);
            txt_horn = new TextField(132, 36, '', '', 24, 0xF2EBBF, false);
            txt_horn.touchable = false;
            txt_horn.hAlign = 'center';
            txt_horn.x = 206;
            txt_horn.y = 443;
            this.addQuiackChild(txt_horn);
            var staticTxt_37:TextField = new TextField(171, 30, '', '', 18, 0x74F500, false);
            staticTxt_37.touchable = false;
            staticTxt_37.hAlign = 'right';
            staticTxt_37.text = '领奖倒计时：';
            staticTxt_37.x = 38;
            staticTxt_37.y = 405;
            this.addQuiackChild(staticTxt_37);
            txt_time = new TextField(133, 28, '', '', 18, 0x619EFA, false);
            txt_time.touchable = false;
            txt_time.hAlign = 'left';
            txt_time.x = 204;
            txt_time.y = 405;
            this.addQuiackChild(txt_time);
            txt_rank = new TextField(131, 28, '', '', 18, 0xFFFFFF, false);
            txt_rank.touchable = false;
            txt_rank.hAlign = 'center';
            txt_rank.x = 209;
            txt_rank.y = 303;
            this.addQuiackChild(txt_rank);
            var staticTxt_38:TextField = new TextField(297, 30, '', '', 18, 0x74F500, false);
            staticTxt_38.touchable = false;
            staticTxt_38.hAlign = 'center';
            staticTxt_38.text = '每天21点发放角斗场奖励';
            staticTxt_38.x = 41;
            staticTxt_38.y = 380;
            this.addQuiackChild(staticTxt_38);
            var staticTxt_39:TextField = new TextField(134, 30, '', '', 20, 0xF0E1C0, false);
            staticTxt_39.touchable = false;
            staticTxt_39.hAlign = 'left';
            staticTxt_39.text = '可获得荣誉：';
            staticTxt_39.x = 48;
            staticTxt_39.y = 449;
            this.addQuiackChild(staticTxt_39);
            var txture_ui_pvp_rongyuzhibiaozhi184443:Texture = AssetMgr.instance.getTexture('ui_pvp_rongyuzhibiaozhi');
            var ui_pvp_rongyuzhibiaozhi184443img_40:Image = new Image(txture_ui_pvp_rongyuzhibiaozhi184443);
            ui_pvp_rongyuzhibiaozhi184443img_40.x = 184;
            ui_pvp_rongyuzhibiaozhi184443img_40.y = 443;
            ui_pvp_rongyuzhibiaozhi184443img_40.width = 31;
            ui_pvp_rongyuzhibiaozhi184443img_40.height = 43;
            ui_pvp_rongyuzhibiaozhi184443img_40.smoothing = TextureSmoothing.BILINEAR;
            ui_pvp_rongyuzhibiaozhi184443img_40.touchable = false;
            this.addQuiackChild(ui_pvp_rongyuzhibiaozhi184443img_40);
            txt_money = new TextField(271, 44, '', '', 26, 0xFFFFFF, false);
            txt_money.touchable = false;
            txt_money.hAlign = 'left';
            txt_money.x = 76;
            txt_money.y = 45;
            this.addQuiackChild(txt_money);
            var txture_ui_tubiao_duanwei1697:Texture = AssetMgr.instance.getTexture('ui_tubiao_duanwei');
            var ui_tubiao_duanwei1697img_41:Image = new Image(txture_ui_tubiao_duanwei1697);
            ui_tubiao_duanwei1697img_41.x = 16;
            ui_tubiao_duanwei1697img_41.y = 97;
            ui_tubiao_duanwei1697img_41.width = 335;
            ui_tubiao_duanwei1697img_41.height = 107;
            ui_tubiao_duanwei1697img_41.smoothing = TextureSmoothing.BILINEAR;
            ui_tubiao_duanwei1697img_41.touchable = false;
            this.addQuiackChild(ui_tubiao_duanwei1697img_41);
            var btn_head_txture:Texture = AssetMgr.instance.getTexture('ui_gongyong_100yingxiongkuang_kong2');
            btn_head = new Button(btn_head_txture);
            btn_head.x = 44;
            btn_head.y = 195;
            var txture_ui_icon_city_vip97:Texture = AssetMgr.instance.getTexture('ui_icon_city_vip');
            var ui_icon_city_vip97img_42:Image = new Image(txture_ui_icon_city_vip97);
            ui_icon_city_vip97img_42.x = -9;
            ui_icon_city_vip97img_42.y = -6;
            ui_icon_city_vip97img_42.width = 65;
            ui_icon_city_vip97img_42.height = 65;
            ui_icon_city_vip97img_42.smoothing = TextureSmoothing.BILINEAR;
            ui_icon_city_vip97img_42.touchable = false;
            btn_head.addQuiackChild(ui_icon_city_vip97img_42);
            ui_icon_city_vip97img_42.visible = false;
            textField = new TextField(48, 30, '', '', 20, 0xFFFFCC, false);
            textField.touchable = false;
            textField.hAlign = 'center';
            textField.x = -3;
            textField.y = 18;
            btn_head.addQuiackChild(textField);
            textField.name = 'txt_rank';
            textField.visible = false;
            this.addQuiackChild(btn_head);
            var txture_ui_gongyong_iocn_paiming184288:Texture = AssetMgr.instance.getTexture('ui_gongyong_iocn_paiming');
            var ui_gongyong_iocn_paiming184288img_43:Image = new Image(txture_ui_gongyong_iocn_paiming184288);
            ui_gongyong_iocn_paiming184288img_43.x = 184;
            ui_gongyong_iocn_paiming184288img_43.y = 288;
            ui_gongyong_iocn_paiming184288img_43.width = 30;
            ui_gongyong_iocn_paiming184288img_43.height = 42;
            ui_gongyong_iocn_paiming184288img_43.smoothing = TextureSmoothing.BILINEAR;
            ui_gongyong_iocn_paiming184288img_43.touchable = false;
            this.addQuiackChild(ui_gongyong_iocn_paiming184288img_43);
            txt_lvl_title = new TextField(133, 33, '', '', 20, 0xE7CE29, false);
            txt_lvl_title.touchable = false;
            txt_lvl_title.hAlign = 'left';
            txt_lvl_title.text = '最强王者';
            txt_lvl_title.x = 226;
            txt_lvl_title.y = 245;
            this.addQuiackChild(txt_lvl_title);
            var txture_mc_progress:Texture = AssetMgr.instance.getTexture('ui_button_abattoir_bar1');
            img_mc_progress = new Image(txture_mc_progress);
            img_mc_progress.x = 356;
            img_mc_progress.y = 283;
            img_mc_progress.width = 0;
            img_mc_progress.height = 0;
            this.addQuiackChild(img_mc_progress);
            var texture_mc_progress:Texture = AssetMgr.instance.getTexture('ui_button_abattoir_bar4');
            var rect_mc_progress:Rectangle = new Rectangle(17, 8, 33, 6);
            var scaleTexture_mc_progress:Scale9Textures = new Scale9Textures(texture_mc_progress, rect_mc_progress);
            scale_mc_progress = new Scale9Image(scaleTexture_mc_progress);
            scale_mc_progress.x = 366;
            scale_mc_progress.y = 134;
            scale_mc_progress.width = 557;
            scale_mc_progress.height = 25;
            this.addQuiackChild(scale_mc_progress);
            txt_name = new TextField(207, 34, '', '方正综艺简体', 22, 0xF2EBBF, false);
            txt_name.touchable = false;
            txt_name.hAlign = 'center';
            txt_name.x = 130;
            txt_name.y = 200;
            this.addQuiackChild(txt_name);
            var txture_ui_gongyong_iocn_zhandouli183340:Texture = AssetMgr.instance.getTexture('ui_gongyong_iocn_zhandouli');
            var ui_gongyong_iocn_zhandouli183340img_44:Image = new Image(txture_ui_gongyong_iocn_zhandouli183340);
            ui_gongyong_iocn_zhandouli183340img_44.x = 183;
            ui_gongyong_iocn_zhandouli183340img_44.y = 340;
            ui_gongyong_iocn_zhandouli183340img_44.width = 32;
            ui_gongyong_iocn_zhandouli183340img_44.height = 28;
            ui_gongyong_iocn_zhandouli183340img_44.smoothing = TextureSmoothing.BILINEAR;
            ui_gongyong_iocn_zhandouli183340img_44.touchable = false;
            this.addQuiackChild(ui_gongyong_iocn_zhandouli183340img_44);
            txt_fight = new TextField(131, 28, '', '', 18, 0xFFFFFF, false);
            txt_fight.touchable = false;
            txt_fight.hAlign = 'center';
            txt_fight.x = 209;
            txt_fight.y = 341;
            this.addQuiackChild(txt_fight);
            var staticTxt_45:TextField = new TextField(142, 30, '', '', 20, 0xECDCC3, false);
            staticTxt_45.touchable = false;
            staticTxt_45.hAlign = 'left';
            staticTxt_45.text = '当前排名：';
            staticTxt_45.x = 48;
            staticTxt_45.y = 300;
            this.addQuiackChild(staticTxt_45);
            var staticTxt_46:TextField = new TextField(142, 30, '', '', 20, 0xF0E1C0, false);
            staticTxt_46.touchable = false;
            staticTxt_46.hAlign = 'left';
            staticTxt_46.text = '当前战斗力:';
            staticTxt_46.x = 48;
            staticTxt_46.y = 338;
            this.addQuiackChild(staticTxt_46);
            var staticTxt_47:TextField = new TextField(134, 30, '', '', 20, 0xF0E1C0, false);
            staticTxt_47.touchable = false;
            staticTxt_47.hAlign = 'left';
            staticTxt_47.text = '可挑战次数：';
            staticTxt_47.x = 48;
            staticTxt_47.y = 487;
            this.addQuiackChild(staticTxt_47);
            txt_pvp_count = new TextField(60, 36, '', '', 24, 0xF2EBBF, false);
            txt_pvp_count.touchable = false;
            txt_pvp_count.hAlign = 'left';
            txt_pvp_count.text = '0/0';
            txt_pvp_count.x = 273;
            txt_pvp_count.y = 482;
            this.addQuiackChild(txt_pvp_count);
            txt_count = new TextField(60, 36, '', '', 24, 0xF2EBBF, false);
            txt_count.touchable = false;
            txt_count.hAlign = 'right';
            txt_count.x = 210;
            txt_count.y = 482;
            this.addQuiackChild(txt_count);
            var txture_img_lvl:Texture = AssetMgr.instance.getTexture('ui_iocn_qualifying6');
            img_img_lvl = new Image(txture_img_lvl);
            img_img_lvl.x = 138;
            img_img_lvl.y = 230;
            img_img_lvl.width = 85;
            img_img_lvl.height = 57;
            this.addQuiackChild(img_img_lvl);
            var list:Vector.<TabButton> = new Vector.<TabButton>();
            tabbtn_pvp0 = new TabButton(AssetMgr.instance.getTexture('ui_button_abattoir2'), AssetMgr.instance.getTexture('ui_button_abattoir2_1'));
            tabbtn_pvp0.x = 0;
            tabbtn_pvp0.y = 0;
            tabbtn_pvp0.name = 'btn_pvp';
            list.push(tabbtn_pvp0);
            tabbtn_fight1 = new TabButton(AssetMgr.instance.getTexture('ui_button_abattoir3'), AssetMgr.instance.getTexture('ui_button_abattoir3_1'));
            tabbtn_fight1.x = 79;
            tabbtn_fight1.y = 0;
            tabbtn_fight1.name = 'btn_fight';
            list.push(tabbtn_fight1);
            tabbtn_buy2 = new TabButton(AssetMgr.instance.getTexture('ui_button_abattoir1'), AssetMgr.instance.getTexture('ui_button_abattoir1_1'));
            tabbtn_buy2.x = 157;
            tabbtn_buy2.y = 0;
            tabbtn_buy2.name = 'btn_buy';
            list.push(tabbtn_buy2);
            tabbtn_regulation0 = new Button(AssetMgr.instance.getTexture('ui_button_abattoir4'));
            tabbtn_regulation0.x = 267;
            tabbtn_regulation0.y = 542;
            tabbtn_regulation0.name = 'btn_regulation';
            this.addChild(tabbtn_regulation0);
            menu_bars = new TabMenu(list);
            menu_bars.x = 34;
            menu_bars.y = 542;
            this.addQuiackChild(menu_bars);
            var txture_mc_quality_1:Texture = AssetMgr.instance.getTexture('ui_iocn_qualifying1');
            img_mc_quality_1 = new Image(txture_mc_quality_1);
            img_mc_quality_1.x = 862;
            img_mc_quality_1.y = 113;
            img_mc_quality_1.width = 85;
            img_mc_quality_1.height = 57;
            this.addQuiackChild(img_mc_quality_1);
            var txture_mc_quality_2:Texture = AssetMgr.instance.getTexture('ui_iocn_qualifying2');
            img_mc_quality_2 = new Image(txture_mc_quality_2);
            img_mc_quality_2.x = 757;
            img_mc_quality_2.y = 113;
            img_mc_quality_2.width = 85;
            img_mc_quality_2.height = 57;
            this.addQuiackChild(img_mc_quality_2);
            var txture_mc_quality_3:Texture = AssetMgr.instance.getTexture('ui_iocn_qualifying3');
            img_mc_quality_3 = new Image(txture_mc_quality_3);
            img_mc_quality_3.x = 651;
            img_mc_quality_3.y = 113;
            img_mc_quality_3.width = 85;
            img_mc_quality_3.height = 57;
            this.addQuiackChild(img_mc_quality_3);
            var txture_mc_quality_4:Texture = AssetMgr.instance.getTexture('ui_iocn_qualifying4');
            img_mc_quality_4 = new Image(txture_mc_quality_4);
            img_mc_quality_4.x = 543;
            img_mc_quality_4.y = 113;
            img_mc_quality_4.width = 88;
            img_mc_quality_4.height = 57;
            this.addQuiackChild(img_mc_quality_4);
            var txture_mc_quality_5:Texture = AssetMgr.instance.getTexture('ui_iocn_qualifying5');
            img_mc_quality_5 = new Image(txture_mc_quality_5);
            img_mc_quality_5.x = 439;
            img_mc_quality_5.y = 113;
            img_mc_quality_5.width = 85;
            img_mc_quality_5.height = 57;
            this.addQuiackChild(img_mc_quality_5);
            var txture_mc_quality_6:Texture = AssetMgr.instance.getTexture('ui_iocn_qualifying6');
            img_mc_quality_6 = new Image(txture_mc_quality_6);
            img_mc_quality_6.x = 330;
            img_mc_quality_6.y = 113;
            img_mc_quality_6.width = 85;
            img_mc_quality_6.height = 57;
            this.addQuiackChild(img_mc_quality_6);

        }

        override public function dispose():void {
            btn_close.dispose();
            tabbtn_regulation0.dispose();
            btn_head.dispose();
            tabbtn_pvp0.dispose();
            tabbtn_fight1.dispose();
            tabbtn_buy2.dispose();
            menu_bars.dispose();
            super.dispose();

        }

    }
}