package game.view.luckyStar {
    import com.dialog.Dialog;
    import com.utils.Constants;

    import flash.geom.Rectangle;

    import feathers.display.Scale9Image;
    import feathers.textures.Scale9Textures;

    import game.manager.AssetMgr;

    import starling.display.Button;
    import starling.display.Image;
    import starling.text.TextField;
    import starling.textures.Texture;

    public class LuckyStarDlgBase extends Dialog {
        public var box10Image:Image;
        public var box11Image:Image;
        public var box12Image:Image;
        public var box13Image:Image;
        public var diamondTxt:TextField;
        public var no1_1Txt:TextField;
        public var box2Image:Image;
        public var box3Image:Image;
        public var box4Image:Image;
        public var box5Image:Image;
        public var box6Image:Image;
        public var box7Image:Image;
        public var box8Image:Image;
        public var box9Image:Image;
        public var startButton:Button;
        public var startCTxt:TextField;
        public var startETxt:TextField;
        public var no2_1Txt:TextField;
        public var no2_2Txt:TextField;
        public var no1_2Txt:TextField;
        public var no3_2Txt:TextField;
        public var box14Image:Image;
        public var no1_3Txt:TextField;
        public var no2_3Txt:TextField;
        public var closeButton:Button;
        public var box1Image:Image;
        public var no3_1Txt:TextField;
        public var awardTxt:TextField;
        public var nameTxt:TextField;
        public var diamondImage:Image;
        public var buyButton:Button;

        public function LuckyStarDlgBase() {
            var ui_gongyong_jinbibaizidi427Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_jinbibaizidi');
            var ui_gongyong_jinbibaizidi427Image:Image = new Image(ui_gongyong_jinbibaizidi427Texture);
            ui_gongyong_jinbibaizidi427Image.x = 4;
            ui_gongyong_jinbibaizidi427Image.y = 27;
            ui_gongyong_jinbibaizidi427Image.width = 166;
            ui_gongyong_jinbibaizidi427Image.height = 51;
            ui_gongyong_jinbibaizidi427Image.smoothing = Constants.smoothing;
            ui_gongyong_jinbibaizidi427Image.touchable = false;
            this.addQuiackChild(ui_gongyong_jinbibaizidi427Image);
            var ui_gongyong_lashenkuang4391Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang4');
            var ui_gongyong_lashenkuang4391Rect:Rectangle = new Rectangle(16, 16, 33, 33);
            var ui_gongyong_lashenkuang43919ScaleTexture:Scale9Textures = new Scale9Textures(ui_gongyong_lashenkuang4391Texture,
                                                                                             ui_gongyong_lashenkuang4391Rect);
            var ui_gongyong_lashenkuang43919Scale:Scale9Image = new Scale9Image(ui_gongyong_lashenkuang43919ScaleTexture);
            ui_gongyong_lashenkuang43919Scale.x = 3;
            ui_gongyong_lashenkuang43919Scale.y = 91;
            ui_gongyong_lashenkuang43919Scale.width = 597;
            ui_gongyong_lashenkuang43919Scale.height = 350;
            this.addQuiackChild(ui_gongyong_lashenkuang43919Scale);
            var ui_gongyong_lashenkuang4622476Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang4');
            var ui_gongyong_lashenkuang4622476Rect:Rectangle = new Rectangle(16, 16, 33, 33);
            var ui_gongyong_lashenkuang46224769ScaleTexture:Scale9Textures = new Scale9Textures(ui_gongyong_lashenkuang4622476Texture,
                                                                                                ui_gongyong_lashenkuang4622476Rect);
            var ui_gongyong_lashenkuang46224769Scale:Scale9Image = new Scale9Image(ui_gongyong_lashenkuang46224769ScaleTexture);
            ui_gongyong_lashenkuang46224769Scale.x = 622;
            ui_gongyong_lashenkuang46224769Scale.y = 476;
            ui_gongyong_lashenkuang46224769Scale.width = 297;
            ui_gongyong_lashenkuang46224769Scale.height = 145;
            this.addQuiackChild(ui_gongyong_lashenkuang46224769Scale);
            var ui_gongyong_lashenkuang1620474Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang1');
            var ui_gongyong_lashenkuang1620474Image:Image = new Image(ui_gongyong_lashenkuang1620474Texture);
            ui_gongyong_lashenkuang1620474Image.x = 620;
            ui_gongyong_lashenkuang1620474Image.y = 474;
            ui_gongyong_lashenkuang1620474Image.width = 14;
            ui_gongyong_lashenkuang1620474Image.height = 16;
            ui_gongyong_lashenkuang1620474Image.smoothing = Constants.smoothing;
            ui_gongyong_lashenkuang1620474Image.touchable = false;
            this.addQuiackChild(ui_gongyong_lashenkuang1620474Image);
            var ui_gongyong_lashenkuang1920474Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang1');
            var ui_gongyong_lashenkuang1920474Image:Image = new Image(ui_gongyong_lashenkuang1920474Texture);
            ui_gongyong_lashenkuang1920474Image.x = 920;
            ui_gongyong_lashenkuang1920474Image.y = 474;
            ui_gongyong_lashenkuang1920474Image.width = 14;
            ui_gongyong_lashenkuang1920474Image.height = 16;
            ui_gongyong_lashenkuang1920474Image.scaleX = -1;
            ui_gongyong_lashenkuang1920474Image.smoothing = Constants.smoothing;
            ui_gongyong_lashenkuang1920474Image.touchable = false;
            this.addQuiackChild(ui_gongyong_lashenkuang1920474Image);
            var ui_gongyong_lashenkuang2627474Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang2');
            var ui_gongyong_lashenkuang2627474Rect:Rectangle = new Rectangle(9, 1, 19, 1);
            var ui_gongyong_lashenkuang26274749ScaleTexture:Scale9Textures = new Scale9Textures(ui_gongyong_lashenkuang2627474Texture,
                                                                                                ui_gongyong_lashenkuang2627474Rect);
            var ui_gongyong_lashenkuang26274749Scale:Scale9Image = new Scale9Image(ui_gongyong_lashenkuang26274749ScaleTexture);
            ui_gongyong_lashenkuang26274749Scale.x = 627;
            ui_gongyong_lashenkuang26274749Scale.y = 474;
            ui_gongyong_lashenkuang26274749Scale.width = 287;
            ui_gongyong_lashenkuang26274749Scale.height = 2;
            this.addQuiackChild(ui_gongyong_lashenkuang26274749Scale);
            var ui_gongyong_lashenkuang3620481Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang3');
            var ui_gongyong_lashenkuang3620481Rect:Rectangle = new Rectangle(1, 6, 1, 12);
            var ui_gongyong_lashenkuang36204819ScaleTexture:Scale9Textures = new Scale9Textures(ui_gongyong_lashenkuang3620481Texture,
                                                                                                ui_gongyong_lashenkuang3620481Rect);
            var ui_gongyong_lashenkuang36204819Scale:Scale9Image = new Scale9Image(ui_gongyong_lashenkuang36204819ScaleTexture);
            ui_gongyong_lashenkuang36204819Scale.x = 620;
            ui_gongyong_lashenkuang36204819Scale.y = 481;
            ui_gongyong_lashenkuang36204819Scale.width = 2;
            ui_gongyong_lashenkuang36204819Scale.height = 136;
            this.addQuiackChild(ui_gongyong_lashenkuang36204819Scale);
            var ui_gongyong_lashenkuang3920481Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang3');
            var ui_gongyong_lashenkuang3920481Rect:Rectangle = new Rectangle(1, 6, 1, 12);
            var ui_gongyong_lashenkuang39204819ScaleTexture:Scale9Textures = new Scale9Textures(ui_gongyong_lashenkuang3920481Texture,
                                                                                                ui_gongyong_lashenkuang3920481Rect);
            var ui_gongyong_lashenkuang39204819Scale:Scale9Image = new Scale9Image(ui_gongyong_lashenkuang39204819ScaleTexture);
            ui_gongyong_lashenkuang39204819Scale.x = 920;
            ui_gongyong_lashenkuang39204819Scale.y = 481;
            ui_gongyong_lashenkuang39204819Scale.width = 2;
            ui_gongyong_lashenkuang39204819Scale.height = 136;
            this.addQuiackChild(ui_gongyong_lashenkuang39204819Scale);
            var ui_gongyong_lashenkuang4621121Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang4');
            var ui_gongyong_lashenkuang4621121Rect:Rectangle = new Rectangle(16, 16, 33, 33);
            var ui_gongyong_lashenkuang46211219ScaleTexture:Scale9Textures = new Scale9Textures(ui_gongyong_lashenkuang4621121Texture,
                                                                                                ui_gongyong_lashenkuang4621121Rect);
            var ui_gongyong_lashenkuang46211219Scale:Scale9Image = new Scale9Image(ui_gongyong_lashenkuang46211219ScaleTexture);
            ui_gongyong_lashenkuang46211219Scale.x = 621;
            ui_gongyong_lashenkuang46211219Scale.y = 121;
            ui_gongyong_lashenkuang46211219Scale.width = 297;
            ui_gongyong_lashenkuang46211219Scale.height = 316;
            this.addQuiackChild(ui_gongyong_lashenkuang46211219Scale);
            var ui_gongyong_lashenkuang1619119Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang1');
            var ui_gongyong_lashenkuang1619119Image:Image = new Image(ui_gongyong_lashenkuang1619119Texture);
            ui_gongyong_lashenkuang1619119Image.x = 619;
            ui_gongyong_lashenkuang1619119Image.y = 119;
            ui_gongyong_lashenkuang1619119Image.width = 14;
            ui_gongyong_lashenkuang1619119Image.height = 16;
            ui_gongyong_lashenkuang1619119Image.smoothing = Constants.smoothing;
            ui_gongyong_lashenkuang1619119Image.touchable = false;
            this.addQuiackChild(ui_gongyong_lashenkuang1619119Image);
            var ui_gongyong_lashenkuang1619439Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang1');
            var ui_gongyong_lashenkuang1619439Image:Image = new Image(ui_gongyong_lashenkuang1619439Texture);
            ui_gongyong_lashenkuang1619439Image.x = 619;
            ui_gongyong_lashenkuang1619439Image.y = 439;
            ui_gongyong_lashenkuang1619439Image.width = 14;
            ui_gongyong_lashenkuang1619439Image.height = 16;
            ui_gongyong_lashenkuang1619439Image.scaleY = -1;
            ui_gongyong_lashenkuang1619439Image.smoothing = Constants.smoothing;
            ui_gongyong_lashenkuang1619439Image.touchable = false;
            this.addQuiackChild(ui_gongyong_lashenkuang1619439Image);
            var ui_gongyong_lashenkuang1920438Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang1');
            var ui_gongyong_lashenkuang1920438Image:Image = new Image(ui_gongyong_lashenkuang1920438Texture);
            ui_gongyong_lashenkuang1920438Image.x = 920;
            ui_gongyong_lashenkuang1920438Image.y = 438;
            ui_gongyong_lashenkuang1920438Image.width = 14;
            ui_gongyong_lashenkuang1920438Image.height = 16;
            ui_gongyong_lashenkuang1920438Image.scaleX = -1;
            ui_gongyong_lashenkuang1920438Image.scaleY = -1;
            ui_gongyong_lashenkuang1920438Image.smoothing = Constants.smoothing;
            ui_gongyong_lashenkuang1920438Image.touchable = false;
            this.addQuiackChild(ui_gongyong_lashenkuang1920438Image);
            var box10Texture:Texture = AssetMgr.instance.getTexture('ui_button_wupinkuang');
            box10Image = new Image(box10Texture);
            box10Image.x = 12;
            box10Image.y = 326;
            box10Image.width = 107;
            box10Image.height = 110;
            this.addQuiackChild(box10Image);
            var box11Texture:Texture = AssetMgr.instance.getTexture('ui_button_wupinkuang');
            box11Image = new Image(box11Texture);
            box11Image.x = 130;
            box11Image.y = 326;
            box11Image.width = 107;
            box11Image.height = 110;
            this.addQuiackChild(box11Image);
            var box12Texture:Texture = AssetMgr.instance.getTexture('ui_button_wupinkuang');
            box12Image = new Image(box12Texture);
            box12Image.x = 249;
            box12Image.y = 326;
            box12Image.width = 107;
            box12Image.height = 110;
            this.addQuiackChild(box12Image);
            var box13Texture:Texture = AssetMgr.instance.getTexture('ui_button_wupinkuang');
            box13Image = new Image(box13Texture);
            box13Image.x = 367;
            box13Image.y = 326;
            box13Image.width = 107;
            box13Image.height = 110;
            this.addQuiackChild(box13Image);
            var ui_gongyong_lashenkuang40455Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang4');
            var ui_gongyong_lashenkuang40455Rect:Rectangle = new Rectangle(16, 16, 33, 33);
            var ui_gongyong_lashenkuang404559ScaleTexture:Scale9Textures = new Scale9Textures(ui_gongyong_lashenkuang40455Texture,
                                                                                              ui_gongyong_lashenkuang40455Rect);
            var ui_gongyong_lashenkuang404559Scale:Scale9Image = new Scale9Image(ui_gongyong_lashenkuang404559ScaleTexture);
            ui_gongyong_lashenkuang404559Scale.x = 0;
            ui_gongyong_lashenkuang404559Scale.y = 455;
            ui_gongyong_lashenkuang404559Scale.width = 597;
            ui_gongyong_lashenkuang404559Scale.height = 165;
            this.addQuiackChild(ui_gongyong_lashenkuang404559Scale);
            var ui_gongyong_lashenkuang1599455Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang1');
            var ui_gongyong_lashenkuang1599455Image:Image = new Image(ui_gongyong_lashenkuang1599455Texture);
            ui_gongyong_lashenkuang1599455Image.x = 599;
            ui_gongyong_lashenkuang1599455Image.y = 455;
            ui_gongyong_lashenkuang1599455Image.width = 14;
            ui_gongyong_lashenkuang1599455Image.height = 16;
            ui_gongyong_lashenkuang1599455Image.scaleX = -1;
            ui_gongyong_lashenkuang1599455Image.smoothing = Constants.smoothing;
            ui_gongyong_lashenkuang1599455Image.touchable = false;
            this.addQuiackChild(ui_gongyong_lashenkuang1599455Image);
            var ui_gongyong_lashenkuang10621Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang1');
            var ui_gongyong_lashenkuang10621Image:Image = new Image(ui_gongyong_lashenkuang10621Texture);
            ui_gongyong_lashenkuang10621Image.x = 0;
            ui_gongyong_lashenkuang10621Image.y = 621;
            ui_gongyong_lashenkuang10621Image.width = 14;
            ui_gongyong_lashenkuang10621Image.height = 16;
            ui_gongyong_lashenkuang10621Image.scaleY = -1;
            ui_gongyong_lashenkuang10621Image.smoothing = Constants.smoothing;
            ui_gongyong_lashenkuang10621Image.touchable = false;
            this.addQuiackChild(ui_gongyong_lashenkuang10621Image);
            var ui_gongyong_lashenkuang10455Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang1');
            var ui_gongyong_lashenkuang10455Image:Image = new Image(ui_gongyong_lashenkuang10455Texture);
            ui_gongyong_lashenkuang10455Image.x = 0;
            ui_gongyong_lashenkuang10455Image.y = 455;
            ui_gongyong_lashenkuang10455Image.width = 14;
            ui_gongyong_lashenkuang10455Image.height = 16;
            ui_gongyong_lashenkuang10455Image.smoothing = Constants.smoothing;
            ui_gongyong_lashenkuang10455Image.touchable = false;
            this.addQuiackChild(ui_gongyong_lashenkuang10455Image);
            var ui_xingyunxing_beijingtu4458Texture:Texture = AssetMgr.instance.getTexture('ui_xingyunxing_beijingtu');
            var ui_xingyunxing_beijingtu4458Image:Image = new Image(ui_xingyunxing_beijingtu4458Texture);
            ui_xingyunxing_beijingtu4458Image.x = 4;
            ui_xingyunxing_beijingtu4458Image.y = 458;
            ui_xingyunxing_beijingtu4458Image.width = 278;
            ui_xingyunxing_beijingtu4458Image.height = 160;
            ui_xingyunxing_beijingtu4458Image.smoothing = Constants.smoothing;
            ui_xingyunxing_beijingtu4458Image.touchable = false;
            this.addQuiackChild(ui_xingyunxing_beijingtu4458Image);
            diamondTxt = new TextField(131, 41, '', '', 24, 0xFFFFFF, false);
            diamondTxt.touchable = false;
            diamondTxt.hAlign = 'left';
            diamondTxt.x = 51;
            diamondTxt.y = 34;
            this.addQuiackChild(diamondTxt);
            no1_1Txt = new TextField(273, 59, '', '', 20, 0xFFFFFF, false);
            no1_1Txt.touchable = false;
            no1_1Txt.hAlign = 'left';
            no1_1Txt.x = 310;
            no1_1Txt.y = 458;
            this.addQuiackChild(no1_1Txt);
            var box2Texture:Texture = AssetMgr.instance.getTexture('ui_button_wupinkuang');
            box2Image = new Image(box2Texture);
            box2Image.x = 130;
            box2Image.y = 96;
            box2Image.width = 107;
            box2Image.height = 110;
            this.addQuiackChild(box2Image);
            var box3Texture:Texture = AssetMgr.instance.getTexture('ui_button_wupinkuang');
            box3Image = new Image(box3Texture);
            box3Image.x = 249;
            box3Image.y = 96;
            box3Image.width = 107;
            box3Image.height = 110;
            this.addQuiackChild(box3Image);
            var box4Texture:Texture = AssetMgr.instance.getTexture('ui_button_wupinkuang');
            box4Image = new Image(box4Texture);
            box4Image.x = 367;
            box4Image.y = 96;
            box4Image.width = 107;
            box4Image.height = 110;
            this.addQuiackChild(box4Image);
            var box5Texture:Texture = AssetMgr.instance.getTexture('ui_button_wupinkuang');
            box5Image = new Image(box5Texture);
            box5Image.x = 485;
            box5Image.y = 96;
            box5Image.width = 107;
            box5Image.height = 110;
            this.addQuiackChild(box5Image);
            var box6Texture:Texture = AssetMgr.instance.getTexture('ui_button_wupinkuang');
            box6Image = new Image(box6Texture);
            box6Image.x = 12;
            box6Image.y = 210;
            box6Image.width = 107;
            box6Image.height = 110;
            this.addQuiackChild(box6Image);
            var box7Texture:Texture = AssetMgr.instance.getTexture('ui_button_wupinkuang');
            box7Image = new Image(box7Texture);
            box7Image.x = 130;
            box7Image.y = 210;
            box7Image.width = 107;
            box7Image.height = 110;
            this.addQuiackChild(box7Image);
            var box8Texture:Texture = AssetMgr.instance.getTexture('ui_button_wupinkuang');
            box8Image = new Image(box8Texture);
            box8Image.x = 367;
            box8Image.y = 210;
            box8Image.width = 107;
            box8Image.height = 110;
            this.addQuiackChild(box8Image);
            var box9Texture:Texture = AssetMgr.instance.getTexture('ui_button_wupinkuang');
            box9Image = new Image(box9Texture);
            box9Image.x = 485;
            box9Image.y = 210;
            box9Image.width = 107;
            box9Image.height = 110;
            this.addQuiackChild(box9Image);
            var startTexture:Texture = AssetMgr.instance.getTexture('ui_butten_sifanganniu');
            startButton = new Button(startTexture);
            startButton.x = 243;
            startButton.y = 209;
            this.addQuiackChild(startButton);
            startCTxt = new TextField(104, 57, '', '', 40, 0xFFFFFF, false);
            startCTxt.touchable = false;
            startCTxt.hAlign = 'center';
            startCTxt.x = 251;
            startCTxt.y = 225;
            this.addQuiackChild(startCTxt);
            startETxt = new TextField(104, 36, '', '', 24, 0xFFFFFF, false);
            startETxt.touchable = false;
            startETxt.hAlign = 'center';
            startETxt.x = 251;
            startETxt.y = 270;
            this.addQuiackChild(startETxt);
            var ui_gongyong_lashenkuang1920119Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang1');
            var ui_gongyong_lashenkuang1920119Image:Image = new Image(ui_gongyong_lashenkuang1920119Texture);
            ui_gongyong_lashenkuang1920119Image.x = 920;
            ui_gongyong_lashenkuang1920119Image.y = 119;
            ui_gongyong_lashenkuang1920119Image.width = 14;
            ui_gongyong_lashenkuang1920119Image.height = 16;
            ui_gongyong_lashenkuang1920119Image.scaleX = -1;
            ui_gongyong_lashenkuang1920119Image.smoothing = Constants.smoothing;
            ui_gongyong_lashenkuang1920119Image.touchable = false;
            this.addQuiackChild(ui_gongyong_lashenkuang1920119Image);
            no2_1Txt = new TextField(251, 30, '', '', 20, 0xFFFFFF, false);
            no2_1Txt.touchable = false;
            no2_1Txt.hAlign = 'left';
            no2_1Txt.x = 310;
            no2_1Txt.y = 524;
            this.addQuiackChild(no2_1Txt);
            no2_2Txt = new TextField(127, 49, '', '', 34, 0xFFFF00, false);
            no2_2Txt.touchable = false;
            no2_2Txt.hAlign = 'left';
            no2_2Txt.x = 331;
            no2_2Txt.y = 516;
            this.addQuiackChild(no2_2Txt);
            var ui_gongyong_lashenkuang1599621Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang1');
            var ui_gongyong_lashenkuang1599621Image:Image = new Image(ui_gongyong_lashenkuang1599621Texture);
            ui_gongyong_lashenkuang1599621Image.x = 599;
            ui_gongyong_lashenkuang1599621Image.y = 621;
            ui_gongyong_lashenkuang1599621Image.width = 14;
            ui_gongyong_lashenkuang1599621Image.height = 16;
            ui_gongyong_lashenkuang1599621Image.scaleX = -1;
            ui_gongyong_lashenkuang1599621Image.scaleY = -1;
            ui_gongyong_lashenkuang1599621Image.smoothing = Constants.smoothing;
            ui_gongyong_lashenkuang1599621Image.touchable = false;
            this.addQuiackChild(ui_gongyong_lashenkuang1599621Image);
            var ui_xingyunxing_wenzidi1624480Texture:Texture = AssetMgr.instance.getTexture('ui_xingyunxing_wenzidi1');
            var ui_xingyunxing_wenzidi1624480Image:Image = new Image(ui_xingyunxing_wenzidi1624480Texture);
            ui_xingyunxing_wenzidi1624480Image.x = 624;
            ui_xingyunxing_wenzidi1624480Image.y = 480;
            ui_xingyunxing_wenzidi1624480Image.width = 293;
            ui_xingyunxing_wenzidi1624480Image.height = 28;
            ui_xingyunxing_wenzidi1624480Image.smoothing = Constants.smoothing;
            ui_xingyunxing_wenzidi1624480Image.touchable = false;
            this.addQuiackChild(ui_xingyunxing_wenzidi1624480Image);
            var ui_gongyong_lashenkuang1620621Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang1');
            var ui_gongyong_lashenkuang1620621Image:Image = new Image(ui_gongyong_lashenkuang1620621Texture);
            ui_gongyong_lashenkuang1620621Image.x = 620;
            ui_gongyong_lashenkuang1620621Image.y = 621;
            ui_gongyong_lashenkuang1620621Image.width = 14;
            ui_gongyong_lashenkuang1620621Image.height = 16;
            ui_gongyong_lashenkuang1620621Image.scaleY = -1;
            ui_gongyong_lashenkuang1620621Image.smoothing = Constants.smoothing;
            ui_gongyong_lashenkuang1620621Image.touchable = false;
            this.addQuiackChild(ui_gongyong_lashenkuang1620621Image);
            var ui_gongyong_lashenkuang1920621Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang1');
            var ui_gongyong_lashenkuang1920621Image:Image = new Image(ui_gongyong_lashenkuang1920621Texture);
            ui_gongyong_lashenkuang1920621Image.x = 920;
            ui_gongyong_lashenkuang1920621Image.y = 621;
            ui_gongyong_lashenkuang1920621Image.width = 14;
            ui_gongyong_lashenkuang1920621Image.height = 16;
            ui_gongyong_lashenkuang1920621Image.scaleX = -1;
            ui_gongyong_lashenkuang1920621Image.scaleY = -1;
            ui_gongyong_lashenkuang1920621Image.smoothing = Constants.smoothing;
            ui_gongyong_lashenkuang1920621Image.touchable = false;
            this.addQuiackChild(ui_gongyong_lashenkuang1920621Image);
            var ui_gongyong_zuanshi67549Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_zuanshi');
            var ui_gongyong_zuanshi67549Image:Image = new Image(ui_gongyong_zuanshi67549Texture);
            ui_gongyong_zuanshi67549Image.x = 67;
            ui_gongyong_zuanshi67549Image.y = 549;
            ui_gongyong_zuanshi67549Image.width = 48;
            ui_gongyong_zuanshi67549Image.height = 46;
            ui_gongyong_zuanshi67549Image.smoothing = Constants.smoothing;
            ui_gongyong_zuanshi67549Image.touchable = false;
            this.addQuiackChild(ui_gongyong_zuanshi67549Image);
            no1_2Txt = new TextField(62, 49, '', '', 34, 0xFFFF00, false);
            no1_2Txt.touchable = false;
            no1_2Txt.hAlign = 'center';
            no1_2Txt.x = 424;
            no1_2Txt.y = 478;
            this.addQuiackChild(no1_2Txt);
            no3_2Txt = new TextField(303, 35, '', '', 20, 0xFFFFFF, false);
            no3_2Txt.touchable = false;
            no3_2Txt.hAlign = 'left';
            no3_2Txt.x = 312;
            no3_2Txt.y = 586;
            this.addQuiackChild(no3_2Txt);
            var ui_gongyong_xinxidikuang_tiekou_luosi291462Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_xinxidikuang_tiekou_luosi');
            var ui_gongyong_xinxidikuang_tiekou_luosi291462Image:Image = new Image(ui_gongyong_xinxidikuang_tiekou_luosi291462Texture);
            ui_gongyong_xinxidikuang_tiekou_luosi291462Image.x = 291;
            ui_gongyong_xinxidikuang_tiekou_luosi291462Image.y = 462;
            ui_gongyong_xinxidikuang_tiekou_luosi291462Image.width = 18;
            ui_gongyong_xinxidikuang_tiekou_luosi291462Image.height = 15;
            ui_gongyong_xinxidikuang_tiekou_luosi291462Image.smoothing = Constants.smoothing;
            ui_gongyong_xinxidikuang_tiekou_luosi291462Image.touchable = false;
            this.addQuiackChild(ui_gongyong_xinxidikuang_tiekou_luosi291462Image);
            var ui_gongyong_xinxidikuang_tiekou_luosi291533Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_xinxidikuang_tiekou_luosi');
            var ui_gongyong_xinxidikuang_tiekou_luosi291533Image:Image = new Image(ui_gongyong_xinxidikuang_tiekou_luosi291533Texture);
            ui_gongyong_xinxidikuang_tiekou_luosi291533Image.x = 291;
            ui_gongyong_xinxidikuang_tiekou_luosi291533Image.y = 533;
            ui_gongyong_xinxidikuang_tiekou_luosi291533Image.width = 18;
            ui_gongyong_xinxidikuang_tiekou_luosi291533Image.height = 15;
            ui_gongyong_xinxidikuang_tiekou_luosi291533Image.smoothing = Constants.smoothing;
            ui_gongyong_xinxidikuang_tiekou_luosi291533Image.touchable = false;
            this.addQuiackChild(ui_gongyong_xinxidikuang_tiekou_luosi291533Image);
            var ui_gongyong_xinxidikuang_tiekou_luosi291572Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_xinxidikuang_tiekou_luosi');
            var ui_gongyong_xinxidikuang_tiekou_luosi291572Image:Image = new Image(ui_gongyong_xinxidikuang_tiekou_luosi291572Texture);
            ui_gongyong_xinxidikuang_tiekou_luosi291572Image.x = 291;
            ui_gongyong_xinxidikuang_tiekou_luosi291572Image.y = 572;
            ui_gongyong_xinxidikuang_tiekou_luosi291572Image.width = 18;
            ui_gongyong_xinxidikuang_tiekou_luosi291572Image.height = 15;
            ui_gongyong_xinxidikuang_tiekou_luosi291572Image.smoothing = Constants.smoothing;
            ui_gongyong_xinxidikuang_tiekou_luosi291572Image.touchable = false;
            this.addQuiackChild(ui_gongyong_xinxidikuang_tiekou_luosi291572Image);
            var ui_chaojixingyunxing2565Texture:Texture = AssetMgr.instance.getTexture('ui_chaojixingyunxing');
            var ui_chaojixingyunxing2565Image:Image = new Image(ui_chaojixingyunxing2565Texture);
            ui_chaojixingyunxing2565Image.x = 256;
            ui_chaojixingyunxing2565Image.y = -5;
            ui_chaojixingyunxing2565Image.width = 419;
            ui_chaojixingyunxing2565Image.height = 97;
            ui_chaojixingyunxing2565Image.smoothing = Constants.smoothing;
            ui_chaojixingyunxing2565Image.touchable = false;
            this.addQuiackChild(ui_chaojixingyunxing2565Image);
            var ui_xingyunxing_huojiangmingdan619441Texture:Texture = AssetMgr.instance.getTexture('ui_xingyunxing_huojiangmingdan');
            var ui_xingyunxing_huojiangmingdan619441Image:Image = new Image(ui_xingyunxing_huojiangmingdan619441Texture);
            ui_xingyunxing_huojiangmingdan619441Image.x = 619;
            ui_xingyunxing_huojiangmingdan619441Image.y = 441;
            ui_xingyunxing_huojiangmingdan619441Image.width = 160;
            ui_xingyunxing_huojiangmingdan619441Image.height = 31;
            ui_xingyunxing_huojiangmingdan619441Image.smoothing = Constants.smoothing;
            ui_xingyunxing_huojiangmingdan619441Image.touchable = false;
            this.addQuiackChild(ui_xingyunxing_huojiangmingdan619441Image);
            var ui_xingyunxing_caifubang61785Texture:Texture = AssetMgr.instance.getTexture('ui_xingyunxing_caifubang');
            var ui_xingyunxing_caifubang61785Image:Image = new Image(ui_xingyunxing_caifubang61785Texture);
            ui_xingyunxing_caifubang61785Image.x = 617;
            ui_xingyunxing_caifubang61785Image.y = 85;
            ui_xingyunxing_caifubang61785Image.width = 82;
            ui_xingyunxing_caifubang61785Image.height = 33;
            ui_xingyunxing_caifubang61785Image.smoothing = Constants.smoothing;
            ui_xingyunxing_caifubang61785Image.touchable = false;
            this.addQuiackChild(ui_xingyunxing_caifubang61785Image);
            var ui_xuanzhong10559Texture:Texture = AssetMgr.instance.getTexture('ui_xuanzhong');
            var ui_xuanzhong10559Image:Image = new Image(ui_xuanzhong10559Texture);
            ui_xuanzhong10559Image.x = 10;
            ui_xuanzhong10559Image.y = 559;
            ui_xuanzhong10559Image.width = 58;
            ui_xuanzhong10559Image.height = 32;
            ui_xuanzhong10559Image.smoothing = Constants.smoothing;
            ui_xuanzhong10559Image.touchable = false;
            this.addQuiackChild(ui_xuanzhong10559Image);
            var ui_jikehuodefanli117561Texture:Texture = AssetMgr.instance.getTexture('ui_jikehuodefanli');
            var ui_jikehuodefanli117561Image:Image = new Image(ui_jikehuodefanli117561Texture);
            ui_jikehuodefanli117561Image.x = 117;
            ui_jikehuodefanli117561Image.y = 561;
            ui_jikehuodefanli117561Image.width = 158;
            ui_jikehuodefanli117561Image.height = 34;
            ui_jikehuodefanli117561Image.smoothing = Constants.smoothing;
            ui_jikehuodefanli117561Image.touchable = false;
            this.addQuiackChild(ui_jikehuodefanli117561Image);
            var ui_gongyong_lashenkuang1289Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang1');
            var ui_gongyong_lashenkuang1289Image:Image = new Image(ui_gongyong_lashenkuang1289Texture);
            ui_gongyong_lashenkuang1289Image.x = 2;
            ui_gongyong_lashenkuang1289Image.y = 89;
            ui_gongyong_lashenkuang1289Image.width = 14;
            ui_gongyong_lashenkuang1289Image.height = 16;
            ui_gongyong_lashenkuang1289Image.smoothing = Constants.smoothing;
            ui_gongyong_lashenkuang1289Image.touchable = false;
            this.addQuiackChild(ui_gongyong_lashenkuang1289Image);
            var ui_gongyong_lashenkuang21689Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang2');
            var ui_gongyong_lashenkuang21689Rect:Rectangle = new Rectangle(9, 1, 19, 1);
            var ui_gongyong_lashenkuang216899ScaleTexture:Scale9Textures = new Scale9Textures(ui_gongyong_lashenkuang21689Texture,
                                                                                              ui_gongyong_lashenkuang21689Rect);
            var ui_gongyong_lashenkuang216899Scale:Scale9Image = new Scale9Image(ui_gongyong_lashenkuang216899ScaleTexture);
            ui_gongyong_lashenkuang216899Scale.x = 16;
            ui_gongyong_lashenkuang216899Scale.y = 89;
            ui_gongyong_lashenkuang216899Scale.width = 578;
            ui_gongyong_lashenkuang216899Scale.height = 2;
            this.addQuiackChild(ui_gongyong_lashenkuang216899Scale);
            var ui_gongyong_lashenkuang212441Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang2');
            var ui_gongyong_lashenkuang212441Rect:Rectangle = new Rectangle(9, 1, 19, 1);
            var ui_gongyong_lashenkuang2124419ScaleTexture:Scale9Textures = new Scale9Textures(ui_gongyong_lashenkuang212441Texture,
                                                                                               ui_gongyong_lashenkuang212441Rect);
            var ui_gongyong_lashenkuang2124419Scale:Scale9Image = new Scale9Image(ui_gongyong_lashenkuang2124419ScaleTexture);
            ui_gongyong_lashenkuang2124419Scale.x = 12;
            ui_gongyong_lashenkuang2124419Scale.y = 441;
            ui_gongyong_lashenkuang2124419Scale.width = 578;
            ui_gongyong_lashenkuang2124419Scale.height = 2;
            this.addQuiackChild(ui_gongyong_lashenkuang2124419Scale);
            var ui_gongyong_lashenkuang12441Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang1');
            var ui_gongyong_lashenkuang12441Image:Image = new Image(ui_gongyong_lashenkuang12441Texture);
            ui_gongyong_lashenkuang12441Image.x = 2;
            ui_gongyong_lashenkuang12441Image.y = 441;
            ui_gongyong_lashenkuang12441Image.width = 14;
            ui_gongyong_lashenkuang12441Image.height = 16;
            ui_gongyong_lashenkuang12441Image.scaleY = -1;
            ui_gongyong_lashenkuang12441Image.smoothing = Constants.smoothing;
            ui_gongyong_lashenkuang12441Image.touchable = false;
            this.addQuiackChild(ui_gongyong_lashenkuang12441Image);
            var ui_gongyong_lashenkuang32103Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang3');
            var ui_gongyong_lashenkuang32103Rect:Rectangle = new Rectangle(1, 6, 1, 12);
            var ui_gongyong_lashenkuang321039ScaleTexture:Scale9Textures = new Scale9Textures(ui_gongyong_lashenkuang32103Texture,
                                                                                              ui_gongyong_lashenkuang32103Rect);
            var ui_gongyong_lashenkuang321039Scale:Scale9Image = new Scale9Image(ui_gongyong_lashenkuang321039ScaleTexture);
            ui_gongyong_lashenkuang321039Scale.x = 2;
            ui_gongyong_lashenkuang321039Scale.y = 103;
            ui_gongyong_lashenkuang321039Scale.width = 2;
            ui_gongyong_lashenkuang321039Scale.height = 324;
            this.addQuiackChild(ui_gongyong_lashenkuang321039Scale);
            var ui_gongyong_lashenkuang3601103Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang3');
            var ui_gongyong_lashenkuang3601103Rect:Rectangle = new Rectangle(1, 6, 1, 12);
            var ui_gongyong_lashenkuang36011039ScaleTexture:Scale9Textures = new Scale9Textures(ui_gongyong_lashenkuang3601103Texture,
                                                                                                ui_gongyong_lashenkuang3601103Rect);
            var ui_gongyong_lashenkuang36011039Scale:Scale9Image = new Scale9Image(ui_gongyong_lashenkuang36011039ScaleTexture);
            ui_gongyong_lashenkuang36011039Scale.x = 601;
            ui_gongyong_lashenkuang36011039Scale.y = 103;
            ui_gongyong_lashenkuang36011039Scale.width = 2;
            ui_gongyong_lashenkuang36011039Scale.height = 324;
            this.addQuiackChild(ui_gongyong_lashenkuang36011039Scale);
            var ui_gongyong_lashenkuang160189Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang1');
            var ui_gongyong_lashenkuang160189Image:Image = new Image(ui_gongyong_lashenkuang160189Texture);
            ui_gongyong_lashenkuang160189Image.x = 601;
            ui_gongyong_lashenkuang160189Image.y = 89;
            ui_gongyong_lashenkuang160189Image.width = 14;
            ui_gongyong_lashenkuang160189Image.height = 16;
            ui_gongyong_lashenkuang160189Image.scaleX = -1;
            ui_gongyong_lashenkuang160189Image.smoothing = Constants.smoothing;
            ui_gongyong_lashenkuang160189Image.touchable = false;
            this.addQuiackChild(ui_gongyong_lashenkuang160189Image);
            var ui_gongyong_lashenkuang1601441Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang1');
            var ui_gongyong_lashenkuang1601441Image:Image = new Image(ui_gongyong_lashenkuang1601441Texture);
            ui_gongyong_lashenkuang1601441Image.x = 601;
            ui_gongyong_lashenkuang1601441Image.y = 441;
            ui_gongyong_lashenkuang1601441Image.width = 14;
            ui_gongyong_lashenkuang1601441Image.height = 16;
            ui_gongyong_lashenkuang1601441Image.scaleX = -1;
            ui_gongyong_lashenkuang1601441Image.scaleY = -1;
            ui_gongyong_lashenkuang1601441Image.smoothing = Constants.smoothing;
            ui_gongyong_lashenkuang1601441Image.touchable = false;
            this.addQuiackChild(ui_gongyong_lashenkuang1601441Image);
            var ui_gongyong_lashenkuang214455Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang2');
            var ui_gongyong_lashenkuang214455Rect:Rectangle = new Rectangle(9, 1, 19, 1);
            var ui_gongyong_lashenkuang2144559ScaleTexture:Scale9Textures = new Scale9Textures(ui_gongyong_lashenkuang214455Texture,
                                                                                               ui_gongyong_lashenkuang214455Rect);
            var ui_gongyong_lashenkuang2144559Scale:Scale9Image = new Scale9Image(ui_gongyong_lashenkuang2144559ScaleTexture);
            ui_gongyong_lashenkuang2144559Scale.x = 14;
            ui_gongyong_lashenkuang2144559Scale.y = 455;
            ui_gongyong_lashenkuang2144559Scale.width = 578;
            ui_gongyong_lashenkuang2144559Scale.height = 2;
            this.addQuiackChild(ui_gongyong_lashenkuang2144559Scale);
            var ui_gongyong_lashenkuang30459Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang3');
            var ui_gongyong_lashenkuang30459Rect:Rectangle = new Rectangle(1, 6, 1, 12);
            var ui_gongyong_lashenkuang304599ScaleTexture:Scale9Textures = new Scale9Textures(ui_gongyong_lashenkuang30459Texture,
                                                                                              ui_gongyong_lashenkuang30459Rect);
            var ui_gongyong_lashenkuang304599Scale:Scale9Image = new Scale9Image(ui_gongyong_lashenkuang304599ScaleTexture);
            ui_gongyong_lashenkuang304599Scale.x = 0;
            ui_gongyong_lashenkuang304599Scale.y = 459;
            ui_gongyong_lashenkuang304599Scale.width = 2;
            ui_gongyong_lashenkuang304599Scale.height = 155;
            this.addQuiackChild(ui_gongyong_lashenkuang304599Scale);
            var ui_gongyong_lashenkuang3599459Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang3');
            var ui_gongyong_lashenkuang3599459Rect:Rectangle = new Rectangle(1, 6, 1, 12);
            var ui_gongyong_lashenkuang35994599ScaleTexture:Scale9Textures = new Scale9Textures(ui_gongyong_lashenkuang3599459Texture,
                                                                                                ui_gongyong_lashenkuang3599459Rect);
            var ui_gongyong_lashenkuang35994599Scale:Scale9Image = new Scale9Image(ui_gongyong_lashenkuang35994599ScaleTexture);
            ui_gongyong_lashenkuang35994599Scale.x = 599;
            ui_gongyong_lashenkuang35994599Scale.y = 459;
            ui_gongyong_lashenkuang35994599Scale.width = 2;
            ui_gongyong_lashenkuang35994599Scale.height = 155;
            this.addQuiackChild(ui_gongyong_lashenkuang35994599Scale);
            var ui_gongyong_lashenkuang214621Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang2');
            var ui_gongyong_lashenkuang214621Rect:Rectangle = new Rectangle(9, 1, 19, 1);
            var ui_gongyong_lashenkuang2146219ScaleTexture:Scale9Textures = new Scale9Textures(ui_gongyong_lashenkuang214621Texture,
                                                                                               ui_gongyong_lashenkuang214621Rect);
            var ui_gongyong_lashenkuang2146219Scale:Scale9Image = new Scale9Image(ui_gongyong_lashenkuang2146219ScaleTexture);
            ui_gongyong_lashenkuang2146219Scale.x = 14;
            ui_gongyong_lashenkuang2146219Scale.y = 621;
            ui_gongyong_lashenkuang2146219Scale.width = 578;
            ui_gongyong_lashenkuang2146219Scale.height = 2;
            this.addQuiackChild(ui_gongyong_lashenkuang2146219Scale);
            var ui_gongyong_lashenkuang2627119Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang2');
            var ui_gongyong_lashenkuang2627119Rect:Rectangle = new Rectangle(9, 1, 19, 1);
            var ui_gongyong_lashenkuang26271199ScaleTexture:Scale9Textures = new Scale9Textures(ui_gongyong_lashenkuang2627119Texture,
                                                                                                ui_gongyong_lashenkuang2627119Rect);
            var ui_gongyong_lashenkuang26271199Scale:Scale9Image = new Scale9Image(ui_gongyong_lashenkuang26271199ScaleTexture);
            ui_gongyong_lashenkuang26271199Scale.x = 627;
            ui_gongyong_lashenkuang26271199Scale.y = 119;
            ui_gongyong_lashenkuang26271199Scale.width = 287;
            ui_gongyong_lashenkuang26271199Scale.height = 2;
            this.addQuiackChild(ui_gongyong_lashenkuang26271199Scale);
            var ui_gongyong_lashenkuang2634438Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang2');
            var ui_gongyong_lashenkuang2634438Rect:Rectangle = new Rectangle(9, 1, 19, 1);
            var ui_gongyong_lashenkuang26344389ScaleTexture:Scale9Textures = new Scale9Textures(ui_gongyong_lashenkuang2634438Texture,
                                                                                                ui_gongyong_lashenkuang2634438Rect);
            var ui_gongyong_lashenkuang26344389Scale:Scale9Image = new Scale9Image(ui_gongyong_lashenkuang26344389ScaleTexture);
            ui_gongyong_lashenkuang26344389Scale.x = 634;
            ui_gongyong_lashenkuang26344389Scale.y = 438;
            ui_gongyong_lashenkuang26344389Scale.width = 272;
            ui_gongyong_lashenkuang26344389Scale.height = 2;
            this.addQuiackChild(ui_gongyong_lashenkuang26344389Scale);
            var ui_gongyong_lashenkuang3619126Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang3');
            var ui_gongyong_lashenkuang3619126Rect:Rectangle = new Rectangle(1, 6, 1, 12);
            var ui_gongyong_lashenkuang36191269ScaleTexture:Scale9Textures = new Scale9Textures(ui_gongyong_lashenkuang3619126Texture,
                                                                                                ui_gongyong_lashenkuang3619126Rect);
            var ui_gongyong_lashenkuang36191269Scale:Scale9Image = new Scale9Image(ui_gongyong_lashenkuang36191269ScaleTexture);
            ui_gongyong_lashenkuang36191269Scale.x = 619;
            ui_gongyong_lashenkuang36191269Scale.y = 126;
            ui_gongyong_lashenkuang36191269Scale.width = 2;
            ui_gongyong_lashenkuang36191269Scale.height = 306;
            this.addQuiackChild(ui_gongyong_lashenkuang36191269Scale);
            var ui_gongyong_lashenkuang3920126Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang3');
            var ui_gongyong_lashenkuang3920126Rect:Rectangle = new Rectangle(1, 6, 1, 12);
            var ui_gongyong_lashenkuang39201269ScaleTexture:Scale9Textures = new Scale9Textures(ui_gongyong_lashenkuang3920126Texture,
                                                                                                ui_gongyong_lashenkuang3920126Rect);
            var ui_gongyong_lashenkuang39201269Scale:Scale9Image = new Scale9Image(ui_gongyong_lashenkuang39201269ScaleTexture);
            ui_gongyong_lashenkuang39201269Scale.x = 920;
            ui_gongyong_lashenkuang39201269Scale.y = 126;
            ui_gongyong_lashenkuang39201269Scale.width = 2;
            ui_gongyong_lashenkuang39201269Scale.height = 306;
            this.addQuiackChild(ui_gongyong_lashenkuang39201269Scale);
            var ui_gongyong_lashenkuang2631621Texture:Texture = AssetMgr.instance.getTexture('ui_gongyong_lashenkuang2');
            var ui_gongyong_lashenkuang2631621Rect:Rectangle = new Rectangle(9, 1, 19, 1);
            var ui_gongyong_lashenkuang26316219ScaleTexture:Scale9Textures = new Scale9Textures(ui_gongyong_lashenkuang2631621Texture,
                                                                                                ui_gongyong_lashenkuang2631621Rect);
            var ui_gongyong_lashenkuang26316219Scale:Scale9Image = new Scale9Image(ui_gongyong_lashenkuang26316219ScaleTexture);
            ui_gongyong_lashenkuang26316219Scale.x = 631;
            ui_gongyong_lashenkuang26316219Scale.y = 621;
            ui_gongyong_lashenkuang26316219Scale.width = 277;
            ui_gongyong_lashenkuang26316219Scale.height = 2;
            this.addQuiackChild(ui_gongyong_lashenkuang26316219Scale);
            var box14Texture:Texture = AssetMgr.instance.getTexture('ui_button_wupinkuang');
            box14Image = new Image(box14Texture);
            box14Image.x = 485;
            box14Image.y = 326;
            box14Image.width = 107;
            box14Image.height = 110;
            this.addQuiackChild(box14Image);
            no1_3Txt = new TextField(107, 30, '', '', 20, 0xFFFFFF, false);
            no1_3Txt.touchable = false;
            no1_3Txt.hAlign = 'left';
            no1_3Txt.x = 480;
            no1_3Txt.y = 487;
            this.addQuiackChild(no1_3Txt);
            no2_3Txt = new TextField(104, 30, '', '', 20, 0xFFFFFF, false);
            no2_3Txt.touchable = false;
            no2_3Txt.hAlign = 'left';
            no2_3Txt.x = 426;
            no2_3Txt.y = 524;
            this.addQuiackChild(no2_3Txt);
            var closeTexture:Texture = AssetMgr.instance.getTexture('ui_gongyong_tuichuanniiu');
            closeButton = new Button(closeTexture);
            closeButton.x = 799;
            closeButton.y = -35;
            this.addQuiackChild(closeButton);
            var box1Texture:Texture = AssetMgr.instance.getTexture('ui_button_wupinkuang');
            box1Image = new Image(box1Texture);
            box1Image.x = 12;
            box1Image.y = 96;
            box1Image.width = 107;
            box1Image.height = 110;
            this.addQuiackChild(box1Image);
            no3_1Txt = new TextField(141, 38, '', '', 20, 0xFFFFFF, false);
            no3_1Txt.touchable = false;
            no3_1Txt.hAlign = 'left';
            no3_1Txt.x = 315;
            no3_1Txt.y = 555;
            this.addQuiackChild(no3_1Txt);
            awardTxt = new TextField(164, 37, '', '', 20, 0xFFFFFF, false);
            awardTxt.touchable = false;
            awardTxt.hAlign = 'center';
            awardTxt.x = 754;
            awardTxt.y = 475;
            this.addQuiackChild(awardTxt);
            nameTxt = new TextField(119, 31, '', '', 20, 0xFFFFFF, false);
            nameTxt.touchable = false;
            nameTxt.hAlign = 'center';
            nameTxt.x = 618;
            nameTxt.y = 475;
            this.addQuiackChild(nameTxt);
            var ui_wudixingyunxing_xingxing1131Texture:Texture = AssetMgr.instance.getTexture('ui_wudixingyunxing_xingxing');
            var ui_wudixingyunxing_xingxing1131Image:Image = new Image(ui_wudixingyunxing_xingxing1131Texture);
            ui_wudixingyunxing_xingxing1131Image.x = 11;
            ui_wudixingyunxing_xingxing1131Image.y = 31;
            ui_wudixingyunxing_xingxing1131Image.width = 41;
            ui_wudixingyunxing_xingxing1131Image.height = 40;
            ui_wudixingyunxing_xingxing1131Image.smoothing = Constants.smoothing;
            ui_wudixingyunxing_xingxing1131Image.touchable = false;
            this.addQuiackChild(ui_wudixingyunxing_xingxing1131Image);
            var diamondTexture:Texture = AssetMgr.instance.getTexture('ui_dianjuan');
            diamondImage = new Image(diamondTexture);
            diamondImage.x = 216;
            diamondImage.y = 507;
            diamondImage.width = 55;
            diamondImage.height = 27;
            this.addQuiackChild(diamondImage);
            var buyTexture:Texture = AssetMgr.instance.getTexture('ui_button_buy');
            buyButton = new Button(buyTexture);
            buyButton.x = 190;
            buyButton.y = 21;
            this.addQuiackChild(buyButton);
        }

        override public function dispose():void {
            startButton.dispose();
            closeButton.dispose();
            buyButton.dispose();
            super.dispose();
        }

    }
}
